### ISSUE TITLE
App starts but gets stuck at test starting

### ISSUE THREAD

**Issue by AshuSharma7** [leancodepl/patrol#1244]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

1. Clone the example app of patrol
2. Try to run the test in real iOS device using "patrol test --target integration_test/example_test.dart"

### Actual results

App starts for test, but it gets stuck at Test starting screen, and sometimes it's just white screen and in logs I'm getting this error "Error: No .xctestrun file was found at /Users/ashusharma/Downloads/patrol-master/packages/patrol/example/build/ios_integ/Build/Products"

### Logs

<details>
<summary>Logs</summary>

```
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/ashusharma/Downloads/patrol-master/packages/patrol/example/integration_test/example_test.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (Ashu's iPhone)
Received 1 device(s) to run on
Received device: Ashu's iPhone
Every test target will be run 1 time(s)
Received 6 --dart-define(s) (0 custom, 6 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building app with entrypoint example_test.dart for iOS device (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --target /Users/ashusharma/Downloads/patrol-master/packages/patrol/example/integration_test/example_test.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example --dart-define PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example --dart-define PATROL_ANDROID_APP_NAME=Patrol example --dart-define PATROL_IOS_APP_NAME=Patrol example --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL=example_test.dart
        Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
        Building pl.leancode.patrol.Example for device (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
        2023-05-03 15:39:10.865 xcodebuild[88140:517543] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
        note: Building targets in dependency order
        warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
✓ Completed building app with entrypoint example_test.dart for iOS device (25.2s)
• Running app with entrypoint example_test.dart for iOS device on device Ashu's iPhone...
Executing on physical iOS device using ios-deploy...
$ ios-deploy --id 00008030-000369281AF9402E --bundle ../build/ios_integ/Build/Products/Debug-iphoneos/Runner.app --debug --no-wifi --args --enable-dart-profiling --enable-checked-mode --verify-entry-points
ios-deploy successfully launched the app
$ xcodebuild -showsdks -json
Assuming SDK version 16.4 for iphonesimulator
Looking for .xctestrun matching Runner_iphoneos16.4*.xctestrun at /Users/ashusharma/Downloads/patrol-master/packages/patrol/example/build/ios_integ/Build/Products
Error: No .xctestrun file was found at /Users/ashusharma/Downloads/patrol-master/packages/patrol/example/build/ios_integ/Build/Products
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.xcTestRunPath (package:patrol_cli/src/ios/ios_test_backend.dart:244:7)
<asynchronous suspension>
#2      IOSTestBackend.execute.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:153:26)
<asynchronous suspension>
#3      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#4      IOSTestBackend.execute (package:patrol_cli/src/ios/ios_test_backend.dart:139:5)
<asynchronous suspension>
#5      TestCommand._executorFor.<anonymous closure> (package:patrol_cli/src/commands/test.dart:280:9)
<asynchronous suspension>
#6      _NativeTestRunner.run.runTestsOnDevice (package:patrol_cli/src/test_runner.dart:243:15)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#8      _NativeTestRunner.run (package:patrol_cli/src/test_runner.dart:258:5)
<asynchronous suspension>
#9      TestCommand.run (package:patrol_cli/src/commands/test.dart:189:21)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:311:18)
<asynchronous suspension>
#12     PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:256:18)
<asynchronous suspension>
#13     patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:66:20)
<asynchronous suspension>
#14     main (file:///Users/ashusharma/.pub-cache/hosted/pub.dev/patrol_cli-1.1.7/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
$ ideviceinstaller --udid 00008030-000369281AF9402E --uninstall pl.leancode.patrol.Example
^[[A^CCaught SIGINT, exiting...
$ ideviceinstaller --udid 00008030-000369281AF9402E --uninstall pl.leancode.patrol.Example.RunnerUITests.xctrunner
 FAIL  example_test.dart on Ashu's iPhone
```

</details>

### Patrol version

patrol: ^1.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.7
Program adb found in /Users/ashusharma/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by AshuSharma7** [comment]
> Removing `IntegrationTestWidgetsFlutterBinding.ensureInitialized();` at the beginning of the test helped me, but app does not exit when all tests completes

@ziadsarour Example app of patrol doesn't have this line

**Comment by ziadsarour** [comment]
> > Removing `IntegrationTestWidgetsFlutterBinding.ensureInitialized();` at the beginning of the test helped me, but app does not exit when all tests completes
> 
> @ziadsarour Example app of patrol doesn't have this line

I was testing my app before using Patrol and this line was required for integration testing.

If you are upgrading your tests to Patrol and forgot to remove this line (because it is not mentioned anywhere), you might encounter this issue like me

**Comment by ziadsarour** [comment]
If anyone had the same problem has me (script does not exit when all tests completes), this post helped me : https://github.com/leancodepl/patrol/issues/1116#issuecomment-1484773642

In Xcode : ```Product > Scheme > Edit scheme```, in the left panel click ```Test``` then uncheck ```RunnerUITestsLaunchTests``` under ```RunnerUITests```

![Capture d’écran 2023-05-05 à 13 31 45](https://user-images.githubusercontent.com/8212468/236446859-06603905-65ca-4ad6-8eae-8057afb88b15.png)

**Comment by bartekpacia** [comment]
Thanks @ziadsarour for sharing this finding with us :) This indeed looks like the cause of the error. We could do a better job in docs, telling our users to delete the `RunnerUITestsLaunchTests` file. See #948.
