### ISSUE TITLE
error: cannot find type 'GRPCAsyncServerCallContext' in scope    context: GRPCAsyncServerCallContext

### ISSUE THREAD

**Issue by shenaway** [leancodepl/patrol#1253]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

1. Setup the project (refer to https://patrol.leancode.co/native/setup)
2. Connect iOS device and run “patrol test --target integration_test/example_test.dart --verbose” in terminal
3. Show error message as attached log

Sample project: https://drive.google.com/file/d/1CaOhyDSvE7bfRkc2wCj2BT5UCIspN3ly/view?usp=sharing

### Actual results

Show error message as attached log

### Logs

<details>
<summary>Logs</summary>

```
(base) thom-macbook-pro:patrol_test thom$ patrol test --target integration_test/example_test.dart --verbose
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/thom/FlutterProjects/patrol_test/integration_test/example_test.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (RDAPP_Thom_iPhoneXR)
Received 1 device(s) to run on
Received device: RDAPP_Thom_iPhoneXR
Every test target will be run 1 time(s)
Received 2 --dart-define(s) (0 custom, 2 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building app with entrypoint example_test.dart for iOS device (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --target /Users/thom/FlutterProjects/patrol_test/integration_test/example_test.dart --dart-define PATROL_WAIT=0 --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL=example_test.dart
        Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
        Building com.example.patrolTest for device (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
        objc[72129]: Class RemoteXPCPair is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cd660) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484000). One of the two will be used. Which one is undefined.
        objc[72129]: Class RemoteXPCShim is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cd6d8) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484078). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury11XPCEndpoint is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cdda8) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484200). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury15XPCPeerEndpoint is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cde48) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e4842a0). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury19XPCListenerEndpoint is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cdee8) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484340). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury16XPCObjectEncoder is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cdff8) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e4843e0). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury17_XPCObjectEncoder is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5ce0a0) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484488). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury16XPCObjectDecoder is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5ce150) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484538). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury17_XPCObjectDecoder is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5ce1f8) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e4845e0). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury14XPCSideChannel is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5ce538) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484690). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury19RemoteDeviceBrowser is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5ce680) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484740). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury17XPCFileDescriptor is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5ce800) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484878). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury12RemoteDevice is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cea50) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e4849a0). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury13XPCConnection is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cec70) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484af8). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury19RemoteXPCConnection is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cee38) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484c28). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury27RemoteXPCListenerConnection is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cef90) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484d78). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury23RemoteXPCPeerConnection is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cf138) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484f18). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury19SystemXPCConnection is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cf9e8) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e4851e0). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury27SystemXPCListenerConnection is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cfb30) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e485328). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury23SystemXPCPeerConnection is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cfca0) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e485498). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7Mercury15XPCFileTransfer is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cfef8) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e485610). One of the two will be used. Which one is undefined.
        objc[72129]: Class _TtC7MercuryP33_2B1830E49151A2D290BADAC81D16B73411_HandlerBox is implemented in both /Library/Developer/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x10d5cda40) and /Library/Apple/System/Library/PrivateFrameworks/Mercury.framework/Versions/A/Mercury (0x11e484148). One of the two will be used. Which one is undefined.
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:21:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:31:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:41:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:50:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:60:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:69:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:79:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:91:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:100:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:113:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:126:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:152:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:163:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:173:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:183:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:193:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:203:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:213:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:223:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:233:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:243:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:253:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:265:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:275:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:285:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:295:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:307:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:331:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:346:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:366:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:384:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:394:16: error: cannot find type 'GRPCAsyncServerCallContext' in scope
              context: GRPCAsyncServerCallContext
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/AutomatorServer.swift:9:32: error: cannot find type 'Patrol_NativeAutomatorAsyncProvider' in scope
          final class AutomatorServer: Patrol_NativeAutomatorAsyncProvider {
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/thom/.pub-cache/hosted/pub.dev/patrol-1.2.0-dev.2/ios/Classes/AutomatorServer/PatrolServer.swift:55:24: error: type of expression is ambiguous without more context
              let server = try await Server.insecure(group: group).withServiceProviders([provider]).bind(
                           ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        note: Using new build system
        note: Planning
        note: Build preparation complete
        note: Building targets in dependency order
        ** TEST BUILD FAILED **
        
✗ Failed to build app with entrypoint example_test.dart for iOS device (xcodebuild exited with code 65) (8.6s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:123:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:71:5)
<asynchronous suspension>
#4      TestCommand._builderFor.<anonymous closure> (package:patrol_cli/src/commands/test.dart:229:9)
<asynchronous suspension>
#5      _NativeTestRunner.run.runTestsOnDevice (package:patrol_cli/src/test_runner.dart:230:13)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#7      _NativeTestRunner.run (package:patrol_cli/src/test_runner.dart:258:5)
<asynchronous suspension>
#8      TestCommand.run (package:patrol_cli/src/commands/test.dart:189:21)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#11     PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:255:18)
<asynchronous suspension>
#12     patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:65:20)
<asynchronous suspension>
#13     main (file:///Users/thom/.pub-cache/hosted/pub.dev/patrol_cli-1.1.8/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.

```

</details>

### Patrol version

patrol: ^1.2.0-dev.2 

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.8
Program adb found in /Users/thom/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/thom/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 11.7.2 20G1020 darwin-arm64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by bartekpacia** [comment]
Hi, you're using a development version, which we don't support. It's very much in flux.

I appreciate your interest though :)

**Comment by shenaway** [comment]
> Hi, you're using a development version, which we don't support. It's very much in flux.
> 
> I appreciate your interest though :)

Hi,
Patrol 1.1.0 can observe this error too.
Could you check it ?

**Comment by bartekpacia** [comment]
That's strange - we don't see this error.

Please provide a full reproduction sample.

**Comment by shenaway** [comment]
> That's strange - we don't see this error.
> 
> Please provide a full reproduction sample.

Hi, 
Here is sample project
https://drive.google.com/file/d/11GPcuTEZOQmRgoBxw-S21x3E0qNpAqpm/view?usp=sharing
