### ISSUE TITLE
 Didn't find class "androidx.test.runner.AndroidJUnitRunner" on path 

### ISSUE THREAD

**Issue by abdalazeez1** [leancodepl/patrol#1268]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

d

### Actual results

i have run 
`patrol develop --target integration_test/feature/add_product_test.dart`

but is not work and give me error 
the app is install on mobile Samsung A50 android 11 but its not open and not showing Testing start

### Logs

<details>
<summary>Logs</summary>

```
    E/AndroidRuntime(18234): FATAL EXCEPTION: main
        E/AndroidRuntime(18234): Process: com.nbs.*****, PID: 18234
        E/AndroidRuntime(18234): java.lang.RuntimeException: Unable to instantiate instrumentation ComponentInfo{com.nbs.*****.test/androidx.test.runner.AndroidJUnitRunner}: java.lang.ClassNotFoundException: Didn't find class "androidx.test.runner.AndroidJUnitRunner" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~0UZd1J9Z6RRv3fRqnX7M6w==/com.nbs.*******.test-X-MhGvvNEe4qTB1Dqf6Hzg==/base.apk", zip file "/data/app/~~MXIUlTVxR87XK2Mz04ID1Q==/com.nbs.*****-1w9L0-FBgS_4dW1zsaKNaQ==/base.apk"],nativeLibraryDirectories=[/system/lib64]]
        E/AndroidRuntime(18234):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7507)
        E/AndroidRuntime(18234):        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
        E/AndroidRuntime(18234):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
        E/AndroidRuntime(18234):        at android.os.Handler.dispatchMessage(Handler.java:106)
        E/AndroidRuntime(18234):        at android.os.Looper.loop(Looper.java:246)
        E/AndroidRuntime(18234):        at android.app.ActivityThread.main(ActivityThread.java:8653)
        E/AndroidRuntime(18234):        at java.lang.reflect.Method.invoke(Native Method)
        E/AndroidRuntime(18234):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        E/AndroidRuntime(18234):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
        E/AndroidRuntime(18234): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.test.runner.AndroidJUnitRunner" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~0UZd1J9Z6RRv3fRqnX7M6w==/com.nbs.******.test-X-MhGvvNEe4qTB1Dqf6Hzg==/base.apk", zip file "/data/app/~~MXIUlTVxR87XK2Mz04ID1Q==/com.nbs.******-1w9L0-FBgS_4dW1zsaKNaQ==/base.apk"],nativeLibraryDirectories=[/system/lib64]]
        E/AndroidRuntime(18234):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        E/AndroidRuntime(18234):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        E/AndroidRuntime(18234):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        E/AndroidRuntime(18234):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7503)
        E/AndroidRuntime(18234):        ... 8 more
        : 
```

</details>

### Patrol version

patrol: ^1.1.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.9
Program adb found in /usr/bin/adb
Env var $ANDROID_HOME set to /home/abd/Android/Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.7.1, on Ubuntu 22.04.1 LTS 5.19.0-41-generic, locale en_US.UTF-8)
    • Flutter version 3.7.1 on channel stable at /home/abd-alazeez/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (3 months ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
                                                                                                                                                                  Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/abd-alazeez/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/abd-alazeez/Android/Sdk
    • Java binary at: /home/abd-alazeez/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/abd-alazeez/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM A505F (mobile) • RR8M607ENRK • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux       • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-41-generic
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by bartekpacia** [comment]
I mean _reproduction sample_, not your Dart test file. 

This was in the template you used:

![Screenshot 2023-05-11 at 5 14 08 PM](https://github.com/leancodepl/patrol/assets/40357511/83e00055-83aa-47a1-85a1-43c6d835fbf3)

Please read and understand [this](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by bartekpacia** [comment]
Closing because of lack of response.
