### ISSUE TITLE
Patrol build android  - Execution failed for task 'app:mergeExtDexDebug'

### ISSUE THREAD

**Issue by Naweap** [leancodepl/patrol#1322]
### Steps to reproduce

1. Follow the official documentation at: [CI - Firebase Test Lab](https://patrol.leancode.co/ci/firebase-test-lab)
2. Run `patrol build android --target integration_test/example_test.dart`
3. Build fails

### Actual results

An exception is thrown during the build:

`ERROR:D8: Cannot fit requested classes in a single dex file (# methods: 87789 > 65536)
        com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
        The number of method references in a .dex file cannot exceed 64K.
        Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
                at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
                at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
                at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
                at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
                at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
                at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
                at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)`

### Logs

<details>
<summary>Logs</summary>

```
PS C:\dev\src\MyStores\mystores> patrol build android --target integration_test/example_test.dart --verbose 
Verbose mode enabled. More logs will be printed.
Received test target: C:\dev\src\MyStores\mystores\integration_test/example_test.dart
Received 4 --dart-define(s) (0 custom, 4 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_ANDROID_APP_NAME=mystores
Received internal --dart-define: PATROL_TEST_LABEL=example_test.dart
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building apk with entrypoint example_test.dart...
$ .\gradlew.bat :app:assembleDebug -Ptarget=C:\dev\src\MyStores\mystores\integration_test/example_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9bXlzdG9yZXM=,UEFUUk9MX1RFU1RfTEFCRUw9ZXhhbXBsZV90ZXN0LmRhcnQ=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33
        : 
        : This Android Gradle plugin (7.2.0) was tested up to compileSdk = 32
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=33
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 33       
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :flutter_secure_storage:preBuild UP-TO-DATE
        : > Task :flutter_secure_storage:preDebugBuild UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugAidl NO-SOURCE
        : > Task :integration_test:preBuild UP-TO-DATE
        : > Task :integration_test:preDebugBuild UP-TO-DATE
        : > Task :integration_test:compileDebugAidl NO-SOURCE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :shared_preferences_android:preBuild UP-TO-DATE
        : > Task :shared_preferences_android:preDebugBuild UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugAidl NO-SOURCE
        : > Task :url_launcher_android:preBuild UP-TO-DATE
        : > Task :url_launcher_android:preDebugBuild UP-TO-DATE
        : > Task :url_launcher_android:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :flutter_secure_storage:packageDebugRenderscript NO-SOURCE
        : > Task :integration_test:packageDebugRenderscript NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :shared_preferences_android:packageDebugRenderscript NO-SOURCE
        : > Task :url_launcher_android:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :flutter_secure_storage:writeDebugAarMetadata UP-TO-DATE
        : > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :shared_preferences_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :url_launcher_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :flutter_secure_storage:mergeDebugShaders UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugShaders NO-SOURCE
        : > Task :flutter_secure_storage:generateDebugAssets UP-TO-DATE
        : > Task :flutter_secure_storage:packageDebugAssets UP-TO-DATE
        : > Task :integration_test:mergeDebugShaders UP-TO-DATE
        : > Task :integration_test:compileDebugShaders NO-SOURCE
        : > Task :integration_test:generateDebugAssets UP-TO-DATE
        : > Task :integration_test:packageDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :shared_preferences_android:mergeDebugShaders UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugShaders NO-SOURCE
        : > Task :shared_preferences_android:generateDebugAssets UP-TO-DATE
        : > Task :shared_preferences_android:packageDebugAssets UP-TO-DATE
        : > Task :url_launcher_android:mergeDebugShaders UP-TO-DATE
        : > Task :url_launcher_android:compileDebugShaders NO-SOURCE
        : > Task :url_launcher_android:generateDebugAssets UP-TO-DATE
        : > Task :url_launcher_android:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugRenderscript NO-SOURCE
        : > Task :flutter_secure_storage:generateDebugResValues UP-TO-DATE
        : > Task :flutter_secure_storage:generateDebugResources UP-TO-DATE
        : > Task :flutter_secure_storage:packageDebugResources UP-TO-DATE
        : > Task :integration_test:compileDebugRenderscript NO-SOURCE
        : > Task :integration_test:generateDebugResValues UP-TO-DATE
        : > Task :integration_test:generateDebugResources UP-TO-DATE
        : > Task :integration_test:packageDebugResources UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugRenderscript NO-SOURCE
        : > Task :shared_preferences_android:generateDebugResValues UP-TO-DATE
        : > Task :shared_preferences_android:generateDebugResources UP-TO-DATE
        : > Task :shared_preferences_android:packageDebugResources UP-TO-DATE
        : > Task :url_launcher_android:compileDebugRenderscript NO-SOURCE
        : > Task :url_launcher_android:generateDebugResValues UP-TO-DATE
        : > Task :url_launcher_android:generateDebugResources UP-TO-DATE
        : > Task :url_launcher_android:packageDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :flutter_secure_storage:extractDeepLinksDebug UP-TO-DATE
        : > Task :flutter_secure_storage:processDebugManifest UP-TO-DATE
        : > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:processDebugManifest UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :shared_preferences_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :shared_preferences_android:processDebugManifest UP-TO-DATE
        : > Task :url_launcher_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :url_launcher_android:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugLibraryResources UP-TO-DATE
        : > Task :flutter_secure_storage:parseDebugLocalResources UP-TO-DATE
        : > Task :flutter_secure_storage:generateDebugRFile UP-TO-DATE
        : > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
        : > Task :integration_test:parseDebugLocalResources UP-TO-DATE
        : > Task :integration_test:generateDebugRFile UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :shared_preferences_android:parseDebugLocalResources UP-TO-DATE
        : > Task :shared_preferences_android:generateDebugRFile UP-TO-DATE
        : > Task :url_launcher_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :url_launcher_android:parseDebugLocalResources UP-TO-DATE
        : > Task :url_launcher_android:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :flutter_secure_storage:generateDebugBuildConfig UP-TO-DATE
        : > Task :flutter_secure_storage:javaPreCompileDebug UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :flutter_secure_storage:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :integration_test:generateDebugBuildConfig UP-TO-DATE
        : > Task :integration_test:javaPreCompileDebug UP-TO-DATE
        : > Task :integration_test:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac
        : > Task :shared_preferences_android:generateDebugBuildConfig UP-TO-DATE
        : > Task :shared_preferences_android:javaPreCompileDebug UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :shared_preferences_android:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :url_launcher_android:generateDebugBuildConfig UP-TO-DATE
        : > Task :url_launcher_android:javaPreCompileDebug UP-TO-DATE
        : > Task :url_launcher_android:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :url_launcher_android:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :app:processDebugJavaRes NO-SOURCE
        : > Task :flutter_secure_storage:processDebugJavaRes NO-SOURCE
        : > Task :flutter_secure_storage:bundleLibResDebug NO-SOURCE
        : > Task :integration_test:processDebugJavaRes NO-SOURCE
        : > Task :integration_test:bundleLibResDebug NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :shared_preferences_android:processDebugJavaRes NO-SOURCE
        : > Task :shared_preferences_android:bundleLibResDebug NO-SOURCE
        : > Task :url_launcher_android:processDebugJavaRes NO-SOURCE
        : > Task :url_launcher_android:bundleLibResDebug NO-SOURCE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :shared_preferences_android:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :patrol:bundleLibResDebug
        : > Task :url_launcher_android:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :flutter_secure_storage:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :flutter_secure_storage:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :flutter_secure_storage:mergeDebugNativeLibs NO-SOURCE
        : > Task :flutter_secure_storage:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :integration_test:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :integration_test:mergeDebugNativeLibs NO-SOURCE
        : > Task :integration_test:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :shared_preferences_android:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :shared_preferences_android:mergeDebugNativeLibs NO-SOURCE
        : > Task :shared_preferences_android:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :url_launcher_android:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :url_launcher_android:mergeDebugNativeLibs NO-SOURCE
        : > Task :url_launcher_android:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug
        : > Task :patrol:bundleLibRuntimeToJarDebug
        : 
        : > Task :app:mergeExtDexDebug FAILED
        ERROR:D8: Cannot fit requested classes in a single dex file (# methods: 87789 > 65536)
        com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
        The number of method references in a .dex file cannot exceed 64K.
        Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
                at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
                at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
                at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
                at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
                at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
                at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
                at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
                at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
                at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
                at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
                at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
                at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
                at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
                at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
                at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
                at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:205)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
                at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
                at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
                at org.gradle.internal.Factories$1.create(Factories.java:31)
                at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
                at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
                at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:114)
                at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
                at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
                at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
                at Version.fakeStackEntry(Version_3.2.47.java:0)
                at com.android.tools.r8.internal.ci.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:68)
                at com.android.tools.r8.internal.ci.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:28)
                at com.android.tools.r8.internal.ci.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:27)
                at com.android.tools.r8.internal.ci.b(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:3)
                at com.android.tools.r8.D8.run(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:11)
                at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
                ... 38 more
        Caused by: com.android.tools.r8.internal.a: Cannot fit requested classes in a single dex file (# methods: 87789 > 65536)
                at com.android.tools.r8.internal.tQ.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:14)
                at com.android.tools.r8.internal.tQ.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:22)
                at com.android.tools.r8.internal.fZ.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:560)
                at com.android.tools.r8.internal.bZ.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:7)
                at com.android.tools.r8.internal.o2.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:383)
                at com.android.tools.r8.internal.o2.c(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:54)
                at com.android.tools.r8.D8.d(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:763)
                at com.android.tools.r8.D8.b(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:1)
                at com.android.tools.r8.internal.ci.a(R8_3.2.47_ebadcf1df6fbed6005a238b8399b2cd411e753b60758261060e399f9498872a5:24)
                ... 41 more

        : 
        : > Task :app:compileDebugKotlin

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:mergeExtDexDebug'.
        > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
           > There was a failure while executing work items
              > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
                 > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
                   The number of method references in a .dex file cannot exceed 64K.
                   Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 18s
        : 
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
        : 
        : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        : 
        : See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
        : 116 actionable tasks: 10 executed, 106 up-to-date
✗ Failed to build apk with entrypoint example_test.dart (Gradle build failed with code 1) (19.5s)
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      BuildAndroidCommand.run (package:patrol_cli/src/commands/build_android.dart:117:7)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:311:18)
<asynchronous suspension>
#6      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:255:18)
<asynchronous suspension>
#7      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:65:20)
<asynchronous suspension>
#8      main (file:///C:/Users/rouechej/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-1.1.11/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      BuildAndroidCommand.run (package:patrol_cli/src/commands/build_android.dart:117:7)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:311:18)
<asynchronous suspension>
#6      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:255:18)
<asynchronous suspension>
#7      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:65:20)
<asynchronous suspension>
#8      main (file:///C:/Users/rouechej/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-1.1.11/bin/main.dart:6:20)
<asynchronous suspension>

PS C:\dev\src\MyStores\mystores> 
```

</details>

### Patrol version

patrol_cli v1.1.11

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.11
Program adb found in C:\lib\android-sdk\platform-tools\adb.exe
Env var $ANDROID_HOME set to C:\lib\android-sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.2965], locale en-GB)
    • Flutter version 3.7.12 on channel stable at C:\dev\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\lib\android-sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\lib\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[√] VS Code
    • VS Code at C:\Users\rouechej\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] VS Code, 64-bit edition (version 1.78.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by bartekpacia** [comment]
Congrats! You've just encountered the famous limitation of dex.

This is not related to Patrol. Please see this [question on SO](https://stackoverflow.com/questions/48804504/what-is-64k-method-counts-limit-for-an-android-application-and-their-graph-of-co).
