### ISSUE TITLE
Tests run on Android successfully but fail on iOS

### ISSUE THREAD

**Issue by ahmdaeyz** [leancodepl/patrol#1330]
### Steps to reproduce

Hello, 
For some reason our tests are failing on iOS and passing on Android. This is how our test file looks like:

```dart
Future<void> main() async {
  setUp(() async {
    final binding = TestWidgetsFlutterBinding.instance;
    await initializeApp(binding: binding);
    await Locator.instance.registerDependencies();
    await LocalCache.instance.deleteAll();
  });
  tearDown(() {
    Locator.instance.getIt.reset();
  });

  patrolTest('''Given: A fresh install
                When: The user open the app and login
                Then: The user should land on the home page''',
      nativeAutomation: true,
      framePolicy: LiveTestWidgetsFlutterBindingFramePolicy.benchmarkLive,
      (PatrolTester $) async {
    await createApp($);
    final permissionDialogExists = await $.native
        .isPermissionDialogVisible(timeout: Duration(seconds: 10));
    if (permissionDialogExists) {
      await $.native.grantPermissionWhenInUse();
    }
    await loginWithAnExistingUser(
      $,
    );
  });
}
``` 

```dart
Future<void> loginWithAnExistingUser(PatrolTester $) async {
  await $.pumpAndSettle();
  await $.waitUntilExists($(OnBoardingPage), timeout: Duration(minutes: 5));
  await bypassOnBoarding($.tester);
  await $.waitUntilVisible(find.byType(PhoneRegistrationPage));
  await startRegisterFlowWithExistUser($);
}
```

```dart
Future<void> bypassOnBoarding(WidgetTester tester) async {
  final skipButton = find.byKey(const Key('onboardPage_skip_button'));
  await tester.tap(skipButton);
  await tester.pumpAndSettle();
}
```

```dart 
Future<void> startRegisterFlowWithExistUser(PatrolTester $) async {
  expect(find.byType(PhoneRegistrationPage), findsOneWidget);

  final phoneField = find.byType(TextFormField).first;
  await $.tester.enterText(phoneField, "000000000");
  await $.pump(Duration(milliseconds: 300));
  expect(find.byType(CommonButton), findsOneWidget);

  final submitButton = find.byType(CommonButton).first;
  await $.tap(submitButton);
  await $.tester.pumpAndSettle();

  await Future.delayed(Duration(seconds: 3));
  await $.tester.pumpAndSettle();

  final registerOtpField = find.byType(PinCodeTextField).first;
  await $.tester.enterText(registerOtpField, "0000");

  await $.waitUntilExists($(LoginVerifiedPage), timeout: Duration(seconds: 10));

  final pinField = find.byType(PinCodeTextField).first;

  await $.tester.enterText(pinField, "0000");

  try {
    await $.waitUntilExists($(EnableNotificationsSheet),
        timeout: Duration(seconds: 25));
    await $.tap(find.byKey(const Key('enableNotificationsLater')));
    await $.pumpAndSettle();
  } catch (e) {
    ;
  }
  await $.waitUntilExists($(HomePage), timeout: Duration(seconds: 25));

  expect(find.byType(HomePage), findsOneWidget);
}
```

This works perfectly fine on Android (along with 2 other tests in the same file (the above is just a sample)).

### Actual results

We keep getting these errors although we await all the calls to the PatrolTester and the WidgetTester on it.

### Logs

<details>
<summary>Logs</summary>

```
Guarded function conflict.
        You must use "await" with all Future-returning test APIs.
        The guarded method "tap" from class PatrolTester was called from
        file:///Users/ahmdaeyz/development/projects/awaed_mobile/integration_test/auth/auth_test.dart on
        line 125.
        Then, the "pumpAndSettle" method from class WidgetTester was called from
        package:patrol/src/custom_finders/patrol_tester.dart on line 174.
        The first method (PatrolTester.tap) had not yet finished executing at the time that the second
        method (WidgetTester.pumpAndSettle) was called. Since both are guarded, and the second was not a
        nested call inside the first, the first must complete its execution before the second can be called.
        Typically, this is achieved by putting an "await" statement in front of the call to the first.
        flutter:
        When the first method (PatrolTester.tap) was called, this was the stack:
        #0      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:66:54)
        #1      PatrolTester.tap (package:patrol/src/custom_finders/patrol_tester.dart:225:27)
        #2      startRegisterFlowWithExistUser (file:///Users/ahmdaeyz/development/projects/awaed_mobile/integration_test/auth/auth_test.dart:125:11)
        <asynchronous suspension>
        #3      loginWithAnExistingUser (file:///Users/ahmdaeyz/development/projects/awaed_mobile/integration_test/common.dart:20:3)
        <asynchronous suspension>
        #4      main.<anonymous closure> (file:///Users/ahmdaeyz/development/projects/awaed_mobile/integration_test/auth/auth_test.dart:51:5)
        <asynchronous suspension>
        #5      patrolTest.<anonymous closure> (package:patrol/src/common.dart:83:7)
        <asynchronous suspension>
        #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
        <asynchronous suspension>
        #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)
        <asynchronous suspension>
        flutter:
        When the exception was thrown, this was the stack:
        #0      TestAsyncUtils.guardSync (package:flutter_test/src/test_async_utils.dart:270:5)
        #1      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:60:5)
        #2      WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:702:27)
        #3      PatrolTester.pumpAndSettle (package:patrol/src/custom_finders/patrol_tester.dart:174:18)
        #4      loginWithAnExistingUser (file:///Users/ahmdaeyz/development/projects/awaed_mobile/integration_test/common.dart:16:11)
        #5      main.<anonymous closure> (file:///Users/ahmdaeyz/development/projects/awaed_mobile/integration_test/auth/auth_test.dart:68:11)
        <asynchronous suspension>
        #6      patrolTest.<anonymous closure> (package:patrol/src/common.dart:83:7)
        <asynchronous suspension>
        #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
        <asynchronous suspension>
        #8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)
        <asynchronous suspension>
        flutter:
        The test description was:
          Given: A fresh install and being able to login
                          When: The user goes to the more tab and tab logout
                          Then: The app logs the user out and the user should land on the phone registration
          page
        ════════════════════════════════════════════════════════════════════════════════════════════════════
        00:14 +0 -1: Given: A fresh install and being able to login
                        When: The user goes to the more tab and tab logout
                        Then: The app logs the user out and the user should land on the phone registration page [E]
          Test failed. See exception logs above.
          The test description was: Given: A fresh install and being able to login
                          When: The user goes to the more tab and tab logout
                          Then: The app logs the user out and the user should land on the phone registration page
        flutter:
        00:14 +0 -2: Given: A fresh install and not having an account
                        When: The user goes through the registration process
                        Then: The process succeeds and the user lands on the home page
        00:14 +0 -2: Given: A fresh install
                        When: The user open the app and login
                        Then: The user should land on the home page
        ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        The following assertion was thrown running a test (but after the test had completed):
        'package:flutter_test/src/binding.dart': Failed assertion: line 1866 pos 12: 'inTest': is not true.
        flutter:
        When the exception was thrown, this was the stack:
        #2      LiveTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1866:12)
        #3      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:709:23)
        <asynchronous suspension>
        #4      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:114:7)
        <asynchronous suspension>
        (elided 2 frames from class _AssertionError)
        ════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Patrol version

patrol: ^1.1.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.10
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 12.6 21G115 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by ahmdaeyz** [comment]
I don't know if this might help, We are using `go_router` and they are calling ` WidgetsFlutterBinding.ensureInitialized()` in the the constructor as follows:

File: `router.dart`
```dart
GoRouter({
    required List<RouteBase> routes,
    // TODO(johnpryan): Change to a route, improve error API
    // See https://github.com/flutter/flutter/issues/108144
    GoRouterPageBuilder? errorPageBuilder,
    GoRouterWidgetBuilder? errorBuilder,
    GoRouterRedirect? redirect,
    Listenable? refreshListenable,
    int redirectLimit = 5,
    bool routerNeglect = false,
    String? initialLocation,
    Object? initialExtra,
    List<NavigatorObserver>? observers,
    bool debugLogDiagnostics = false,
    GlobalKey<NavigatorState>? navigatorKey,
    String? restorationScopeId,
  })
      : backButtonDispatcher = RootBackButtonDispatcher(),
        assert(
        initialExtra == null || initialLocation != null,
        'initialLocation must be set in order to use initialExtra',
        ) {
    setLogging(enabled: debugLogDiagnostics);
    WidgetsFlutterBinding.ensureInitialized();

    navigatorKey ??= GlobalKey<NavigatorState>();

    _routeConfiguration = RouteConfiguration(
      routes: routes,
      topRedirect: redirect ?? (_, __) => null,
      redirectLimit: redirectLimit,
      navigatorKey: navigatorKey,
    );

    _routeInformationParser = GoRouteInformationParser(
      configuration: _routeConfiguration,
      debugRequireGoRouteInformationProvider: true,
    );

    _routeInformationProvider = GoRouteInformationProvider(
      initialRouteInformation: RouteInformation(
        // TODO(chunhtai): remove this ignore and migrate the code
        // https://github.com/flutter/flutter/issues/124045.
        // ignore: deprecated_member_use
        location: _effectiveInitialLocation(initialLocation),
        state: initialExtra,
      ),
      refreshListenable: refreshListenable,
    );

    _routerDelegate = GoRouterDelegate(
      configuration: _routeConfiguration,
      errorPageBuilder: errorPageBuilder,
      errorBuilder: errorBuilder,
      routerNeglect: routerNeglect,
      observers: <NavigatorObserver>[
        ...observers ?? <NavigatorObserver>[],
      ],
      restorationScopeId: restorationScopeId,
      // wrap the returned Navigator to enable GoRouter.of(context).go() et al,
      // allowing the caller to wrap the navigator themselves
      builderWithNav: (BuildContext context, Widget child) =>
          InheritedGoRouter(goRouter: this, child: child),
    );
    _routerDelegate.addListener(_handleStateMayChange);

    assert(() {
      log.info('setting initial location $initialLocation');
      return true;
    }());
  }
```

**Comment by ahmdaeyz** [comment]
I kind of figured this out. I had some un awaited asynchronous operations especially requesting permissions. Closing since it is no longer relevant.
