### ISSUE TITLE
FormatException: Missing extension byte on Sample Project

### ISSUE THREAD

**Issue by ocakliemre** [leancodepl/patrol#1334]
### Steps to reproduce

1. Clone https://github.com/leancodepl/patrol/blob/master/example
2. Run patrol test --target integration_test/example_test.dart 

### Actual results

I am getting the following error both in my own project and in the sample project.

`
• Building apk with entrypoint example_test.dart...
Unhandled exception:
FormatException: Missing extension byte (at offset 3)                             
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#16     _StreamController._add (dart:async/stream_controller.dart:650:7)
#17     _StreamController.add (dart:async/stream_controller.dart:598:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
No device specified, using the first one (emulator-5554)
Every test target will be run 1 time(s)
• Building apk with entrypoint example_test.dart...
Unhandled exception:
FormatException: Missing extension byte (at offset 3)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#16     _StreamController._add (dart:async/stream_controller.dart:650:7)
#17     _StreamController.add (dart:async/stream_controller.dart:598:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
`
[pub_log.txt](https://github.com/leancodepl/patrol/files/11651019/pub_log.txt)

### Logs

<details>
<summary>Logs</summary>

```
 PS C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example> patrol test --target integration_test/example_test.dart --verbose
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on
Received device: emulator-5554
Every test target will be run 1 time(s)
Received 6 --dart-define(s) (0 custom, 6 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building apk with entrypoint example_test.dart...
$ .\gradlew.bat :app:assembleDebug -Ptarget=C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUU
k9MX0FQUF9QQUNLQUdFX05BTUU9cGwubGVhbmNvZGUucGF0cm9sLmV4YW1wbGU=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9cGwubGVhbmNvZGUucGF0cm9sLkV4YW1wbGU=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9UGF0cm9sIGV4YW1wbGU=,UEFUUk9MX0lPU19BUFBfTkFNRT1QY
XRyb2wgZXhhbXBsZQ==,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUw9ZXhhbXBsZV90ZXN0LmRhcnQ=
        : Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

Unhandled exception:
FormatException: Missing extension byte (at offset 609)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
FINE: Pub 3.0.3
FINE: Package Config up to date.
FINE: Package Config up to date.
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on                                                     
Received device: emulator-5554                                                     
Every test target will be run 1 time(s)                                            
Received 6 --dart-define(s) (0 custom, 6 internal)                                 
Received internal --dart-define: PATROL_WAIT=0                                     
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building apk with entrypoint example_test.dart...
$ .\gradlew.bat :app:assembleDebug -Ptarget=C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUU
k9MX0FQUF9QQUNLQUdFX05BTUU9cGwubGVhbmNvZGUucGF0cm9sLmV4YW1wbGU=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9cGwubGVhbmNvZGUucGF0cm9sLkV4YW1wbGU=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9UGF0cm9sIGV4YW1wbGU=,UEFUUk9MX0lPU19BUFBfTkFNRT1QY
XRyb2wgZXhhbXBsZQ==,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUw9ZXhhbXBsZV90ZXN0LmRhcnQ=

        FAILURE: Build failed with an exception.
Unhandled exception:
FormatException: Missing extension byte (at offset 576)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
PS C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example> patrol test --target integration_test/example_test.dart --verbose
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on
Received device: emulator-5554
Every test target will be run 1 time(s)
Received 6 --dart-define(s) (0 custom, 6 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building apk with entrypoint example_test.dart...
$ .\gradlew.bat :app:assembleDebug -Ptarget=C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUU
k9MX0FQUF9QQUNLQUdFX05BTUU9cGwubGVhbmNvZGUucGF0cm9sLmV4YW1wbGU=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9cGwubGVhbmNvZGUucGF0cm9sLkV4YW1wbGU=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9UGF0cm9sIGV4YW1wbGU=,UEFUUk9MX0lPU19BUFBfTkFNRT1QY
XRyb2wgZXhhbXBsZQ==,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUw9ZXhhbXBsZV90ZXN0LmRhcnQ=

        FAILURE: Build failed with an exception.
                                                
        * Where:                                
Unhandled exception:                            
FormatException: Missing extension byte (at offset 564)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#16     _StreamController._add (dart:async/stream_controller.dart:650:7)
#17     _StreamController.add (dart:async/stream_controller.dart:598:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
FINE: Pub 3.0.3
FINE: Package Config up to date.
FINE: Package Config up to date.
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on
Received device: emulator-5554
Every test target will be run 1 time(s)
Received 6 --dart-define(s) (0 custom, 6 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building apk with entrypoint example_test.dart...
$ .\gradlew.bat :app:assembleDebug -Ptarget=C:\Users\HP\Desktop\Emre\02-Projeler\sample.flutter.project\patrol\packages\patrol\example\integration_test/example_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUU
k9MX0FQUF9QQUNLQUdFX05BTUU9cGwubGVhbmNvZGUucGF0cm9sLmV4YW1wbGU=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9cGwubGVhbmNvZGUucGF0cm9sLkV4YW1wbGU=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9UGF0cm9sIGV4YW1wbGU=,UEFUUk9MX0lPU19BUFBfTkFNRT1QY
XRyb2wgZXhhbXBsZQ==,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUw9ZXhhbXBsZV90ZXN0LmRhcnQ=

        FAILURE: Build failed with an exception.

Unhandled exception:
FormatException: Missing extension byte (at offset 574)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#16     _StreamController._add (dart:async/stream_controller.dart:650:7)
#17     _StreamController.add (dart:async/stream_controller.dart:598:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
IO  : Writing 6684 characters to text file C:\Users\HP\AppData\Local\Pub\Cache\log\pub_log.txt.
MSG : Logs written to C:\Users\HP\AppData\Local\Pub\Cache\log\pub_log.txt.

```

</details> 
[pub_log.txt](https://github.com/leancodepl/patrol/files/11650965/pub_log.txt)

### Patrol version

patrol: ^1.1.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
patrol doctor
Patrol CLI version: 1.1.11
Program adb found in C:\Users\HP\AppData\Local\Android\Sdk\platform-tools\adb.exe
Env var $ANDROID_HOME set to C:\Users\HP\AppData\Local\Android\Sdk\platform-tools\

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
flutter doctor --verbose
[√] Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version 10.0.19045.2965], locale tr-TR)
    • Flutter version 3.10.3 on channel stable at C:\src\flutter                                  
    • Upstream repository https://github.com/flutter/flutter.git                                  
    • Framework revision f92f44110e (3 days ago), 2023-06-01 18:17:33 -0500                       
    • Engine revision 2a3401c9bb                                                                  
    • Dart version 3.0.3                                                                          
    • DevTools version 2.23.1                                             
                                                                          
[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\HP\AppData\Local\Android\Sdk\platform-tools\
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.90
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.37

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by ha6-6ru** [comment]
I also encountered the same error and resolved it by changing the language settings on Windows from Japanese to English. Though it's closed now, just for your reference.

environment is
patrol v2.2.0
patrol_cli v2.1.0
Flutter 3.10.6
Dart 3.0.6
