### ISSUE TITLE
Error: xcodebuild exited with code 65

### ISSUE THREAD

**Issue by Naweap** [leancodepl/patrol#1338]
### Steps to reproduce

Apparently a few people have already faced this issue. However, I didn't find any valuable post regarding this error. Either people were not replying or not providing useful information for debugging. For this reason, I'm posting again today.

1. Follow the official documentation at [Native automation](https://patrol.leancode.co/getting-started/native) and [CI - Firebase Test Lab](https://patrol.leancode.co/ci/firebase-test-lab)
3. Run `patrol build ios --target integration_test/example_test.dart --verbose`
4. Build fails

### Actual results

An exception is thrown during the build:
`Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:123:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:71:5)
<asynchronous suspension>
#4      BuildIOSCommand.run (package:patrol_cli/src/commands/build_ios.dart:124:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:311:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:255:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:65:20)
<asynchronous suspension>
#9      main (file:///Users/username/.pub-cache/hosted/pub.dev/patrol_cli-1.1.11/bin/main.dart:6:20)
<asynchronous suspension>`

### Logs

<details>
<summary>Logs</summary>

```
username@PC appname % patrol build ios --target integration_test/example_test.dart --verbose 
Verbose mode enabled. More logs will be printed.
Received test target: /Users/username/dev/src/appname/appname/integration_test/example_test.dart
Received 5 --dart-define(s) (0 custom, 5 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.appname
Received internal --dart-define: PATROL_IOS_APP_NAME=appname
Received internal --dart-define: PATROL_TEST_LABEL=example_test.dart
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building app with entrypoint example_test.dart for iOS device (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --target /Users/username/dev/src/appname/appname/integration_test/example_test.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_BUNDLE_ID=com.example.appname --dart-define PATROL_IOS_APP_NAME=appname --dart-define PATROL_TEST_LABEL=example_test.dart --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
        Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
        Building com.example.appname for device (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
        2023-06-08 13:32:23.531 xcodebuild[52531:319897] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
        note: Building targets in dependency order
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOHTTP1' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOHTTP2' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOSSL' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOAtomics' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOWindows' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOPosix' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOHPACK' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'Logging' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOCore' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOFoundationCompat' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CGRPCZlib' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOBoringSSLShims' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOBoringSSL' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOLinux' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIO' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOHTTPParser' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOExtras' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOConcurrencyHelpers' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Runner.xcodeproj: error: No profiles for 'com.example.appname.RunnerUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.appname.RunnerUITests.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOEmbedded' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftProtobuf' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOTransportServices' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOTLS' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIODarwin' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target '_NIODataStructures' from project 'Pods')
        /Users/username/dev/src/appname/appname/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'gRPC-Swift' from project 'Pods')
        note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        ** TEST BUILD FAILED **

✗ Failed to build app with entrypoint example_test.dart for iOS device (xcodebuild exited with code 65) (31.3s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:123:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:71:5)
<asynchronous suspension>
#4      BuildIOSCommand.run (package:patrol_cli/src/commands/build_ios.dart:124:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:311:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:255:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:65:20)
<asynchronous suspension>
#9      main (file:///Users/username/.pub-cache/hosted/pub.dev/patrol_cli-1.1.11/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:123:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:71:5)
<asynchronous suspension>
#4      BuildIOSCommand.run (package:patrol_cli/src/commands/build_ios.dart:124:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:311:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:255:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:65:20)
<asynchronous suspension>
#9      main (file:///Users/username/.pub-cache/hosted/pub.dev/patrol_cli-1.1.11/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

patrol: 1.1.4
patrol_cli v1.1.11

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
username@PC appname % patrol doctor 
Patrol CLI version: 1.1.11
Program adb not found 
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
Program ios-deploy found in /usr/local/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
username@PC appname % flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.3.1 22E261 darwin-x64, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.78.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by bartekpacia** [comment]
Hi, thanks for this detailed bug report.

This is the problem:

```
error: No profiles for 'com.example.appname.RunnerUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.appname.RunnerUITests.xctrunner'.
```

You need to open your `ios` project in Xcode and manually set up codesigning. Our docs are lacking in this matter, I agree. We'll improve them – see #1189.

**Comment by Naweap** [comment]
> Hi, thanks for this detailed bug report.
> 
> This is the problem:
> 
> ```
> error: No profiles for 'com.example.appname.RunnerUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.appname.RunnerUITests.xctrunner'.
> ```
> 
> You need to open your `ios` project in Xcode and manually set up codesigning. Our docs are lacking in this matter, I agree. We'll improve them – see #1189.

Thanks for your quick reply and pointing out the issue.

At the moment, I'm using a single provisioning profile. However, this profile can only sign a specific bundle ID (which is the app bundle ID). Also, I guess each target should have a unique bundle ID. That said, does it mean I should create another provisioning profile to sign RunnerUITests (which is the UI tests runner)?

Thanks in advance.

**Comment by bartekpacia** [comment]
Yes, you should create a new provisioning profile for RunnerUITests. In general, there should be no errors/warnings in Xcode regarding code signing.

Please let me know if you make any progress. I'll do my best to help.

**Comment by Naweap** [comment]
I've been able to deal with the provisioning profiles and certificates. The build process is now successfully. Thanks for the great support as always!

**Comment by Naweap** [comment]
Close as solved
