### ISSUE TITLE
Patrol develop hot restart failed

### ISSUE THREAD

**Issue by Kendru98** [leancodepl/patrol#1362]
### Steps to reproduce

1. Clone cryptoPro repo
 2. Start Android emulator Pixel_3a_API33_arm64-v8a
3. Run test with patrol develop

### Actual results

![image](https://github.com/leancodepl/patrol/assets/82384301/8ff2d1d4-5a93-4758-8a82-75249beee7d8)

### Logs

<details>
<summary>Logs</summary>

```
 E/flutter (23239): [ERROR:flutter/shell/common/shell.cc(89)] Dart Error: Can't load Kernel binary: Invalid SDK hash.
        E/flutter (23239): [ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
        E/flutter (23239): [ERROR:flutter/runtime/runtime_controller.cc(422)] Could not create root isolate.
        : Performing hot restart...                                       
        : Restarted application in 2 964ms.
        : Application finished.
        hot restart failed to complete: _flutter.runInView: (-32000) Could not run configuration in engine.
        #0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1822:45)
        #1      VmService._call (package:vm_service/src/vm_service.dart:2366:21)
        #2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2337:14)
        #3      VmService.callMethod (package:vm_service/src/vm_service.dart:2319:12)
        #4      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:529:28)
        #5      FlutterVmService.runInView (package:flutter_tools/src/vmservice.dart:608:11)
        <asynchronous suspension>
        #6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
        <asynchronous suspension>
        #7      HotRunner._launchInView (package:flutter_tools/src/run_hot.dart:548:5)
        <asynchronous suspension>
        #8      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
        <asynchronous suspension>
        #9      HotRunner._launchFromDevFS (package:flutter_tools/src/run_hot.dart:568:5)
        <asynchronous suspension>
        #10     HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:669:5)
        <asynchronous suspension>
        #11     HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:790:16)
        <asynchronous suspension>
        #12     HotRunner.restart (package:flutter_tools/src/run_hot.dart:730:38)
        <asynchronous suspension>
        #13     TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1781:40)
        <asynchronous suspension>
        #14     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1821:7)
        <asynchronous suspension>

        : Waiting for a new connection from Flutter on sdk gphone64 arm64...
        Error connecting to the service protocol: Exception: connection to device ended too early

```

</details>

### Patrol version

2.0.0-dev.2

### Patrol Doctor output

<details>
<summary>Patrol CLI version: 2.0.0-dev.2
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
</summary>

```

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.3, on macOS 12.6 21G115 darwin-arm64, locale pl-PL)
    • Flutter version 3.10.3 on channel stable at /Users/szymonkwiatek/fvm/versions/3.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (2 weeks ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/szymonkwiatek/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/szymonkwiatek/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.61.20230301

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by Kendru98** [comment]
After simulator reset it working 🤡

**Comment by bartekpacia** [comment]
XD
