### ISSUE TITLE
patrolAppService has not been initialized

### ISSUE THREAD

**Issue by pferrell3164** [leancodepl/patrol#1392]
### Steps to reproduce

1. clone GitHub.com/leancodepl/patrol/tree/master
2. patrol test --target integration_test/webview_hackernews_test.dart

### Actual results

test launches on phone and hangs on "Test Starting" page

### Logs

<details>
<summary>Logs</summary>

```
/flutter ( 9826): PatrolBinding: tearDown(): count: 2, results: {: {"methodName":"interacts with the orange website in a webview","details":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\nThe following LateError was thrown running a test:\nLateInitializationError: Field 'patrolAppService' has not been\ninitialized.\n\nWhen the exception was thrown, this was the stack:\n#0      PatrolBinding.patrolAppService (package:patrol/src/binding.dart)\n#1      patrolTest.<anonymous closure> (package:patrol/src/common.dart:105:56)\n#2      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)\n<asynchronous suspension>\n#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)\n<asynchronous suspension>\n\nThe test description was:\n  interacts with the orange website in a webview\n═════════════════════════════════════�
I/flutter ( 9826):   LateInitializationError: Field 'patrolAppService' has not been initialized.
I/flutter ( 9826):   package:patrol/src/binding.dart                   PatrolBinding.patrolAppService
I/flutter ( 9826):   package:patrol/src/binding.dart 84:41             new PatrolBinding.<fn>
I/flutter ( 9826):   dart:async/future.dart 305:31                     new Future.sync
I/flutter ( 9826):   package:test_api/src/backend/invoker.dart 236:18  Invoker.runTearDowns.<fn>.<fn>
I/flutter ( 9826):   package:test_api/src/backend/invoker.dart 258:17  Invoker._waitForOutstandingCallbacks.<fn>
I/flutter ( 9826):   dart:async/zone.dart 1399:13                      _rootRun
I/flutter ( 9826):   dart:async/zone.dart 1301:19                      _CustomZone.run
I/flutter ( 9826):   dart:async/zone.dart 1804:10                      _runZoned
I/flutter ( 9826):   dart:async/zone.dart 1747:10                      runZoned
I/flutter ( 9826):   package:test_api/src/backend/invoker.dart 254:5   Invoker._waitForOutstandingCallbacks
I/flutter ( 9826):   package:test_api/src/backend/invoker.dart 235:9   Invoker.runTearDowns.<fn>
I/flutter ( 9826):   ===== asynchronous gap ===========================
I/flutter ( 9826):   package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
I/flutter ( 9826):   
I/flutter ( 9826): 00:00 +0 -1: (tearDownAll)
I/flutter ( 9826): 00:00 +1 -1: Some tests failed.

```

</details>

### Patrol version

patrol version from GitHub.com/leandcodepl/patrol/master

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.11
Program adb found in /Users/xyz/library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/xyz/library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Program ios-deploy not found (install with `brew install ios-deploy`)

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E261 darwin-x64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/xyz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (10 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xyz/library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/xyz/library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

```

</details>

**Comment by bartekpacia** [comment]
> Patrol CLI version: 1.1.11

You're using wrong Patrol CLI version. See [example app's README](https://github.com/leancodepl/patrol/blob/master/packages/patrol/example/README.md).
