### ISSUE TITLE
storyview package having issue with stories test navigation on tap

### ISSUE THREAD

**Issue by AshuSharma7** [leancodepl/patrol#1400]
### Steps to reproduce

1. Download this file: https://github.com/blackmann/story_view/blob/master/example/example.dart
2. Write test cases for changing the stories on tap using offset values
3. Run the test

### Actual results

It's giving error that pumpAndSettle timed out but it should switch to next story

### Logs

<details>
<summary>Logs</summary>

```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
pumpAndSettle timed out

When the exception was thrown, this was the stack:
#0      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:677:11)
<asynchronous suspension>
#1      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
<asynchronous suspension>

The test description was:
Dashboard
═════════════════════════════════════════════════════════════════

at pl.leancode.patrol.PatrolTestRunner.run(PatrolTestRunner.kt:76)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2367)
```

</details>

### Patrol version

patrol: ^1.1.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Program adb found in /Users/ashusharma/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/ashusharma/Library/Android/sdk/
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
This issue is not reproducible. Please read & understand the issue template.

> Write test cases for changing the stories on tap using offset values

Please provide such a test.
