### ISSUE TITLE
Can't run Patrol tests on non-latest iOS version

### ISSUE THREAD

**Issue by eroshinn** [leancodepl/patrol#1441]
Hello!

First of all, thanks a lot for an awesome framework, it adds crucial missing features to the Flutter integration tests thus making our lives much easier

### Steps to reproduce

1) Create a default Flutter project
2) Integrate Patrol, use the default example_test.dart
3) Launch any iOS simulator with non-latest iOS version (e.g. 15.5)
4) Try running a Patrol test

### Actual results

Test doesn't launch, this error log is shown:

```
No device specified, using the first one (iPhone 13 Pro)
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
✓ Completed building app with entrypoint test_bundle.dart for iOS simulator (26.2s)
• Running app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 13 Pro...
	2023-06-30 16:36:00.680 xcodebuild[70063:17854795] Writing error result bundle to /var/folders/5x/_dlphwk153z51v3xp2l30lccqn9pft/T/ResultBundle_2023-30-06_16-36-0000.xcresult
	xcodebuild: error: Unable to find a destination matching the provided destination specifier:
			{ platform:iOS Simulator, OS:latest, name:iPhone 13 Pro }
...
```

The `OS:latest` bit seems suspicious: you can run a test without any problems if you use a simulator with the highest available iOS version your xcode allows

It seems like a bug, because Patrol should work fine with iOS ^13.0

### Patrol version

patrol: ^1.1.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.0.0
Program adb not found 
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 12.6.1 21G217 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!v
```

</details>

**Comment by bartekpacia** [comment]
Hi @eroshinn, thanks for reporting this and sorry for the problem.

**Comment by bartekpacia** [comment]
Here's my output. I have started iPhone 11 simulator running iOS 13.7. It crashed.

<details><summary>Details</summary>

```
$ patrol test -t integration_test/permissions_many_test.dart --device 'iPhone 11' -v
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/bartek/dev/leancode/patrol/packages/patrol/example/integration_test/permissions_many_test.dart
Generated entrypoint /Users/bartek/dev/leancode/patrol/packages/patrol/example/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check devices --machine
Received 1 device(s) to run on
Received device: iPhone 11
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --simulator --target /Users/bartek/dev/leancode/patrol/packages/patrol/example/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example --dart-define PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example --dart-define PATROL_ANDROID_APP_NAME=Patrol example --dart-define PATROL_IOS_APP_NAME=Patrol example --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true
	Building pl.leancode.patrol.Example for simulator (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Debug -only-testing RunnerUITests -sdk iphonesimulator -destination generic/platform=iOS Simulator -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
	2023-07-20 13:43:42.562 xcodebuild[20015:2879898] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDenote: Building targets in dependency order
	warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
✓ Completed building app with entrypoint test_bundle.dart for iOS simulator (44.0s)
Will uninstall apps before running tests
$ xcrun simctl uninstall 5339525B-2F92-446D-9D3D-8D6E1E1D3A7A pl.leancode.patrol.Example
$ xcrun simctl uninstall 5339525B-2F92-446D-9D3D-8D6E1E1D3A7A pl.leancode.patrol.Example.RunnerUITests.xctrunner
• Running app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 11...
$ xcodebuild -showsdks -json
Assuming SDK version 16.4 for iphonesimulator
Looking for .xctestrun matching Runner_iphonesimulator16.4*.xctestrun at /Users/bartek/dev/leancode/patrol/packages/patrol/example/build/ios_integ/Build/Products
Found 1 match(es), the first one will be used
Found /Users/bartek/dev/leancode/patrol/packages/patrol/example/build/ios_integ/Build/Products/Runner_iphonesimulator16.4-arm64-x86_64.xctestrun
$ xcodebuild test-without-building -xctestrun /Users/bartek/dev/leancode/patrol/packages/patrol/example/build/ios_integ/Build/Products/Runner_iphonesimulator16.4-arm64-x86_64.xctestrun -only-testing RunnerUITests -destination platform=iOS Simulator,name=iPhone 11
	2023-07-20 13:44:12.278 xcodebuild[22014:2886006] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
	Command line invocation:
	    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /Users/bartek/dev/leancode/patrol/packages/patrol/example/build/ios_integ/Build/Products/Runner_iphonesimulator16.4-arm64-x86_64.xctestrun -only-testing RunnerUITests -destination "platform=iOS Simulator,name=iPhone 11"

	User defaults from command line:
	    IDEPackageSupportUseBuiltinSCM = YES

	--- xcodebuild: WARNING: Using the first of multiple matching destinations:
	{ platform:macOS, arch:arm64e, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:arm64, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:x86_64, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:arm64e, variant:Mac Catalyst, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:arm64, variant:Mac Catalyst, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:arm64e, variant:DriverKit, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:arm64, variant:DriverKit, id:00008103-000C258C0EBB001E }
	{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-000C258C0EBB001E }
	{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
	{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
	{ platform:macOS, name:Any Mac }
	{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
	{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
	{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }
	{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
	{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Any watchOS Simulator Device }
	{ platform:iOS Simulator, id:D1F8AF15-E1B7-4E1F-A843-641D902097B2, OS:13.7, name:iPad (7th generation) }
	{ platform:iOS Simulator, id:F1791C9A-4234-4E99-A8A7-2E2DE8DDE8B7, OS:16.4, name:iPad (10th generation) }
	{ platform:iOS Simulator, id:F1791C9A-4234-4E99-A8A7-2E2DE8DDE8B7, OS:16.4, name:iPad (10th generation) }
	{ platform:iOS Simulator, id:A983991C-9FE1-4131-82BD-191C5D596875, OS:13.7, name:iPad Air (3rd generation) }
	{ platform:iOS Simulator, id:91CF5112-DC48-4012-894A-220D87E42E4B, OS:16.4, name:iPad Air (5th generation) }
	{ platform:iOS Simulator, id:91CF5112-DC48-4012-894A-220D87E42E4B, OS:16.4, name:iPad Air (5th generation) }
	{ platform:iOS Simulator, id:F3AE92E3-8D82-443F-A68A-AFE7EF5B4C08, OS:13.7, name:iPad Pro (9.7-inch) }
	{ platform:iOS Simulator, id:9C40035E-A012-4BF0-ADA7-B412C118F7C1, OS:13.7, name:iPad Pro (11-inch) (2nd generation) }
	{ platform:iOS Simulator, id:08F44E9F-0D6B-4724-82DA-5C37227AB201, OS:16.4, name:iPad Pro (11-inch) (4th generation) }
	{ platform:iOS Simulator, id:08F44E9F-0D6B-4724-82DA-5C37227AB201, OS:16.4, name:iPad Pro (11-inch) (4th generation) }
	{ platform:iOS Simulator, id:82B2CA3F-4EB5-47F1-B9AB-921D0AB33EF3, OS:13.7, name:iPad Pro (12.9-inch) (4th generation) }
	{ platform:iOS Simulator, id:FDF5CE16-9B59-47E8-8949-0ABAFDE24540, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
	{ platform:iOS Simulator, id:FDF5CE16-9B59-47E8-8949-0ABAFDE24540, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
	{ platform:iOS Simulator, id:8524FE2F-FEC2-4FA8-91DA-5C0E65CB29C7, OS:16.4, name:iPad mini (6th generation) }
	{ platform:iOS Simulator, id:8524FE2F-FEC2-4FA8-91DA-5C0E65CB29C7, OS:16.4, name:iPad mini (6th generation) }
	{ platform:iOS Simulator, id:C5E9C9A9-9139-4E09-9E83-6F308F5CB3B0, OS:13.7, name:iPhone 6s }
	{ platform:iOS Simulator, id:5339525B-2F92-446D-9D3D-8D6E1E1D3A7A, OS:13.7, name:iPhone 11 }
	{ platform:iOS Simulator, id:796A67FD-2DF7-474C-A482-BDDA28986058, OS:13.7, name:iPhone 11 Pro }
	{ platform:iOS Simulator, id:D36502FC-E8A8-45D7-A223-3AC3F367D171, OS:13.7, name:iPhone 11 Pro Max }
	{ platform:iOS Simulator, id:2CE2A079-7CC9-4625-9A16-EA439A6BEEF4, OS:16.4, name:iPhone 14 }
	{ platform:iOS Simulator, id:2CE2A079-7CC9-4625-9A16-EA439A6BEEF4, OS:16.4, name:iPhone 14 }
	{ platform:iOS Simulator, id:74FC06CB-8DD0-47F1-883B-FAB120239706, OS:16.4, name:iPhone 14 Plus }
	{ platform:iOS Simulator, id:74FC06CB-8DD0-47F1-883B-FAB120239706, OS:16.4, name:iPhone 14 Plus }
	{ platform:iOS Simulator, id:80F20938-C634-4225-9F4B-6823007057C2, OS:16.4, name:iPhone 14 Pro }
	{ platform:iOS Simulator, id:80F20938-C634-4225-9F4B-6823007057C2, OS:16.4, name:iPhone 14 Pro }
	{ platform:iOS Simulator, id:30801237-660E-4DE2-B37F-92C094B51319, OS:16.4, name:iPhone 14 Pro Max }
	{ platform:iOS Simulator, id:30801237-660E-4DE2-B37F-92C094B51319, OS:16.4, name:iPhone 14 Pro Max }
	{ platform:iOS Simulator, id:E366E3A2-5862-46CB-ACFD-C7A961C03FA0, OS:13.7, name:iPhone SE (2nd generation) }
	{ platform:iOS Simulator, id:849B9EFB-4B11-45ED-9B10-A8F9DFD35EF7, OS:16.4, name:iPhone SE (3rd generation) }
	{ platform:iOS Simulator, id:849B9EFB-4B11-45ED-9B10-A8F9DFD35EF7, OS:16.4, name:iPhone SE (3rd generation) }


	*** If you believe this error represents a bug, please attach the result bundle at /Users/bartek/Library/Developer/Xcode/DerivedData/Runner-dgfwrkqvtnkwowdqoiwzarzipfcp/Logs/Test/Test-Runner-2023.07.20_1-44-42-+0200.xcresult

	2023-07-20 13:44:51.601 xcodebuild[22014:2886006] [MT] IDETestOperationsObserverDebug: 8.749 elapsed -- Testing started completed.
	2023-07-20 13:44:51.601 xcodebuild[22014:2886006] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
	2023-07-20 13:44:51.601 xcodebuild[22014:2886006] [MT] IDETestOperationsObserverDebug: 8.749 sec, +8.749 sec -- end

	Test session results, code coverage, and logs:
		/Users/bartek/Library/Developer/Xcode/DerivedData/Runner-dgfwrkqvtnkwowdqoiwzarzipfcp/Logs/Test/Test-Runner-2023.07.20_1-44-42-+0200.xcresult

	Testing failed:
		Could not launch “RunnerUITests”
		RunnerUITests-Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/bartek/Library/Developer/Xcode/DerivedData/Runner-dgfwrkqvtnkwowdqoiwzarzipfcp/Logs/Test/Test-Runner-2023.07.20_1-44-42-+0200.xcresult. (Underlying Error: Could not launch “RunnerUITests”. The LaunchServices launcher has returned an error. Please check the system logs for the underlying cause of the error. (Underlying Error: The operation couldn’t be completed. (OSStatus error -10661.))))

	** TEST EXECUTE FAILED **

	Testing started
✗ Failed to execute tests of app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 11 (xcodebuild exited with code 65) (44.3s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.execute.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:181:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#3      IOSTestBackend.execute (package:patrol_cli/src/ios/ios_test_backend.dart:147:5)
<asynchronous suspension>
#4      TestCommand._execute (package:patrol_cli/src/commands/test.dart:269:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:169:23)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:254:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:72:20)
<asynchronous suspension>
#10     main (file:///Users/bartek/dev/leancode/patrol/packages/patrol_cli/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
$ xcrun simctl uninstall 5339525B-2F92-446D-9D3D-8D6E1E1D3A7A pl.leancode.patrol.Example
$ xcrun simctl uninstall 5339525B-2F92-446D-9D3D-8D6E1E1D3A7A pl.leancode.patrol.Example.RunnerUITests.xctrunner

```

</details>

**Comment by bartekpacia** [comment]
Firebase Test Lab also dropped support for iOS 13.
I'm going to run any other non-16 version.

**Comment by bartekpacia** [comment]
I managed to run on iPhone 13 simulator running iOS 15.5.

First run `patrol build ios --debug --simulator`.

Then go to the `ios` directory and run:

```
xcodebuild test-without-building -xctestrun /Users/bartek/dev/leancode/patrol/packages/patrol/example/build/ios_integ/Build/Products/Runner_iphonesimulator16.4-arm64-x86_64.xctestrun -only-testing RunnerUITests -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'
```

The only difference between the above `xcodebuild` invocation and the one that `patrol_cli` does internally is in the `-destination`:

- **(works)** `-destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'`
- **(doesn't work) `-destination 'platform=iOS Simulator,name=iPhone 13'`

**Comment by fylyppo** [comment]
Related to https://github.com/leancodepl/patrol/discussions/1662

**Comment by nursultan-akhmetzhanov** [comment]
Experiencing the same issue with the latest version of xcode (16.0) after upgrading it. Patrol refuses to run tests on iOS 17.2 since Xcode knows of iOS 18.0's existence. 

Is there a fix for this?

**Comment by matthew-carroll** [comment]
I'm currently trying to configure my first Patrol app. I'm getting the `65` error code when I try to run on a local simulator.

I tried running against my standard simulator, which is iOS 17.4. But I also just tried to running against the latest simulator I have available to me, which is iOS 18.2. Both fail with the `65` error code.

Mac OS: 15.2

Patrol CLI: v3.4.1

Error logs:
<details><summary>Details</summary>
<code>
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:141:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:80:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:332:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:250:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#10     main (file:///Users/admin/.pub-cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:20)
<asynchronous suspension>
</code>
</details>  

I also noticed the following line in the output, which might be relevant:
```
/bin/sh: "/Users/admin/DevLibs/flutter/packages/flutter_tools/bin/xcode_backend.sh": No such file or directory
```

I checked, and `xcode_backend.sh` is definitely available at that path. I also made it executable, just in case that was the issue.

**Comment by matthew-carroll** [comment]
@mateuszwojtczak any chance we can get some eyes on this? It's blocking me from being able to tell my client that Patrol works with their app, which is then blocking them from considering greater investments into Patrol.

**Comment by jaybe78** [comment]
Any news on this one ?

**Comment by psstoyanov** [comment]
Check where you have placed this line:
```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
```
It should be inside the free text field bellow the shell command.

![Image](https://github.com/user-attachments/assets/e0f39587-a0d4-4d1a-9b56-c9f4dda414b3)

**Comment by Crawl3rGer** [comment]
Any news on this one, @bartekpacia ? If I change my iOS Simulator to non-latest iOS Version, I always get xcodebuild error code 70.

**Comment by bartekpacia** [comment]
Hey @Crawl3rGer sorry I don't work on Patrol anymore.

**Comment by Crawl3rGer** [comment]
@piotruela How is responsible for this issue now?

**Comment by Kendru98** [comment]
Hi, please use --ios flag that was introduced in patrol_cli some time ago, it should help
