### ISSUE TITLE
Error on patrol test " No .xctestrun file was found"

### ISSUE THREAD

**Issue by sqcsabbey** [leancodepl/patrol#1442]
### Steps to reproduce

When I run [a simple integration test](https://patrol.leancode.co/getting-started/native#create-a-simple-integration-test), with `patrol test --target integration_test/patrol_config_test.dart --verbose --release`, on iOS, I get:

> 2023-06-30 09:43:30.947 xcodebuild[9959:92788] Writing error result bundle to /var/folders/05/kl3dm3yn3j78c5vll7jttq5r0000gp/T/ResultBundle_2023-30-06_09-43-0030.xcresult
> xcodebuild: error: Failed writing xctestrun file: The folder “Runner_iphoneos16.4-arm64.xctestrun” doesn’t exist..

This looks similar to #1105, but I have the fix from that one; I'm using *patrol_cli v2.0.0*. 

To answer the questions from that [other bug](https://github.com/leancodepl/patrol/issues/1105), I do have Rosetta enabled, I'm on an M1 Mac, and here's the output of `ls -lAh build/ios_integ/Build/Products`: 

> ls: build/ios_integ/Build/Products: No such file or directory

... and here are my architecture settings:

![Screenshot 2023-06-30 at 9 28 43 AM](https://github.com/leancodepl/patrol/assets/101229198/7215dba0-62cf-4c6f-b313-beeaa32ea65b)

... please let me know if there's any other info that will help. 

### Actual results

Test runs successfully.

### Logs

<details>
<summary>Logs</summary>

```
> patrol test --target integration_test/patrol_config_test.dart --verbose 
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/csabbey/code/sqsurvey-flutter/integration_test/patrol_config_test.dart
Bundled 1 test(s) in /Users/csabbey/code/sqsurvey-flutter/integration_test/test_bundle.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (Craig’s iPhone (2))
Received 1 device(s) to run on
Received device: Craig’s iPhone (2)
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.signalquest.survey
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.signalquest.survey
Received internal --dart-define: PATROL_ANDROID_APP_NAME=SQSurvey
Received internal --dart-define: PATROL_IOS_APP_NAME=SQSurvey
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building app with entrypoint test_bundle.dart for iOS device (release)...
$ flutter build ios --no-version-check --config-only --no-codesign --release --target /Users/csabbey/code/sqsurvey-flutter/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=com.signalquest.survey --dart-define PATROL_APP_BUNDLE_ID=com.signalquest.survey --dart-define PATROL_ANDROID_APP_NAME=SQSurvey --dart-define PATROL_IOS_APP_NAME=SQSurvey --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true
        The plugin `flutter_midi` uses a deprecated version of the Android embedding.
        To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
        If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
        Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
        Building com.signalquest.survey for device (ios-release)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
        2023-06-30 09:43:26.635 xcodebuild[9959:92788] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
        note: Building targets in dependency order
        /Users/csabbey/code/sqsurvey-flutter/ios/Runner.xcodeproj: error: Signing for "RunnerUITests" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_build embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_build backend' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'flutter_blue_plus' from project 'Pods')
        note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        warning: no rule to process file '/Users/csabbey/code/sqsurvey-flutter/native/ntrip/CMakeLists.txt' of type 'text' for architecture 'arm64' (in target 'Runner' from project 'Runner')
        warning: no rule to process file '/Users/csabbey/code/sqsurvey-flutter/native/sq_gis/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Runner' from project 'Runner')
        warning: no rule to process file '/Users/csabbey/code/sqsurvey-flutter/native/cop/CMakeLists.txt' of type 'text' for architecture 'arm64' (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        2023-06-30 09:43:30.947 xcodebuild[9959:92788] Writing error result bundle to /var/folders/05/kl3dm3yn3j78c5vll7jttq5r0000gp/T/ResultBundle_2023-30-06_09-43-0030.xcresult
        xcodebuild: error: Failed writing xctestrun file: The folder “Runner_iphoneos16.4-arm64.xctestrun” doesn’t exist..
✗ Failed to build app with entrypoint test_bundle.dart for iOS device (xcodebuild exited with code 70) (14.7s)
Error: xcodebuild exited with code 70
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:127:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:67:5)
<asynchronous suspension>
#4      TestCommand._builderFor.<anonymous closure> (package:patrol_cli/src/commands/test.dart:231:9)
<asynchronous suspension>
#5      _NativeTestRunner.run.runTestsOnDevice (package:patrol_cli/src/test_runner.dart:232:13)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#7      _NativeTestRunner.run (package:patrol_cli/src/test_runner.dart:260:5)
<asynchronous suspension>
#8      TestCommand.run (package:patrol_cli/src/commands/test.dart:194:21)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:314:18)
<asynchronous suspension>
#11     PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:258:18)
<asynchronous suspension>
#12     patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:73:20)
<asynchronous suspension>
#13     main (file:///Users/csabbey/homebrew/Caskroom/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dev/patrol_cli-2.0.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
 FAIL  test_bundle.dart on Craig’s iPhone (2)

```

</details>

### Patrol version

patrol: ^2.0.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.0.0
Program adb found in /Users/csabbey/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/csabbey/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /Users/csabbey/homebrew/bin/ideviceinstaller

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by bartekpacia** [comment]
Hi @sqcsabbey, this looks like a code signing issue. From your logs:

```
/Users/csabbey/code/sqsurvey-flutter/ios/Runner.xcodeproj: error: Signing for "RunnerUITests" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'RunnerUITests' from project 'Runner')

```

**Comment by sqcsabbey** [comment]
Thank you, @bartekpacia! 

If anyone else gets stuck here... here were my steps to get this running:

1. Selected a development team for signing
2. Edited my Test Scheme in Xcode to pass the `-allowProvisioningUpdates` argument
3. Ran a `flutter clean`
4. Ran this test with my original invocation, above (`patrol test --target integration_test/patrol_config_test.dart --verbose --release`)

**Comment by bartekpacia** [comment]
Happy to hear that you've found a solution! :)
