### ISSUE TITLE
Working in android but getting an error while executing with ios 

### ISSUE THREAD

**Issue by lravihs** [leancodepl/patrol#1470]
### Steps to reproduce

Working in android but getting an error while executing with ios

### Actual results

No device specified, using the first one (iPhone 14 Pro)
• Building app with entrypoint example_test.dart for iOS simulator (debug)...
** TEST BUILD FAILED **

✗ Failed to build app with entrypoint example_test.dart for iOS simulator (xcodebuild exited with code 65) (70.8s)
Error: xcodebuild exited with code 65
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65

### Logs

lallu@Laliths-MacBook-Pro Next-Gen-App % patrol develop --target integration_test/sign_up_test.dart --flavor jk --verbose
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Verbose mode enabled. More logs will be printed.
Received test target: /Users/lallu/Documents/GitHub/Next-Gen-App/integration_test/sign_up_test.dart
Generated entrypoint /Users/lallu/Documents/GitHub/Next-Gen-App/integration_test/test_bundle.dart
Received Android flavor: jk
Received iOS flavor: jk
$ flutter --no-version-check devices --machine
No device specified, using the first one (iPhone 14 Pro)
Received device: iPhone 14 Pro
Received 8 --dart-define(s) (0 custom, 8 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.paytronix.nexgenfl
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.paytronix.nexgenfl
Received internal --dart-define: PATROL_ANDROID_APP_NAME=NGA JK Cafe
Received internal --dart-define: PATROL_IOS_APP_NAME=NGA JK Cafe
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_HOT_RESTART=true
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --simulator --flavor jk --target /Users/lallu/Documents/GitHub/Next-Gen-App/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=com.paytronix.nexgenfl --dart-define PATROL_APP_BUNDLE_ID=com.paytronix.nexgenfl --dart-define PATROL_ANDROID_APP_NAME=NGA JK Cafe --dart-define PATROL_IOS_APP_NAME=NGA JK Cafe --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true --dart-define PATROL_HOT_RESTART=true
Building com.paytronix.nexgenfl for simulator (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme jk -configuration Debug-jk -only-testing RunnerUITests -sdk iphonesimulator -destination generic/platform=iOS Simulator -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
/Users/lallu/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.6.0/ios/Classes/FWFWebViewHostApi.m:204:45: error: no visible @interface for 'FWFWebView' declares the selector 'setInspectable:'
[[self webViewForIdentifier:identifier] setInspectable:inspectable.boolValue];
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~
1 error generated.
note: Building targets in dependency order
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOBoringSSL' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIODarwin' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target '_NIODataStructures' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftProtobuf' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'ReachabilitySwift' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'Logging' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOWindows' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOLinux' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOHTTPParser' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOAtomics' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CGRPCZlib' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOTransportServices' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOHTTP2' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOBoringSSLShims' from project 'Pods')
warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOPosix' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOExtras' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOHTTP1' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOFoundationCompat' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOSSL' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOEmbedded' from project 'Pods')
note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIO' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOCore' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOHPACK' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOTLS' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'gRPC-Swift' from project 'Pods')
/Users/lallu/Documents/GitHub/Next-Gen-App/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOConcurrencyHelpers' from project 'Pods')
** TEST BUILD FAILED **

✗ Failed to build app with entrypoint test_bundle.dart for iOS simulator (xcodebuild exited with code 65) (44.6s)
Error: xcodebuild exited with code 65
#0 throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
https://github.com/leancodepl/patrol/issues/1 IOSTestBackend.build. (package:patrol_cli/src/ios/ios_test_backend.dart:127:9)

https://github.com/leancodepl/patrol/issues/2 DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)

https://github.com/leancodepl/patrol/issues/3 IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:67:5)

https://github.com/leancodepl/patrol/issues/4 DevelopCommand._build (package:patrol_cli/src/commands/develop.dart:190:7)

https://github.com/leancodepl/patrol/issues/5 DevelopCommand.run (package:patrol_cli/src/commands/develop.dart:163:5)

https://github.com/leancodepl/patrol/issues/6 CommandRunner.runCommand (package:args/command_runner.dart:212:13)

https://github.com/leancodepl/patrol/issues/7 PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)

https://github.com/leancodepl/patrol/issues/8 PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:254:18)

https://github.com/leancodepl/patrol/issues/9 patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:72:20)

https://github.com/leancodepl/patrol/issues/10 main (file:///Users/lallu/.pub-cache/hosted/pub.dev/patrol_cli-2.0.1/bin/main.dart:6:20)
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
#0 throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
https://github.com/leancodepl/patrol/issues/1 IOSTestBackend.build. (package:patrol_cli/src/ios/ios_test_backend.dart:127:9)

https://github.com/leancodepl/patrol/issues/2 DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)

https://github.com/leancodepl/patrol/issues/3 IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:67:5)

https://github.com/leancodepl/patrol/issues/4 DevelopCommand._build (package:patrol_cli/src/commands/develop.dart:190:7)

https://github.com/leancodepl/patrol/issues/5 DevelopCommand.run (package:patrol_cli/src/commands/develop.dart:163:5)

https://github.com/leancodepl/patrol/issues/6 CommandRunner.runCommand (package:args/command_runner.dart:212:13)

https://github.com/leancodepl/patrol/issues/7 PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)

https://github.com/leancodepl/patrol/issues/8 PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:254:18)

https://github.com/leancodepl/patrol/issues/9 patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:72:20)

https://github.com/leancodepl/patrol/issues/10 main (file:///Users/lallu/.pub-cache/hosted/pub.dev/patrol_cli-2.0.1/bin/main.dart:6:20)

### Patrol version

patrol:^2.0.1

### Patrol Doctor output

patrol doctor

### Flutter Doctor output

flutter doctor

**Comment by bartekpacia** [comment]
This is not an issue with Patrol, but with a WebView dependency. See also:
- https://github.com/flutter/flutter/issues/129602
- https://github.com/flutter/flutter/issues/129587
