### ISSUE TITLE
iOS test are working at local machine but when I try to run test in firebase, always get the same error (Only with iOS)

### ISSUE THREAD

**Issue by johandavidcm** [leancodepl/patrol#1493]
### Steps to reproduce

1. I execute this command to make the build `patrol build ios -t integration_test --release --flavor dev --verbose`
2. I create the zip file with this command `pushd build/ios_integ/Build/Products zip -r ios_tests.zip Release-dev-iphoneos dev_iphoneos15.2-arm64.xctestrun popd`
3. I upload the zip file to firebase `gcloud firebase test ios run --test build/ios_integ/Build/Products/ios_tests.zip --device model=iphone13pro,version=15.2`

Both test have this structure, the only difference are the credentials and the expect

```
void main() {
  patrolTest(
    "Login succesfully",
    nativeAutomation: true,
    (PatrolTester $) async {
      await $.pumpWidget(const MyApp());
      await $.pumpAndSettle();
      await $.enterText(
        LocatorsLogin.fieldEmail,
        Enviroments.userLogin,
      );
      await $.pumpAndSettle();
      await $.enterText(
        LocatorsLogin.fieldPassword,
        Enviroments.passwordSuccessfulLogin,
      );
      await $.tester.testTextInput.receiveAction(TextInputAction.done);
      await $.tap(LocatorsLogin.buttonLogin);
      await $.pumpAndSettle();
      final currentRoute = GetIt.instance.get<AppRouter>().current.name;
      expect(currentRoute != LoginRoute.name, isTrue);
    },
  );
}

```

### Actual results

I getting this test results at firebase 

![Captura de pantalla 2023-07-10 a la(s) 10 38 19 a m](https://github.com/leancodepl/patrol/assets/62624815/e38139a2-05d3-4d21-8ca2-813d3e1c9208)

And inside of every test this is the error
`
Failure at /ios/RunnerUITests/RunnerUITests.m:5 - Assertion Failure at RunnerUITests.m:5: ((response.passed) is true) failed `

![Captura de pantalla 2023-07-10 a la(s) 10 41 58 a m](https://github.com/leancodepl/patrol/assets/62624815/aa1ad395-c5c8-4105-bdb1-46a8fd666d9c)

### Logs

<details>
<summary>Patrol Build</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Verbose mode enabled. More logs will be printed.
Received 2 test target(s)
Received test target: /Users/johan/enerBit/enerbit.app.userApp/integration_test/login/login_succesfully_test.dart
Received test target: /Users/johan/enerBit/enerbit.app.userApp/integration_test/login/login_unsuccesfully_test.dart
Bundled 2 test(s) in /Users/johan/enerBit/enerbit.app.userApp/integration_test/test_bundle.dart
Received iOS flavor: dev
Received 5 --dart-define(s) (0 custom, 5 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_BUNDLE_ID=dev.enerbit
Received internal --dart-define: PATROL_IOS_APP_NAME=enerBit Tests
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building app with entrypoint test_bundle.dart for iOS device (release)...
$ flutter build ios --no-version-check --config-only --no-codesign --release --flavor dev --target /Users/johan/enerBit/enerbit.app.userApp/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_BUNDLE_ID=dev.enerbit --dart-define PATROL_IOS_APP_NAME=enerBit Tests --dart-define PATROL_TEST_LABEL_ENABLED=true --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
        Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
        Building dev.enerbit for device (ios-release)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme dev -configuration Release-dev -only-testing RunnerUITests -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
        2023-07-10 10:45:51.320 xcodebuild[61856:317139] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
        note: Building targets in dependency order
        note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'Copy GoogleService-Info.plist to the correct location' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        warning: Skipping duplicate build file in Copy Bundle Resources build phase: /Users/johan/enerBit/enerbit.app.userApp/ios/Runner/GoogleService-Info.plist (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
✓ Completed building app with entrypoint test_bundle.dart for iOS device (42.4s)
build/ios_integ/Build/Products/Release-iphoneos/Runner.app (app under test)
build/ios_integ/Build/Products/Release-iphoneos/RunnerUITests-Runner.app (test instrumentation app)
$ xcodebuild -showsdks -json
Assuming SDK version 16.4 for iphonesimulator
Looking for .xctestrun matching dev_iphoneos16.4*.xctestrun at build/ios_integ/Build/Products
Found 1 match(es), the first one will be used
Found /Users/johan/enerBit/enerbit.app.userApp/build/ios_integ/Build/Products/dev_iphoneos16.4-arm64.xctestrun
build/ios_integ/Build/Products/dev_iphoneos16.4-arm64.xctestrun (xctestrun file)
```

</details>

<details>
<summary>GCloud Logs</summary>

```
Have questions, feedback, or issues? Get support by emailing:
  ftl-ios-feedback@google.com

Uploading [build/ios_integ/Build/Products/ios_tests.zip] to Firebase Test Lab...
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/test-lab-8zkkzvv78d5u0-nzq0ym4bax47m/2023-07-10_10:17:01.269309_QpEk/]

Test [matrix-2gbxf1j09sddv] has been created in the Google Cloud.
Firebase Test Lab will execute your xctest test on 1 device(s). More devices may be added later if flaky test attempts are specified.
Creating individual test executions...done.                                                                

Test results will be streamed to [ https://console.firebase.google.com/project/flutter-tests-eb/testlab/histories/bh.5a180a4bade0e929/matrices/6353759010672390554 ].
10:19:33 Test is Pending
10:19:46 Test is Running
10:19:53 Starting attempt 1.
10:19:53 Checking Internet connection...
10:20:19 Internet connection stable!
10:20:58 Starting iOS test.
10:21:49 Completed iOS test.
10:22:40 Done. Test time = 48 (secs)
10:22:40 Starting results processing. Attempt: 1
10:22:53 Completed results processing. Time taken = 13 (secs)
10:22:53 Test is Finished

Xctest testing complete.

More details are available at [ https://console.firebase.google.com/project/flutter-tests-eb/testlab/histories/bh.5a180a4bade0e929/matrices/6353759010672390554 ].
┌─────────┬──────────────────────────────┬─────────────────────┐
│ OUTCOME │       TEST_AXIS_VALUE        │     TEST_DETAILS    │
├─────────┼──────────────────────────────┼─────────────────────┤
│ Failed  │ iphone11pro-16.3-en-portrait │ 2 test cases failed │
└─────────┴──────────────────────────────┴─────────────────────┘
```

</details>

### Patrol version

patrol: ^2.0.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.0.2
Program adb found in /Users/johan/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/johan/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by johandavidcm** [comment]
https://github.com/leancodepl/patrol/assets/62624815/fd73c258-33de-4c4a-b672-0691569454be

**Comment by bartekpacia** [comment]
Download the log file from Firebase Test Lab and post it here. There'll be a lot in there, but it almost always helps to pinpoint the cause.

**Comment by johandavidcm** [comment]
This is the log from firebase

https://drive.google.com/file/d/1WwKngPdfS6mB-MEBsiBogZvlcs11rR7H/view?usp=sharing

**Comment by bartekpacia** [comment]
I see the following error in your logs (CTRL+F for `Guarded function conflict`):

```
flutter: Failed host lookup: 'itunes.apple.com'
flutter: #0      IOClient.send (package:http/src/io_client.dart:94)
flutter: <asynchronous suspension>
flutter: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
flutter: <asynchronous suspension>
flutter: #2      _withClient (package:http/http.dart:166)
flutter: <asynchronous suspension>
flutter: #3      NewVersionPlus._getiOSStoreVersion (package:new_version_plus/new_version_plus.dart:158)
flutter: <asynchronous suspension>
flutter: #4      CommonBloc._handleOnIsAppVersionRequested (package:enerbit/domain/common/blocs/common_bloc/common_bloc.dart:73)
flutter: <asynchronous suspension>
flutter: #5      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:229)
flutter: <asynchronous suspension>
flutter: 00:01 +1: login.login_succesfully_test Login succesfully [E]
flutter:   Test failed. See exception logs above.
flutter:
flutter: PatrolBinding: tearDown(): count: 2, results: {login.login_succesfully_test: {"methodName":"Login succesfully","details":""}, Login succesfully: success}
flutter: PatrolBinding: tearDown(): test "Login succesfully" in group "login.login_succesfully_test", passed: false
flutter: PatrolAppService.markDartTestAsCompleted(): login.login_succesfully_test
flutter: 00:01 +1 -1: login.login_unsuccesfully_test Login unsuccesfully
flutter: Guarded function conflict.
flutter: #0      TestAsyncUtils.guardSync (package:flutter_test/src/test_async_utils.dart:270)
flutter: #1      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:60)
flutter: #2      LiveTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1873)
saction created: (<private>) <private>
flutter: #3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:975)
e>: Task <10B03FBD-43B6-4674-9F5D-FDCD7875AEFA>.<155359> resuming, timeouts(60.0, 604800.0) QOS(0x15) Voucher (null)
flutter: #6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:964)
flutter: #7      LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1935)
flutter: #8      IntegrationTestWidgetsFlutterBinding.runTest (package:integration_test/integration_test.dart:239)
flutter: #9      PatrolBinding.runTest (package:patrol/src/binding.dart:156)
flutter: #10     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:163)
flutter: #11     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215)
flutter: <asynchronous suspension>
flutter: #12     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213)
flutter: <asynchronous suspension>
e>: [Telemetry]: Activity <nw_activity 12:2[89A05B4B-FE4A-412C-BA00-33FBF5258284] (reporting strategy default)> on Task <10B03FBD-43B6-4674-9F5D-FDCD7875AEFA>.<155359> was not selected for reporting
flutter: #13     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:258)
flutter: <asynchronous suspension>
wnloading from https://cl4.apple.com/2/m2/a.1//availability.pb.gz to /var/root/Library/Caches/locationd/indoor_tiles/availability.pb.gz.temp
flutter: (elided 2 frames from dart:async)
Avl, update, 1, state, 0
flutter: 00:01 +1 -1: login.login_unsuccesfully_test Login unsuccesfully [E]
e>: Task <10B03FBD-43B6-4674-9F5D-FDCD7875AEFA>.<155359> {strength 0, tls 4, sub 0, sig 1, ciphers 0, bundle 1, builtin 0}
```

**Comment by johandavidcm** [comment]
I don' really get it, 'cause this is my test script:

```
void main() {
  patrolTest(
    "Login succesfully",
    nativeAutomation: true,
    timeout: const Timeout(
      Duration(
        minutes: 2,
      ),
    ),
    (PatrolTester $) async {
      await IntegrationUtils.initUtilities();
      await $.pumpWidgetAndSettle(const EnerbitApp());
      await $(#text_form_field_email_login).enterText(
        Constants.userLogin,
      );
      await $.pumpAndSettle();
      await $(#text_form_field_password_login).enterText(
        Constants.passwordSuccessfulLogin,
      );
      await $.tester.testTextInput.receiveAction(TextInputAction.done);
      await $(#button_login).tap();
      await $.pumpAndSettle();
      final lobbyFinder = await $(#lobby_mobile_content).waitUntilVisible();
      expect(lobbyFinder.exists, isTrue);
      ProcessUtils.logout();
      await $.pumpAndSettle();
    },
  );
}
```

And al async function has his respective `await` then I tried deleting a call to a bloc event wich is it in the app main method, and that works, but I really don't understand why

**Comment by bartekpacia** [comment]
> then I tried deleting a call to a bloc event wich is it in the app main method, and that works

This sounds like a problem with your app, and Patrol has nothing to do with that. If you were to run your tests with `integration_test`, you'd probably get the same error. It's not coming from `patrol`, but from `flutter_test`.

**Comment by johandavidcm** [comment]
Thanks for the help, without I don't know how much time would have spent searching the error.

Thanks a lot.
