### ISSUE TITLE
`patrol develop` and `patrol test` should uninstall app before trying to run the test

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1496]
It would make using them easier.
Now app is not even closed after ending `patrol develop`, and both `patrol develop` and `patrol test` have some problems, when app under test is installed before running those commands.

**Comment by pszklarska** [comment]
@bartekpacia I'm seeing this exception when running tests on Android for the first time:

<details><summary>Logs</summary>
<p>

```
Will uninstall apps before running tests
Uninstalling <package_name> from SM G965F
Exception: 
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: <package_name>
        at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4632)
        at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:26068)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:26074)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:21746)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:1030)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1701)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:206)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26673)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5433)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5033)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

#0      Adb.uninstall (package:adb/src/adb.dart:99:7)
<asynchronous suspension>
#1      AndroidTestBackend.uninstall (package:patrol_cli/src/android/android_test_backend.dart:147:5)
<asynchronous suspension>
#2      TestCommand._preExecute (package:patrol_cli/src/commands/test.dart:197:11)
<asynchronous suspension>
#3      TestCommand.run (package:patrol_cli/src/commands/test.dart:168:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#6      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:254:18)
<asynchronous suspension>
#7      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:72:20)
<asynchronous suspension>
#8      main (file:///Users/paulina/.pub-cache/hosted/pub.dev/patrol_cli-2.0.3/bin/main.dart:6:20)
<asynchronous suspension>
```

</p>
</details> 

It seems that patrol doesn't check if the app is there before trying to uninstall it.
I see it in 2.0.3, but not in 2.0.2, so I thought it may be related to this issue.
