### ISSUE TITLE
What went wrong: Execution failed for task :app:connectedDebugAndroidTest

### ISSUE THREAD

**Issue by JosueMCapita** [leancodepl/patrol#1579]
### Steps to reproduce

1. Clone https://github.com/leancodepl/patrol.git and `cd` into `patrol/packages/patrol/example/` `[master]`
2. Start the emulator
```
Android 11
API 30
x86
```

3. Verify that the app builds fine: `flutter build apk --debug`
```
Running Gradle task 'assembleDebug'...                             17.9s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
```

4. Run the integration test: `patrol test --target integration_test/example_test.dart`

### Actual results

Is resulting in to the following error:

``` What went wrong: Execution failed for task ':app:connectedDebugAndroidTest'. ```

It's not showing success of failure regarding the integration test and no other details about the showed error.

### Logs

<details>
<summary>Logs</summary>

```
patrol test --target integration_test/example_test.dart -d emulator-5554 --verbose

You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/<MY_USER>/projects/flutter/patrol/packages/patrol/example/integration_test/example_test.dart
Generated entrypoint /Users/<MY_USER>/projects/flutter/patrol/packages/patrol/example/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check devices --machine
Received 1 device(s) to run on
Received device: emulator-5554
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building apk with entrypoint test_bundle.dart...
$ ./gradlew :app:assembleDebug -Ptarget=/Users/<MY_USER>/projects/flutter/patrol/packages/patrol/example/integration_test/test_bundle.dart -Pdart-defines=...
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :<EVERY OTHER TASK> UP-TO-DATE/NO-SOURCE
        :
        : BUILD SUCCESSFUL in 20s
        : 160 actionable tasks: 7 executed, 153 up-to-date
$ ./gradlew :app:assembleDebugAndroidTest -Ptarget=/Users/<MY_USER>/projects/flutter/patrol/packages/patrol/example/integration_test/test_bundle.dart -Pdart-defines=...
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :<EVERY OTHER TASK> UP-TO-DATE/NO-SOURCE
        : 
        : BUILD SUCCESSFUL in 4s
        : 162 actionable tasks: 2 executed, 160 up-to-date
✓ Completed building apk with entrypoint test_bundle.dart (25.2s)
Will uninstall apps before running tests
Uninstalling pl.leancode.patrol.example from Android SDK built for x86
Uninstalling pl.leancode.patrol.example.test from Android SDK built for x86
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
$ ./gradlew :app:connectedDebugAndroidTest -Ptarget=/Users/<MY_USER>/projects/flutter/patrol/packages/patrol/example/integration_test/test_bundle.dart -Pdart-defines=...
        : > Task :app:compileFlutterBuildDebug
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :<EVERY OTHER TASK> UP-TO-DATE/NO-SOURCE
        : 04:54:46 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
        : 04:54:46 V/JdwpProxy-Buffer: DEVICE WRITE (14) JDWP2dHandshake
        : 04:54:46 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
        : ...
        : 
        : > Task :app:connectedDebugAndroidTest
        : Starting 0 tests on <DEVICE NAME>_API_30(AVD) - 11
        Instrumentation did not complete:
        Instrumentation code: 0
        Instrumentation result bundle: 
        : 
        : > Task :app:connectedDebugAndroidTest FAILED
        : 185 actionable tasks: 7 executed, 178 up-to-date
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:connectedDebugAndroidTest'.
        See the report at: file:///Users/<MY_USER>/projects/flutter/patrol/packages/patrol/example/build/app/reports/androidTests/connected/index.html
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 22s
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (22.9s)
Exception: Gradle test execution failed with code 1
#0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:140:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:106:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:269:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:169:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:254:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:72:20)
<asynchronous suspension>
#9      main (file:///Users/<MY_USER>/.pub-cache/hosted/pub.dev/patrol_cli-2.0.4/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Uninstalling pl.leancode.patrol.example from Android SDK built for x86
Uninstalling pl.leancode.patrol.example.test from Android SDK built for x86

```

Log trimmed due to Github issue's body limit: [There was an error creating your Issue: body is too long (maximum is 65536 characters).]
You can see the full log [here](https://gist.github.com/JosueMCapita/95b18f803982e94fc91b2429ee113406).

</details>

### Patrol version

```
patrol:
  path: ../ (^2.1.0)
```

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
$ patrol doctor
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.0.4
Program adb found in /Users/<MY_USER>/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/<MY_USER>/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 11.7.8 20G1351 darwin-x64, locale
    en-AO)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] VS Code (version 1.80.1)
[✓] Proxy Configuration
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by jBorkowska** [comment]
Hi @JosueMCapita. Thanks for creating this issue. Our main developer is on vacation right now, but we will look into this problem once he's back.

Probably connected with https://github.com/leancodepl/patrol/issues/1575

**Comment by jBorkowska** [comment]
Hi @JosueMCapita, we released new `patrol` and `patrol_cli` versions yesterday, that have a fix for your issue. Please check it out and give us some feedback, if it helped.

**Comment by JosueMCapita** [comment]
Hi @jBorkowska, thank you!!!
I will check it out and give you a feedback.

**Comment by datdang1995** [comment]
@jBorkowska sorry but this issue happens again with `patrol: ^2.3.0` and `patrol_cli v2.2.0`
