### ISSUE TITLE
Task 'xcodebuild build-for-testing' is failing at Pipeline but works fine at local machine

### ISSUE THREAD

**Issue by johandavidcm** [leancodepl/patrol#1596]
### Steps to reproduce

Test are working fine at local machine but at the moment to try to run these test at Azure DevOps doesn't work

This is my `.yaml` file

```
  displayName: Build ipa
  jobs: 
  - job: Build
    displayName: Build ios
    pool:
      vmImage: 'macOS-latest'
    steps:    

    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'IOS-developer.p12'
        certPwd: '$(PasswordCertDeveloperIOS)'
        keychain: 'temp'

    - task: InstallAppleProvisioningProfile@1
      displayName: "Install Apple Mobile Provisioning Profile"
      inputs:
        provisioningProfileLocation: "secureFiles"
        provProfileSecureFile: "developerprofile.mobileprovision"
        
    - task: FlutterInstall@0
      displayName: 'Install flutter'
      inputs:
        mode: "auto"
        channel: "stable"
        version: "custom"
        customVersion: "3.10.6"

    - script: |
        PATH="$PATH":"$HOME/.pub-cache/bin"
        dart --version
        dart pub global activate patrol_cli
        patrol --version
        patrol build ios -t integration_test --release --flavor dev --verbose
      displayName: 'Install patrol and build tests'
```

### Actual results

<details>
<summary>Azure Logs</summary>

```
Building package executables...
Built patrol_cli:main.
Installed executable patrol.
Activated patrol_cli 2.1.0.
Verbose mode enabled. More logs will be printed.

Completion files installed. To enable completion, run the following command in your shell:
source /Users/runner/.bash_profile

Received 3 test target(s)
Received test target: /Users/runner/work/1/s/integration_test/login/login_succesfully_test.dart
Received test target: /Users/runner/work/1/s/integration_test/login/login_unsuccesfully_test.dart
Received test target: /Users/runner/work/1/s/integration_test/payment/payment_nequi_succesfully_test.dart
Generated entrypoint /Users/runner/work/1/s/integration_test/test_bundle.dart with 3 bundled test(s)
Received iOS flavor: dev
Received 3 --dart-define(s) (0 custom, 3 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
• Building app with entrypoint test_bundle.dart for iOS device (release)...
$ flutter build ios --no-version-check --config-only --no-codesign --release --flavor dev --target /Users/runner/work/1/s/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_TEST_LABEL_ENABLED=true --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
	Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
	Building dev.enerbit for device (ios-release)...
	Running pod install...                                            364.0s
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme dev -configuration Release-dev -only-testing RunnerUITests -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
	note: Building targets in dependency order
	/Users/runner/work/1/s/ios/Runner.xcodeproj: error: No profiles for 'dev.enerbit' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'dev.enerbit'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Runner' from project 'Runner')
	note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'Copy GoogleService-Info.plist to the correct location' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	warning: Skipping duplicate build file in Copy Bundle Resources build phase: /Users/runner/work/1/s/ios/Runner/GoogleService-Info.plist (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	** TEST BUILD FAILED **
	
✗ Failed to build app with entrypoint test_bundle.dart for iOS device (xcodebuild exited with code 65) (417.7s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:131:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:71:5)
<asynchronous suspension>
#4      BuildIOSCommand.run (package:patrol_cli/src/commands/build_ios.dart:133:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:320:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:264:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:76:20)
<asynchronous suspension>
#9      main (file:///Users/runner/.pub-cache/hosted/pub.dev/patrol_cli-2.1.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:131:9)

```

</details>

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.0.7

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.0
Program adb found in /Users/johan/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/johan/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by Albert221** [comment]
> Maybe is because I have `CODE_SIGN_STYLE` in automatic?

Most probably, yes. What I recommend (and this shall land in Patrol's documentation later) is to create an Identifier for `app.enerbit.RunnerUITests.xctrunner` in your Apple Developer account. Then, create a development Provisioning Profile using that Identifier.

Download this profile and install it to your Keychain locally.

Then, in your `project.pbxproj`, below the `PRODUCT_BUNDLE_IDENTIFIER = ...` line add this:
```
PROVISIONING_PROFILE_SPECIFIER = "";
"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "<your new provisioning profile name>";
```

You can now check in Xcode whether it was indeed set. You will probably see a warning icon next to the profile name, because XCode wants  "...RunnerUITests" profile and you provide "...RunnerUITests.xctrunner", but it's safe to ignore it. Your patrol tests will run anyway.

The last thing you need to do is to commit this change in your pbxproj and add a step for installing your new provisioning profile in Azure Pipelines.

Hope this helps :)

**Comment by johandavidcm** [comment]
@Albert221  I created a new profile and that works for me, thanks a lot.
