### ISSUE TITLE
Test app crashes when trying to open camera view

### ISSUE THREAD

**Issue by derrickgw** [leancodepl/patrol#1597]
### Steps to reproduce

1. Start an emulator. I used both "Pixel XL API 33" and "Pixel 6 Pro API 33 (with 4GB of RAM)"
2.  `git clone git@github.com:OurDataMine/flutter_notification_plugin.git`
3. `cd flutter_notification_plugin/example/`
4. `flutter pub get`
5.  `patrol build android`
6. `patrol test --verbose`

### Actual results

It appears that the gRPC server is crashing.  The logs are vauge, but as soon as the notification tries to pull up the view that starts the camera, everything crashes.  logcat just prints the exception generated by the patrol test driver, and nothing useful from the camera subsystem.

It should be noted that the view started by the notification is entirely native, to avoid any latency from starting the DartVM when the user clicks on the notification. But the notification is created from flutter and the quick-actions from the notification do call flutter code.

### Logs

[Logs (github gist)](https://gist.github.com/derrickgw/4c5932b5c0fa3766a7aba32bd1eed82f)

### Patrol version

patrol: ^2.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
$ patrol doctor
Patrol CLI version: 2.1.0
Program adb found in /home/derrick/bin/adb
Env var $ANDROID_HOME is not set
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on Ubuntu 20.04.4 LTS 5.15.0-71-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
Can confirm this happens, but not every time (at least in my case).

A few log lines that look suspicious:
- `UiAutomationManager: UiAutomation service owner died`
- `ActivityManager: Got obituary of 6834:com.ourdatamine.lock_screen_notification_example`
- `ActivityManager: Force stopping androidx.test.orchestrator appid=10174 user=0: finished inst`
- `ActivityManager: Killing 6709:androidx.test.orchestrator/u0a174 (adj 0): stop androidx.test.orchestrator due to finished inst`
- `ActivityManager: Error shutting down UiAutomationConnection`

And here's the exception thrown by gRPC:

<details><summary>Details</summary>

```
8-07 13:42:32.435  7430  7449 E PatrolServer: PatrolJUnitRunner.runDartTest(main_test): UNAVAILABLE
08-07 13:42:32.435  7430  7449 E PatrolServer: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 8082) from /:: (port 57734): connect failed: ECONNREFUSED (Connection refused)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at libcore.io.IoBridge.connect(IoBridge.java:187)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.Socket.connect(Socket.java:646)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.Socket.connect(Socket.java:595)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.Socket.<init>(Socket.java:475)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.net.Socket.<init>(Socket.java:275)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:285)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at io.grpc.okhttp.OkHttpClientTransport$3.run(OkHttpClientTransport.java:532)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at java.lang.Thread.run(Thread.java:1012)
08-07 13:42:32.435  7430  7449 E PatrolServer: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at libcore.io.Linux.connect(Native Method)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at libcore.io.ForwardingOs.connect(ForwardingOs.java:201)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:158)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at libcore.io.ForwardingOs.connect(ForwardingOs.java:201)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:201)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	at libcore.io.IoBridge.connect(IoBridge.java:179)
08-07 13:42:32.435  7430  7449 E PatrolServer: 	... 15 more
```

</details>

**Comment by Kendru98** [comment]
Not sure if this is still an issue, please fill a new one if you still have a problem, closing for now
