### ISSUE TITLE
Error when trying to run on iPhone

### ISSUE THREAD

**Issue by pandoras-toolbox** [leancodepl/patrol#1599]
### Steps to reproduce

1. Create a new Flutter application in Visual Code. It will contain the Counter App.
2. Follow the [instructions](https://patrol.leancode.co/getting-started/native) in that new project to setup native automation for iOS.
3. Connect a real iPhone 11 device to the MacBook.

It works when running it on an iPhone 11 simulator by the way.

### Actual results

The command to execute the test fails.

`counter_app patrol test --target integration_test/example_test.dart --release --verbose`

### Logs

<details>
<summary>Logs</summary>

```
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/integration_test/example_test.dart
Generated entrypoint /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check devices --machine
No device specified, using the first one (SWE-iPhone-11)
Received 1 device(s) to run on
Received device: SWE-iPhone-11
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.example.counter_app
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.counter_app
Received internal --dart-define: PATROL_ANDROID_APP_NAME=counter_app
Received internal --dart-define: PATROL_IOS_APP_NAME=counter_app
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building app with entrypoint test_bundle.dart for iOS device (release)...
$ flutter build ios --no-version-check --config-only --no-codesign --release --target /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=com.example.counter_app --dart-define PATROL_APP_BUNDLE_ID=com.example.counter_app --dart-define PATROL_ANDROID_APP_NAME=counter_app --dart-define PATROL_IOS_APP_NAME=counter_app --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true
        Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
        Building com.example.counterApp for device (ios-release)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Release -only-testing RunnerUITests -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
        2023-08-03 11:04:31.997 xcodebuild[25225:128468] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
        note: Building targets in dependency order
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOLinux' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Runner.xcodeproj: error: Signing for "Runner" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'Runner' from project 'Runner')
        note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target '_NIODataStructures' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIODarwin' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOBoringSSLShims' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftProtobuf' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Runner.xcodeproj: error: Signing for "RunnerTests" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'RunnerTests' from project 'Runner')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOExtras' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOBoringSSL' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOConcurrencyHelpers' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOHPACK' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOTransportServices' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'Logging' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOHTTPParser' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOWindows' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOCore' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Runner.xcodeproj: error: No profiles for 'com.example.RunnerUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.RunnerUITests.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOEmbedded' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'gRPC-Swift' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOHTTP2' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOHTTP1' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOPosix' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOFoundationCompat' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOSSL' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CGRPCZlib' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIO' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'CNIOAtomics' from project 'Pods')
        /Volumes/Macintosh HD - Data/VsCodeProjects/counter_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'SwiftNIOTLS' from project 'Pods')
        ** TEST BUILD FAILED **

✗ Failed to build app with entrypoint test_bundle.dart for iOS device (xcodebuild exited with code 65) (15.7s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:131:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:71:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:230:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:320:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:264:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:76:20)
<asynchronous suspension>
#10     main (file:///Users/mario/.pub-cache/hosted/pub.dev/patrol_cli-2.1.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:131:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:71:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:230:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:320:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:264:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:76:20)
<asynchronous suspension>
#10     main (file:///Users/mario/.pub-cache/hosted/pub.dev/patrol_cli-2.1.0/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

<details>
<summary>Logs (non verbose)</summary>

```
No device specified, using the first one (SWE-iPhone-11)
• Building app with entrypoint test_bundle.dart for iOS device (release)...
        2023-08-03 11:08:05.603 xcodebuild[25695:131318] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
        ** TEST BUILD FAILED **

✗ Failed to build app with entrypoint test_bundle.dart for iOS device (xcodebuild exited with code 65) (16.0s)
Error: xcodebuild exited with code 65
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
```

</details>

### Patrol version

patrol: ^2.2.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.1.0
Program adb found in /Users/mario/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/mario/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/mario/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mario/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mario/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b829.16-10353782)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b829.16-10353782)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • SWE-iPhone-11 (mobile) • 00008030-000E5D2126D1402E • ios            • iOS 16.6 20G75
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by pandoras-toolbox** [comment]
Wait, it is something with codesign stuff.

**Comment by pandoras-toolbox** [comment]
It was a problem in the section "Signing & Capabilities" in Xcode. And then there was a input dialog which popped up, "codesign wants to access key", but the system password was not accepted. I had to modify access control in Keychain to allow all applications to access the item.

Maybe you can reference in your manual page to a Xcode tutorial for iOS development, especially related to developer accounts and code signing? I am a test automator and not a mobile app developer. Usually test automation tools allow a black box approach and do not require to know such internal stuff, so I do not know them like a mobile developer would know.

**Comment by jBorkowska** [comment]
Hi @pandoras-toolbox, good to hear you resolved it yourself :) We'll take your idea into account in near future, thank you for that
