### ISSUE TITLE
`patrol test --target` gives build error

### ISSUE THREAD

**Issue by benjamin-inspectly** [leancodepl/patrol#1616]
### Steps to reproduce

I'm trying to use the "patrol test" and "patrol develop" commands with the "--target" attribute but I cannot get it to work.

It's working on a coworkers PC but I cannot get it to work. With the exact same command. 

As soon as I add the attribute I get some crazy build errors and I'm not sure if it's a bug or if it's just me. "patrol test" on its own, works perfectly.

### Actual results

My command: 
`patrol test --target integration_test/critical_workflows/checklists/0002_Create_simple_with_each_question_type_test.dart`

<details>
<summary>Command line result</summary>

```
PS E:\Projects\AppTestAutomated\AppNew> patrol develop --target integration_test\critical_workflows\photoDoc\0002_Create_simple_without_location_test.dart  
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
        Invalid depfile: E:\Projects\AppTestAutomated\AppNew\.dart_tool\flutter_build\0b0d2e57aa91fea684b4d62ac17bf222\kernel_snapshot.d
        Invalid depfile: E:\Projects\AppTestAutomated\AppNew\.dart_tool\flutter_build\0b0d2e57aa91fea684b4d62ac17bf222\kernel_snapshot.d
        Unhandled exception:
        FileSystemException(uri=e:/Projects/AppTestAutomated/AppNew/integration_test/critical_workflows/photoDoc/0003_Create_full_2_of_each_doc_test.dart; message=StandardFileSystem only supports file:* and data:* URIs)
        #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
        #1      IncrementalCompiler._initializeExperimentalInvalidation (package:front_end/src/fasta/incremental_compiler.dart:1268:56)
        #2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:325:17)
        <asynchronous suspension>
        #3      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
        <asynchronous suspension>
        #4      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:595:11)
        <asynchronous suspension>
        #5      starter (package:frontend_server/starter.dart:99:12)
        <asynchronous suspension>
        #6      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
        <asynchronous suspension>

        Target kernel_snapshot failed: Exception


        FAILURE: Build failed with an exception.

        * Where:
        Script 'E:\FlutterDev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201

        * What went wrong:
        Execution failed for task ':app:compileFlutterBuildAppCenterDebug'.
        > Process 'command 'E:\FlutterDev\flutter\bin\flutter.bat'' finished with non-zero exit value 1

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 36s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (36.9s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      DevelopCommand._build (package:patrol_cli/src/commands/develop.dart:193:7)
<asynchronous suspension>
#4      DevelopCommand.run (package:patrol_cli/src/commands/develop.dart:165:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:320:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:264:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:76:20)
<asynchronous suspension>
#9      main (file:///C:/Users/TorbenFlyvholm/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-2.1.0/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

<details>
<summary>test_bundle.dart - in case it is important</summary>

```
// ignore_for_file: type=lint, invalid_use_of_internal_member

import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

// START: GENERATED TEST IMPORTS
import 'critical_workflows/photoDoc/0002_Create_simple_without_location_test.dart' as critical_workflows__photoDoc__0002_Create_simple_without_location_test;
// END: GENERATED TEST IMPORTS

Future<void> main() async {
  final nativeAutomator = NativeAutomator(config: NativeAutomatorConfig());
  await nativeAutomator.initialize();
  PatrolBinding.ensureInitialized();

  // START: GENERATED TEST GROUPS
  group('critical_workflows.photoDoc.0002_Create_simple_without_location_test', critical_workflows__photoDoc__0002_Create_simple_without_location_test.main);
  // END: GENERATED TEST GROUPS
}


```

</details>

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.2.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
PS E:\Projects\AppTestAutomated\AppNew> patrol doctor
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.0
Program adb found in E:\Android_SDK_HOME\Sdk\platform-tools\adb.exe
Env var $ANDROID_HOME set to E:\Android_SDK_HOME\Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```

PS E:\Projects\AppTestAutomated\AppNew> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.2070], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.7.0 Preview 5.0)
[!] Android Studio (version 2021.3)
    X Unable to find bundled Java version.
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.81.0)
[√] Connected device (4 available)
[√] Network resources

```

</details>

**Comment by jBorkowska** [comment]
Hi @benjamin-inspectly, try providing absolute path to the test file. We have some problems with paths on Windows, it's related to this issue: https://github.com/leancodepl/patrol/issues/1256

**Comment by benjamin-inspectly** [comment]
Hi @jBorkowska 
Thanks for replying so rapidly!

Unfortunately, I get the same error when I use the absolute path.

I tried these 2 commands but get below error as before. The "kernel"-files are both 0 bytes in case that means anything.

patrol develop --target E:\Projects\AppTestAutomated\AppNew\integration_test\critical_workflows\photoDoc\1001_Create_simple_with_location_test.dart

OR

patrol develop --target E:/Projects/AppTestAutomated/AppNew/integration_test/critical_workflows/photoDoc/1001_Create_simple_with_location_test.dart


You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

 

No device specified, using the first one (RF8R810Z1LP)
• Building apk with entrypoint test_bundle.dart...
Invalid depfile: E:\Projects\AppTestAutomated\AppNew\.dart_tool\flutter_build\0b0d2e57aa91fea684b4d62ac17bf222\kernel_snapshot.d
        Invalid depfile: E:\Projects\AppTestAutomated\AppNew\.dart_tool\flutter_build\0b0d2e57aa91fea684b4d62ac17bf222\kernel_snapshot.d
        Unhandled exception:
        FileSystemException(uri=e:/Projects/AppTestAutomated/AppNew/integration_test/critical_workflows/photoDoc/0003_Create_full_2_of_each_doc_test.dart; message=StandardFileSystem only supports file:* and data:* URIs)
        #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
        #1      IncrementalCompiler._initializeExperimentalInvalidation (package:front_end/src/fasta/incremental_compiler.dart:1268:56)
        #2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:325:17)
        <asynchronous suspension>
        #3      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
        <asynchronous suspension>
        #4      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:595:11)
        <asynchronous suspension>
        #5      starter (package:frontend_server/starter.dart:99:12)
        <asynchronous suspension>
        #6      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
        <asynchronous suspension>

 

        Target kernel_snapshot failed: Exception

 

 

        FAILURE: Build failed with an exception.

 

        * Where:
        Script 'E:\FlutterDev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201

 

        * What went wrong:
        Execution failed for task ':app:compileFlutterBuildAppCenterDebug'.
        > Process 'command 'E:\FlutterDev\flutter\bin\flutter.bat'' finished with non-zero exit value 1

 

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

        * Get more help at https://help.gradle.org/

 

        BUILD FAILED in 9s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (10.7s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)

**Comment by jBorkowska** [comment]
Just to make sure - does your app run without problems?

**Comment by bartekpacia** [comment]
This looks similar to #1428

**Comment by benjamin-inspectly** [comment]
> Just to make sure - does your app run without problems?

Yes, both in debug and if I use "patrol test" without arguments :)

**Comment by MathiasTP** [comment]
+1 on this issue. 
My app build fine, and i can start patrol test --flavor dev but not test cases are run. 
If i try to add the path to my integration test it fails and wont build the apk.

**Comment by benjamin-inspectly** [comment]
> +1 on this issue. My app build fine, and i can start patrol test --flavor dev but not test cases are run. If i try to add the path to my integration test it fails and wont build the apk.

For my case "patrol test --flavor XXX" executes all test cases :)



> Can you confirm that this occurs only on Windows?

@bartekpacia  Hmm.. Good question! I don't have access to anything but windows at my company, but I'm cannot confirm it's not a problem on any other OS :/
Perhaps I can borrow a colleagues Mac in one of the following days when he are at the office then, if you need me to fully confirm.

**Comment by benjamin-inspectly** [comment]
Hi @bartekpacia and @jBorkowska ,

New discovery.. I don't know why, but suddenly "patrol test --target" works (from my original issue report), but the develop-command, as per below reply from me yesterday, still gives this kernel issue.

The question is, if there are any difference in that regard between the test and develop command? Hope this helps.

**Current status**

This works: patrol test --target integration_test\critical_workflows\photoDoc\1003_Create_full_2_of_each_doc_test.dart
This fails: patrol develop --target integration_test\critical_workflows\photoDoc\1003_Create_full_2_of_each_doc_test.dart
(on windows)


Old reply:
> Hi @jBorkowska Thanks for replying so rapidly!
> 
> Unfortunately, I get the same error when I use the absolute path.
> 
> I tried these 2 commands but get below error as before. The "kernel"-files are both 0 bytes in case that means anything.
> 
> ```
> patrol develop --target E:\Projects\AppTestAutomated\AppNew\integration_test\critical_workflows\photoDoc\1001_Create_simple_with_location_test.dart
> 
> OR
> 
> patrol develop --target E:/Projects/AppTestAutomated/AppNew/integration_test/critical_workflows/photoDoc/1001_Create_simple_with_location_test.dart
> 
> 
> You're using Patrol CLI 2.0, which has breaking changes.
> Read the migration guide at https://patrol.leancode.co/v2.
> Disable this warning by setting the PATROL_MIGRATED environment variable.
> 
>  
> 
> No device specified, using the first one (RF8R810Z1LP)
> • Building apk with entrypoint test_bundle.dart...
> Invalid depfile: E:\Projects\AppTestAutomated\AppNew\.dart_tool\flutter_build\0b0d2e57aa91fea684b4d62ac17bf222\kernel_snapshot.d
>         Invalid depfile: E:\Projects\AppTestAutomated\AppNew\.dart_tool\flutter_build\0b0d2e57aa91fea684b4d62ac17bf222\kernel_snapshot.d
>         Unhandled exception:
>         FileSystemException(uri=e:/Projects/AppTestAutomated/AppNew/integration_test/critical_workflows/photoDoc/0003_Create_full_2_of_each_doc_test.dart; message=StandardFileSystem only supports file:* and data:* URIs)
>         #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
>         #1      IncrementalCompiler._initializeExperimentalInvalidation (package:front_end/src/fasta/incremental_compiler.dart:1268:56)
>         #2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:325:17)
>         <asynchronous suspension>
>         #3      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
>         <asynchronous suspension>
>         #4      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:595:11)
>         <asynchronous suspension>
>         #5      starter (package:frontend_server/starter.dart:99:12)
>         <asynchronous suspension>
>         #6      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
>         <asynchronous suspension>
> 
>  
> 
>         Target kernel_snapshot failed: Exception
> 
>  
> 
>  
> 
>         FAILURE: Build failed with an exception.
> 
>  
> 
>         * Where:
>         Script 'E:\FlutterDev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201
> 
>  
> 
>         * What went wrong:
>         Execution failed for task ':app:compileFlutterBuildAppCenterDebug'.
>         > Process 'command 'E:\FlutterDev\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
>  
> 
>         * Try:
>         Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
>  
> 
>         * Get more help at https://help.gradle.org/
> 
>  
> 
>         BUILD FAILED in 9s
> ✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (10.7s)
> Exception: Gradle build failed with code 1
> See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
> Exception: Gradle build failed with code 1
> #0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
> <asynchronous suspension>
> #1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
> ```

**Comment by benjamin-inspectly** [comment]
Sorry for spamming... another discovery..

It seems as if I use "flutter clean" and "flutter pub get", I then have the opportunity to use ex "patrol develop XXX" and that works.
If I afterwards use "patrol test", then I'll get the "kernel"-error and then both "patrol test" and "patrol develop" fails - until I use "flutter clean" again.

I have tested this both ways, and it'll work in both "patrol test --target" and "patrol develop --target" right after I clean - but only the first one I choose. If I have used "patrol test --target" - then I need to clean before trying "patrol develop --target" and the other way around.

I don't know if this helps?

**Comment by bartekpacia** [comment]
The cause of the first problem is that [you don't have `adb` on your path](https://stackoverflow.com/questions/10303639/adb-command-not-found). Run `patrol doctor` to verify it.

The second problem is actually a bug – see #1428. [Workaround is here](https://github.com/leancodepl/patrol/issues/1428#issuecomment-1615207382).

**Comment by bartekpacia** [comment]
Closing because of lack of activity. Anyway, looks like it's been solved anyway.
