### ISSUE TITLE
No signature of method and  compileSdkVersion is not specified

### ISSUE THREAD

**Issue by eliezer-castro** [leancodepl/patrol#1620]
### Steps to reproduce

When I start the test with patrol with the command patrol test --target integration_test\app_test.dart, the error message appears with 2 failures, both related to patrol.

### Actual results

1. A problem occurred evaluating project ':patrol'.
>  No signature of method: build_16uuacgxpp0mf10vhdhfmfs2o.android() is applicable for argument types: (build_16uuacgxpp0mf10vhdhfmfs2o$_run_closure3) values: [build_16uuacgxpp0mf10vhdhfmfs2o$_run_closure3@5891274e]

2.  A problem occurred configuring project ':patrol'.
> compileSdkVersion is not specified. Please add it to build.gradle

### Logs

<details>
<summary>Logs</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

No device specified, using the first one (66e8064d0407)
• Building apk with entrypoint test_bundle.dart...

        FAILURE: Build completed with 2 failures.

        1: Task failed with an exception.
        -----------
        * Where:
        Build file 'C:\Users\ELIEZER.CASTRO\.puro\shared\pub_cache\hosted\pub.dartlang.org\patrol-2.2.1\android\build.gradle' line: 36

        * What went wrong:
        A problem occurred evaluating project ':patrol'.
        > No signature of method: build_16uuacgxpp0mf10vhdhfmfs2o.android() is applicable for argument types: (build_16uuacgxpp0mf10vhdhfmfs2o$_run_closure3) values: [build_16uuacgxpp0mf10vhdhfmfs2o$_run_closure3@2d7d5872]

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
        ==============================================================================

        2: Task failed with an exception.
        -----------
        * What went wrong:
        A problem occurred configuring project ':patrol'.
        > compileSdkVersion is not specified. Please add it to build.gradle

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
        ==============================================================================

        * Get more help at https://help.gradle.org

        BUILD FAILED in 2s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (3.2s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:230:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:320:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:264:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:76:20)
<asynchronous suspension>
#9      main (file:///C:/Users/ELIEZER.CASTRO/.puro/shared/pub_cache/hosted/pub.dartlang.org/patrol_cli-2.1.0/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

patrol: ^2.2.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.0
Program adb found in C:\Users\ELIEZER.CASTRO\AppData\Local\Android\Sdk\platform-tools\adb.exe
Env var $ANDROID_HOME set to C:\Users\ELIEZER.CASTRO\AppData\Local\Android\Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [versÆo 10.0.22621.1992], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Community Edition (version 2022.3)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

**Comment by bartekpacia** [comment]
What Gradle and AGP versions is your project using?

**Comment by eliezer-castro** [comment]
Here is Gradle and AGP version

1. android/gradle/wrapper/gradle-wrapper.properties:
> `distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip`
--
2. android/build.gradle:   
> `dependencies { 
    classpath 'com.android.tools.build:gradle:4.1.0'
 }
`

**Comment by eliezer-castro** [comment]
OK thanks!

**Comment by bartekpacia** [comment]
If it helped, please close the issue :)
