### ISSUE TITLE
.tap() throws pumpandSettle timedout when tap to navigating on the fluter view #1626

### ISSUE THREAD

**Issue by ashwinichannaveerappa** [leancodepl/patrol#1644]
### Steps to reproduce

Steps to reproduce:
1. The screen which contains rev animation
![image](https://github.com/leancodepl/patrol/assets/58765248/60bf83f5-fb80-454e-a65e-738e384b7fbe)

2. Tap on continue button

```
    await _requestAndGrantMicrophonePermission($);

    if (await $(S.current.skip).visible) {
      while (await $(S.current.skip).visible) {
        await $(S.current.skip).tap();
      }
    }else{
      await $(S.current.continue_).waitUntilVisible();

      await $(S.current.continue_).tap();

    }
```

### Actual results

java.lang.AssertionError: Dart test failed: tests.course_test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
pumpAndSettle timed out

When the exception was thrown, this was the stack:
#0 WidgetTester.pumpAndSettle. (package:flutter_test/src/widget_tester.dart:707:11)

https://github.com/leancodepl/patrol/issues/1 TestAsyncUtils.guard. (package:flutter_test/src/test_async_utils.dart:114:7)
The test description was:
Assigned Courses Test
═════════════════════════════════════════════════════════════════

at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:130)
at pl.leancode.patrol.example.MainActivityTest.runDartTest(MainActivityTest.java:30)

### Patrol version

You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.       

Update available! 2.1.1 → 2.1.2
Run patrol update to update

patrol_cli v2.1.1

### Patrol Doctor output

You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.       

Patrol CLI version: 2.1.1
Program adb found in C:\Users\achannav\scoop\shims\adb.exe
Env var $ANDROID_HOME set to C:\Users\achannav\AppData\Local\Android\sdk       

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version
    10.0.19045.3324], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)      
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.   
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all 
      of its default components
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.81.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

**Comment by ashwinichannaveerappa** [comment]
@jBorkowska  thanks a lot for the quick response. settlepolicy() worked like a charm.

``      await $(S.current.continue_).tap(settlePolicy: SettlePolicy.trySettle);
``

**Comment by ashwinichannaveerappa** [comment]
@jBorkowska thanks a lot for the quick response. settlepolicy() worked like a charm.

` await $(S.current.continue_).tap(settlePolicy: SettlePolicy.trySettle);`
