### ISSUE TITLE
Native tests fail to execute on Android simulator `Execution failed for task ':audio_session:compileDebugJavaWithJavac'.`

### ISSUE THREAD

**Issue by martinlachev** [leancodepl/patrol#1649]
### Steps to reproduce

1. Add patrol depndecies
2. Setup native automation for Android and ios
3. Use the example_test
4. Execute a `patrol test` command on an Android simulator

### Actual results

The native automation works on iOS simulators but not on Android.
The Android build process stops on `Execution failed for task ':audio_session:compileDebugJavaWithJavac'.`

### Logs

<details>
<summary>Logs</summary>

```
Verbose mode enabled. More logs will be printed.
Received 2 test target(s)
Received test target: /Users/martinlachev/Desktop/Projects/Orbis/nextmart/next_mart_app/integration_test/login_test.dart
Received test target: /Users/martinlachev/Desktop/Projects/Orbis/nextmart/next_mart_app/integration_test/login_with_wrong_credentials_test.dart
Generated entrypoint /Users/martinlachev/Desktop/Projects/Orbis/nextmart/next_mart_app/integration_test/test_bundle.dart with 2 bundled test(s)
$ flutter --no-version-check devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on
Received device: emulator-5554
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.example.next_mart_app
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.nextMartApp
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Next Mart App
Received internal --dart-define: PATROL_IOS_APP_NAME=Next Mart App
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building apk with entrypoint test_bundle.dart...
$ ./gradlew :app:assembleDebug -Ptarget=/Users/martinlachev/Desktop/Projects/Orbis/nextmart/next_mart_app/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUubmV4dF9tYXJ0X2FwcA==,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUubmV4dE1hcnRBcHA=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9TmV4dCBNYXJ0IEFwcA==,UEFUUk9MX0lPU19BUFBfTkFNRT1OZXh0IE1hcnQgQXBw,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :audio_session:preBuild UP-TO-DATE
        : > Task :audio_session:preDebugBuild UP-TO-DATE
        : > Task :audio_session:compileDebugAidl NO-SOURCE
        : > Task :background_downloader:preBuild UP-TO-DATE
        : > Task :background_downloader:preDebugBuild UP-TO-DATE
        : > Task :sqflite:preBuild UP-TO-DATE
        : > Task :sqflite:preDebugBuild UP-TO-DATE
        : > Task :sqflite:compileDebugAidl NO-SOURCE
        : > Task :background_downloader:compileDebugAidl NO-SOURCE
        : > Task :device_information:preBuild UP-TO-DATE
        : > Task :device_information:preDebugBuild UP-TO-DATE
        : > Task :device_information:compileDebugAidl NO-SOURCE
        : > Task :flutter_secure_storage:preBuild UP-TO-DATE
        : > Task :flutter_secure_storage:preDebugBuild UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugAidl NO-SOURCE
        : > Task :integration_test:preBuild UP-TO-DATE
        : > Task :integration_test:preDebugBuild UP-TO-DATE
        : > Task :integration_test:compileDebugAidl NO-SOURCE
        : > Task :just_audio:preBuild UP-TO-DATE
        : > Task :just_audio:preDebugBuild UP-TO-DATE
        : > Task :just_audio:compileDebugAidl NO-SOURCE
        : > Task :package_info_plus:preBuild UP-TO-DATE
        : > Task :package_info_plus:preDebugBuild UP-TO-DATE
        : > Task :package_info_plus:compileDebugAidl NO-SOURCE
        : > Task :path_provider_android:preBuild UP-TO-DATE
        : > Task :path_provider_android:preDebugBuild UP-TO-DATE
        : > Task :path_provider_android:compileDebugAidl NO-SOURCE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :permission_handler_android:preBuild UP-TO-DATE
        : > Task :permission_handler_android:preDebugBuild UP-TO-DATE
        : > Task :permission_handler_android:compileDebugAidl NO-SOURCE
        : > Task :shared_preferences_android:preBuild UP-TO-DATE
        : > Task :shared_preferences_android:preDebugBuild UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugAidl NO-SOURCE
        : > Task :url_launcher_android:preBuild UP-TO-DATE
        : > Task :url_launcher_android:preDebugBuild UP-TO-DATE
        : > Task :url_launcher_android:compileDebugAidl NO-SOURCE
        : > Task :video_player_android:preBuild UP-TO-DATE
        : > Task :video_player_android:preDebugBuild UP-TO-DATE
        : > Task :video_player_android:compileDebugAidl NO-SOURCE
        : > Task :wakelock_plus:preBuild UP-TO-DATE
        : > Task :wakelock_plus:preDebugBuild UP-TO-DATE
        : > Task :wakelock_plus:compileDebugAidl NO-SOURCE
        : > Task :webview_flutter_android:preBuild UP-TO-DATE
        : > Task :webview_flutter_android:preDebugBuild UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :audio_session:packageDebugRenderscript NO-SOURCE
        : > Task :background_downloader:packageDebugRenderscript NO-SOURCE
        : > Task :device_information:packageDebugRenderscript NO-SOURCE
        : > Task :flutter_secure_storage:packageDebugRenderscript NO-SOURCE
        : > Task :integration_test:packageDebugRenderscript NO-SOURCE
        : > Task :just_audio:packageDebugRenderscript NO-SOURCE
        : > Task :package_info_plus:packageDebugRenderscript NO-SOURCE
        : > Task :path_provider_android:packageDebugRenderscript NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :permission_handler_android:packageDebugRenderscript NO-SOURCE
        : > Task :shared_preferences_android:packageDebugRenderscript NO-SOURCE
        : > Task :sqflite:packageDebugRenderscript NO-SOURCE
        : > Task :url_launcher_android:packageDebugRenderscript NO-SOURCE
        : > Task :video_player_android:packageDebugRenderscript NO-SOURCE
        : > Task :wakelock_plus:packageDebugRenderscript NO-SOURCE
        : > Task :webview_flutter_android:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :audio_session:writeDebugAarMetadata UP-TO-DATE
        : > Task :background_downloader:writeDebugAarMetadata UP-TO-DATE
        : > Task :device_information:writeDebugAarMetadata UP-TO-DATE
        : > Task :flutter_secure_storage:writeDebugAarMetadata UP-TO-DATE
        : > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
        : > Task :just_audio:writeDebugAarMetadata UP-TO-DATE
        : > Task :package_info_plus:writeDebugAarMetadata UP-TO-DATE
        : > Task :path_provider_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :permission_handler_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :shared_preferences_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :sqflite:writeDebugAarMetadata UP-TO-DATE
        : > Task :url_launcher_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :video_player_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :wakelock_plus:writeDebugAarMetadata UP-TO-DATE
        : > Task :webview_flutter_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :audio_session:mergeDebugShaders UP-TO-DATE
        : > Task :audio_session:compileDebugShaders NO-SOURCE
        : > Task :audio_session:generateDebugAssets UP-TO-DATE
        : > Task :audio_session:packageDebugAssets UP-TO-DATE
        : > Task :background_downloader:mergeDebugShaders UP-TO-DATE
        : > Task :background_downloader:compileDebugShaders NO-SOURCE
        : > Task :background_downloader:generateDebugAssets UP-TO-DATE
        : > Task :background_downloader:packageDebugAssets UP-TO-DATE
        : > Task :device_information:mergeDebugShaders UP-TO-DATE
        : > Task :device_information:compileDebugShaders NO-SOURCE
        : > Task :device_information:generateDebugAssets UP-TO-DATE
        : > Task :device_information:packageDebugAssets UP-TO-DATE
        : > Task :flutter_secure_storage:mergeDebugShaders UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugShaders NO-SOURCE
        : > Task :flutter_secure_storage:generateDebugAssets UP-TO-DATE
        : > Task :flutter_secure_storage:packageDebugAssets UP-TO-DATE
        : > Task :integration_test:mergeDebugShaders UP-TO-DATE
        : > Task :integration_test:compileDebugShaders NO-SOURCE
        : > Task :integration_test:generateDebugAssets UP-TO-DATE
        : > Task :integration_test:packageDebugAssets UP-TO-DATE
        : > Task :just_audio:mergeDebugShaders UP-TO-DATE
        : > Task :just_audio:compileDebugShaders NO-SOURCE
        : > Task :just_audio:generateDebugAssets UP-TO-DATE
        : > Task :just_audio:packageDebugAssets UP-TO-DATE
        : > Task :package_info_plus:mergeDebugShaders UP-TO-DATE
        : > Task :package_info_plus:compileDebugShaders NO-SOURCE
        : > Task :package_info_plus:generateDebugAssets UP-TO-DATE
        : > Task :package_info_plus:packageDebugAssets UP-TO-DATE
        : > Task :path_provider_android:mergeDebugShaders UP-TO-DATE
        : > Task :path_provider_android:compileDebugShaders NO-SOURCE
        : > Task :path_provider_android:generateDebugAssets UP-TO-DATE
        : > Task :path_provider_android:packageDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :permission_handler_android:mergeDebugShaders UP-TO-DATE
        : > Task :permission_handler_android:compileDebugShaders NO-SOURCE
        : > Task :permission_handler_android:generateDebugAssets UP-TO-DATE
        : > Task :permission_handler_android:packageDebugAssets UP-TO-DATE
        : > Task :shared_preferences_android:mergeDebugShaders UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugShaders NO-SOURCE
        : > Task :shared_preferences_android:generateDebugAssets UP-TO-DATE
        : > Task :shared_preferences_android:packageDebugAssets UP-TO-DATE
        : > Task :sqflite:mergeDebugShaders UP-TO-DATE
        : > Task :sqflite:compileDebugShaders NO-SOURCE
        : > Task :sqflite:generateDebugAssets UP-TO-DATE
        : > Task :sqflite:packageDebugAssets UP-TO-DATE
        : > Task :url_launcher_android:mergeDebugShaders UP-TO-DATE
        : > Task :url_launcher_android:compileDebugShaders NO-SOURCE
        : > Task :url_launcher_android:generateDebugAssets UP-TO-DATE
        : > Task :url_launcher_android:packageDebugAssets UP-TO-DATE
        : > Task :video_player_android:mergeDebugShaders UP-TO-DATE
        : > Task :video_player_android:compileDebugShaders NO-SOURCE
        : > Task :video_player_android:generateDebugAssets UP-TO-DATE
        : > Task :video_player_android:packageDebugAssets UP-TO-DATE
        : > Task :wakelock_plus:mergeDebugShaders UP-TO-DATE
        : > Task :wakelock_plus:compileDebugShaders NO-SOURCE
        : > Task :wakelock_plus:generateDebugAssets UP-TO-DATE
        : > Task :wakelock_plus:packageDebugAssets UP-TO-DATE
        : > Task :webview_flutter_android:mergeDebugShaders UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugShaders NO-SOURCE
        : > Task :webview_flutter_android:generateDebugAssets UP-TO-DATE
        : > Task :webview_flutter_android:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :audio_session:compileDebugRenderscript NO-SOURCE
        : > Task :audio_session:generateDebugResValues UP-TO-DATE
        : > Task :audio_session:generateDebugResources UP-TO-DATE
        : > Task :audio_session:packageDebugResources UP-TO-DATE
        : > Task :background_downloader:compileDebugRenderscript NO-SOURCE
        : > Task :background_downloader:generateDebugResValues UP-TO-DATE
        : > Task :background_downloader:generateDebugResources UP-TO-DATE
        : > Task :background_downloader:packageDebugResources UP-TO-DATE
        : > Task :device_information:compileDebugRenderscript NO-SOURCE
        : > Task :device_information:generateDebugResValues UP-TO-DATE
        : > Task :device_information:generateDebugResources UP-TO-DATE
        : > Task :device_information:packageDebugResources UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugRenderscript NO-SOURCE
        : > Task :flutter_secure_storage:generateDebugResValues UP-TO-DATE
        : > Task :flutter_secure_storage:generateDebugResources UP-TO-DATE
        : > Task :flutter_secure_storage:packageDebugResources UP-TO-DATE
        : > Task :integration_test:compileDebugRenderscript NO-SOURCE
        : > Task :integration_test:generateDebugResValues UP-TO-DATE
        : > Task :integration_test:generateDebugResources UP-TO-DATE
        : > Task :integration_test:packageDebugResources UP-TO-DATE
        : > Task :just_audio:compileDebugRenderscript NO-SOURCE
        : > Task :just_audio:generateDebugResValues UP-TO-DATE
        : > Task :just_audio:generateDebugResources UP-TO-DATE
        : > Task :just_audio:packageDebugResources UP-TO-DATE
        : > Task :package_info_plus:compileDebugRenderscript NO-SOURCE
        : > Task :package_info_plus:generateDebugResValues UP-TO-DATE
        : > Task :package_info_plus:generateDebugResources UP-TO-DATE
        : > Task :package_info_plus:packageDebugResources UP-TO-DATE
        : > Task :path_provider_android:compileDebugRenderscript NO-SOURCE
        : > Task :path_provider_android:generateDebugResValues UP-TO-DATE
        : > Task :path_provider_android:generateDebugResources UP-TO-DATE
        : > Task :path_provider_android:packageDebugResources UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :permission_handler_android:compileDebugRenderscript NO-SOURCE
        : > Task :permission_handler_android:generateDebugResValues UP-TO-DATE
        : > Task :permission_handler_android:generateDebugResources UP-TO-DATE
        : > Task :permission_handler_android:packageDebugResources UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugRenderscript NO-SOURCE
        : > Task :shared_preferences_android:generateDebugResValues UP-TO-DATE
        : > Task :shared_preferences_android:generateDebugResources UP-TO-DATE
        : > Task :shared_preferences_android:packageDebugResources UP-TO-DATE
        : > Task :sqflite:compileDebugRenderscript NO-SOURCE
        : > Task :sqflite:generateDebugResValues UP-TO-DATE
        : > Task :sqflite:generateDebugResources UP-TO-DATE
        : > Task :sqflite:packageDebugResources UP-TO-DATE
        : > Task :url_launcher_android:compileDebugRenderscript NO-SOURCE
        : > Task :url_launcher_android:generateDebugResValues UP-TO-DATE
        : > Task :url_launcher_android:generateDebugResources UP-TO-DATE
        : > Task :url_launcher_android:packageDebugResources UP-TO-DATE
        : > Task :video_player_android:compileDebugRenderscript NO-SOURCE
        : > Task :video_player_android:generateDebugResValues UP-TO-DATE
        : > Task :video_player_android:generateDebugResources UP-TO-DATE
        : > Task :video_player_android:packageDebugResources UP-TO-DATE
        : > Task :wakelock_plus:compileDebugRenderscript NO-SOURCE
        : > Task :wakelock_plus:generateDebugResValues UP-TO-DATE
        : > Task :wakelock_plus:generateDebugResources UP-TO-DATE
        : > Task :wakelock_plus:packageDebugResources UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugRenderscript NO-SOURCE
        : > Task :webview_flutter_android:generateDebugResValues UP-TO-DATE
        : > Task :webview_flutter_android:generateDebugResources UP-TO-DATE
        : > Task :webview_flutter_android:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :audio_session:extractDeepLinksDebug UP-TO-DATE
        : > Task :audio_session:processDebugManifest UP-TO-DATE
        : > Task :background_downloader:extractDeepLinksDebug UP-TO-DATE
        : > Task :background_downloader:processDebugManifest UP-TO-DATE
        : > Task :device_information:extractDeepLinksDebug UP-TO-DATE
        : > Task :device_information:processDebugManifest UP-TO-DATE
        : > Task :flutter_secure_storage:extractDeepLinksDebug UP-TO-DATE
        : > Task :flutter_secure_storage:processDebugManifest UP-TO-DATE
        : > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:processDebugManifest UP-TO-DATE
        : > Task :just_audio:extractDeepLinksDebug UP-TO-DATE
        : > Task :just_audio:processDebugManifest UP-TO-DATE
        : > Task :package_info_plus:extractDeepLinksDebug UP-TO-DATE
        : > Task :package_info_plus:processDebugManifest UP-TO-DATE
        : > Task :path_provider_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :path_provider_android:processDebugManifest UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :permission_handler_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :permission_handler_android:processDebugManifest UP-TO-DATE
        : > Task :shared_preferences_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :shared_preferences_android:processDebugManifest UP-TO-DATE
        : > Task :sqflite:extractDeepLinksDebug UP-TO-DATE
        : > Task :sqflite:processDebugManifest UP-TO-DATE
        : > Task :url_launcher_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :url_launcher_android:processDebugManifest UP-TO-DATE
        : > Task :video_player_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :video_player_android:processDebugManifest UP-TO-DATE
        : > Task :wakelock_plus:extractDeepLinksDebug UP-TO-DATE
        : > Task :wakelock_plus:processDebugManifest UP-TO-DATE
        : > Task :webview_flutter_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :webview_flutter_android:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :audio_session:compileDebugLibraryResources UP-TO-DATE
        : > Task :audio_session:parseDebugLocalResources UP-TO-DATE
        : > Task :audio_session:generateDebugRFile UP-TO-DATE
        : > Task :background_downloader:compileDebugLibraryResources UP-TO-DATE
        : > Task :background_downloader:parseDebugLocalResources UP-TO-DATE
        : > Task :sqflite:parseDebugLocalResources UP-TO-DATE
        : > Task :sqflite:generateDebugRFile UP-TO-DATE
        : > Task :background_downloader:generateDebugRFile UP-TO-DATE
        : > Task :device_information:compileDebugLibraryResources UP-TO-DATE
        : > Task :device_information:parseDebugLocalResources UP-TO-DATE
        : > Task :device_information:generateDebugRFile UP-TO-DATE
        : > Task :flutter_secure_storage:compileDebugLibraryResources UP-TO-DATE
        : > Task :flutter_secure_storage:parseDebugLocalResources UP-TO-DATE
        : > Task :flutter_secure_storage:generateDebugRFile UP-TO-DATE
        : > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
        : > Task :integration_test:parseDebugLocalResources UP-TO-DATE
        : > Task :integration_test:generateDebugRFile UP-TO-DATE
        : > Task :just_audio:compileDebugLibraryResources UP-TO-DATE
        : > Task :just_audio:parseDebugLocalResources UP-TO-DATE
        : > Task :just_audio:generateDebugRFile UP-TO-DATE
        : > Task :package_info_plus:compileDebugLibraryResources UP-TO-DATE
        : > Task :package_info_plus:parseDebugLocalResources UP-TO-DATE
        : > Task :package_info_plus:generateDebugRFile UP-TO-DATE
        : > Task :path_provider_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :path_provider_android:parseDebugLocalResources UP-TO-DATE
        : > Task :path_provider_android:generateDebugRFile UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :permission_handler_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :permission_handler_android:parseDebugLocalResources UP-TO-DATE
        : > Task :permission_handler_android:generateDebugRFile UP-TO-DATE
        : > Task :shared_preferences_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :shared_preferences_android:parseDebugLocalResources UP-TO-DATE
        : > Task :shared_preferences_android:generateDebugRFile UP-TO-DATE
        : > Task :sqflite:compileDebugLibraryResources UP-TO-DATE
        : > Task :url_launcher_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :url_launcher_android:parseDebugLocalResources UP-TO-DATE
        : > Task :url_launcher_android:generateDebugRFile UP-TO-DATE
        : > Task :video_player_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :video_player_android:parseDebugLocalResources UP-TO-DATE
        : > Task :video_player_android:generateDebugRFile UP-TO-DATE
        : > Task :wakelock_plus:compileDebugLibraryResources UP-TO-DATE
        : > Task :wakelock_plus:parseDebugLocalResources UP-TO-DATE
        : > Task :wakelock_plus:generateDebugRFile UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :webview_flutter_android:parseDebugLocalResources UP-TO-DATE
        : > Task :webview_flutter_android:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :audio_session:generateDebugBuildConfig UP-TO-DATE
        : > Task :audio_session:javaPreCompileDebug UP-TO-DATE
        : 
        : > Task :audio_session:compileDebugJavaWithJavac FAILED
        warning: [options] source value 8 is obsolete and will be removed in a future release
        warning: [options] target value 8 is obsolete and will be removed in a future release
        warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
        error: warnings found and -Werror specified

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':audio_session:compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 4s
        : 
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
        : 
        : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        : 
        : See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
        : 180 actionable tasks: 5 executed, 175 up-to-date
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (5.3s)
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:230:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:320:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:264:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:76:20)
<asynchronous suspension>
#9      main (file:///Users/martinlachev/.pub-cache/hosted/pub.dev/patrol_cli-2.1.2/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:230:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:320:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:264:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:76:20)
<asynchronous suspension>
#9      main (file:///Users/martinlachev/.pub-cache/hosted/pub.dev/patrol_cli-2.1.2/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

patrol: ^2.2.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.1.2
Program adb found in /Users/martinlachev/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/martinlachev/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-BG)
    • Flutter version 3.10.6 on channel stable at /Users/martinlachev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/martinlachev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/martinlachev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by fylyppo** [comment]
Hi, can you show me the output from `./android/gradlew --version`? I want to check your Gradle version. Maybe it's incompatible with your java version.

**Comment by fylyppo** [comment]
So probably that's the issue. You have java 20 and gradle 7.5. Check out [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html). You can downgrade your java version to 17 and check if the tests will be compiling.

**Comment by mateuszwojtczak** [comment]
Hi @martinlachev! It looks like audio_session Android plugin can't compile with Patrol, maybe there's some other logs that could tell us more? It could also be related to Java version, it's always recommended to use Java Bundled Runtime (jbr) from Android Studio toolchain.

**Comment by martinlachev** [comment]
@fylyppo @mateuszwojtczak Thanks for the support guys! 
I was able to run the tests on Android.
Should I close the issue?

**Comment by fylyppo** [comment]
@martinlachev what was the issue and how you resolved it?

**Comment by martinlachev** [comment]
@fylyppo As you suggested I used the appropriate gradle and jdk versions.
