### ISSUE TITLE
Close a dialog by clicking its ModalBarrier

### ISSUE THREAD

**Issue by HeropolisDa2ny** [leancodepl/patrol#1669]
### Steps to reproduce

The page :

```
class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ElevatedButton(
        onPressed: () => showDialog(
          context: context,
          builder: (context) => Dialog(
            child: Card(
              child: SizedBox(
                height: MediaQuery.of(context).size.height,
                width: MediaQuery.of(context).size.width,
              ),
            ),
          ),
        ),
        child: Text('Test'),
      ),
    );
  }
}
```

The failing tests :

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $.tester.tap(find.byType(ModalBarrier));
```

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $.tester.tap(find.byType(ModalBarrier).first);
```

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $.tester.tap(find.byType(ModalBarrier).last);
```

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $(ModalBarrier).tap();
```

### Actual results

I am trying to close a dialog which hasn't closing buttons.

I tried these solutions but seems not working on patrol : https://stackoverflow.com/questions/56602717/how-to-close-dialog-using-flutterdriver.

The errors for the tests : 

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $(ModalBarrier).tap();
```

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $.tester.tap(find.byType(ModalBarrier));
```

 ```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        The following WaitUntilVisibleTimeoutException was thrown running a test:
        TimeoutException after 0:00:10.000000: Finder "2 widgets with type "ModalBarrier" (ignoring offstage
        widgets): [ModalBarrier, ModalBarrier(dependencies: [Directionality])]" did not find any visible
        (i.e. hit-testable) widgets
        
        When the exception was thrown, this was the stack:
        #0      PatrolTester.waitUntilVisible.<anonymous closure> (package:patrol_finders/src/custom_finders/patrol_tester.dart:382:11)
        <asynchronous suspension>
        #1      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:114:7)
        <asynchronous suspension>
```

---------------------------------------------------------------------------------------------------------------

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $.tester.tap(find.byType(ModalBarrier).first);
```

```
Warning: A call to tap() with finder "exactly one widget with type "ModalBarrier" (ignoring all but first) (ignoring offstage widgets): ModalBarrier" derived an Offset (Offset(205.7, 453.1)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
The finder corresponds to this RenderBox: RenderBlockSemantics#2af3a
The hit test result at that offset is: HitTestResult(_RenderInkFeatures#9060d@Offset(161.7, 386.3), RenderCustomPaint#7f982@Offset(161.7, 386.3), RenderPhysicalShape#53c6f@Offset(161.7, 386.3), RenderPadding#b6231@Offset(165.7, 390.3), RenderSemanticsAnnotations#2271a@Offset(165.7, 390.3), _RenderInkFeatures#e4973@Offset(165.7, 390.3), RenderCustomPaint#4ca6b@Offset(165.7, 390.3), RenderPhysicalShape#306dd@Offset(165.7, 390.3), RenderConstrainedBox#58b61@Offset(165.7, 390.3), RenderPositionedBox#c55fb@Offset(165.7, 390.3), RenderPadding#edccb@Offset(205.7, 414.3), RenderPadding#7c86b@Offset(205.7, 414.3), RenderPadding#1e6f0@Offset(205.7, 414.3), RenderSemanticsAnnotations#8992d@Offset(205.7, 414.3), RenderRepaintBoundary#737a5@Offset(205.7, 414.3), RenderIgnorePointer#22673@Offset(205.7, 414.3), RenderAnimatedOpacity#a41d1@Offset(205.7, 414.3), RenderRepaintBoundary#2ab41@Offset(205.7, 414.3), RenderSemanticsAnnotations#94629@Offset(205.7, 414.3), RenderOffstage#c0e45@Offset(205.7, 414.3), RenderSemanticsAn
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1347:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      incidentMultiple.<anonymous closure> (file:///Users/[USER]/Projects/front-flutter/integration_test/incidents/success/incidents.multiple_steps.dart:102:20)
<asynchronous suspension>
#4      patrolTest.<anonymous closure> (package:patrol/src/common.dart:136:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following WaitUntilVisibleTimeoutException was thrown running a test:
TimeoutException after 0:00:10.000000: Finder "exactly one widget with text "Incidents" (ignoring
offstage widgets): RichText(softWrap: wrapping at box width, maxLines: unlimited, text: "Incidents",
dependencies: [Directionality, _LocalizationsScope-[GlobalKey#036be]], renderObject:
RenderParagraph#ef47a)" did not find any visible (i.e. hit-testable) widgets

When the exception was thrown, this was the stack:
#0      PatrolTester.waitUntilVisible.<anonymous closure> (package:patrol_finders/src/custom_finders/patrol_tester.dart:382:11)
<asynchronous suspension>
#1      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:114:7)
<asynchronous suspension>

════════════════════════════════════════════════════════════════════════════════════════════════════
```

---------------------------------------------------------------------------------------------------------------

```
await $('Test').tap();
await $(Dialog).waitUntilVisible();
await $.tester.tap(find.byType(ModalBarrier).last);
```

```
Warning: A call to tap() with finder "exactly one widget with type "ModalBarrier" (ignoring all but last) (ignoring offstage widgets): ModalBarrier(dependencies: [Directionality])" derived an Offset (Offset(205.7, 453.1)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
The finder corresponds to this RenderBox: RenderBlockSemantics#8f569
The hit test result at that offset is: HitTestResult(_RenderInkFeatures#29923@Offset(161.7, 386.3), RenderCustomPaint#9c187@Offset(161.7, 386.3), RenderPhysicalShape#ac4f8@Offset(161.7, 386.3), RenderPadding#18e81@Offset(165.7, 390.3), RenderSemanticsAnnotations#a8709@Offset(165.7, 390.3), _RenderInkFeatures#35a64@Offset(165.7, 390.3), RenderCustomPaint#4e19a@Offset(165.7, 390.3), RenderPhysicalShape#fefaa@Offset(165.7, 390.3), RenderConstrainedBox#b6384@Offset(165.7, 390.3), RenderPositionedBox#b01ce@Offset(165.7, 390.3), RenderPadding#26b3f@Offset(205.7, 414.3), RenderPadding#a2cd9@Offset(205.7, 414.3), RenderPadding#52d40@Offset(205.7, 414.3), RenderSemanticsAnnotations#8bbb7@Offset(205.7, 414.3), RenderRepaintBoundary#7034b@Offset(205.7, 414.3), RenderIgnorePointer#3c29c@Offset(205.7, 414.3), RenderAnimatedOpacity#49183@Offset(205.7, 414.3), RenderRepaintBoundary#0930b@Offset(205.7, 414.3), RenderSemanticsAnnotations#7bb94@Offset(205.7, 414.3), RenderOffstage#6ac86@Offset(205.7, 414.3), RenderSemanticsAn
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1347:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      incidentMultiple.<anonymous closure> (file:///Users/[USER]/Projects/front-flutter/integration_test/incidents/success/incidents.multiple_steps.dart:102:20)
<asynchronous suspension>
#4      patrolTest.<anonymous closure> (package:patrol/src/common.dart:136:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following WaitUntilVisibleTimeoutException was thrown running a test:
TimeoutException after 0:00:10.000000: Finder "exactly one widget with text "Incidents" (ignoring
offstage widgets): RichText(softWrap: wrapping at box width, maxLines: unlimited, text: "Incidents",
dependencies: [Directionality, _LocalizationsScope-[GlobalKey#3a001]], renderObject:
RenderParagraph#dd6d1)" did not find any visible (i.e. hit-testable) widgets

When the exception was thrown, this was the stack:
#0      PatrolTester.waitUntilVisible.<anonymous closure> (package:patrol_finders/src/custom_finders/patrol_tester.dart:382:11)
<asynchronous suspension>
#1      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:114:7)
<asynchronous suspension>

════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.2.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.2
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
/Users/[USER]/development/flutter/bin/flutter doctor --verbose
  [!] Flutter (Channel stable, 3.10.6, on macOS 13.0 22A380 darwin-arm64, locale en-FR)
  • Flutter version 3.10.6 on channel stable at /Users/[USER]/development/flutter
  ! The flutter binary is not on your path. Consider adding /Users/[USER]/development/flutter/bin to your path.
  ! The dart binary is not on your path. Consider adding /Users/[USER]/development/flutter/bin to your path.
  • Upstream repository https://github.com/flutter/flutter.git
  • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
  • Engine revision cdbeda788a
  • Dart version 3.0.6
  • DevTools version 2.23.1
  • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
  
  [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
  • Android SDK at /Users/[USER]/Library/Android/sdk
  • Platform android-33, build-tools 33.0.2
• Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
  • All Android licenses accepted.
  
  [!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Build 14E300c
  ✗ CocoaPods not installed.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
  To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
  
  [✓] Chrome - develop for the web
  • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  
  [✓] Android Studio (version 2022.2)
  • Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
  🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
  🔨 https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
  
  [✓] VS Code (version 1.78.2)
  • VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
  🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
  
  [✓] Connected device (3 available)
  • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
  • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
  • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.140
  
  [✓] Network resources
  • All expected network resources are available.
  
  ! Doctor found issues in 2 categories.
```

</details>

**Comment by mateuszwojtczak** [comment]
Hey! Logs indicate that Patrol found the ModalBarrier widget, but it wasn't hittestable. Maybe there's something else that obscures it.
If you use Android, you can try executing `$.native.pressBack()` - it should also dismiss modals.
If not, please provide some minimal reproducible sample, so we can debug it :)

**Comment by bartekpacia** [comment]
Closing because of inactivity and lack of reproducible example.

Feel free to open a new issue with all the required information provided, including a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).
