### ISSUE TITLE
Execution failed for task ':patrol:compileDebugKotlin' by using "patrol build android"

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1676]
### Steps to reproduce

patrol build android --target integration_test/patrol_test.dart --debug

### Actual results

<details>
<summary>Logs</summary>

```
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

• Building apk with entrypoint test_bundle.dart...
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:20:37 Unresolved reference: nativeView
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:21:37 Unresolved reference: notification
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:25:12 Unresolved reference: nativeView
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:27:13 Unresolved reference: className
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:31:13 Unresolved reference: text
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:35:13 Unresolved reference: contentDescription
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:38:9 Unresolved reference: focused
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:39:9 Unresolved reference: enabled
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:40:9 Unresolved reference: childCount
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:43:13 Unresolved reference: resourceName
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:47:13 Unresolved reference: applicationPackage
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:50:9 Unresolved reference: children
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:337:32 Unresolved reference: notification
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:340:26 Unresolved reference: appName
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:346:26 Unresolved reference: title
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/Automator.kt:355:26 Unresolved reference: content
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:12:37 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:13:37 Unresolved reference: getNativeViewsResponse
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:14:37 Unresolved reference: getNotificationsResponse
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:15:37 Unresolved reference: permissionDialogVisibleResponse
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:23:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:28:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:33:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:38:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:43:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:48:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:53:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:58:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:63:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:68:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:73:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:78:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:83:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:88:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:93:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:98:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:103:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:108:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:113:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:118:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:123:16 Unresolved reference: getNativeViewsResponse
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:123:41 Unresolved reference: nativeViews
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:128:16 Unresolved reference: getNotificationsResponse
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:128:43 Unresolved reference: notifications
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:138:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:148:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:170:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:181:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:190:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:195:16 Unresolved reference: permissionDialogVisibleResponse
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:195:55 Unresolved reference: visible
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:205:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:214:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:223:16 Unresolved reference: empty
        e: file:///Users/rus/.pub-cache/hosted/pub.dev/patrol-2.2.4/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt:228:16 Unresolved reference: empty
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':patrol:compileDebugKotlin'.
        > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
           > Compilation error. See log for more details
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 17s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (17.9s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      BuildAndroidCommand.run (package:patrol_cli/src/commands/build_android.dart:125:7)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:329:18)
<asynchronous suspension>
#6      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:273:18)
<asynchronous suspension>
#7      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:85:20)
<asynchronous suspension>
#8      main (file:///Users/rus/.pub-cache/hosted/pub.dev/patrol_cli-2.1.3/bin/main.dart:6:20)
<asynchronous suspension>

```

</details>

### Patrol version

^2.2.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.3
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4 22F66 darwin-arm64, locale ru-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android SDK file not found: /Users/rus/Library/Android/sdk/platforms/android-34/android.jar.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (2 available)            
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by bartekpacia** [comment]
Hi, try these (line by line):

```
cd ./android && ./gradlew :clean && cd ..
rm -rf ./build
rm -rf ~/.gradle/caches
dart pub cache clean && flutter pub get
./gradlew --stop
```

**Comment by bartekpacia** [comment]
Closing - lack of response.
