### ISSUE TITLE
enterTextByIndex in webview doesn't work

### ISSUE THREAD

**Issue by ashwinichannaveerappa** [leancodepl/patrol#1679]
### Steps to reproduce

1.Use auth0.loin.domainName.com as base url
2. try to enter text in form and submit
3. App stuck on login screen

### Actual results

I have tried the way mentioned in the patrol docs. It was working earlier now after upgrading to Patrol_CLI its failing.

```
 await $.native.enterTextByIndex("test@gmail.com", index: 0); // enter username
    await $.native.enterTextByIndex("Testing@1234", index: 1); // enter password
    await $.native.tap(Selector(resourceId: "1-submit"));
```

Tried  with resource ID as well
```
await $.native.enterText(Selector(resourceId: "1-email"),  text: "ashu.analyst@gmail.com");
    await $.native.enterText(Selector(resourceId: "1-password"),  text: "Testing@1234");
```

![image](https://github.com/leancodepl/patrol/assets/58765248/312398e9-5457-4a4f-8df7-a89c73cd37cc)

```java.lang.AssertionError: Dart test failed: tests.training_test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: GrpcError: enterTextByIndex() failed with
code NOT_FOUND (selector BySelector
[CLASS='\Qandroid.widget.EditText\E'] found nothing)``


Device information
Device: Pixel 3
Android 12

### Logs

java.lang.AssertionError: Dart test failed: tests.training_test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: GrpcError: enterTextByIndex() failed with
code NOT_FOUND (selector BySelector
[CLASS='\Qandroid.widget.EditText\E'] found nothing)

When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:237:7)
<asynchronous suspension>
#1      NativeAutomator.enterTextByIndex (package:patrol/src/native/native_automator.dart:622:5)
<asynchronous suspension>
#2      BaseClass.loginWithValidCredentials (file:///C:/Users/achannav/redi_flutter/redi2-app/integration_test/screens/base_class.dart:33:5)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///C:/Users/achannav/redi_flutter/redi2-app/integration_test/tests/training_test.dart:21:9)
<asynchronous suspension>
#4      patrolTest.<anonymous closure> (package:patrol/src/common.dart:136:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:165:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:982:5)
<asynchronous suspension>

The test description was:
Training Session  Test
═════════════════════════════════════════════════════════════════

at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:130)
at com.medel.ai.redi.MainActivityTest.runDartTest(MainActivityTest.java:30)

### Patrol version

  patrol: ^2.0.0


### Patrol Doctor output

In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.

You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.3
Program adb found in C:\Users\achannav\scoop\shims\adb.exe
Env var $ANDROID_HOME set to C:\Users\achannav\AppData\Local\Android\sdk


### Flutter Doctor output

[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
    • Flutter version 3.13.0 on channel stable at C:\Users\achannav\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (4 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\achannav\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\achannav\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3
    • Flutter plugin version 72.1.5
    • Dart plugin version 231.8109.91

[√] VS Code (version 1.81.0)
    • VS Code at C:\Users\achannav\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (4 available)
    • Pixel 3 (mobile)  • 8AXX11EA2 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows   • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)      • chrome    • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)        • edge      • web-javascript • Microsoft Edge 116.0.1938.76

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by bartekpacia** [comment]
auth0.loin.domainName.com doesn't exist. This issue is not reproducible.

Interaction with WebView has its problems, see #244 to learn more.

**Comment by ashwinichannaveerappa** [comment]
@bartekpacia `auth.login.medel.com`

**Comment by bartekpacia** [comment]
I'm getting `Access Denied`

**Comment by ashwinichannaveerappa** [comment]
could you please try this url

`https://auth.login.medel.com/login?state=hKFo2SBCcFZrT0tmSzB3RUJqTkJ2emhGRllnSHNZRVI1Y1ZjQ6FupWxvZ2luo3RpZNkgZUc1M3RMWWRwNjFFakxidWp0TUxmcjdycmU5a3pFOGijY2lk2SBtc1phWkVPbFFiaXM4TXlQWmlVd2lmY0tTN1poU1pYUw&client=msZaZEOlQbis8MyPZiUwifcKS7ZhSZXS&protocol=oauth2&response_type=code&redirect_uri=https%3A%2F%2Fdashboard.redi.medel.ai%2F%23%2Fcallback&scope=openid%20email%20offline_access&audience=https%3A%2F%2Fapi.redi.medel.ai%2F&lc=en&connection_scope=openid%20email%20offline_access&code_challenge=r8Dfot7yDTancqnaLvvlWIT9adgdeuEZSr9BfCu2A6Y&code_challenge_method=S256`

**Comment by bartekpacia** [comment]
Yeah, I got it now.

**Comment by bartekpacia** [comment]
We have quite a big backlog, but we'll get to it sooner or later.

**Comment by ashwinichannaveerappa** [comment]
@bartekpacia thanks a lot, but very strange thing is the same code was working from last2 months. today only change i made is upgraded to latest Patrol CLI

**Comment by ashwinichannaveerappa** [comment]
@bartekpacia is anything wrong with my common.dart?
```
Future<void> createApp(PatrolIntegrationTester $) async {
  await app.main();
}

final desiredLocale = String.fromEnvironment('locale', defaultValue: 'en'); //.split(',');

Future<void> loadLocalization() async {
  await S.load(Locale(desiredLocale));
}



void patrol(
    String description,
    Future<void> Function(PatrolTester) callback, {
      bool? skip,
      NativeAutomatorConfig? nativeAutomatorConfig,
      LiveTestWidgetsFlutterBindingFramePolicy framePolicy =
          LiveTestWidgetsFlutterBindingFramePolicy.fadePointers,
    }) {
  patrolTest(
    description,
    config: _patrolTesterConfig,
    nativeAutomatorConfig: nativeAutomatorConfig ?? _nativeAutomatorConfig,
    framePolicy: framePolicy,
    skip: skip,
    callback,
  );
}```

**Comment by ashwinichannaveerappa** [comment]
Hello @bartekpacia, I hope you're doing well. I was wondering if there have been any updates regarding this issue?

**Comment by bartekpacia** [comment]
No updates, sorry.

**Comment by moodiradi** [comment]
Hello @bartekpacia , i am facing the same problem i have two edit texts in a web view one for user name and the other for password, when i run the test its entering the data in the first field but its not finding the second edit field, i tried to remove the first field in the test and keep the password it worked patrol found the second field but when both are available its filling only one field.

await $.native.enterTextByIndex('Text', index: 0); // i remove this line the second field will be filled 
await $.native.enterTextByIndex('Text', index: 1); 

The following PatrolActionException was thrown running a test:
Patrol action failed: NativeAutomatorClientException:
enterTextByIndex() failed with Invalid response: 404 selector
BySelector [CLASS='\Qandroid.widget.EditText\E'] found nothing

I cant share the link for the website because its private but those appeared from window_dump.xml 

`<node
                                                                                                    bounds="[66,1367][214,1409]"
                                                                                                    checkable="false"
                                                                                                    checked="false"
                                                                                                    class="android.view.View"
                                                                                                    clickable="false"
                                                                                                    content-desc=""
                                                                                                    enabled="true"
                                                                                                    focusable="false"
                                                                                                    focused="false"
                                                                                                    index="2"
                                                                                                    long-clickable="false"
                                                                                                    package="com.youtap.aera.consumer2.staging"
                                                                                                    password="false"
                                                                                                    resource-id=""
                                                                                                    scrollable="false"
                                                                                                    selected="false"
                                                                                                    text="Username" />
                                                                                                <node
                                                                                                    NAF="true"
                                                                                                    bounds="[66,1422][1014,1527]"
                                                                                                    checkable="false"
                                                                                                    checked="false"
                                                                                                    class="android.widget.EditText"
                                                                                                    clickable="true"
                                                                                                    content-desc=""
                                                                                                    enabled="true"
                                                                                                    focusable="true"
                                                                                                    focused="true"
                                                                                                    index="3"
                                                                                                    long-clickable="false"
                                                                                                    package="com.youtap.aera.consumer2.staging"
                                                                                                    password="false"
                                                                                                    resource-id=""
                                                                                                    scrollable="false"
                                                                                                    selected="false"
                                                                                                    text="" />`

`<node
                                                                                                    bounds="[66,1563][211,1604]"
                                                                                                    checkable="false"
                                                                                                    checked="false"
                                                                                                    class="android.view.View"
                                                                                                    clickable="false"
                                                                                                    content-desc=""
                                                                                                    enabled="true"
                                                                                                    focusable="false"
                                                                                                    focused="false"
                                                                                                    index="4"
                                                                                                    long-clickable="false"
                                                                                                    package="com.test.something"
                                                                                                    password="false"
                                                                                                    resource-id=""
                                                                                                    scrollable="false"
                                                                                                    selected="false"
                                                                                                    text="Password" />
                                                                                                <node
                                                                                                    NAF="true"
                                                                                                    bounds="[66,1618][1014,1722]"
                                                                                                    checkable="false"
                                                                                                    checked="false"
                                                                                                    class="android.widget.EditText"
                                                                                                    clickable="true"
                                                                                                    content-desc=""
                                                                                                    enabled="true"
                                                                                                    focusable="true"
                                                                                                    focused="false"
                                                                                                    index="5"
                                                                                                    long-clickable="false"
                                                                                                    package="com.test.something"
                                                                                                    password="true"
                                                                                                    resource-id=""
                                                                                                    scrollable="false"
                                                                                                    selected="false"
                                                                                                    text="" />`

**Comment by bartekpacia** [comment]
I no longer work on Patrol.

**Comment by Paul2022-app** [comment]
Same Issue I'm facing. Is there any update on this?
