### ISSUE TITLE
`Instrumentation crashes` when test name is too long

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1725]
Repro: make a test with a _quite long name_

E.g. modify `example_test.dart` by multiplying its name 10 times:

```dart
void main() {
  patrol(
    'counter state is the same after going to Home and switching apps' * 10,
    ($) async {
      // ..
    },
  );
}
```

```
09-20 12:09:24.427 16223 16243 E AndroidRuntime: FATAL EXCEPTION: AndroidTestOrchestrator
09-20 12:09:24.427 16223 16243 E AndroidRuntime: Process: androidx.test.orchestrator, PID: 16223
09-20 12:09:24.427 16223 16243 E AndroidRuntime: java.lang.RuntimeException: Could not open stream for output
09-20 12:09:24.427 16223 16243 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.getOutputStream(AndroidTestOrchestrator.java:5)
09-20 12:09:24.427 16223 16243 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.executeNextTest(AndroidTestOrchestrator.java:11)
09-20 12:09:24.427 16223 16243 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.runFinished(AndroidTestOrchestrator.java:10)
09-20 12:09:24.427 16223 16243 E AndroidRuntime: 	at androidx.test.orchestrator.TestRunnable.run(TestRunnable.java:11)
09-20 12:09:24.427 16223 16243 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-20 12:09:24.427 16223 16243 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-20 12:09:24.427 16223 16243 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
```

**Comment by bartekpacia** [comment]
[Reported to `android/android-test` repo](https://github.com/android/android-test/issues/1935)

**Comment by bartekpacia** [comment]
[Submitted a PR with a fix to `android/android-test` repo](https://github.com/android/android-test/issues/1935)

**Comment by bartekpacia** [comment]
Fix was merged, when it becomes available we should prompt all users to update the dependency in their `app/build.gradle` files.

**Comment by bartekpacia** [comment]
My fix is released in [orchestrator-1.5.0-alpha02](https://developer.android.com/jetpack/androidx/releases/test#orchestrator-1.5.0-alpha02)

**Comment by Kendru98** [comment]
We have test with very long name in our Ci tests
