### ISSUE TITLE
Patrol requires app to use Kotlin 1.8.x, crashes at runtime or buildtime when other version is used

### ISSUE THREAD

**Issue by itsJoKr** [leancodepl/patrol#1775]
### Steps to reproduce

I've went through the Getting started page and integrated it into my project. 
Then I went to run the test from example:  https://patrol.leancode.co/getting-started#create-a-simple-integration-test

### Actual results

The test fails and logs don't tell much, but the line that is suspicious is `Starting 0 tests on Pixel_3a_API_34(AVD) - 14`.

I've run the same test in the patrol example project and there it works and says `Starting 1 tests on Pixel_3a_API_34(AVD) - 14`. It's hard to compare with that example project because it is very different, for example it uses `patrol(` instead of `patrolTest(` etc, but I retraced all my steps and I have no idea what is wrong.

### Logs

<details>
<summary>Logs</summary>

```
josip.krnjic@Movemedical-V93F4Y7XJQ move-app-flutter %  patrol test -d emulator-5554 --verbose -t integration_test/example_test.dart     

In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/josip.krnjic/IdeaProjects/move-app-flutter/integration_test/example_test.dart
Generated entrypoint /Users/josip.krnjic/IdeaProjects/move-app-flutter/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check devices --machine
Received 1 device(s) to run on
Received device: emulator-5554
Received 5 --dart-define(s) (0 custom, 5 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.movemedical.move_app_flutter
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.MyApp
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building apk with entrypoint test_bundle.dart...
$ ./gradlew :app:assembleDebug -Ptarget=/Users/josip.krnjic/IdeaProjects/move-app-flutter/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLm1vdmVtZWRpY2FsLm1vdmVfYXBwX2ZsdXR0ZXI=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuTXlBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :audioplayers_android:preBuild UP-TO-DATE
       // deleted lines because comment was too long
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :app:compressDebugAssets
        : > Task :app:packageDebug
        : > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebug
        : 
        : BUILD SUCCESSFUL in 7s
        : 320 actionable tasks: 7 executed, 313 up-to-date
$ ./gradlew :app:assembleDebugAndroidTest -Ptarget=/Users/josip.krnjic/IdeaProjects/move-app-flutter/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLm1vdmVtZWRpY2FsLm1vdmVfYXBwX2ZsdXR0ZXI=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuTXlBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :audioplayers_android:preBuild UP-TO-DATE
        : > Task :audioplayers_android:preDebugBuild UP-TO-DATE
        : > Task :audioplayers_android:compileDebugAidl NO-SOURCE
        : > Task :connectivity_plus:preBuild UP-TO-DATE
         // deleted lines because comment was too long
        : > Task :connectivity_plus:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :shared_preferences_android:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :isar_flutter_libs:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :package_info_plus:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:validateSigningDebugAndroidTest UP-TO-DATE
        : > Task :app:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
        : > Task :app:mergeLibDexDebugAndroidTest UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:bundleDebugClassesToCompileJar UP-TO-DATE
        : > Task :app:compileDebugAndroidTestKotlin NO-SOURCE
        : > Task :app:compileDebugAndroidTestJavaWithJavac UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJavaResource UP-TO-DATE
        : > Task :app:dexBuilderDebugAndroidTest
        : > Task :app:mergeProjectDexDebugAndroidTest UP-TO-DATE
        : > Task :app:packageDebugAndroidTest UP-TO-DATE
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebugAndroidTest UP-TO-DATE
        : 
        : BUILD SUCCESSFUL in 1s
        : 322 actionable tasks: 2 executed, 320 up-to-date
✓ Completed building apk with entrypoint test_bundle.dart (9.7s)
Will uninstall apps before running tests
Uninstalling com.movemedical.move_app_flutter from sdk gphone64 arm64
Uninstalling com.movemedical.move_app_flutter.test from sdk gphone64 arm64
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
$ ./gradlew :app:connectedDebugAndroidTest -Ptarget=/Users/josip.krnjic/IdeaProjects/move-app-flutter/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLm1vdmVtZWRpY2FsLm1vdmVfYXBwX2ZsdXR0ZXI=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuTXlBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl
        : > Task :app:compileFlutterBuildDebug
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :audioplayers_android:preBuild UP-TO-DATE
       // deleted lines because comment was too long
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : 
        : > Task :app:connectedDebugAndroidTest
        : Starting 0 tests on Pixel_3a_API_34(AVD) - 14
        Instrumentation did not complete:
        Instrumentation code: 0
        Instrumentation result bundle: 
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:connectedDebugAndroidTest'.
        See the report at: file:///Users/josip.krnjic/IdeaProjects/move-app-flutter/build/app/reports/androidTests/connected/index.html
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 13s
        : 
        : > Task :app:connectedDebugAndroidTest FAILED
        : 345 actionable tasks: 7 executed, 338 up-to-date
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (13.5s)
Exception: Gradle test execution failed with code 1
#0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:140:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:106:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:277:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:169:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#9      main (file:///Users/josip.krnjic/.pub-cache/hosted/pub.dev/patrol_cli-2.2.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Uninstalling com.movemedical.move_app_flutter from sdk gphone64 arm64
Uninstalling com.movemedical.move_app_flutter.test from sdk gphone64 arm64
josip.krnjic@Movemedical-V93F4Y7XJQ move-app-flutter % 


```

</details>

### Patrol version

patrol: ^2.3.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.2.0
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME set to /Users/josip.krnjic/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.5)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by yisusdevp** [comment]
Facing the same issue over here

**Comment by bartekpacia** [comment]
Please post output of `adb logcat`, something bad must've happened and it'll likely be logged there.

**Comment by itsJoKr** [comment]
OK. There are so many logs in logcat, this is response filtered by keyword 'patrol'. 

It seems that the problem is with some kotlin class in Patrol and maybe the change that happened recently. My kotlin version was 1.9.0. I went and changed it to 1.8.22 and the test will run. It fails, unfortunately, but that's a different issue. 

So seems like setting kotlin to 1.8.22 will fix this issue, but you might want to check this on your 


<details>
  <summary>LOGS</summary>
  
```
2023-10-06 07:55:35.394 27938-27938 PatrolServer            com.movemedical.move_app_flutter     I  --------------------------------
2023-10-06 07:55:35.394 27938-27938 PatrolServer            com.movemedical.move_app_flutter     I  PatrolJUnitRunner.onCreate() (initial run)
2023-10-06 07:55:35.408 27938-27964 PatrolServer            com.movemedical.move_app_flutter     I  PatrolJUnitRunner.setUp(): activityClass = com.movemedical.move_app_flutter.MainActivity
2023-10-06 07:55:35.464 27938-27964 PatrolServer            com.movemedical.move_app_flutter     I  Starting server...
2023-10-06 07:55:35.596 27938-27964 PatrolServer            com.movemedical.move_app_flutter     I  Created and started PatrolServer, port: 8081
2023-10-06 07:55:35.604 27938-27964 PatrolServer            com.movemedical.move_app_flutter     I  Created PatrolAppServiceClient: http://localhost:8082/
2023-10-06 07:55:35.604 27938-27964 PatrolServer            com.movemedical.move_app_flutter     I  PatrolJUnitRunner.setUp(): Waiting for PatrolAppService to report its readiness...
2023-10-06 07:55:36.124 27938-27979 flutter                 com.movemedical.move_app_flutter     I  Patrol (native): initialize() started
2023-10-06 07:55:36.235 27938-27972 PatrolServer            com.movemedical.move_app_flutter     I  POST /initialize started
2023-10-06 07:55:36.267 27938-27972 PatrolServer            com.movemedical.move_app_flutter     I  POST /initialize took 32 ms
2023-10-06 07:55:36.330 27938-27979 flutter                 com.movemedical.move_app_flutter     I  Patrol (native): initialize() succeeded
2023-10-06 07:55:36.444 27938-27979 flutter                 com.movemedical.move_app_flutter     I  ║ In next major release, patrolTest method will be intended for UI tests only        ║
2023-10-06 07:55:36.444 27938-27979 flutter                 com.movemedical.move_app_flutter     I  ║ If you want to use Patrol in your widget tests, use patrol_finders package.        ║
2023-10-06 07:55:36.444 27938-27979 flutter                 com.movemedical.move_app_flutter     I  ║ For more information, see https://patrol.leancode.co/patrol-finders-release        ║
2023-10-06 07:55:36.474 27938-27979 flutter                 com.movemedical.move_app_flutter     I  00:00 +0: patrol_test_explorer
2023-10-06 07:55:36.481 27938-27979 flutter                 com.movemedical.move_app_flutter     I  patrol_test_explorer: obtained Dart-side test hierarchy:
2023-10-06 07:55:36.488 27938-27979 flutter                 com.movemedical.move_app_flutter     I  PatrolAppService started, address: 0.0.0.0, host: 0.0.0.0, port: 8082
2023-10-06 07:55:36.489 27938-27979 flutter                 com.movemedical.move_app_flutter     I  Patrol (native): markPatrolAppServiceReady() started
2023-10-06 07:55:36.497 27938-27974 PatrolServer            com.movemedical.move_app_flutter     I  POST /markPatrolAppServiceReady started
2023-10-06 07:55:36.497 27938-27974 PatrolServer            com.movemedical.move_app_flutter     I  POST /markPatrolAppServiceReady took 0 ms
2023-10-06 07:55:36.497 27938-27964 PatrolServer            com.movemedical.move_app_flutter     I  PatrolJUnitRunner.setUp(): PatrolAppService is ready to report Dart tests
2023-10-06 07:55:36.497 27938-27964 PatrolServer            com.movemedical.move_app_flutter     I  PatrolAppServiceClient.listDartTests()
2023-10-06 07:55:36.523 27938-27979 flutter                 com.movemedical.move_app_flutter     I  Patrol (native): markPatrolAppServiceReady() succeeded
2023-10-06 07:55:36.648 27938-27979 flutter                 com.movemedical.move_app_flutter     I  PatrolAppService.listDartTests() called
2023-10-06 07:55:36.930 27938-27964 TestRunner              com.movemedical.move_app_flutter     E  kotlinx.serialization.SerializationException: Serializer for class 'ListDartTestsResponse' is not found.
                                                                                                    Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
                                                                                                    
                                                                                                    	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
                                                                                                    	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:28)
                                                                                                    	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:134)
                                                                                                    	at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
                                                                                                    	at pl.leancode.patrol.contracts.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:63)
                                                                                                    	at pl.leancode.patrol.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:32)
                                                                                                    	at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(PatrolJUnitRunner.java:109)
                                                                                                    	at com.movemedical.move_app_flutter.MainActivityTest.testCases(MainActivityTest.java:17)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
                                                                                                    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                                                    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
                                                                                                    	at org.junit.runners.Parameterized$RunnersFactory.allParameters(Parameterized.java:424)
                                                                                                    	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:375)
                                                                                                    	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:360)
                                                                                                    	at org.junit.runners.Parameterized.<init>(Parameterized.java:303)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
                                                                                                    	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
                                                                                                    	at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:63)
                                                                                                    	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
                                                                                                    	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
                                                                                                    	at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:149)
                                                                                                    	at androidx.test.internal.runner.AndroidLogOnlyBuilder.runnerForClass(AndroidLogOnlyBuilder.java:93)
                                                                                                    	at androidx.test.internal.runner.ScanningTestLoader.doCreateRunner(ScanningTestLoader.java:50)
                                                                                                    	at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:64)
                                                                                                    	at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:835)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:650)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:418)
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2402)
---------------------------- PROCESS ENDED (27938) for package com.movemedical.move_app_flutter ----------------------------
```

</details>

**Comment by bartekpacia** [comment]
Ah, right, this error - we know about it, and it's been introduced in `patrol v2.3.0`. It's because we started depending on `kotlinx.serialization`, which is bound to Kotlin version used by the plugin (in Patrol's case it's Kotlin 1.8.22). This is a mistake that we weren't aware of, and we'll fix it by ditching `kotlin.serialization` in favor of, let's say, Gson.

### Temporary workarounds

The simplest one is to set your app to use Kotlin 1.8.22.

If you don't want to do that, you can also add the `kotlinx.serialization` yourself:

android/app/build.gradle:

```diff
 apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
+apply plugin: 'kotlinx-serialization'
```

android/build.gradle

```diff
 dependencies {
   classpath 'com.android.tools.build:gradle:7.4.2'
   classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
+  classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
 }
```

**Comment by bartekpacia** [comment]
FWIW, I've also [reported this problem to Flutter](https://github.com/flutter/flutter/issues/135995), because other plugins also might want to use `kotlinx.serialization`, but Flutter team doesn't consider this an issue on their side.

**Comment by itsJoKr** [comment]
OK, great. I understand the problem you are facing.

I just want to mention that as a developer, I don't mind if you put these two lines in the "Getting started" guide. I'm just following the steps there, which are mostly copy-pasting. And having two more lines to copy-paste shouldn't be an issue.
