### ISSUE TITLE
"Unable to load contents of file list" error when running on iOS

### ISSUE THREAD

**Issue by vlazdra** [leancodepl/patrol#1796]
### Steps to reproduce

Don't have any specific steps to reproduce since I'm not sure how it even occurs.

### Actual results

The tests won't start.

### Logs

<details>
<summary>Logs</summary>

```
❯ patrol test -t integration_test/app_test.dart --flavor development -d C8A230EF-A56C-4B30-9742-401A7F46537A --verbose --debug
Can't load Kernel binary: Invalid SDK hash.
FINE: Pub 3.1.3
FINE: Package Config up to date.
FINE: Package Config up to date.
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/vlazdra/Documents/Projects/project/integration_test/app_test.dart
Generated entrypoint /Users/vlazdra/Documents/Projects/project/integration_test/test_bundle.dart with 1 bundled test(s)
Received Android flavor: development
Received iOS flavor: development
$ flutter --no-version-check devices --machine
Received 1 device(s) to run on
Received device: iPhone 15 Pro Max
Received 34 --dart-define(s) (27 custom, 7 internal)
...
Received custom --dart-define: SENTRY_DSN
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=[package_id]
Received internal --dart-define: PATROL_APP_BUNDLE_ID=[package_id]
Received internal --dart-define: PATROL_ANDROID_APP_NAME=[app_name]
Received internal --dart-define: PATROL_IOS_APP_NAME=[app_name]
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --simulator --flavor development --target /Users/vlazdra/Documents/Projects/project/integration_test/test_bundle.dart --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true
	Building [package_id] for simulator (ios)...
	Running pod install...                                              5.3s
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme development -configuration Debug-development -only-testing RunnerUITests -sdk iphonesimulator -destination generic/platform=iOS Simulator -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
	error: Unable to load contents of file list: '/Target Support Files/Intercom/Intercom-xcframeworks-input-files.xcfilelist' (in target 'Intercom' from project 'Pods')
	error: Unable to load contents of file list: '/Target Support Files/Intercom/Intercom-xcframeworks-output-files.xcfilelist' (in target 'Intercom' from project 'Pods')
	warning: Run script build phase '[CP] Copy XCFrameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Intercom' from project 'Pods')
	error: Unable to load contents of file list: '/Target Support Files/GoogleAppMeasurement/GoogleAppMeasurement-xcframeworks-input-files.xcfilelist' (in target 'GoogleAppMeasurement' from project 'Pods')
	error: Unable to load contents of file list: '/Target Support Files/GoogleAppMeasurement/GoogleAppMeasurement-xcframeworks-output-files.xcfilelist' (in target 'GoogleAppMeasurement' from project 'Pods')
	warning: Run script build phase '[CP] Copy XCFrameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'GoogleAppMeasurement' from project 'Pods')
	error: Unable to load contents of file list: '/Target Support Files/FirebaseAnalytics/FirebaseAnalytics-xcframeworks-input-files.xcfilelist' (in target 'FirebaseAnalytics' from project 'Pods')
	error: Unable to load contents of file list: '/Target Support Files/FirebaseAnalytics/FirebaseAnalytics-xcframeworks-output-files.xcfilelist' (in target 'FirebaseAnalytics' from project 'Pods')
	warning: Run script build phase '[CP] Copy XCFrameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'FirebaseAnalytics' from project 'Pods')
	warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	error: Unable to load contents of file list: '/Target Support Files/GoogleMaps/GoogleMaps-xcframeworks-input-files.xcfilelist' (in target 'GoogleMaps' from project 'Pods')
	error: Unable to load contents of file list: '/Target Support Files/GoogleMaps/GoogleMaps-xcframeworks-output-files.xcfilelist' (in target 'GoogleMaps' from project 'Pods')
	warning: Run script build phase '[CP] Copy XCFrameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'GoogleMaps' from project 'Pods')
	note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'Copy GoogleService-Info.plist' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	warning: Run script build phase '[firebase_crashlytics] Crashlytics Upload Symbols' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
	2023-10-11 18:09:55.803 xcodebuild[62331:6259624] Writing error result bundle to /var/folders/by/c6b6qf5j03x29ckj628q6vh00000gn/T/ResultBundle_2023-11-10_18-09-0055.xcresult
	xcodebuild: error: Failed writing xctestrun file: The folder “development_iphonesimulator17.0-arm64-x86_64.xctestrun” doesn’t exist..
✗ Failed to build app with entrypoint test_bundle.dart for iOS simulator (xcodebuild exited with code 70) (22.9s)
Error: xcodebuild exited with code 70
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:132:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:72:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:234:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#10     main (file:///Users/vlazdra/.pub-cache/hosted/pub.dev/patrol_cli-2.2.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 70
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:132:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:72:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:234:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#10     main (file:///Users/vlazdra/.pub-cache/hosted/pub.dev/patrol_cli-2.2.0/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

2.3.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
❯ patrol doctor
Can't load Kernel binary: Invalid SDK hash.
Patrol CLI version: 2.2.0
Program adb found in /Users/vlazdra/Library/Android/sdk/platform-tools//adb
Env var $ANDROID_HOME set to /Users/vlazdra/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
❯ flutter doctor --verbose
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64, locale en-RS)
    • Flutter version 3.13.6 on channel stable at /Users/vlazdra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/vlazdra/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/vlazdra/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] VS Code (version 1.83.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.73.20230904

[✓] Connected device (4 available)
    • Vladimir’s iPhone (mobile) • 00008020-000575301409002E            • ios            • iOS 16.4.1 20E252
    • iPhone 15 Pro Max (mobile) • C8A230EF-A56C-4B30-9742-401A7F46537A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 117.1.58.137

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
Hi @vlazdra,

Unfortunately I cannot help you without [a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by vlazdra** [comment]
Hi @bartekpacia! 👋 

I understand that the information I've provided is not much, but hope you understand that I'm unable to share the project with you since it's private company owned code. 😞 

Is there really nothing else I can additionally provide that might at least help direct me towards at least trying something out?

**Comment by vlazdra** [comment]
Hey @bartekpacia I think I found something, still not sure why it happens but I do believe it shouldn't be working like this.

So my project has a bunch of custom configurations setup via CocoaPods and in the project specifically. So what I found is that when I run:
`patrol test -t integration_test/app_test.dart --flavor development -d C8A230EF-A56C-4B30-9742-401A7F46537A --verbose`

The ptrol CLI uses the wrong Configuration for the Pods project for some reason.

This is how my Podfile looks like:
<img width="345" alt="Screenshot 2023-10-12 at 15 44 16" src="https://github.com/leancodepl/patrol/assets/6934014/e4a1d1ca-54a4-42e7-89ee-79add6da4db8">

Note that there are no **Debug** and **Release** configurations specified.

Now because of that the Pods project has the Debug and Release configs but they are not setup at all since I don't specify them in the Podfile:
<img width="532" alt="Screenshot 2023-10-12 at 15 45 36" src="https://github.com/leancodepl/patrol/assets/6934014/cdf57bf6-8c7b-4338-91c4-82c24249a7e0">

Because of that, some frameworks my app uses don't have the ENV properly set because the Debug and Release configs are not setup properly (because I don't use them, that's why I have a separate config for separate setup). 
The error I was getting:
```
error: Unable to load contents of file list: '/Target Support Files/Intercom/Intercom-xcframeworks-input-files.xcfilelist' (in target 'Intercom' from project 'Pods')
	error: Unable to load contents of file list: '/Target Support Files/Intercom/Intercom-xcframeworks-output-files.xcfilelist' (in target 'Intercom' from project 'Pods')
	warning: Run script build phase '[CP] Copy XCFrameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Intercom' from project 'Pods')
```
was because the $(PODS_ROOT) was basically empty, and those frameworks that need some additional files to be copied over failed.
<img width="1138" alt="Screenshot 2023-10-12 at 15 47 15" src="https://github.com/leancodepl/patrol/assets/6934014/fbf9bd2a-321f-476b-b8db-6a088605a529">


### Got it to work - kinda

So as soon as I figured this one out, I added the Debug and Release configs inside my Podfile for testing purposes to see if it would help.
<img width="336" alt="Screenshot 2023-10-12 at 15 48 50" src="https://github.com/leancodepl/patrol/assets/6934014/731cb8f1-10dd-41df-a90f-d14f9fcc05e9">

Now the Pods projects has the Debug and Release configs setup, and patrol can pass through the issue mentioned in start of this ticket:
<img width="531" alt="Screenshot 2023-10-12 at 15 49 50" src="https://github.com/leancodepl/patrol/assets/6934014/3591e19d-bd29-4820-a1ff-faff759906e4">

### Correct behaviour?

Not sure why and where patrol decides which Pods config to pull in, but it is obvious that if I have a custom one setup, it's not pulling the correct one.
Do you have advice as to what I can do regarding this?

**Comment by bartekpacia** [comment]
Thanks for all the detailed information you've provided. Unfortunately we have limited bandwidth and can only focus on issues that have a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by bartekpacia** [comment]
Hi @vlazdra, could you provide a mini-project that reproduces this bug? I understand you cannot share the original project where the bug occurred.

**Comment by vlazdra** [comment]
Hi @bartekpacia, I will try to provide a minimal, reproducible example.
