### ISSUE TITLE
 Android Open App not working

### ISSUE THREAD

**Issue by balajiks-dev** [leancodepl/patrol#1815]
### Steps to reproduce

Run the example application and run this command

    await $.native.pressHome();
    await $.native.openApp();

### Actual results

I'm trying to test press home and open the app in the android where as am getting this below issue.
    await $.native.pressHome();
    await $.native.openApp();

### Logs

<details>
<summary>Logs</summary>

```
When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:231:7)
<asynchronous suspension>
#1      NativeAutomator.openApp (package:patrol/src/native/native_automator.dart:314:5)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/eample/integration_test/example_test.dart:35:5)
<asynchronous suspension>
#3      patrolTest.<anonymous closure> (package:patrol/src/common.dart:140:7)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:165:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:982:5)
<asynchronous suspension>
```

</details>

### Patrol version

patrol: ^2.3.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

Program adb found in /Users/user/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/user/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

</details>

**Comment by bartekpacia** [comment]
Hi @balajiks-dev,

Do you have `package_name` defined in `pubspec.yaml`? For example:

```yaml
patrol:
  app_name: Patrol example
  android:
    package_name: pl.leancode.patrol.example
  ios:
    bundle_id: pl.leancode.patrol.Example
```

**Comment by balajiks-dev** [comment]
@bartekpacia  Yes I have defined the package name in pubspec.yaml

**Comment by bartekpacia** [comment]
Please post logcat.

Might be related to #1390.

**Comment by balajiks-dev** [comment]
@bartekpacia  Same issue but doesn't know the solution

**Comment by bartekpacia** [comment]
Please provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Otherwise we cannot help you and the issue will be closed.

**Comment by bartekpacia** [comment]
Closing because of inactivity.

Feel free to open a new issue with all the required information provided, including a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).
