### ISSUE TITLE
On real iOS device enterText() doesn't work when TextField is focused

### ISSUE THREAD

**Issue by aqrc** [leancodepl/patrol#1868]
### Steps to reproduce

I experienced the same problem described in https://github.com/leancodepl/patrol/issues/1483.
This is not an issue on simulator.

<details>
  <summary>Minimal reproducible example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

void main() {
  patrolTest(
    'should enter text into focused field but doesnt',
    nativeAutomation: true,
    ($) async {
      await $.pumpWidgetAndSettle(
        MaterialApp(
          home: Scaffold(
            appBar: AppBar(title: const Text('app')),
            body: const Column(
              children: [
                TextField(
                  key: Key('autofocused_field'),
                  autofocus: true,
                ),
                TextField(
                  key: Key('not_focused_field'),
                ),
              ],
            ),
          ),
        ),
      );

      const testText = 'text for test';
      await $(#autofocused_field).enterText(testText); // doesn't work, fails later
      // await $(#not_focused_field).enterText(testText); // works fine
      await Future.delayed(const Duration(seconds: 4));
      expect($(testText), findsOneWidget);
    },
  );
}

```

</details>

### Actual results

On real iOS device, when `TextField` is focused, text is not getting entered into this `TextField` using `.enterText()`.  
Field might be focused due to `autofocus` (`TextField(autofocus: true)`), or due to previous call of `.tap()` method (like in the referenced issue).  

### Logs

<details>
<summary>Logs</summary>

```
andrey@Andreys-MacBook-Pro-276 frontend % patrol test --target integration_test/patrol_issue_test.dart --release --verbose
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
Verbose mode enabled. More logs will be printed.

Update available! 2.1.5 → 2.2.2
Run patrol update to update

Received 1 test target(s)
Received test target: /Users/andrey/companyname/frontend/integration_test/patrol_issue_test.dart
Generated entrypoint /Users/andrey/companyname/frontend/integration_test/test_bundle.dart with 1 bundled test(s)
Received Android flavor: dev
Received iOS flavor: dev
$ flutter --no-version-check devices --machine
No device specified, using the first one (My_real_iPhone)
Received 1 device(s) to run on
Received device: My_real_iPhone
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.companyname.app.dev
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.companyname.app.dev
Received internal --dart-define: PATROL_ANDROID_APP_NAME=companyname DEV
Received internal --dart-define: PATROL_IOS_APP_NAME=companyname DEV
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building app with entrypoint test_bundle.dart for iOS device (release)...
$ flutter build ios --no-version-check --config-only --no-codesign --release --flavor dev --target /Users/andrey/companyname/frontend/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=com.companyname.app.dev --dart-define PATROL_APP_BUNDLE_ID=com.companyname.app.dev --dart-define PATROL_ANDROID_APP_NAME=companyname DEV --dart-define PATROL_IOS_APP_NAME=companyname DEV --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true
    Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
    Building com.companyname.app.dev for device (ios-release)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme dev -configuration Release-dev -only-testing RunnerUITests -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
    note: Building targets in dependency order
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Copy GoogleService-Info.plist to the correct location' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    warning: Run script build phase '[firebase_crashlytics] Crashlytics Upload Symbols' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'xcode_backend build' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'RunnerUITests' from project 'Runner')
    note: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'RunnerUITests' from project 'Runner')
✓ Completed building app with entrypoint test_bundle.dart for iOS device (70.5s)
Will uninstall apps before running tests
$ ideviceinstaller --udid 01b42848d9f54375a4f10bda88dbe46eedb07774 --uninstall com.companyname.app.dev
$ ideviceinstaller --udid 01b42848d9f54375a4f10bda88dbe46eedb07774 --uninstall com.companyname.app.RunnerUITests.xctrunner
• Running app with entrypoint test_bundle.dart for iOS device on device My_real_iPhone...
$ xcodebuild -showsdks -json
Assuming SDK version 16.2 for iphonesimulator
Looking for .xctestrun matching dev_*iphoneos16.2*.xctestrun at /Users/andrey/companyname/frontend/build/ios_integ/Build/Products
Found 1 match(es), the first one will be used
Found /Users/andrey/companyname/frontend/build/ios_integ/Build/Products/dev_iphoneos16.2-arm64.xctestrun
$ xcodebuild test-without-building -xctestrun /Users/andrey/companyname/frontend/build/ios_integ/Build/Products/dev_iphoneos16.2-arm64.xctestrun -only-testing RunnerUITests -destination platform=iOS,name=My_real_iPhone -resultBundlePath /Users/andrey/companyname/frontend/build/ios_results_1699342882211.xcresult
    Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /Users/andrey/companyname/frontend/build/ios_integ/Build/Products/dev_iphoneos16.2-arm64.xctestrun -only-testing RunnerUITests -destination platform=iOS,name=My_real_iPhone -resultBundlePath /Users/andrey/companyname/frontend/build/ios_results_1699342882211.xcresult
    
    User defaults from command line:
        IDEBuildOperationResultBundlePath = /Users/andrey/companyname/frontend/build/ios_results_1699342882211.xcresult
        IDEPackageSupportUseBuiltinSCM = YES
    
    Writing result bundle at path:
            /Users/andrey/companyname/frontend/build/ios_results_1699342882211.xcresult
    
    2023-11-07 09:42:46.577881+0200 RunnerUITests-Runner[1121:56709] Running tests...
    2023-11-07 09:42:50.401474+0200 RunnerUITests-Runner[1121:56709] PatrolServer: INFO: PATROL_PORT is null, falling back to default (8081)
    2023-11-07 09:42:50.401676+0200 RunnerUITests-Runner[1121:56709] PatrolServer: INFO: PatrolServer constructor called
    2023-11-07 09:42:50.401765+0200 RunnerUITests-Runner[1121:56709] PatrolServer: INFO: PATROL_ENABLED flag is defined
    2023-11-07 09:42:50.403582+0200 RunnerUITests-Runner[1121:56709] PatrolAppServiceClient: created, port: 8082
    2023-11-07 09:42:50.428454+0200 RunnerUITests-Runner[1121:56786] [si_destination_compare] send failed: Invalid argument
    2023-11-07 09:42:50.433604+0200 RunnerUITests-Runner[1121:56786] [si_destination_compare] send failed: Undefined error: 0
    2023-11-07 09:42:50.443180+0200 RunnerUITests-Runner[1121:56787] PatrolServer: INFO: Server started on http://localhost:8081
        t =      nans Checking existence of `"Allow" Button`
        t =      nans Ignoring failure to get hierarchy for remote element in process 518 (Error getting main window kAXErrorServerNotFound)
        t =      nans Open com.companyname.app.dev
        t =      nans     Launch com.companyname.app.dev
        t =      nans         Wait for accessibility to load
        t =      nans         Setting up automation session
        t =      nans         Wait for com.companyname.app.dev to idle
    2023-11-07 09:43:24.084830+0200 RunnerUITests-Runner[1121:56788] PatrolServer: INFO: App reported that it is ready
    2023-11-07 09:43:26.107125+0200 RunnerUITests-Runner[1121:56791] PatrolAppServiceClient.listDartTests()
    2023-11-07 09:43:27.111891+0200 RunnerUITests-Runner[1121:56709] Got 1 Dart tests: (
        "patrol_issue_test"
    )
    2023-11-07 09:43:27.113223+0200 RunnerUITests-Runner[1121:56709] RunnerUITests.testInvocations(): selectorName = patrolIssueTest, signature: <NSMethodSignature: 0xbffd53cd4a50e8b7>
    Test Suite 'All tests' started at 2023-11-07 09:43:27.115
    Test Suite 'RunnerUITests.xctest' started at 2023-11-07 09:43:27.116
    Test Suite 'RunnerUITests' started at 2023-11-07 09:43:27.116
    Test Case '-[RunnerUITests patrolIssueTest]' started.
        t =     0.00s Start Test at 2023-11-07 09:43:27.119
        t =     0.02s Set Up
        t =     0.03s Open com.companyname.app.dev
        t =     0.04s     Launch com.companyname.app.dev
        t =     0.04s         Terminate com.companyname.app.dev:1127
    2023-11-07 09:43:32.900140+0200 RunnerUITests-Runner[1121:56788] PatrolServer: INFO: App reported that it is ready
        t =     5.80s         Setting up automation session
        t =     5.93s         Wait for com.companyname.app.dev to idle
    2023-11-07 09:43:34.079951+0200 RunnerUITests-Runner[1121:56787] PatrolAppServiceClient.runDartTest(patrol_issue_test)
    /Users/andrey/companyname/frontend/ios/RunnerUITests/RunnerUITests.m:12: error: -[RunnerUITests patrolIssueTest] : ((response.passed) is true) failed
        t =    14.11s Tear Down
    Test Case '-[RunnerUITests patrolIssueTest]' failed (14.311 seconds).
    Test Suite 'RunnerUITests' failed at 2023-11-07 09:43:41.428.
             Executed 1 test, with 1 failure (0 unexpected) in 14.311 (14.312) seconds
    Test Suite 'RunnerUITests.xctest' failed at 2023-11-07 09:43:41.429.
             Executed 1 test, with 1 failure (0 unexpected) in 14.311 (14.313) seconds
    Test Suite 'All tests' failed at 2023-11-07 09:43:41.430.
             Executed 1 test, with 1 failure (0 unexpected) in 14.311 (14.315) seconds
    2023-11-07 09:43:41.337 xcodebuild[37673:3144955] [MT] IDETestOperationsObserverDebug: 136.863 elapsed -- Testing started completed.
    2023-11-07 09:43:41.337 xcodebuild[37673:3144955] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
    2023-11-07 09:43:41.337 xcodebuild[37673:3144955] [MT] IDETestOperationsObserverDebug: 136.863 sec, +136.863 sec -- end
    
    Test session results, code coverage, and logs:
            /Users/andrey/companyname/frontend/build/ios_results_1699342882211.xcresult
    
    Failing tests:
            -[RunnerUITests patrolIssueTest]
    
    ** TEST EXECUTE FAILED **
    
    2023-11-07 09:43:41.408 xcodebuild[37673:3144955] [MT] IDEResultKit: Warning: While writing a result bundle to /Users/andrey/companyname/frontend/build/ios_results_1699342882211.xcresult, not all contents have been imported, as the Staging directory still contains the following files/directories: ["1_Test"]
    Testing started
✗ Failed to execute tests of app with entrypoint test_bundle.dart for iOS device on device My_real_iPhone (xcodebuild exited with code 65) (139.2s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.execute.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:188:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.execute (package:patrol_cli/src/ios/ios_test_backend.dart:148:5)
<asynchronous suspension>
#4      TestCommand._execute (package:patrol_cli/src/commands/test.dart:277:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:169:23)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#10     main (file:///Users/andrey/.pub-cache/hosted/pub.dev/patrol_cli-2.1.5/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
$ ideviceinstaller --udid 01b42848d9f54375a4f10bda88dbe46eedb07774 --uninstall com.companyname.app.dev
$ ideviceinstaller --udid 01b42848d9f54375a4f10bda88dbe46eedb07774 --uninstall com.companyname.app.RunnerUITests.xctrunner
```

</details>

### Patrol version

patrol: 2.2.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.1.5
Program adb found in /Users/andrey/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-IL)
    • Flutter version 3.13.8 on channel stable at /Users/andrey/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (3 weeks ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Екатерина (mobile) • 01b42848d9f54375a4f10bda88dbe46eedb07774 • ios            • iOS 14.4 18D52
    • macOS (desktop)    • macos                                    • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)       • chrome                                   • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
Thanks for reporting. Unfortunately I don't have a physical iOS device to reproduce it.


Totally wild guess why it might be happening:

https://github.com/leancodepl/patrol/blob/a9f90f165c805949fd3e1efe1188c0d9a80ea406/packages/patrol/lib/src/common.dart#L125-L132

This doesn't explain why it only happens on physical iOS and not on simulator, though.

**Comment by aqrc** [comment]
You can use Firebase Test Lab, first time I experienced this issue was there

**Comment by jacjac11** [comment]
I managed to test on physical device only, for simulator unable to try due to wifi/cellular switch not working (will separate issue)

**Comment by aqrc** [comment]
Hey @bartekpacia, did you manage to reproduce the issue?

**Comment by bartekpacia** [comment]
nope, not yet

**Comment by piotruela** [comment]
Hey @aqrc, I was able to reproduce the issue on iOS device. @bartekpacia it seems to be connected with [this bug](https://github.com/flutter/flutter/pull/89703). You've introduced a workaround into the code that registers text fields before calling `enterText`:
https://github.com/leancodepl/patrol/blob/0829eaf81f16b535effa3e31744b905ecfe23e96/packages/patrol_finders/lib/src/custom_finders/patrol_tester.dart#L337-L341
but it seems that it doesn't work for fields that are focused. For everyone experiencing this issue, a solution could be to invoke `$.tester.testTextInput.register();` at the beginning of the test. As for the patrol, we can consider moving this workaround to the beginning of the `patrolTest` method body.

**Comment by jBorkowska** [comment]
I spotted this bug on simulator as well

**Comment by nikitadol** [comment]
https://github.com/leancodepl/patrol/issues/1868#issuecomment-1814241939 - This solved this problem


Here is a small wrapper for "correctly" running `patrol` tests:
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';
// Replace `my_app` with your package name
import 'package:my_app/main.dart' as app;

void appTest(
  String description,
  PatrolTesterCallback callback,
) {
  patrolTest(
    description,
    ($) async {
      // https://github.com/leancodepl/patrol/issues/1868#issuecomment-1814241939
      $.tester.testTextInput.register();
      await app.main();
      await $.pumpAndSettle();


      return callback($);
    },
    // Replace/remove/keep/add other arguments at your discretion
    framePolicy: LiveTestWidgetsFlutterBindingFramePolicy.fullyLive,
    nativeAutomatorConfig: const NativeAutomatorConfig(
      findTimeout: Duration(seconds: 20),
    ),
  );
}

void appSetUp(dynamic Function() body) => patrolSetUp(body);

void appTearDown(dynamic Function() body) => patrolTearDown(body);

```

**Comment by piotruela** [comment]
This issue should be fixed in [patrol 3.15.1](https://pub.dev/packages/patrol/versions/3.15.1) and [patrol_finders 2.7.2](https://pub.dev/packages/patrol_finders/versions/2.7.2).
