### ISSUE TITLE
Hot restart doesn't work

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1884]
After pressing R I get this exception:
```Hot Restart for entrypoint test_bundle.dart...
        hot restart failed to complete: _flutter.runInView: (-32000) Could not run configuration in engine.
        #0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
        #1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1771:25)
        #2      VmService._call (package:vm_service/src/vm_service.dart:1783:8)
        #3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1733:14)
        #4      VmService.callMethod (package:vm_service/src/vm_service.dart:1716:12)
        #5      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:501:28)
        #6      FlutterVmService.runInView (package:flutter_tools/src/vmservice.dart:580:11)
        <asynchronous suspension>
        #7      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
        <asynchronous suspension>
        #8      HotRunner._launchInView (package:flutter_tools/src/run_hot.dart:588:5)
        <asynchronous suspension>
        #9      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
        <asynchronous suspension>
        #10     HotRunner._launchFromDevFS (package:flutter_tools/src/run_hot.dart:608:5)
        <asynchronous suspension>
        #11     HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:709:5)
        <asynchronous suspension>
        #12     HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:830:16)
        <asynchronous suspension>
        #13     HotRunner.restart (package:flutter_tools/src/run_hot.dart:770:38)
        <asynchronous suspension>
        #14     TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1790:40)
        <asynchronous suspension>
        #15     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1830:7)
        <asynchronous suspension>

        Error connecting to the service protocol: Exception: connection to device ended too early```

App still works, but devtools gets disconnected.
`patrol_cli` hangs up after this and I have to ctrl+c to quit.

**Comment by jBorkowska** [comment]
Closing, doesn't occur after rebase on master
