### ISSUE TITLE
Remove workaround for `debugDefaultTargetPlatformOverride` being changed during test by DevTools

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1930]
We were forced to add a workaround because of a bug in DevTols. See https://github.com/flutter/devtools/issues/6719

Long story short: the DevTools change a global Flutter value `debugDefaultTargetPlatformOverride`, but don't reset it at the end of the test. This results in assertions being broken in `flutter_test` binding.

There are 3 parts to the workaround:

https://github.com/leancodepl/patrol/blob/f0cbe876911115f74ac3c4044b3345a1bf94a436/packages/patrol/lib/src/binding.dart#L149-L153

https://github.com/leancodepl/patrol/blob/f0cbe876911115f74ac3c4044b3345a1bf94a436/packages/patrol/lib/src/common.dart#L116-L117

https://github.com/leancodepl/patrol/blob/f0cbe876911115f74ac3c4044b3345a1bf94a436/packages/patrol_cli/lib/src/test_bundler.dart#L142-L144

### What does success look like

1. Flutter team acknowledges the issue
2. The fix is merged in Flutter
3. We can remove the workaround code from Patrol

**Comment by bartekpacia** [comment]
Adding `blocked` since it doesn't depend entirely on us.

**Comment by daohoangson** [comment]
I'm getting `Cannot modify debugDefaultTargetPlatformOverride in non-debug builds.` when testing with Firebase Test Labs. 

```
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: Cannot modify debugDefaultTargetPlatformOverride in non-debug builds.
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: #0      debugDefaultTargetPlatformOverride= (package:flutter/src/foundation/platform.dart:106)
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: #1      patrolTest.<anonymous closure> (package:patrol/src/common.dart:140)
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: <asynchronous suspension>
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: #2      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183)
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: <asynchronous suspension>
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: #3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017)
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: <asynchronous suspension>
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: #4      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:809)
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter: <asynchronous suspension>
May 20 09:36:28 iPhone Runner(Flutter)[534] <Notice>: flutter:   Test failed. See exception logs above.
```

It appears to be related to this workaround. Since each test is being executed separately, a dirty fix can skip the workaround in non-debug mode, I think?

**Comment by bkeelon** [comment]
Was wondering if anyone ran into this as well. We are getting the same thing when running on Firebase for iOS with flutter version 3.22. Anyone have a workaround for this? @daohoangson @bartekpacia

**Comment by daohoangson** [comment]
@bkeelon after the #2203 fix, I have been able to use patrol@3.7.1 (and up) to run the tests on Firebase Test Lab without issue. For example, this run https://github.com/daohoangson/flutter_widget_from_html/actions/runs/9437960791/job/25994432496
