### ISSUE TITLE
Patrol Throws an Unhandled Exception after running a test.

### ISSUE THREAD

**Issue by theflyingmacaroon** [leancodepl/patrol#1954]
### Steps to reproduce

1. Enter project folder.
2. Run emulator Nexus 10, API 33.
3. Run ```patrol develop -t integration_test\test.dart --dart-define=DEV_MODE=true```

### Actual results

Patrol throws an Unhandled Exception after running a test. However, the test throws an output of a success or failure and it keeps on restarting until it stops.

This has happened after I've upgraded Flutter, patrol and patrol_cli to latest verisons.

### Logs

<details>
<summary>Logs</summary>

```
Unhandled exception:
ProcessException: Failed to find "start" in the search path.
  Command: start
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      LoggingLocalProcessManager.start (package:patrol_cli/src/base/process.dart:27:18)
#2      FlutterTool._openDevtoolsPage (package:patrol_cli/src/crossplatform/flutter_tool.dart:217:41)
#3      FlutterTool.attach.<anonymous closure>.<anonymous closure> (package:patrol_cli/src/crossplatform/flutter_tool.dart:129:21)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#8      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#9      _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#10     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:164:13)
#11     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131:7)
#12     StringConversionSink.add (dart:convert/string_conversion.dart:39:5)
#13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#17     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#18     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#19     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#20     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#21     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#22     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#23     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#29     _StreamController._add (dart:async/stream_controller.dart:658:7)
#30     _StreamController.add (dart:async/stream_controller.dart:606:5)
#31     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#36     _StreamController._add (dart:async/stream_controller.dart:658:7)
#37     _StreamController.add (dart:async/stream_controller.dart:606:5)
#38     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#39     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

### Patrol version

patrol: 3.0.2+1
patrol_cli: v2.3.1+1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.3.1+1
Program adb found in User\AppData\Local\Android\Sdk\platform-tools\adb.exe
Env var $ANDROID_HOME is not set

```

The env var has been set, but after i've updated to latest patrol version it cannot read it anymore.
</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.19045.3693], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.84.2)
[√] Connected device (4 available)
[√] Network resources

```

</details>

**Comment by adrian-moisa** [comment]
This is a rather severe problem on windows machines, we had to rollback Flutter to be able to work with a prior version of Patrol. Additionally it seems it does not happen on a mac M1 on the same patrol version

**Comment by piotruela** [comment]
Hi, I was able to reproduce the issue. The exception is thrown while patrol is trying to open devtools on windows. In order to 'fix' it you can pass `--no-open-devtools` flag to `patrol develop` command.
