### ISSUE TITLE
PatrolAppServiceClientException when running more than one test on android emulator in CI cloud

### ISSUE THREAD

**Issue by bbjay** [leancodepl/patrol#2005]
### Steps to reproduce

1. fork https://github.com/bbjay/patrol-demo
2. goto https://codemagic.io and create a free account 
3. add your patrol-demo fork as an app in Codemagic.io
4. goto https://emulator.wtf and create a free account
5. configure EW_API_TOKEN environment variable in Codemagic, see https://docs.codemagic.io/yaml-testing/emulator-wtf/
6. start build with the "Android Integration Tests on emulator.wtf" workflow
 
The emulator from emulators.wtf used in the above setup is a Pixel2, API level 33

### Actual results

One test passes, the other fails with:
```
java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:140)
at com.example.patrol_demo.MainActivityTest.runDartTest(MainActivityTest.java:31)
... 39 trimmed
Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
at pl.leancode.patrol.contracts.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:23)
at pl.leancode.patrol.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:39)
at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:133)
... 41 more
```

The patrol-demo repo was created as a minimal example, following the patrol setup from the latest docs.
It contains two test files:
- integration_test/t00_smoke_test.dart
- integration_test/t01_smoke_test.dart

They are both identical.

When running the test with just one test file, it passes (`patrol build android -t integration_test/t00_smoke_test.dart`).
Running the test locally on my machine (apple silicon M2, Pixel2 33 emulator) works and all tests pass.

Other things I have tried, all resulting in the same issue:
- combining the two tests in one file
- `patrol build android --wait 1`
- different emulator device model (`--device model=Pixel2Atd,version=30`, NexusLowRes 23)
- running the tests directly on Codemagic with a linux_x2 instance and default emulator (and `patrol test`)
- also with an older setup with Flutter 3.13.5 , Patrol 2.4.0-dev.3 and patrol-cli 2.2.1

There's also a similar issue, but without example: https://github.com/leancodepl/patrol/issues/1831

### Logs

<details>
<summary>Logs</summary>

```
12-12 13:49:41.688  5953  5968 I TestRunner: started: runDartTest[t01_smoke_test tap increment button works](com.example.patrol_demo.MainActivityTest)
12-12 13:49:41.688  5953  5968 I PatrolServer: PatrolJUnitRunner.runDartTest(t01_smoke_test tap increment button works): Requested execution
12-12 13:49:41.688  5953  5968 I PatrolServer: PatrolAppServiceClient.runDartTest(t01_smoke_test tap increment button works)
12-12 13:49:41.691  5953  5983 I flutter : PatrolAppService: registered "t01_smoke_test tap increment button works"
12-12 13:49:41.691  5953  5983 I flutter : PatrolAppService: registered test "t01_smoke_test tap increment button works" was not matched by requested test "t00_smoke_test tap increment button works"
12-12 13:49:41.717  5953  5983 I flutter : [ERROR] 2023-12-12 13:49:41.692292	0:00:00.001538	POST	/runDartTest
12-12 13:49:41.717  5953  5983 I flutter : 'package:patrol/src/native/patrol_app_service.dart': Failed assertion: line 142 pos 12: '_testExecutionCompleted.isCompleted == false': is not true.
12-12 13:49:41.717  5953  5983 I flutter : dart:core                                                                 _AssertionError._throwNew
12-12 13:49:41.717  5953  5983 I flutter : package:patrol/src/native/patrol_app_service.dart 142:12                  PatrolAppService.runDartTest
12-12 13:49:41.717  5953  5983 I flutter : package:patrol/src/native/contracts/patrol_app_service_server.dart 27:28  PatrolAppServiceServer.handle
12-12 13:49:41.722  5953  5968 E PatrolServer: PatrolJUnitRunner.runDartTest(t01_smoke_test tap increment button works): Invalid response 500, Internal Server Error
12-12 13:49:41.722  5953  5968 E TestRunner: failed: runDartTest[t01_smoke_test tap increment button works](com.example.patrol_demo.MainActivityTest)
12-12 13:49:41.722  5953  5968 E TestRunner: ----- begin exception -----
12-12 13:49:41.723  5953  5968 E TestRunner: java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
12-12 13:49:41.723  5953  5968 E TestRunner: 	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:140)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at com.example.patrol_demo.MainActivityTest.runDartTest(MainActivityTest.java:31)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2361)
12-12 13:49:41.723  5953  5968 E TestRunner: Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
12-12 13:49:41.723  5953  5968 E TestRunner: 	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at pl.leancode.patrol.contracts.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:23)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at pl.leancode.patrol.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:39)
12-12 13:49:41.723  5953  5968 E TestRunner: 	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:133)
12-12 13:49:41.723  5953  5968 E TestRunner: 	... 41 more
12-12 13:49:41.723  5953  5968 E TestRunner: ----- end exception -----
12-12 13:49:41.724  5953  5968 I TestRunner: finished: runDartTest[t01_smoke_test tap increment button works](com.example.patrol_demo.MainActivityTest)
end of com.example.patrol_demo.MainActivityTest.runDartTest[t01_smoke_test tap increment button works]
12-12 13:49:41.725  5953  5968 I TestRunner: run finished: 2 tests, 1 failed, 0 ignored
12-12 13:49:41.727  5953  5983 I flutter : PatrolBinding: tearDown(): count: 1, results: {tap increment button works: success}
12-12 13:49:41.727  5953  5983 I flutter : PatrolBinding: finished test t01_smoke_test tap increment button works, but it was not requested, so its status will not be reported back to the native side
12-12 13:49:41.727  5953  5983 I flutter : 00:01 +3: All tests passed!
12-12 13:49:41.729   572   572 D BatterySaverPolicy: accessibility changed to false, updating policy.
12-12 13:49:41.733  2258  2405 I A       : NGA disabled due to not being eligible.
12-12 13:49:41.735   572  1948 I ActivityManager: Force stopping com.example.patrol_demo appid=10171 user=0: finished inst
12-12 13:49:41.735  5939  5939 I app_process: System.exit called, status: 0
12-12 13:49:41.735  5939  5939 I AndroidRuntime: VM exiting with result code 0.
12-12 13:49:41.736   572  1948 I ActivityManager: Killing 5953:com.example.patrol_demo/u0a171 (adj 0): stop com.example.patrol_demo due to finished inst
12-12 13:49:41.737   572  1948 W ActivityTaskManager: Force removing ActivityRecord{3e085af u0 com.example.patrol_demo/.MainActivity} t9 f}}: app died, no saved state
12-12 13:49:41.740   572  1948 W InputManager-JNI: Input channel object '3451852 com.example.patrol_demo/com.example.patrol_demo.MainActivity (client)' was disposed without first being removed with the input manager!
```

</details>

### Patrol version

patrol: ^3.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.3.1+1
Program adb found in /usr/local/share/android-sdk/platform-tools/adb
Env var $ANDROID_HOME set to /usr/local/share/android-sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by jBorkowska** [comment]
Hi @bbjay, we managed to reproduce your issue and we figured out that flag `--use-orchestrator` in ew-cli command was lacking. We recommend also adding `--clear-package-data` flag as well - it clears apps data between tests in the whole run

**Comment by bbjay** [comment]
Hi @jBorkowska , thanks for looking into this! I can confirm adding this option resolves this issue.
