### ISSUE TITLE
Unable to run patrol test with example app

### ISSUE THREAD

**Issue by cheuk0324** [leancodepl/patrol#2019]
### Steps to reproduce

1. create flutter app
2. follow the setup guide
3. run patrol test

### Actual results

Getting error on running `patrol test -t integration_test/example_test.dart --verbose

### Logs

<details>
<summary>Logs</summary>

```
error: integration_test/test_bundle.dart:50:50: Error: Too many positional arguments: 0 allowed, but 1 found.
	Try removing the extra positional arguments.
	  final binding = PatrolBinding.ensureInitialized(NativeAutomatorConfig());
	                                                 ^
	../../../.pub-cache/hosted/pub.dev/patrol-2.3.2/lib/src/binding.dart:104:11: Context: Found this candidate, but the arguments don't match.
	  factory PatrolBinding.ensureInitialized() {
	          ^^^^^^^^^^^^^^^^^
	Target kernel_snapshot failed: Exception
	Failed to package /Users/cheukkwanchan/Documents/playground/my_example_app.
	note: Building targets in dependency order
	note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	** TEST BUILD FAILED **
	
✗ Failed to build app with entrypoint test_bundle.dart for iOS simulator (xcodebuild exited with code 65) (28.8s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:132:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:72:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:234:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:322:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:266:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#10     main (file:///Users/cheukkwanchan/.pub-cache/hosted/pub.dev/patrol_cli-2.3.0/bin/main.dart:6:20)
<asynchronous suspension>

```

</details>

### Patrol version

patrol: ^2.3.2
patrol_cli v2.3.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Program adb found in /Users/cheukkwanchan/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/cheukkwanchan/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[!] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-arm64, locale en-US)
    • Flutter version 3.13.7 on channel stable at /Users/y/Documents/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/y/Documents/flutter. Consider adding /Users/y/Documents/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (10 weeks ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/y/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/y/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.85.0-insider)
    • VS Code at /Users/y/Downloads/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.77.20231101

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) 
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by cheuk0324** [comment]
after downgrade the cli to 2.2.2, now I am getting 
```
	/bin/sh: "/Users/cheukkwanchan/Documents/flutter/packages/flutter_tools/bin/xcode_backend.sh": No such file or directory
	Command PhaseScriptExecution failed with a nonzero exit code
	note: Building targets in dependency order
	note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
```
