### ISSUE TITLE
get_it service locator resets between every patrolTest()

### ISSUE THREAD

**Issue by GameOnAnil** [leancodepl/patrol#2037]
### Steps to reproduce

1. Clone https://github.com/GameOnAnil/patrol_bug_demo.git
2. Start android emulator
3. Verify app build by `flutter build apk --debug`
4. Run: `patrol test --target integration_test/buggy_test.dart`

### Actual results

Hi, i would like to save my login credential in between test so that i don't have to login again for every test that needs user to be logged in.
So for that is use  `get_it: ^7.6.4` that provides me service locator where i could save login token.
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get_it/get_it.dart';
import 'package:patrol/patrol.dart';

void main() {
  final locator = GetIt.instance;
  setUpAll(() {
    /// Register data class as locator in getIt
    locator.registerLazySingleton(() => DataClass());
  });
  group("", () {
    patrolTest("set value", (tester) async {
      // Set value in data class
      locator<DataClass>().setName("James");
      // Print value
      final name = locator<DataClass>().name;
      debugPrint("First test value:$name");
    });

    patrolTest("show value", (tester) async {
      // Should expect name to be "James"
      expect(locator<DataClass>().name, "James");
    });
  });
}

class DataClass {
  String? name;

  setName(String value) {
    name = value;
  }
}

```
Here the value of name is stored in a service called `DataClass` when is accessed by both patrolTest().

Now the problem is that the value doesn't persist between test.

When i run `patrol develop --target integration_test/buggy_test.dart` using `develop` the test passes. 

But when i use `patrol test --target integration_test/buggy_test.dart` it fails.
Similarly the test passes for `flutter test` using `testWidget()` instead of `patrolDevelop()`

My question is that is there a way for me to persist data between patrolTest() and why is the locator value being reset between test? Would greatly appreciate your feedback.

### Logs

<details>
<summary>Logs</summary>

```
No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (21.7s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
        See the report at: file:///Users/anilthapa/Flutter%20Projects/flutter_application_2/build/app/reports/androidTests/connected/index.html
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (16.4s)
Exception: Gradle test execution failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
```
```
java.lang.AssertionError: Dart test failed: buggy_test  show value
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure was thrown running a test:
Expected: 'James'
Actual: <null>
Which: not an <Instance of 'String'>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/anilthapa/Flutter%20Projects/flutter_application_2/integration_test/buggy_test.dart:23:7)
#5      patrolTest.<anonymous closure> (package:patrol/src/common.dart:120:21)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:804:12)
<asynchronous suspension>

This was caught by the test expectation on the following line:
file:///Users/anilthapa/Flutter%20Projects/flutter_application_2/integration_test/buggy_test.dart line 23
The test description was:
show value
═════════════════════════════════════════════════════════════════

at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:135)
at com.example.flutter_application_2.MainActivityTest.runDartTest(MainActivityTest.java:31)
```

</details>

### Patrol version

  patrol: ^3.0.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.5.0
Program adb found in /Users/anilthapa/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/anilthapa/Library/Android/sdk/
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.4 22F66 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.1)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by piotruela** [comment]
Hi @GameOnAnil, `setUpAll` method will not work as every patrol test is run in the isolation. You can create a `shortcut method` which will log in to the app and invoke it at the beginning of every test.

**Comment by GameOnAnil** [comment]
> Contributor

My problem is not the setup method, I could remove the setUpAll method and call this code in main 
```dart
 /// Register data class as locator in getIt
 locator.registerLazySingleton(() => DataClass());
```,
I have an issue that i cannot share the service locator between patrolTest(). As you have said every patrolTest runs in isolation, is it not possible to share data between them at all?

**Comment by robsonsilv4** [comment]
@GameOnAnil have you tested with `patrolSetUpAll`, instead of test `setUpAll`?

**Comment by GameOnAnil** [comment]
@robsonsilv4  Hi, I think you misunderstood my issue I have modified my code with this
```dart
void main() {
  final locator = GetIt.asNewInstance();

  /// Register data class as locator in getIt
  locator.registerLazySingleton(() => DataClass());

  patrolTest("set value", (tester) async {
    await tester.pumpWidget(
      const MaterialApp(
        home: Scaffold(
            body: Center(
          child: Text("Home Page"),
        )),
      ),
    );
    await Future.delayed(const Duration(seconds: 2));
    // Set value in data class
    locator<DataClass>().setName("James");
    // Print value
    final name = locator<DataClass>().name;
    debugPrint("First test value:$name");
  });

  patrolTest("show value", (tester) async {
    // Should expect name to be "James"
    expect(locator<DataClass>().name, "James");
  });
}
```

Even when i remove the setUp() the test fails, I would like to ask "every patrol test is run in the isolation" does this mean my 2 test case will not run one after another and might run at the same time?
