### ISSUE TITLE
gallery - select a video

### ISSUE THREAD

**Issue by adipeleg** [leancodepl/patrol#2038]
### Steps to reproduce

Hi, thanks for the awesome library!

I'm trying to select an mp4 file using the file picker but the element is not selected.
using the same line for images does work:
     await $.native.tap(Selector(className: 'Image'), appId: appId);
but for videos no.

the dom is:

`{"AXFrame":"{{-2.5431315151536182e-06, 102.99999745686848}, {129.66667175292969, 129.66667175292969}}","AXUniqueId":null,"frame":{"y":102.99999745686848,"x":-2.5431315151536182e-06,"width":129.66667175292969,"height":129.66667175292969},"role_description":"image","AXLabel":"Video","content_required":false,"type":"Image","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXImage","subrole":null}`
 
but searching for Image or Video doesn't do the trick.

please help me:)

### Actual results

the test freezes

### Logs

<details>
<summary>Logs</summary>

```
 App reported that it is ready
        2024-01-01 18:36:24.086800+0200 RunnerUITests-Runner[48871:5225524] PatrolAppServiceClient.runDartTest(login_test e2e veni login)
        2024-01-01 18:36:24.095942+0200 RunnerUITests-Runner[48871:5225786] [connection] nw_socket_handle_socket_event [C2.1.1:2] Socket SO_ERROR [61: Connection refused]
        2024-01-01 18:36:49.568417+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: tapping on view with text "Allow Full Access" at index 0 in app com.apple.springboard...
        2024-01-01 18:36:49.572278+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: waiting for existence of view with text "Allow Full Access" at index 0 in app com.apple.springboard
            t =    29.82s Get all elements bound by index for: Elements matching predicate 'label == "Allow Full Access" OR title == "Allow Full Access" OR identifier == "Allow Full Access"'
            t =    30.00s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.01s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.03s Checking existence of `Any (Element at index 0)`
            t =    30.15s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.15s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.16s Find the Any (Element at index 0)
            t =    30.26s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.26s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.30s Tap "Allow Full Access" Button
            t =    30.30s     Wait for com.apple.springboard to idle
            t =    30.31s     Find the "Allow Full Access" Button
            t =    30.42s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.42s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.44s     Check for interrupting elements affecting "Allow Full Access" Button
            t =    30.53s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.53s Ignoring failure to get hierarchy for remote element in process 5132 (Error getting main window kAXErrorInvalidUIElement)
            t =    30.55s     Synthesize event
            t =    30.89s     Wait for com.apple.springboard to idle
        2024-01-01 18:36:50.930105+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: done tapping on view with text "Allow Full Access" at index 0 in app com.apple.springboard
        2024-01-01 18:36:50.936109+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: result: ()
        2024-01-01 18:36:51.062079+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: tapping on view with text "" at index 0 in app com.veni.veniApp...
        2024-01-01 18:36:51.064104+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: waiting for existence of view with text "" at index 0 in app com.veni.veniApp
            t =    31.31s Get all elements bound by index for: Elements matching predicate 'label == "" OR title == "" OR identifier == ""'
            t =    31.81s Checking existence of `Any (Element at index 0)`
            t =    31.95s Find the Any (Element at index 0)
            t =    32.11s Tap Window at {{0.0, 0.0}, {393.0, 852.0}}
            t =    32.11s     Wait for com.veni.veniApp to idle
            t =    32.11s     Find the Window at {{0.0, 0.0}, {393.0, 852.0}}
            t =    32.26s     Check for interrupting elements affecting Window
            t =    32.37s     Synthesize event
            t =    32.69s     Wait for com.veni.veniApp to idle
        2024-01-01 18:36:53.005963+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: done tapping on view with text "" at index 0 in app com.veni.veniApp
        2024-01-01 18:36:53.006357+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: result: ()
        2024-01-01 18:36:59.705112+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: tapping on view with text "" at index 0 in app com.apple.springboard...
        2024-01-01 18:36:59.707019+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: waiting for existence of view with text "" at index 0 in app com.apple.springboard
            t =    39.96s Get all elements bound by index for: Elements matching predicate 'label == "" OR title == "" OR identifier == ""'
            t =    40.09s Checking existence of `Any (Element at index 0)`
            t =    40.13s Find the Any (Element at index 0)
            t =    40.19s Tap Window at {{0.0, 0.0}, {393.0, 852.0}}[0.00, 0.00]
            t =    40.19s     Wait for com.apple.springboard to idle
            t =    40.20s     Find the Window at {{0.0, 0.0}, {393.0, 852.0}}
            t =    40.24s     Check for interrupting elements affecting Window
            t =    40.25s         Wait for com.veni.veniApp to idle
            t =    40.39s     Synthesize event
            t =    40.39s         Find the Window at {{0.0, 0.0}, {393.0, 852.0}}
            t =    40.44s         Find the Window at {{0.0, 0.0}, {393.0, 852.0}}
            t =    40.49s         Find the Window at {{0.0, 0.0}, {393.0, 852.0}}
            t =    40.84s     Wait for com.apple.springboard to idle
        2024-01-01 18:37:00.593485+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: done tapping on view with text "" at index 0 in app com.apple.springboard
        2024-01-01 18:37:00.593729+0200 RunnerUITests-Runner[48871:5225524] PatrolServer: INFO: result: ()
^CCaught SIGINT, exiting...
✗ Failed to execute tests of app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 15 (xcodebuild was interrupted) (1801.7s)
Interrupted: xcodebuild was interrupted
#0      throwToolInterrupted (package:patrol_cli/src/base/exceptions.dart:15:3)
#1      IOSTestBackend.execute.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:184:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.execute (package:patrol_cli/src/ios/ios_test_backend.dart:148:5)
<asynchronous suspension>
#4      TestCommand._execute (package:patrol_cli/src/commands/test.dart:298:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:190:23)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:329:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:273:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:69:20)
<asynchronous suspension>
#10     main (file:///Users/****/.pub-cache/hosted/pub.dev/patrol_cli-2.5.0/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

patrol: ^3.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.5.0
Program adb found in /Users/***/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/****/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```

```

</details>

**Comment by piotruela** [comment]
Hi @adipeleg, please share the reproducible example of a code that causes this issue.
