### ISSUE TITLE
Unable to run integration test: Error: xcodebuild exited with code 65

### ISSUE THREAD

**Issue by amanxnanda** [leancodepl/patrol#2039]
### Steps to reproduce

Here is the minimal reproducible code [patrol_test](https://github.com/amanxnanda/patrol_test)

### Actual results

Unable to run the integration test using patrol after following the given docs.

### Logs

<details>
<summary>Logs</summary>

```
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/amann/Developer/Experiments/patrol_test/integration_test/example_test.dart
Generated entrypoint /Users/amann/Developer/Experiments/patrol_test/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check devices --machine
No device specified, using the first one (iPhone 15 Pro Max)
Received 1 device(s) to run on
Received device: iPhone 15 Pro Max
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.amannanda.patrolTest
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.amannanda.patrolTest
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol Test
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol Test
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --simulator --target /Users/amann/Developer/Experiments/patrol_test/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=com.amannanda.patrolTest --dart-define PATROL_APP_BUNDLE_ID=com.amannanda.patrolTest --dart-define PATROL_ANDROID_APP_NAME=Patrol Test --dart-define PATROL_IOS_APP_NAME=Patrol Test --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true
	Building com.amannanda.patrolTest for simulator (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphonesimulator -destination generic/platform=iOS Simulator -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
	error: Sandbox: dart(73036) deny(1) file-read-data /Users/amann/Developer/Experiments/patrol_test/build/ios_integ/Build/Products/Debug-iphonesimulator/Flutter.framework/Flutter (in target 'RunnerUITests' from project 'Runner')
	error: Sandbox: dart(73036) deny(1) file-read-data /Users/amann/Developer/Experiments/patrol_test/build/ios_integ/Build/Products/Debug-iphonesimulator/.last_build_id (in target 'RunnerUITests' from project 'Runner')
	error: Flutter failed to read a file at "/Users/amann/Developer/Experiments/patrol_test/build/ios_integ/Build/Products/Debug-iphonesimulator/.last_build_id".
	Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
	Try running:
	  sudo chown -R $(whoami) /Users/amann/Developer/Experiments/patrol_test/build/ios_integ/Build/Products/Debug-iphonesimulator/.last_build_id
	Failed to package /Users/amann/Developer/Experiments/patrol_test.
	/Users/amann/Developer/Experiments/patrol_test/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'CocoaAsyncSocket' from project 'Pods')
	/Users/amann/Developer/Experiments/patrol_test/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'patrol' from project 'Pods')
	note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
	warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
	/Users/amann/Developer/Experiments/patrol_test/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Flutter' from project 'Pods')
✗ Failed to build app with entrypoint test_bundle.dart for iOS simulator (xcodebuild exited with code 65) (25.4s)
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:132:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:72:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:254:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:188:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:329:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:273:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:69:20)
<asynchronous suspension>
#10     main (file:///Users/amann/.pub-cache/hosted/pub.dev/patrol_cli-2.5.0/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

 patrol: ^3.3.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.5.0
Program adb found in /Users/amann/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/amann/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.1 23B81 darwin-arm64, locale en-IN)
    • Flutter version 3.16.5 on channel stable at /Users/amann/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (13 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/amann/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/amann/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • iPhone 15 Pro Max (mobile) • 6F4BC066-24D3-489E-9A59-FFC54858145B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 119.1.60.125
    ! Error: Browsing on the local area network for Tessarion. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by piotruela** [comment]
Hi @amanxnanda. Looks like this error is caused because `User Script Sandboxing` is enabled. Make sure to set it to `No` for all Targets. 
<img width="1126" alt="Screenshot 2024-01-03 at 14 06 58" src="https://github.com/leancodepl/patrol/assets/37781044/d0f6c9cb-b448-4dd3-8502-7d20dd6cebeb">
Since this is a setup issue rather than an actual bug, I'm closing the issue. If you encounter any additional setup problems, feel free to ask on our [Discord channel](https://discord.gg/gcEAcgPM3Y).
