### ISSUE TITLE
Cannot find text inside native TextField on iOS

### ISSUE THREAD

**Issue by fylyppo** [leancodepl/patrol#2081]
### Steps to reproduce

1. Clone https://github.com/leancodepl/patrol.git and checkout to `bug/ios-reproduce-examples`
2. run iOS simulator, open messages and tap on tile to see conversation on the screen and message bottom bar
3. `in patrol/dev/e2e_app` run: `patrol test -t integration_test/ios_text_field_text_test.dart`

### Actual results

`waitUntilVisible()` failed

### Logs

<details>
<summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        The following PatrolActionException was thrown running a test:
        Patrol action failed: NativeAutomatorClientException: waitUntilVisible() failed with Invalid
        response: 400 The operation couldnât be completed. (patrol.PatrolError error 0.)
        When the exception was thrown, this was the stack:
        #0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:226:7)
        <asynchronous suspension>
        #1      NativeAutomator.waitUntilVisible (package:patrol/src/native/native_automator.dart:693:5)
        <asynchronous suspension>
        #2      main.<anonymous closure> (file:///Users/fylyppo/Documents/GitHub/patrol/dev/e2e_app/integration_test/ios_text_field_text_test.dart:13:7)
        <asynchronous suspension>
        #3      patrolTest.<anonymous closure> (package:patrol/src/common.dart:130:7)
        <asynchronous suspension>
        #4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
        <asynchronous suspension>
        #5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
        <asynchronous suspension>
        #6      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:804:12)
        <asynchronous suspension>
```

</details>

### Patrol version

from branch

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by zltnDC** [comment]
So, I investigated this issue and there are few problems:
