### ISSUE TITLE
Cannot build Android release build with Patrol in dev_dependencies

### ISSUE THREAD

**Issue by DavidI7** [leancodepl/patrol#2084]
### Steps to reproduce

 flutter run --release --verbose -d emulator-5554 (an Android emulator)

### Actual results

In release mode, the build completes but the the app crashes with the following error:
```
[+1231 ms] E/AndroidRuntime(10621): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(10621): Process: PRIVATE_BUNDLE_ID, PID: 10621
[        ] E/AndroidRuntime(10621): java.lang.NoClassDefFoundError: q5.c
[        ] E/AndroidRuntime(10621):     at l5.Q.b(SourceFile:10)
[        ] E/AndroidRuntime(10621):     at l5.o.E(SourceFile:4)
[        ] E/AndroidRuntime(10621):     at l5.o$a$p.invoke(SourceFile:2)
[        ] E/AndroidRuntime(10621):     at l5.N$a.invoke(SourceFile:4)
[        ] E/AndroidRuntime(10621):     at l5.o$a.j(SourceFile:2)
[        ] E/AndroidRuntime(10621):     at l5.o.getSimpleName(SourceFile:1)
[        ] E/AndroidRuntime(10621):     at com.instabug.library.sessionV3.manager.l.onActivityResumed(SourceFile:2)
[        ] E/AndroidRuntime(10621):     at android.app.Application.dispatchActivityResumed(Application.java:431)
[        ] E/AndroidRuntime(10621):     at android.app.Activity.dispatchActivityResumed(Activity.java:1435)
[        ] E/AndroidRuntime(10621):     at android.app.Activity.onResume(Activity.java:1996)
[        ] E/AndroidRuntime(10621):     at Y3.c.onResume(SourceFile:1)
[        ] E/AndroidRuntime(10621):     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1564)
[        ] E/AndroidRuntime(10621):     at android.app.Activity.performResume(Activity.java:8437)
[        ] E/AndroidRuntime(10621):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4763)
[        ] E/AndroidRuntime(10621):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806)
[        ] E/AndroidRuntime(10621):     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
[        ] E/AndroidRuntime(10621):     at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
[        ] E/AndroidRuntime(10621):     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
[        ] E/AndroidRuntime(10621):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
[        ] E/AndroidRuntime(10621):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
[        ] E/AndroidRuntime(10621):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(10621):     at android.os.Looper.loopOnce(Looper.java:201)
[        ] E/AndroidRuntime(10621):     at android.os.Looper.loop(Looper.java:288)
[        ] E/AndroidRuntime(10621):     at android.app.ActivityThread.main(ActivityThread.java:7872)
[        ] E/AndroidRuntime(10621):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(10621):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[        ] E/AndroidRuntime(10621):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[        ] E/AndroidRuntime(10621): Caused by: java.lang.ExceptionInInitializerError
[        ] E/AndroidRuntime(10621):     at Y5.e.q(SourceFile:1)
[        ] E/AndroidRuntime(10621):     at q5.c.<clinit>(SourceFile:61)
[        ] E/AndroidRuntime(10621):     at l5.Q.b(SourceFile:10)
[        ] E/AndroidRuntime(10621):     at l5.o.E(SourceFile:4)
[        ] E/AndroidRuntime(10621):     at l5.o$a$p.invoke(SourceFile:2)
[        ] E/AndroidRuntime(10621):     at l5.N$a.invoke(SourceFile:4)
[        ] E/AndroidRuntime(10621):     at l5.o$a.j(SourceFile:2)
[        ] E/AndroidRuntime(10621):     at l5.o.getSimpleName(SourceFile:1)
[        ] E/AndroidRuntime(10621):     at com.instabug.library.sessionV3.ratingDialogDetection.m.a(SourceFile:6)
[        ] E/AndroidRuntime(10621):     at com.instabug.library.sessionV3.ratingDialogDetection.m.e(Unknown Source:0)
[        ] E/AndroidRuntime(10621):     at androidx.core.content.res.g.run(Unknown Source:51)
[        ] E/AndroidRuntime(10621):     at com.instabug.library.util.threading.c.run(SourceFile:1)
[        ] E/AndroidRuntime(10621):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[        ] E/AndroidRuntime(10621):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[        ] E/AndroidRuntime(10621):     at com.instabug.library.util.threading.PriorityThreadFactory.lambda$newThread$0(SourceFile:2)
[        ] E/AndroidRuntime(10621):     at com.instabug.library.util.threading.PriorityThreadFactory.a(Unknown Source:0)
[        ] E/AndroidRuntime(10621):     at androidx.core.content.res.g.run(Unknown Source:39)
[        ] E/AndroidRuntime(10621):     at java.lang.Thread.run(Thread.java:1012)
[        ] E/AndroidRuntime(10621):     at com.instabug.library.util.threading.j.run(SourceFile:2)
[        ] E/AndroidRuntime(10621): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: o5.h.values []
[        ] E/AndroidRuntime(10621):     at java.lang.Enum.enumValues(Enum.java:272)
[        ] E/AndroidRuntime(10621):     at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
[        ] E/AndroidRuntime(10621):     at java.lang.Enum$1.create(Enum.java:279)
[        ] E/AndroidRuntime(10621):     at java.lang.Enum$1.create(Enum.java:277)
[        ] E/AndroidRuntime(10621):     at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
[        ] E/AndroidRuntime(10621):     at java.lang.Enum.getSharedConstants(Enum.java:291)
[        ] E/AndroidRuntime(10621):     at java.lang.Class.getEnumConstantsShared(Class.java:2461)
[        ] E/AndroidRuntime(10621):     at java.util.EnumMap.getKeyUniverse(EnumMap.java:754)
[        ] E/AndroidRuntime(10621):     at java.util.EnumMap.<init>(EnumMap.java:134)
[        ] E/AndroidRuntime(10621):     at Y5.e.<clinit>(SourceFile:12)
[        ] E/AndroidRuntime(10621):     ... 19 more
[        ] E/AndroidRuntime(10621): Caused by: java.lang.NoSuchMethodException: o5.h.values []
[        ] E/AndroidRuntime(10621):     at java.lang.Class.getMethod(Class.java:2103)
[        ] E/AndroidRuntime(10621):     at java.lang.Class.getDeclaredMethod(Class.java:2081)
[        ] E/AndroidRuntime(10621):     at java.lang.Enum.enumValues(Enum.java:269)
[        ] E/AndroidRuntime(10621):     ... 28 more 
```

if I change android/app.build.gradle like this: 

```
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false // With this two lines, it works properly
            shrinkResources false // second line
        }
    }
```
then it'll work properly.  

Running the app it debug mode also causes it to work fine.

Also, if I downgrade the patrol version to 2.3.2, it'll work properly. From my testing, this was introduced between patrol versions 2.2.5 and 2.3.0, with 2.3.0 being the first version where I encounter the crash. 

Thinking it was perhaps a Java version issue, I tried running the project with both Android Studio Giraffe and Android Studio Hedgehog, with the same result.

### Logs

<details>
<summary>Logs</summary>

```
```

</details>

### Patrol version

patrol: ^3.5.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.0
Android: 
• Program adb found in /Users/user/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/user/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[!] Flutter (Channel stable, 3.16.9, on macOS 14.0 23A344 darwin-arm64, locale en-RO)
    • Flutter version 3.16.9 on channel stable at /Users/user/fvm/versions/3.16.9
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart-sdk/3.2.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/user/fvm/versions/3.16.9. Consider adding /Users/user/fvm/versions/3.16.9/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (6 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.83.0)
    • VS Code at /Users/cyberivan/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • David's iPhone (mobile)     • 00008030-00083824113A802E            • ios            • iOS 17.2.1 21C66
    • iPhone 15 (mobile)          • E8AACF5D-D5FF-4B3E-83ED-ED8E2594C9DD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by jBorkowska** [comment]
Hi @DavidI7 , it can be caused by using proguard. Check this issue for more info: https://github.com/leancodepl/patrol/issues/1542

**Comment by jBorkowska** [comment]
Also let us know if it helped

**Comment by DavidI7** [comment]
Hi @jBorkowska !  

I've tried the solution that you mentioned and it worked, thank you very much :) ! 

For people stumbling across this via searches, the solution that worked for me is:
1. Create a proguard-rules.pro file inside android/app
2. Write the following lines inside: 
```
-keep class pl.leancode.patrol.** { *; }
-keep class kotlin.reflect.jvm.internal.impl.builtins.PrimitiveType { *; }
```
