### ISSUE TITLE
patrol is broken through non-JSON message `FormatException: Unexpected character (at line 14, character 3)`

### ISSUE THREAD

**Issue by DrBu7cher** [leancodepl/patrol#2087]
### Steps to reproduce

1. run `flutter --no-version-check --suppress-analytics --version --machine` (or update flutter to a new version?)
2. run `patrol doctor`
3. see patrol crash

### Actual results

running `#> patrol doctor` crashes patrol

### Logs

<details>
<summary>Logs</summary>

```
Unhandled exception:
FormatException: Unexpected character (at line 14, character 3)
  ╔════════════════════════════════════════════════════════════════════════...
  ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:913:48)
#2      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      _getFlutterVersion (package:patrol_cli/src/analytics/analytics.dart:198:23)
#7      new Analytics (package:patrol_cli/src/analytics/analytics.dart:50:44)
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:49:16)
#9      main (file:///home/jbadstuebner/.pub-cache/hosted/pub.dev/patrol_cli-2.6.2/bin/main.dart:6:26)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

</details>

### Patrol version

patrol_cli: ^2.6.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output (on second run)</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.2
Android: 
• Program adb found in /usr/bin/adb
• Env var $ANDROID_HOME is not set. (See the link: https://developer.android.com/tools/variables#set)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝
....
```

</details>

**Comment by DrBu7cher** [comment]
If I run patrol for a test (has been working before the flutter upgrade) it breaks here: https://github.com/leancodepl/patrol/blob/master/packages/patrol_cli/lib/src/analytics/analytics.dart#L198
Because the output of `flutter --no-version-check --suppress-analytics --version --machine` looks like
```
{
  "frameworkVersion": "3.19.0-0.3.pre",
  "channel": "beta",
  "repositoryUrl": "https://github.com/flutter/flutter.git",
  "frameworkRevision": "1b197762c51e993cb77d7fafe9729ef2506e2bf7",
  "frameworkCommitDate": "2024-01-25 22:23:26 -0800",
  "engineRevision": "968e2945c75c817f594e2e737bdd7bf68cba6bc0",
  "dartSdkVersion": "3.3.0 (build 3.3.0-279.2.beta)",
  "devToolsVersion": "2.31.0",
  "flutterVersion": "3.19.0-0.3.pre",
  "flutterRoot": "/home/jbadstuebner/fvm/versions/3.19.0-0.3.pre"
}

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════
```

**Comment by DrBu7cher** [comment]
Where the whole "welcome to flutter" message is not valid JSON.
Is there a way to suppress this message forever, so patrol does not break? And could you add this to the patrol command?

**Comment by DrBu7cher** [comment]
It seems to be an upstream problem...https://github.com/flutter/flutter/issues/122814
But I am unsure how to work around this for patrol? As far as I know, this message should only be shown once - but it appears for me if I run `patrol doctor` and then `flutter doctor` - or the other way around.
