### ISSUE TITLE
Native waitUntilVisible failing with error response: 404 selector UiSelector found nothing

### ISSUE THREAD

**Issue by lewismmaina** [leancodepl/patrol#2102]
### Steps to reproduce

Code is in a private repo.
1. Run native tests either using patrol develop/test on an android emulator API 31
2. See logs below on output

### Actual results

Part of code:
Future<void> updateAddressAfterAVSFailureOnPaymentMethodsViaPatrol(
    String card, String cvv, String selectorTextTitle, String errorMessage, String check, $) async {
  await $(newCardText).tap();
  await nativeAddCardDetailsViaCheckoutUsingPatrolStep(card, cvv, $);
  await Future.delayed(longDelay);
  await $.native.waitUntilVisible(Selector(textContains: selectorTextTitle), appId: defaultDevAppId);
  await $.native.waitUntilVisible(Selector(textContains: errorMessage), appId: defaultDevAppId);
  await $.native.tap(Selector(text: patrolUpdateMyAddressButtonFinder));

  await $(AppKeys.senderAddressScreenRoute_AddressLine1Key).enterText(commonAddressLine1);

  await $(AppKeys.senderAddressScreenRoute_ContinueButtonKey).tap();

  log('Check completed successfully for $check');
}

When running native tests with on a Webview, the following error is thrown 

 : ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        : The following PatrolActionException was thrown running a test:
        : Patrol action failed: NativeAutomatorClientException: waitUntilVisible() failed with Invalid
        : response: 404 selector UiSelector[CONTAINS_TEXT=We couldn't save your card] found nothing
        : 
        : When the exception was thrown, this was the stack:
        : #0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:231:7)
        : <asynchronous suspension>
        : #1      NativeAutomator.waitUntilVisible (package:patrol/src/native/native_automator.dart:618:5)
        : <asynchronous suspension>
        : #2      updateAddressAfterAVSFailureOnPaymentMethodsViaPatrol (file:///Users/lew/Workspace/Protype/integration_test/flows/transaction_flow.dart:1335:3)
        : <asynchronous suspension>
        : #3      main.<anonymous closure> (file:///Users/lew/Workspace/Protype/integration_test/us_card_checks_test.dart:67:7)
        : <asynchronous suspension>
        : #4      patrolTest.<anonymous closure> (package:patrol/src/common.dart:140:7)
        : <asynchronous suspension>
        : #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
        : <asynchronous suspension>
        : #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:935:5)
        : <asynchronous suspension>
        : 
        : The test description was:
        :   US card flow

### Logs

When running native tests with on a Webview, the following error is thrown 

 : ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        : The following PatrolActionException was thrown running a test:
        : Patrol action failed: NativeAutomatorClientException: waitUntilVisible() failed with Invalid
        : response: 404 selector UiSelector[CONTAINS_TEXT=We couldn't save your card] found nothing
        : 
        : When the exception was thrown, this was the stack:
        : #0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:231:7)
        : <asynchronous suspension>
        : #1      NativeAutomator.waitUntilVisible (package:patrol/src/native/native_automator.dart:618:5)
        : <asynchronous suspension>
        : #2      updateAddressAfterAVSFailureOnPaymentMethodsViaPatrol (file:///Users/lew/Workspace/Protype/integration_test/flows/transaction_flow.dart:1335:3)
        : <asynchronous suspension>
        : #3      main.<anonymous closure> (file:///Users/lew/Workspace/Protype/integration_test/us_card_checks_test.dart:67:7)
        : <asynchronous suspension>
        : #4      patrolTest.<anonymous closure> (package:patrol/src/common.dart:140:7)
        : <asynchronous suspension>
        : #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
        : <asynchronous suspension>
        : #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:935:5)
        : <asynchronous suspension>
        : 
        : The test description was:
        :   US card flow

### Patrol version

patrol v 2.2.2

### Patrol Doctor output

In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
Patrol CLI version: 2.2.2

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on macOS 14.3.1 23D60 darwin-arm64, locale en-KE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by lewismmaina** [comment]
@bartekpacia @jBorkowska any help with above
