### ISSUE TITLE
 AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)

### ISSUE THREAD

**Issue by nc-jeni** [leancodepl/patrol#2105]
### Steps to reproduce

Issue starts when upgrading from 2.6.2 to 2.6.4.

1. Add an integration test

```
  group('Dummy tests =>', ()
  {
    patrolSetUp(() => ($) async {
      await $.native.initialize();
      await $.native.configure();
    });

    patrolWidgetTest(
      'find app text on widget',
      config: const PatrolTesterConfig(visibleTimeout: Duration(seconds: 10)),
          ($) async {
        await $.pumpWidgetAndSettle(
          MaterialApp(
            home: Scaffold(
              appBar: AppBar(title: const Text('app')),
              backgroundColor: Colors.blue,
            ),
          ),
        );
        expect($('app'), findsOneWidget);
        // TODO Fix - fails on emulator only
        // A SemanticsHandle was active at the end of the test.
        // All SemanticsHandle instances must be disposed by calling
        // dispose() on the SemanticsHandle.
      },
    );
  });
```

2. dart pub global activate patrol_cli
3. patrol test

### Actual results

<details>
<summary>Actual results</summary>

```console
        FAILURE: Build failed with an exception.

        * What went wrong:
        Task 'assembleDevelopmentDebug' not found in project ':app'.

        * Try:
        > Run gradlew tasks to get a list of available tasks.
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 2s
```
</details>

### Logs

<details>
<summary>Logs</summary>

```
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (3.2s)
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///.../AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-2.6.4/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///.../AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-2.6.4/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

  patrol: ^3.5.0
  patrol_finders: ^2.0.1+1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.4
Android:
• Program adb found in ...\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to ...\AppData\Local\Android\Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22631.3007], locale en-DK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.6.2)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Community Edition (version 2022.3)
[√] VS Code (version 1.77.3)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by nc-jeni** [comment]
Solved by adding flavors to the `build.gradle` file.

```
    flavorDimensions "default"
    productFlavors {
        development {
            dimension "default"
            versionNameSuffix "--dev"
        }
        staging {
            dimension "default"
            versionNameSuffix "--stage"
        }
        production {
            dimension "default"
        }
    }
```
