### ISSUE TITLE
patrolSetUp is never called with patrol cli

### ISSUE THREAD

**Issue by nc-jeni** [leancodepl/patrol#2108]
### Steps to reproduce

1. Create integration tests with the following snippet in a file such as `integration_test/app_test.dart`.

```dart
  group('Dummy tests =>', () {
    bool? bIsBoolean;

    patrolSetUp(() => (PatrolIntegrationTester $) async {
      await $.native.initialize();
      await $.native.configure();
      bIsBoolean = true;
    });

    patrolWidgetTest(
      'find app text on widget',
      config: const PatrolTesterConfig(visibleTimeout: Duration(seconds: 10)),
          (PatrolTester $) async {
        await $.pumpWidgetAndSettle(
          MaterialApp(
            home: Scaffold(
              appBar: AppBar(title: const Text('app')),
              backgroundColor: Colors.blue,
            ),
          ),
        );
        expect(bIsBoolean, isNotNull);
        expect(bIsBoolean, isTrue);
        expect($('app'), findsOneWidget);
      },
    );

    patrolTest(
      'toggle app',
      nativeAutomatorConfig: const NativeAutomatorConfig(
        packageName: 'com.arosii.mobilize_me.execution',
        bundleId: 'com.arosii.mobilize',
      ), (PatrolIntegrationTester $) async {
        await $.pumpWidgetAndSettle(
          MaterialApp(
            home: Scaffold(
              appBar: AppBar(title: const Text('app')),
              backgroundColor: Colors.blue,
            ),
          ),
        );
        expect(bIsBoolean, isNotNull);
        expect(bIsBoolean, isTrue);
        expect($('app'), findsOneWidget);
        await $.native.pressHome();
        await $.native.openApp();
      },
    );
  });
```

2. Start emulator `Resizable Experimental API 34 (mobile)`
3. Run `flutter run` to generate gradlew and to make sure that the example app builds and runs just fine
4. Install Patrol CLI, which is needed to run Flutter integration tests that use Patrol's native UI automation feature. Use the latest release version: 2.6.2.

```
dart pub global activate patrol_cli
```

5. Run `patrol test --target integration_test/app_test.dart` to run the simple integration tests above.

It might be related to: https://github.com/leancodepl/patrol/issues/1503

### Actual results

```console
No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (25.4s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
        See the report at: file:///app_root/build/app/reports/androidTests/connected/index.html
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (57.2s)
Exception: Gradle test execution failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
```

### Logs

<details>
<summary>Logs</summary>

```
java.lang.AssertionError: Dart test failed: app_test Dummy tests => find app text on widget
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure was thrown running a test:
Expected: not null
Actual: <null>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///app_root/integration_test/app_test.dart:70:9)
<asynchronous suspension>
#5      patrolWidgetTest.<anonymous closure> (package:patrol_finders/src/common.dart:52:7)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:804:12)
<asynchronous suspension>

This was caught by the test expectation on the following line:
file:///app_root/integration_test/app_test.dart line 70
The test description was:
find app text on widget
═════════════════════════════════════════════════════════════════

at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:135)


java.lang.AssertionError: Dart test failed: app_test Dummy tests => toggle app
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure was thrown running a test:
Expected: not null
Actual: <null>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///app_root/integration_test/app_test.dart:90:9)
<asynchronous suspension>
#5      patrolTest.<anonymous closure> (package:patrol/src/common.dart:130:7)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:804:12)
<asynchronous suspension>

This was caught by the test expectation on the following line:
file:///app_root/integration_test/app_test.dart line 90
The test description was:
toggle app
═════════════════════════════════════════════════════════════════

at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:135)
```

</details>

### Patrol version

patrol: ^3.5.0
patrol_finders: ^2.0.1+1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.4
Android:
• Program adb found in C:\Users\...\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to C:\Users\...\AppData\Local\Android\Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22631.3155], locale en-DK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.6.2)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Community Edition (version 2022.3)
[√] VS Code (version 1.77.3)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by piotruela** [comment]
Hi @nc-jeni. It seems that the problem lies in how you are trying to define `patrolSetUp`. Inside your `patrolSetUp` you defined that it returns a callback which takes `PatrolIntegrationTester` as parameter but it's never actually called (and cannot be called as `patrolSetUp` has no access to `PatrolIntegrationTester`. If you define it like this:
```dart
    patrolSetUp(
      () {
        bIsBoolean = true;
      },
    );
```
Then it will work as expected.
