### ISSUE TITLE
No podspec found for patrol in .symlinks/plugins/patrol/ios

### ISSUE THREAD

**Issue by Noxiver** [leancodepl/patrol#2119]
### Steps to reproduce

1.Setup by following the documentation
2.Run cd ios 
3.Run pod install

### Actual results

No podspec found for `patrol` in `.symlinks/plugins/patrol/ios`

### Logs

<details>
<summary>Logs</summary>

```
ios % pod install
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
Ignoring ffi-1.16.3 because its extensions are not built. Try: gem pristine ffi --version 1.16.3
Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.
firebase_crashlytics: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
firebase_performance: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
[!] No podspec found for `patrol` in `.symlinks/plugins/patrol/ios`
artemmoiseev@MBP-Artem ios % pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Runner-RunnerUITests`: (``)

Fetching external sources
-> Fetching podspec for `Flutter` from `Flutter`
-> Fetching podspec for `app_settings` from `.symlinks/plugins/app_settings/ios`
-> Fetching podspec for `connectivity_plus` from `.symlinks/plugins/connectivity_plus/ios`
-> Fetching podspec for `contacts_service` from `.symlinks/plugins/contacts_service/ios`
-> Fetching podspec for `device_info_plus` from `.symlinks/plugins/device_info_plus/ios`
-> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
firebase_analytics: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
firebase_core: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
Ignoring ffi-1.16.3 because its extensions are not built. Try: gem pristine ffi --version 1.16.3
Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.
firebase_crashlytics: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_dynamic_links` from `.symlinks/plugins/firebase_dynamic_links/ios`
firebase_dynamic_links: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
firebase_messaging: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_performance` from `.symlinks/plugins/firebase_performance/ios`
firebase_performance: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_remote_config` from `.symlinks/plugins/firebase_remote_config/ios`
firebase_remote_config: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
-> Fetching podspec for `flutter_app_badger` from `.symlinks/plugins/flutter_app_badger/ios`
-> Fetching podspec for `flutter_exif_rotation` from `.symlinks/plugins/flutter_exif_rotation/ios`
-> Fetching podspec for `flutter_ffmpeg` from `.symlinks/plugins/flutter_ffmpeg/ios`
-> Fetching podspec for `flutter_isolate` from `.symlinks/plugins/flutter_isolate/ios`
-> Fetching podspec for `flutter_keyboard_visibility` from `.symlinks/plugins/flutter_keyboard_visibility/ios`
-> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
-> Fetching podspec for `flutter_mailer` from `.symlinks/plugins/flutter_mailer/ios`
-> Fetching podspec for `flutter_native_splash` from `.symlinks/plugins/flutter_native_splash/ios`
-> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
-> Fetching podspec for `google_sign_in_ios` from `.symlinks/plugins/google_sign_in_ios/ios`
-> Fetching podspec for `heic_to_jpg` from `.symlinks/plugins/heic_to_jpg/ios`
-> Fetching podspec for `image_cropper` from `.symlinks/plugins/image_cropper/ios`
-> Fetching podspec for `in_app_review` from `.symlinks/plugins/in_app_review/ios`
-> Fetching podspec for `integration_test` from `.symlinks/plugins/integration_test/ios`
-> Fetching podspec for `light_compressor` from `.symlinks/plugins/light_compressor/ios`
-> Fetching podspec for `media_picker` from `.symlinks/plugins/media_picker/ios`
-> Fetching podspec for `open_mail_app` from `.symlinks/plugins/open_mail_app/ios`
-> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
-> Fetching podspec for `path_provider_foundation` from `.symlinks/plugins/path_provider_foundation/ios`
-> Fetching podspec for `patrol` from `.symlinks/plugins/patrol/ios`
[!] No podspec found for `patrol` in `.symlinks/plugins/patrol/ios`

/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:997:in `fetch_external_source'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:976:in `block (2 levels) in fetch_external_sources'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:975:in `each'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:975:in `block in fetch_external_sources'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:974:in `fetch_external_sources'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.14.3/libexec/bin/pod:25:in `<main>'
```

</details>

### Patrol version

patrol: ^3.5.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.6.4
Android: 
• Program adb found in /opt/homebrew/bin/adb
• Env var $ANDROID_HOME set to /Users/artemmoiseev/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64 (Rosetta), locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] Connected device (5 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by Noxiver** [comment]
<img width="368" alt="image" src="https://github.com/leancodepl/patrol/assets/38157188/4ade7a84-2f49-41ad-bf96-a7cf498cb7ec">

**Comment by Noxiver** [comment]
Idk how, but it error disappear  after reinstalling project and all dependences
