### ISSUE TITLE
Error: Failed to read patrol version. Make sure you have patrol dependency in your pubspec.yaml file

### ISSUE THREAD

**Issue by shrijanRegmi** [leancodepl/patrol#2127]
### Steps to reproduce

1. Add latest dependencies (patrol and patrol_filders) in pubspec.yaml
2. Complete Android and iOS setup
3. Create folder integration_test
4. Create file app_test.dart inside integration_test
5. Create a basic UI test using patrol
6. Run patrol test -t integration_test/app_test.dart

### Actual results

Getting error `Error: Failed to read patrol version. Make sure you have patrol dependency in your pubspec.yaml file`

### Logs

<details>
<summary>Logs</summary>

```
Unhandled exception:
Error: Failed to read patrol version. Make sure you have patrol dependency in your pubspec.yaml file
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      CompatibilityChecker.checkVersionsCompatibility.<anonymous closure>.<anonymous closure> (package:patrol_cli/src/compatibility_checker.dart:64:13)
#2      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#3      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#4      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#5      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#6      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#7      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#8      _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#9      _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
#10     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#11     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#12     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#13     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#14     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#15     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#16     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#17     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#18     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
#19     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#20     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#21     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#24     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#25     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#26     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#27     _StreamController.close (dart:async/stream_controller.dart:640:5)
#28     _Socket._onData (dart:io-patch/socket_patch.dart:2454:21)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#33     _StreamController._add (dart:async/stream_controller.dart:658:7)
#34     _StreamController.add (dart:async/stream_controller.dart:606:5)
#35     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1943:35)
#36     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1372:18)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#40     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

### Patrol version

patrol: ^3.5.2
patrol_finders: ^2.0.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.4
Android: 
• Program adb found in /Users/shrijanregmi/Library/Android/sdk/platform-tools//adb
• Env var $ANDROID_HOME set to /Users/shrijanregmi/Library/Android/sdk/:/Users/shrijanregmi/Projects/Flutter/sdk/bin/:/Users/shrijanregmi/fvm/versions/3.13.6/bin/:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/shrijanregmi/fvm/versions/3.13.6/bin/:/Users/shrijanregmi/google-cloud-sdk/bin:/Users/shrijanregmi/.nvm/versions/node/v18.16.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/shrijanregmi/Library/Android/sdk/platform-tools/:/Users/shrijanregmi/Projects/Flutter/sdk/bin/:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Users/shrijanregmi/.pub-cache/bin
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.0, on macOS 14.2.1 23C71 darwin-arm64, locale en-NP)
    ! Warning: `flutter` on your path resolves to /Users/shrijanregmi/Projects/Flutter/sdk/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/shrijanregmi/fvm/versions/3.16.0. Consider adding /Users/shrijanregmi/fvm/versions/3.16.0/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/shrijanregmi/fvm/versions/3.16.0. Consider adding /Users/shrijanregmi/fvm/versions/3.16.0/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Shrijan’s iPhone . Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by shrijanRegmi** [comment]
> Hi, could you confirm that you're running `patrol test -t integration_test/app_test.dart` command inside flutter root directory?

Yes, I can confirm that I am inside flutter root directory.

**Comment by piotruela** [comment]
Hi @shrijanRegmi. Can you please run the `flutter --suppress-analytics --no-version-check pub deps --style=list` command in your project root directory and paste here the output of this command?
