### ISSUE TITLE
Patrol Build failing when running on release mode in ios 

### ISSUE THREAD

**Issue by AlviaNabil** [leancodepl/patrol#2135]
### Steps to reproduce

1. Run an app on Flutter 3.16
2. Make sure it has multiple flavors
3. Run the patrol test in release mode on ios physical device
4. Added `TREE_SHAKE_ICONS = false` in RunnerUITests

### Actual results

When I try to run the tests on ios physical device it fails to build the test apk. It works fine on android device. 

### Logs

<details>
<summary>Logs</summary>

```
 error: This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
          - file:///Users/user_name/.pub-cache/hosted/pub.dev/json_theme-6.4.0/lib/src/codec/theme_decoder.dart:5473:16
        Target release_ios_bundle_flutter_assets failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
        Failed to package /Users/user_name/Developments/work/app.
        note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'Firebase Setup' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
        note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        ** TEST BUILD FAILED **
        
✗ Failed to build app with entrypoint test_bundle.dart for iOS device (xcodebuild exited with code 65) (166.2s)
Error: xcodebuild exited with code 65

#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:136:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:76:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/user_name/.pub-cache/hosted/pub.dev/patrol_cli-2.6.4/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:136:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:76:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/user_name/.pub-cache/hosted/pub.dev/patrol_cli-2.6.4/bin/main.dart:6:20)
<asynchronous suspension>

```

</details>

### Patrol version

patrol: ^3.4.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.4
Android: 
• Program adb found in /Users/user_name/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to ~/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.5, on macOS 14.3.1 23D60 darwin-x64, locale en-GB)
    ! Warning: `flutter` on your path resolves to /Users/user_name/Developments/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/user_name/developments/flutter.
      Consider adding /Users/user_name/developments/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/user_name/Developments/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/user_name/developments/flutter. Consider
      adding /Users/user_name/developments/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by piotruela** [comment]
Hi @AlviaNabil, I tried to reproduce the issue in [patrol example project](https://github.com/leancodepl/patrol/tree/master/packages/patrol/example) and I couldn't see the issue you described. Looking to the logs you provided it seems that the during the build it tries to shake icon tree but it cannot because `json_theme` package does not allow to do it. So please provide the following information to let us continue the investigation:
- Are you sure that `TREE_SHAKE_ICONS` is set to false for both `Runner` and `RunnerUITests` when you run the `patrol test` command?
- Does your ios app runs normally in release mode on the device when you set `TREE_SHAKE_ICONS` to false?
- Does `patrol test` works on Simulator when you set `TREE_SHAKE_ICONS` to false?
You might try to reproduce the issue in patrol example project or provide a link to github repository in which you encountered this. This would make it much easier to solve the problem : )
