### ISSUE TITLE
disableCellular() failed with Invalid response: 400 The operation

### ISSUE THREAD

**Issue by creatorpiyush** [leancodepl/patrol#2179]
### Steps to reproduce

1. Clone https://github.com/leancodepl/patrol.git
2. Run iOS simulator(any)
3. in patrol/dev/e2e_app run: `patrol test --target=integration_test/service_cellular_test.dart --device="iPhone 15" --verbose`

### Actual results

disableCellular() and other services should work and not return 400

### Logs

<details>
<summary>Logs</summary>

```
((passed) is true) failed - ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: NativeAutomatorClientException:
disableCellular() failed with Invalid response: 400 The operation
couldnât be completed. (patrol.PatrolError error 3.)

When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:226:7)
<asynchronous suspension>
#1      main.<anonymous closure> (file:///Users/piyushanand/github_clones/patrol/dev/e2e_app/integration_test/service_cellular_test.dart:7:5)
<asynchronous suspension>
#2      patrolTest.<anonymous closure> (package:patrol/src/common.dart:134:7)
<asynchronous suspension>
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:804:12)
<asynchronous suspension>

The test description was:
  disables and enables cellular twice
═════════════════════════════════════════════════════════════════
```

</details>

### Patrol version

patrol: path: ../../packages/patrol (Master)
and also checked with patrol: 3.6.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.16.9 • channel [user-branch]
Android: 
• Program adb found in /Users/piyushanand/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/piyushanand/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

**Comment by bartekpacia** [comment]
https://github.com/leancodepl/patrol/issues/396

not related but worth to keep in mind

**Comment by Kendru98** [comment]
Already added in docs https://patrol.leancode.co/documentation/native/feature-parity
