### ISSUE TITLE
 patrol 3.6.1 Stuck at app:connectedDebugAndroidTest Failed 

### ISSUE THREAD

**Issue by alifaalfarizi** [leancodepl/patrol#2187]
### Steps to reproduce

1. Clone https://github.com/alifaalfarizi/test_patrol
2. Start Pixel_3a_API_33 (Emulator)
3. Run patrol test `patrol test -t integration_test/example_test.dart --verbose`

### Actual results

![Capture](https://github.com/leancodepl/patrol/assets/134401356/c612d93d-69c2-48a3-8735-b6af7f405745)

I encountered an issue while initializing the Patrol project. Upon initialization, I received the following error message: app:connectedDebugAndroidTest. Upon further inspection, the details of this error appeared to be empty.

Steps Taken:

1. Initially, I attempted to initialize the project using the Patrol. following the guidelines outlined in https://patrol.leancode.co/getting-started.
2. The error `app:connectedDebugAndroidTest` persisted.
3. I created a new flutter project template https://github.com/alifaalfarizi/test_patrol but the error output still same.

### Logs

<details>
<summary>Logs</summary>

```
Verbose mode enabled. More logs will be printed.
$ flutter --suppress-analytics --no-version-check pub deps --style=list
Received 1 test target(s)
Received test target: D:\Project\latihan\test patrol\test_patrol\integration_test/example_test.dart
Generated entrypoint D:\Project\latihan\test patrol\test_patrol\integration_test\test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check --suppress-analytics devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on
Received device: emulator-5554
Received 10 --dart-define(s) (0 custom, 10 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.example.myapp
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.MyApp
Received internal --dart-define: PATROL_MACOS_APP_BUNDLE_ID=com.example.macos.MyApp    
Received internal --dart-define: PATROL_ANDROID_APP_NAME=My App
Received internal --dart-define: PATROL_IOS_APP_NAME=My App
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_TEST_SERVER_PORT=8081
Received internal --dart-define: PATROL_APP_SERVER_PORT=8082
• Building apk with entrypoint test_bundle.dart...
$ .\gradlew.bat :app:assembleDebug -Ptarget=D:\Project\latihan\test patrol\test_patrol\integration_test\test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUubXlhcHA=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuTXlBcHA=,UEFUUk9MX01BQ09TX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUubWFjb3MuTXlBcHA=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9TXkgQXBw,UEFUUk9MX0lPU19BUFBfTkFNRT1NeSBBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==,UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy -Papp-server-port=8082 -Ptest-server-port=8081
        : > Task :gradle:compileJava NO-SOURCE
        : > Task :gradle:compileGroovy UP-TO-DATE
        : > Task :gradle:pluginDescriptors UP-TO-DATE
        : > Task :gradle:processResources UP-TO-DATE
        : > Task :gradle:classes UP-TO-DATE
        : > Task :gradle:jar UP-TO-DATE
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (7.3.0) was tested up to compileSdk = 33
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 34
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug UP-TO-DATE
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :app:processDebugJavaRes NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :patrol:bundleLibResDebug UP-TO-DATE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToDirDebug UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :app:mergeLibDexDebug UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:mergeDebugJavaResource UP-TO-DATE
        : > Task :app:dexBuilderDebug UP-TO-DATE
        : > Task :app:mergeProjectDexDebug UP-TO-DATE
        : > Task :app:packageDebug UP-TO-DATE
        : > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebug
        : 
        : BUILD SUCCESSFUL in 2s
        : 60 actionable tasks: 5 executed, 55 up-to-date
$ .\gradlew.bat :app:assembleDebugAndroidTest -Ptarget=D:\Project\latihan\test patrol\test_patrol\integration_test\test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUubXlhcHA=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuTXlBcHA=,UEFUUk9MX01BQ09TX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUubWFjb3MuTXlBcHA=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9TXkgQXBw,UEFUUk9MX0lPU19BUFBfTkFNRT1NeSBBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==,UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy -Papp-server-port=8082 -Ptest-server-port=8081
        : > Task :gradle:compileJava NO-SOURCE
        : > Task :gradle:compileGroovy UP-TO-DATE
        : > Task :gradle:pluginDescriptors UP-TO-DATE
        : > Task :gradle:processResources UP-TO-DATE
        : > Task :gradle:classes UP-TO-DATE
        : > Task :gradle:jar UP-TO-DATE
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (7.3.0) was tested up to compileSdk = 33
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 34
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:preDebugAndroidTestBuild SKIPPED
        : > Task :app:compileDebugAndroidTestAidl NO-SOURCE
        : > Task :app:processDebugAndroidTestManifest UP-TO-DATE
        : > Task :app:compileDebugAndroidTestRenderscript NO-SOURCE
        : > Task :app:generateDebugAndroidTestBuildConfig UP-TO-DATE
        : > Task :app:checkDebugAndroidTestAarMetadata UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResValues UP-TO-DATE
        : > Task :app:mapDebugAndroidTestSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResources UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestResources UP-TO-DATE
        : > Task :app:processDebugAndroidTestResources UP-TO-DATE
        : > Task :app:javaPreCompileDebugAndroidTest UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestShaders UP-TO-DATE
        : > Task :app:compileDebugAndroidTestShaders NO-SOURCE
        : > Task :app:generateDebugAndroidTestAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:compressDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:processDebugAndroidTestJavaRes NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :patrol:bundleLibResDebug UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestNativeLibs NO-SOURCE
        : > Task :app:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugAndroidTestFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebugAndroidTest UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :patrol:bundleLibRuntimeToDirDebug UP-TO-DATE
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:bundleDebugClassesToCompileJar UP-TO-DATE
        : > Task :app:compileDebugAndroidTestKotlin NO-SOURCE
        : > Task :app:compileDebugAndroidTestJavaWithJavac
        : > Task :app:mergeLibDexDebugAndroidTest UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJavaResource
        : > Task :app:dexBuilderDebugAndroidTest
        : > Task :app:validateSigningDebugAndroidTest UP-TO-DATE
        : > Task :app:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
        : > Task :app:mergeProjectDexDebugAndroidTest
        : > Task :app:packageDebugAndroidTest
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebugAndroidTest
        : 
        : BUILD SUCCESSFUL in 1s
        : 62 actionable tasks: 6 executed, 56 up-to-date
✓ Completed building apk with entrypoint test_bundle.dart (5.2s)
Will uninstall apps before running tests
Uninstalling com.example.myapp from sdk gphone64 x86 64
Uninstalling com.example.myapp.test from sdk gphone64 x86 64
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
$ .\gradlew.bat :app:connectedDebugAndroidTest -Ptarget=D:\Project\latihan\test patrol\test_patrol\integration_test\test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUubXlhcHA=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuTXlBcHA=,UEFUUk9MX01BQ09TX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUubWFjb3MuTXlBcHA=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9TXkgQXBw,UEFUUk9MX0lPU19BUFBfTkFNRT1NeSBBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==,UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy -Papp-server-port=8082 -Ptest-server-port=8081
        : > Task :gradle:compileJava NO-SOURCE
        : > Task :gradle:compileGroovy UP-TO-DATE
        : > Task :gradle:pluginDescriptors UP-TO-DATE
        : > Task :gradle:processResources UP-TO-DATE
        : > Task :gradle:classes UP-TO-DATE
        : > Task :gradle:jar UP-TO-DATE
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (7.3.0) was tested up to compileSdk = 33
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 34
        : > Task :app:compileFlutterBuildDebug UP-TO-DATE
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:preDebugAndroidTestBuild SKIPPED
        : > Task :app:compileDebugAndroidTestAidl NO-SOURCE
        : > Task :app:processDebugAndroidTestManifest UP-TO-DATE
        : > Task :app:compileDebugAndroidTestRenderscript NO-SOURCE
        : > Task :app:generateDebugAndroidTestBuildConfig UP-TO-DATE
        : > Task :app:checkDebugAndroidTestAarMetadata UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResValues UP-TO-DATE
        : > Task :app:mapDebugAndroidTestSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResources UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestResources UP-TO-DATE
        : > Task :app:processDebugAndroidTestResources UP-TO-DATE
        : > Task :app:javaPreCompileDebugAndroidTest UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :app:processDebugJavaRes NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :patrol:bundleLibResDebug UP-TO-DATE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToDirDebug UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :app:mergeLibDexDebug UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestShaders UP-TO-DATE
        : > Task :app:compileDebugAndroidTestShaders NO-SOURCE
        : > Task :app:generateDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:compressDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:processDebugAndroidTestJavaRes NO-SOURCE
        : > Task :app:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestNativeLibs NO-SOURCE
        : > Task :app:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugAndroidTestFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebugAndroidTest UP-TO-DATE
        : > Task :app:mergeLibDexDebugAndroidTest UP-TO-DATE
        : > Task :app:validateSigningDebugAndroidTest UP-TO-DATE
        : > Task :app:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:bundleDebugClassesToCompileJar UP-TO-DATE
        : > Task :app:compileDebugAndroidTestKotlin NO-SOURCE
        : > Task :app:compileDebugAndroidTestJavaWithJavac UP-TO-DATE
        : > Task :app:mergeDebugJavaResource UP-TO-DATE
        : > Task :app:dexBuilderDebug UP-TO-DATE
        : > Task :app:mergeProjectDexDebug UP-TO-DATE
        : > Task :app:packageDebug UP-TO-DATE
        : > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJavaResource UP-TO-DATE
        : > Task :app:dexBuilderDebugAndroidTest UP-TO-DATE
        : > Task :app:mergeProjectDexDebugAndroidTest UP-TO-DATE
        : > Task :app:packageDebugAndroidTest UP-TO-DATE
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : 
        : > Task :app:connectedDebugAndroidTest
        : Starting 0 tests on Pixel_3a_API_33(AVD) - 13
        Instrumentation did not complete:
        Instrumentation code: 0
        Instrumentation result bundle: 
        : 

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:connectedDebugAndroidTest'.
        See the report at: file:///D:/Project/latihan/test%20patrol/test_patrol/build/app/reports/androidTests/connected/index.html    

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 12s
        : > Task :app:connectedDebugAndroidTest FAILED
        : 85 actionable tasks: 5 executed, 80 up-to-date
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (12.9s)
Exception: Gradle test execution failed with code 1
#0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:140:9)
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:106:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:323:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:215:23)
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:347:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:291:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///C:/Users/XPERTSPEDIA/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-2.7.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Uninstalling com.example.myapp from sdk gphone64 x86 64
Uninstalling com.example.myapp.test from sdk gphone64 x86 64
```

</details>

### Patrol version

 patrol: ^3.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.19.6 • channel stable
Android:
• Program adb found in C:\Users\XPERTSPEDIA\Downloads\scrcpy-win64-v1.24\adb.exe
• Env var $ANDROID_HOME set to C:\Users\XPERTSPEDIA\AppData\Local\Android\Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output **I am using VS code to run the flutter app**</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.4291], locale en-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2021.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.88.1)
[√] Connected device (4 available)
[√] Network resources
```

</details>

**Comment by Kendru98** [comment]
Hi, I found a mistake in your config. This line was wrong: 
![image](https://github.com/leancodepl/patrol/assets/82384301/a37aed3c-3532-40f3-bbc8-96eb233c3ede)
Your android manifest is not using `android:name="io.flutter.embedding.android.FlutterActivity"` so there should be  `instrumentation.setUp(MainActivity.class);` as on screenshot. After this change, it works for me :D

**Comment by alifaalfarizi** [comment]
Thanks! @Kendru98 .

The problem has been solved. For anyone who has the same problem while initializing the project, you can try forking or cloning https://github.com/alifaalfarizi/test_patrol and test it in your ends (to test if you have a problem outside project's code itself).
![Capture](https://github.com/leancodepl/patrol/assets/134401356/6f023fad-dbae-441c-8f14-aeb274dc699c)

If you have problem when using flutter flavor, make sure that you are using correct package name. Using package name app in your device, you can check what package name that is installed while you run your patrol test.
