### ISSUE TITLE
broken test_bundle generation

### ISSUE THREAD

**Issue by AlexanderThiele** [leancodepl/patrol#2194]
### Steps to reproduce

1. just followed the getting started guide on https://patrol.leancode.co/getting-started
2. implemented in an existing project.
3. broken test_bundle

### Actual results

get the error:
Failed to build app with entrypoint test_bundle.dart for iOS simulator

when checking the test_bundle file, i can see that there are dart issues. Error is `Target of URI doesn't exist: 'Users/alex/.../mobile-app/investment_integration_tests/tests/partrol_test/patrol_test.dart'.`

2 errors with the import statement: import 'Users/alex./.../mobile-app/investment_integration_tests/tests/partrol_test/patrol_test.dart' as Users__alexanderthiele__projects__mobile-app__investment_integration_tests__tests__partrol_test__patrol_test;
* the import path starts without a slash /. so it thinks, it's a relative path.
* the as statement is not correct because there is a dash inside the name (the project itself has a dash inside the name. i know it's not a great way to name a project but the project is already 5 years old and still exists so far and never had an issue with the name)

### Logs

<details>
<summary>Logs</summary>

```
patrol test -t tests/partrol_test/patrol_test.dart --verbose --device 18025B9A-B8A5-4B69-915A-9C992D587830
Verbose mode enabled. More logs will be printed.
$ flutter --suppress-analytics --no-version-check pub deps --style=list
Received 1 test target(s)
Received test target: /Users/alex/projects/.../mobile-app/investment_integration_tests/tests/partrol_test/patrol_test.dart
Generated entrypoint /Users/alex/projects/.../mobile-app/investment_integration_tests/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check --suppress-analytics devices --machine
Received 1 device(s) to run on
Received device: iPad Pro (12.9-inch) (6th generation)
Received 8 --dart-define(s) (0 custom, 8 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_BUNDLE_ID=de.alex.test
Received internal --dart-define: PATROL_ANDROID_APP_NAME=My App
Received internal --dart-define: PATROL_IOS_APP_NAME=My App
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_TEST_SERVER_PORT=8081
Received internal --dart-define: PATROL_APP_SERVER_PORT=8082
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
$ flutter build ios --no-version-check --suppress-analytics --config-only --no-codesign --debug --simulator --target /Users/alex/projects/.../mobile-app/investment_integration_tests/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_BUNDLE_ID=de.alex.test --dart-define PATROL_ANDROID_APP_NAME=My App --dart-define PATROL_IOS_APP_NAME=My App --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true --dart-define PATROL_TEST_SERVER_PORT=8081 --dart-define PATROL_APP_SERVER_PORT=8082
        Application not configured for iOS
✗ Failed to build app with entrypoint test_bundle.dart for iOS simulator (`flutter  build ios` exited with code 1) (0.4s)
Error: `flutter  build ios` exited with code 1
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:110:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:76:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:279:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:213:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:347:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:291:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/alexanderthiele/.pub-cache/hosted/pub.dev/patrol_cli-2.7.0/bin/main.dart:6:20)
<asynchronous suspension>

```

</details>

### Patrol version

patrol: ^3.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.19.4 • channel stable
Android: 
• Program adb found in /Users/alex/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME is not set. (See the link: https://developer.android.com/tools/variables#set)
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/alex/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/alex/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.0.3
    • Dart plugin version 223.8888

[✓] Connected device (4 available)
    • Pixel 7 Pro (mobile)                           • 28101FDH300CR7                       • android-arm64  • Android 14 (API 34)
    • iPad Pro (12.9-inch) (6th generation) (mobile) • 18025B9A-B8A5-4B69-915A-9C992D587830 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 124.0.6367.207
    ! Error: Browsing on the local area network for iPad Pro von Thorben. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by AlexanderThiele** [comment]
and #2162
