### ISSUE TITLE
Failed to call finalizer: AdbExecutableNotFound: No such file or directory AdbExecutableNotFound: No such file or directory

### ISSUE THREAD

**Issue by abdullahehab** [leancodepl/patrol#2245]
### Steps to reproduce

I have installed `patrol: ^3.9.0` and when running a test the following message is displayed and the test fails.

<img width="837" alt="Screenshot 2024-06-27 at 12 36 42 PM" src="https://github.com/leancodepl/patrol/assets/30800958/75345304-ac07-41cf-917f-2d55f3a0dde4">
\

### Actual results

Test is passed!

### Logs

<details>
<summary>Logs</summary>

```


Failed to call finalizer: AdbExecutableNotFound: No such file or directory
AdbExecutableNotFound: No such file or directory
#0      AdbInternals.ensureServerRunning (package:adb/src/internals.dart:38:7)
<asynchronous suspension>
#1      Adb.uninstall (package:adb/src/adb.dart:77:5)
<asynchronous suspension>
#2      AndroidTestBackend.uninstall (package:patrol_cli/src/android/android_test_backend.dart:147:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:345:9)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:228:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:348:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:292:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///Users/apple/.pub-cache/hosted/pub.dev/patrol_cli-2.8.1/bin/main.dart:6:20)
<asynchronous suspension>

```

</details>

### Patrol version

patrol: ^3.9.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.8.1
Flutter command: flutter 
  Flutter 3.22.2 • channel stable
Android: 
• Program adb found in /Users/apple/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/apple/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.3.1 23D60 darwin-arm64, locale
    en-EG)
    • Flutter version 3.22.2 on channel stable at /Users/apple/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone (mobile)                 • 00008101-00096D880141001E • ios
      • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Kendru98** [comment]
Please also look at these old issues:

- https://github.com/leancodepl/patrol/issues/1106
- https://github.com/leancodepl/patrol/issues/1153
And you can also check our discord, someone can help / have similar issue there but looks like something wrong with config. https://discord.com/invite/ukBK5t4EZg
