### ISSUE TITLE
Unable to run test on Apple Silicon Mac - Simulator Build Fails on simulator iPhone 15 Pro Max iOS 17.5

### ISSUE THREAD

**Issue by bash-bigpay** [leancodepl/patrol#2257]
### Steps to reproduce

1. Build project on an Apple Silicon Mac.
2. Attempt to run tests on an iPhone 15 Pro Max simulator running iOS 17.5.
3. Observe the test failures.
4. Additionally, run tests on an iPhone 15 simulator running iOS 17.5 and note the errors at the end even tho all test passes

### Actual results

We are encountering issues when running tests on an Apple Silicon Mac iOS simulators. 

Specifically:

- On an Intel Mac, all tests run successfully.
- On an Apple Silicon Mac:
      -     Tests fail to build on an iPhone 15 Pro Max simulator running iOS 17.5.
      -     Tests on an iPhone 15 simulator running iOS 17.5 complete but end with errors even tho all test passes.
- This issue seems to be exclusive to Apple Silicon Macs, as the Intel Mac does not exhibit these problems as observed.

### Logs

<details>
<summary>Logs</summary>

```
• Running app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 15 Pro Max...
$ xcodebuild -showsdks -json
Assuming SDK version 17.5 for iphonesimulator
Looking for .xctestrun matching mobile_*iphonesimulator17.5*.xctestrun at /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_integ/Build/Products
Found 1 match(es), the first one will be used
Found /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_integ/Build/Products/mobile_PatrolTestPlan_iphonesimulator17.5-arm64-x86_64.xctestrun
$ xcodebuild test-without-building -xctestrun /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_integ/Build/Products/mobile_PatrolTestPlan_iphonesimulator17.5-arm64-x86_64.xctestrun -only-testing RunnerUITests/RunnerUITests -destination platform=iOS Simulator,name=iPhone 15 Pro Max -destination-timeout 1 -resultBundlePath /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_results_1720590073836.xcresult
        Command line invocation:
            /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_integ/Build/Products/mobile_PatrolTestPlan_iphonesimulator17.5-arm64-x86_64.xctestrun -only-testing RunnerUITests/RunnerUITests -destination "platform=iOS Simulator,name=iPhone 15 Pro Max" -destination-timeout 1 -resultBundlePath /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_results_1720590073836.xcresult

        User defaults from command line:
            IDEBuildOperationResultBundlePath = /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_results_1720590073836.xcresult
            IDEPackageSupportUseBuiltinSCM = YES

        Writing result bundle at path:
                /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_results_1720590073836.xcresult

        --- xcodebuild: WARNING: Using the first of multiple matching destinations:
        { platform:macOS, arch:arm64e, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:arm64, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:x86_64, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:arm64e, variant:Mac Catalyst, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:arm64, variant:Mac Catalyst, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:x86_64, variant:Mac Catalyst, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:arm64e, variant:DriverKit, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:arm64, variant:DriverKit, id:00006000-000A08EA0251801E, name:My Mac }
        { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-000A08EA0251801E, name:My Mac }
        { platform:iOS, arch:arm64e, id:00008130-00092D993ED2001C, name:Bashcious’s iPhone }
        { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
        { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
        { platform:macOS, name:Any Mac }
        { platform:macOS, variant:Mac Catalyst, name:Any Mac }
        { platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
        { platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }
        { platform:visionOS, id:dvtdevice-DVTiOSDevicePlaceholder-xros:placeholder, name:Any visionOS Device }
        { platform:visionOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-xrsimulator:placeholder, name:Any visionOS Simulator Device }
        { platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
        { platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Any watchOS Simulator Device }
        { platform:iOS Simulator, id:1501AEA9-B069-4AFC-822F-52AF29F834A5, OS:16.2, name:iPad (10th generation) }
        { platform:iOS Simulator, id:1501AEA9-B069-4AFC-822F-52AF29F834A5, OS:16.2, name:iPad (10th generation) }
        { platform:iOS Simulator, id:1F8C85C9-D264-4062-BD72-3570BF4584DE, OS:17.0.1, name:iPad (10th generation) }
        { platform:iOS Simulator, id:1F8C85C9-D264-4062-BD72-3570BF4584DE, OS:17.0.1, name:iPad (10th generation) }
        { platform:iOS Simulator, id:C284263A-0F5A-400F-8809-76EFD98EC8B0, OS:17.2, name:iPad (10th generation) }
        { platform:iOS Simulator, id:C284263A-0F5A-400F-8809-76EFD98EC8B0, OS:17.2, name:iPad (10th generation) }
        { platform:iOS Simulator, id:A0FE1131-8E79-426D-AF08-DE4164650343, OS:17.4, name:iPad (10th generation) }
        { platform:iOS Simulator, id:A0FE1131-8E79-426D-AF08-DE4164650343, OS:17.4, name:iPad (10th generation) }
        { platform:iOS Simulator, id:DAA4D7B6-C43C-45DB-B219-DFBECB56FCEF, OS:17.5, name:iPad (10th generation) }
        { platform:iOS Simulator, id:DAA4D7B6-C43C-45DB-B219-DFBECB56FCEF, OS:17.5, name:iPad (10th generation) }
        { platform:iOS Simulator, id:52EFE559-CF84-4B09-98CB-30B4DD1B75D5, OS:16.2, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:52EFE559-CF84-4B09-98CB-30B4DD1B75D5, OS:16.2, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:87DE896F-D426-4495-B763-B8CE8DCA3B43, OS:17.0.1, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:87DE896F-D426-4495-B763-B8CE8DCA3B43, OS:17.0.1, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:E2ECE220-D15E-4FF7-A160-839EDD522B5A, OS:17.2, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:E2ECE220-D15E-4FF7-A160-839EDD522B5A, OS:17.2, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:52239E87-0581-4D13-9A0B-2C963A83765C, OS:17.4, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:52239E87-0581-4D13-9A0B-2C963A83765C, OS:17.4, name:iPad Air (5th generation) }
        { platform:iOS Simulator, id:FC0EDEE9-4C29-4234-8119-E9B54761BC05, OS:17.4, name:iPad Air 11-inch (M2) }
        { platform:iOS Simulator, id:FC0EDEE9-4C29-4234-8119-E9B54761BC05, OS:17.4, name:iPad Air 11-inch (M2) }
        { platform:iOS Simulator, id:A42104AE-AD74-48E2-977B-D7E4BD7C11AE, OS:17.5, name:iPad Air 11-inch (M2) }
        { platform:iOS Simulator, id:A42104AE-AD74-48E2-977B-D7E4BD7C11AE, OS:17.5, name:iPad Air 11-inch (M2) }
        { platform:iOS Simulator, id:CDE27CF4-10E3-4549-8500-D3438C6B9C44, OS:17.4, name:iPad Air 13-inch (M2) }
        { platform:iOS Simulator, id:CDE27CF4-10E3-4549-8500-D3438C6B9C44, OS:17.4, name:iPad Air 13-inch (M2) }
        { platform:iOS Simulator, id:A4B80856-AD82-4413-9A01-55C9504C4F36, OS:17.5, name:iPad Air 13-inch (M2) }
        { platform:iOS Simulator, id:A4B80856-AD82-4413-9A01-55C9504C4F36, OS:17.5, name:iPad Air 13-inch (M2) }
        { platform:iOS Simulator, id:1A4AEC21-920D-44B7-9B7F-5D674E8009CF, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:1A4AEC21-920D-44B7-9B7F-5D674E8009CF, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:5328B520-6937-43DE-AB18-79C78D78B23A, OS:17.0.1, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:5328B520-6937-43DE-AB18-79C78D78B23A, OS:17.0.1, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:A72F0C01-9205-4C72-BA43-946ABEF129A0, OS:17.2, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:A72F0C01-9205-4C72-BA43-946ABEF129A0, OS:17.2, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:2A255AA0-7B34-4D7A-B1B1-8F642FF09E90, OS:17.4, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:2A255AA0-7B34-4D7A-B1B1-8F642FF09E90, OS:17.4, name:iPad Pro (11-inch) (4th generation) }
        { platform:iOS Simulator, id:CA68C577-3356-4230-AF11-0F55982E4FC3, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:CA68C577-3356-4230-AF11-0F55982E4FC3, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:2C6F9ED9-EE0D-4E5E-B3D4-56BCE2FA39AF, OS:17.0.1, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:2C6F9ED9-EE0D-4E5E-B3D4-56BCE2FA39AF, OS:17.0.1, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:774B9286-6CDE-4202-B827-F9F01192F675, OS:17.2, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:774B9286-6CDE-4202-B827-F9F01192F675, OS:17.2, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:C9CEEBFB-27B8-48E6-AC88-6544A97184DD, OS:17.4, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:C9CEEBFB-27B8-48E6-AC88-6544A97184DD, OS:17.4, name:iPad Pro (12.9-inch) (6th generation) }
        { platform:iOS Simulator, id:4BD58500-623C-49C6-B224-D8149FDC546B, OS:17.4, name:iPad Pro 11-inch (M4) }
        { platform:iOS Simulator, id:4BD58500-623C-49C6-B224-D8149FDC546B, OS:17.4, name:iPad Pro 11-inch (M4) }
        { platform:iOS Simulator, id:0A51D065-04B7-40DB-A880-0E850C715925, OS:17.5, name:iPad Pro 11-inch (M4) }
        { platform:iOS Simulator, id:0A51D065-04B7-40DB-A880-0E850C715925, OS:17.5, name:iPad Pro 11-inch (M4) }
        { platform:iOS Simulator, id:CFD34336-F859-490B-AFB3-B2569E693C5E, OS:17.4, name:iPad Pro 13-inch (M4) }
        { platform:iOS Simulator, id:CFD34336-F859-490B-AFB3-B2569E693C5E, OS:17.4, name:iPad Pro 13-inch (M4) }
        { platform:iOS Simulator, id:4D65FDF8-95D9-4407-8D3A-84EEB72C45D4, OS:17.5, name:iPad Pro 13-inch (M4) }
        { platform:iOS Simulator, id:4D65FDF8-95D9-4407-8D3A-84EEB72C45D4, OS:17.5, name:iPad Pro 13-inch (M4) }
        { platform:iOS Simulator, id:7967926D-A748-46ED-89B4-0337646238A1, OS:16.2, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:7967926D-A748-46ED-89B4-0337646238A1, OS:16.2, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:DBF24E9E-CF03-4B30-9612-9CEFC3CE8160, OS:17.0.1, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:DBF24E9E-CF03-4B30-9612-9CEFC3CE8160, OS:17.0.1, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:D6F1464A-38BA-4767-AC48-597314CC75AF, OS:17.2, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:D6F1464A-38BA-4767-AC48-597314CC75AF, OS:17.2, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:A24696C7-E91E-447F-9BF7-170E29BC2E81, OS:17.4, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:A24696C7-E91E-447F-9BF7-170E29BC2E81, OS:17.4, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:53B22F98-A3BA-408C-9AB0-01DFDEB22952, OS:17.5, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:53B22F98-A3BA-408C-9AB0-01DFDEB22952, OS:17.5, name:iPad mini (6th generation) }
        { platform:iOS Simulator, id:8E013BFE-6CA9-4B7F-8068-193422E8CEB0, OS:16.2, name:iPhone 14 }
        { platform:iOS Simulator, id:8E013BFE-6CA9-4B7F-8068-193422E8CEB0, OS:16.2, name:iPhone 14 }
        { platform:iOS Simulator, id:DE8AF112-0C92-4BA7-801C-C1BC35D35E4D, OS:16.2, name:iPhone 14 Plus }
        { platform:iOS Simulator, id:DE8AF112-0C92-4BA7-801C-C1BC35D35E4D, OS:16.2, name:iPhone 14 Plus }
        { platform:iOS Simulator, id:B6603999-25C6-4B49-8C2E-4D047D4956EA, OS:16.2, name:iPhone 14 Pro }
        { platform:iOS Simulator, id:B6603999-25C6-4B49-8C2E-4D047D4956EA, OS:16.2, name:iPhone 14 Pro }
        { platform:iOS Simulator, id:5173DFFA-8490-49D7-B9C1-AB1A6C1E82B2, OS:16.2, name:iPhone 14 Pro Max }
        { platform:iOS Simulator, id:5173DFFA-8490-49D7-B9C1-AB1A6C1E82B2, OS:16.2, name:iPhone 14 Pro Max }
        { platform:iOS Simulator, id:85736EFC-248A-4904-9A99-9ED87234A411, OS:16.2, name:iPhone 14 Pro Max }
        { platform:iOS Simulator, id:85736EFC-248A-4904-9A99-9ED87234A411, OS:16.2, name:iPhone 14 Pro Max }
        { platform:iOS Simulator, id:ABA9422A-1123-44CB-9201-72F6BB4D78C7, OS:17.2, name:iPhone 14 Pro Max }
        { platform:iOS Simulator, id:ABA9422A-1123-44CB-9201-72F6BB4D78C7, OS:17.2, name:iPhone 14 Pro Max }
        { platform:iOS Simulator, id:E5D13C55-3746-4221-BA75-CD65EDB8243D, OS:17.0.1, name:iPhone 15 }
        { platform:iOS Simulator, id:E5D13C55-3746-4221-BA75-CD65EDB8243D, OS:17.0.1, name:iPhone 15 }
        { platform:iOS Simulator, id:2FE1C928-AA1F-4847-A3E4-227F76E2CB29, OS:17.2, name:iPhone 15 }
        { platform:iOS Simulator, id:2FE1C928-AA1F-4847-A3E4-227F76E2CB29, OS:17.2, name:iPhone 15 }
        { platform:iOS Simulator, id:F5668F4A-BFB0-45F3-BC4C-D77BE8E74F1D, OS:17.4, name:iPhone 15 }
        { platform:iOS Simulator, id:F5668F4A-BFB0-45F3-BC4C-D77BE8E74F1D, OS:17.4, name:iPhone 15 }
        { platform:iOS Simulator, id:1FE73FD3-4556-412B-B7DF-E923A898368E, OS:17.5, name:iPhone 15 }
        { platform:iOS Simulator, id:1FE73FD3-4556-412B-B7DF-E923A898368E, OS:17.5, name:iPhone 15 }
        { platform:iOS Simulator, id:9B54D9AC-9FA8-4809-A447-CF47ED2A696B, OS:17.0.1, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:9B54D9AC-9FA8-4809-A447-CF47ED2A696B, OS:17.0.1, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:A6A27602-6864-4924-89D2-9B53A2A00E7B, OS:17.2, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:A6A27602-6864-4924-89D2-9B53A2A00E7B, OS:17.2, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:6E7E659B-4C4E-4C99-B3AD-0AEF921963FF, OS:17.4, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:6E7E659B-4C4E-4C99-B3AD-0AEF921963FF, OS:17.4, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:49D293E9-118F-4B2B-B54E-B6B0674A93C4, OS:17.5, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:49D293E9-118F-4B2B-B54E-B6B0674A93C4, OS:17.5, name:iPhone 15 Plus }
        { platform:iOS Simulator, id:24D918CD-61C4-4252-AF5F-6E8523CB522D, OS:17.0.1, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:24D918CD-61C4-4252-AF5F-6E8523CB522D, OS:17.0.1, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:CD90A69C-2A38-4E7D-B419-C4D5A451BD8F, OS:17.2, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:CD90A69C-2A38-4E7D-B419-C4D5A451BD8F, OS:17.2, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:1E730749-2037-444B-8B52-E4B5787FF74C, OS:17.4, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:1E730749-2037-444B-8B52-E4B5787FF74C, OS:17.4, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:3E2039CF-B43D-4120-AB38-977361AD3E7B, OS:17.5, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:3E2039CF-B43D-4120-AB38-977361AD3E7B, OS:17.5, name:iPhone 15 Pro }
        { platform:iOS Simulator, id:35E0C381-D42C-4AEF-97D6-CE0C66018EE1, OS:17.0.1, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:35E0C381-D42C-4AEF-97D6-CE0C66018EE1, OS:17.0.1, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:4A4A94A1-E18A-42C7-9F76-555FC1DFC098, OS:17.0.1, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:4A4A94A1-E18A-42C7-9F76-555FC1DFC098, OS:17.0.1, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:3C6FD29F-C883-4CE1-935B-61AAFA21A4B2, OS:17.2, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:3C6FD29F-C883-4CE1-935B-61AAFA21A4B2, OS:17.2, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:850AD8E8-56D8-48F5-88C5-4043381C5EBA, OS:17.4, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:850AD8E8-56D8-48F5-88C5-4043381C5EBA, OS:17.4, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:2A8B8B06-2B1E-490E-BCAB-0DA176EAB48F, OS:17.5, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:2A8B8B06-2B1E-490E-BCAB-0DA176EAB48F, OS:17.5, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:5DCBAA3C-D1D8-4A42-9600-947D5DD5F91C, OS:17.5, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:5DCBAA3C-D1D8-4A42-9600-947D5DD5F91C, OS:17.5, name:iPhone 15 Pro Max }
        { platform:iOS Simulator, id:AB15EE0E-FA08-4772-B9E0-3E6AD315272B, OS:16.2, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:AB15EE0E-FA08-4772-B9E0-3E6AD315272B, OS:16.2, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:1D9DB2AE-DA10-4C29-92AF-CB65DA2DDD14, OS:17.0.1, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:1D9DB2AE-DA10-4C29-92AF-CB65DA2DDD14, OS:17.0.1, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:CBF6730F-3D88-40B7-8FE9-7A1A7BDD3E84, OS:17.2, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:CBF6730F-3D88-40B7-8FE9-7A1A7BDD3E84, OS:17.2, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:32D1F5AB-2BC0-472B-9D27-0AA180866A08, OS:17.4, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:32D1F5AB-2BC0-472B-9D27-0AA180866A08, OS:17.4, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:B22C1FB6-22F0-4AA4-8165-52D0B8E351A0, OS:17.5, name:iPhone SE (3rd generation) }
        { platform:iOS Simulator, id:B22C1FB6-22F0-4AA4-8165-52D0B8E351A0, OS:17.5, name:iPhone SE (3rd generation) }
        2024-07-10 13:41:15.616 xcodebuild[4926:587190]  IDELaunchReport: b6006162cfeb520:b6006162cfeb520: Finished with error: Could not launch “RunnerUITests”
        Domain: IDELaunchErrorDomain
        Code: 20
        Recovery Suggestion: LaunchServices has returned error -10661. Please check the system logs for the underlying cause of the error.
        User Info: {
            DVTRadarComponentKey = 113722;
            IDERunOperationFailingWorker = IDELaunchServicesLauncher;
        }
        --
        The operation couldn’t be completed. (OSStatus error -10661.)
        Domain: NSOSStatusErrorDomain
        Code: -10661
        User Info: {
            "_LSFunction" = "_LSOpenStuffCallLocal";
            "_LSLine" = 4129;
        }
        --
        2024-07-10 13:41:15.616 xcodebuild[4926:587190]  IDELaunchReport: b6006162cfeb520:b6006162cfeb520: com.apple.dt.IDERunOperationWorkerFinished {
            "device_model" = "MacBookPro18,1";
            "device_osBuild" = "14.5 (23F79)";
            "device_platform" = "com.apple.platform.macosx";
            "dvt_coredevice_version" = "355.28";
            "dvt_mobiledevice_version" = "1643.120.2";
            "launchSession_schemeCommand" = Test;
            "launchSession_state" = 1;
            "launchSession_targetArch" = arm64e;
            "operation_duration_ms" = 21;
            "operation_errorCode" = 20;
            "operation_errorDomain" = IDELaunchErrorDomain;
            "operation_errorWorker" = IDELaunchServicesLauncher;
            "operation_name" = IDERunOperationWorkerGroup;
            "param_debugger_attachToExtensions" = 0;
            "param_debugger_attachToXPC" = 0;
            "param_debugger_type" = 1;
            "param_destination_isProxy" = 0;
            "param_destination_platform" = "com.apple.platform.macosx";
            "param_diag_MainThreadChecker_stopOnIssue" = 0;
            "param_diag_MallocStackLogging_enableDuringAttach" = 0;
            "param_diag_MallocStackLogging_enableForXPC" = 0;
            "param_diag_allowLocationSimulation" = 1;
            "param_diag_checker_tpc_enable" = 0;
            "param_diag_gpu_frameCapture_enable" = 3;
            "param_diag_gpu_shaderValidation_enable" = 0;
            "param_diag_gpu_validation_enable" = 1;
            "param_diag_memoryGraphOnResourceException" = 0;
            "param_diag_queueDebugging_enable" = 1;
            "param_diag_runtimeProfile_generate" = 1;
            "param_diag_sanitizer_asan_enable" = 0;
            "param_diag_sanitizer_tsan_enable" = 0;
            "param_diag_sanitizer_tsan_stopOnIssue" = 0;
            "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
            "param_diag_showNonLocalizedStrings" = 0;
            "param_diag_viewDebugging_enabled" = 0;
            "param_diag_viewDebugging_insertDylibOnLaunch" = 0;
            "param_install_style" = 2;
            "param_launcher_UID" = 2;
            "param_launcher_allowDeviceSensorReplayData" = 0;
            "param_launcher_kind" = 0;
            "param_launcher_style" = 0;
            "param_launcher_substyle" = 8192;
            "param_runnable_appExtensionHostRunMode" = 0;
            "param_runnable_productType" = "com.apple.product-type.application";
            "param_structuredConsoleMode" = 0;
            "param_testing_launchedForTesting" = 1;
            "param_testing_suppressSimulatorApp" = 1;
            "param_testing_usingCLI" = 0;
            "sdk_canonicalName" = "macosx14.5";
            "sdk_osVersion" = "14.5";
            "sdk_variant" = macos;
        }


        *** If you believe this error represents a bug, please attach the result bundle at /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_results_1720590073836.xcresult

        2024-07-10 13:41:19.753 xcodebuild[4926:587129] [MT] IDETestOperationsObserverDebug: 4.543 elapsed -- Testing started completed.
        2024-07-10 13:41:19.753 xcodebuild[4926:587129] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
        2024-07-10 13:41:19.753 xcodebuild[4926:587129] [MT] IDETestOperationsObserverDebug: 4.543 sec, +4.543 sec -- end

        Test session results, code coverage, and logs:
                /Users/bashir.isyaka/Desktop/Workspace/mobile/flutter/build/ios_results_1720590073836.xcresult

        Testing failed:
                Could not launch “RunnerUITests”
                RunnerUITests-Runner encountered an error (Failed to install or launch the test runner. (Underlying Error: Could not launch “RunnerUITests”. LaunchServices has returned error -10661. Please check the system logs for the underlying cause of the error. (Underlying Error: The operation couldn’t be completed. (OSStatus error -10661.))))

        ** TEST EXECUTE FAILED **

        Testing started
✗ Failed to execute tests of app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 15 Pro Max (xcodebuild exited with code 65) (8.9s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.execute.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:198:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.execute (package:patrol_cli/src/ios/ios_test_backend.dart:153:5)
<asynchronous suspension>
#4      TestCommand._execute (package:patrol_cli/src/commands/test.dart:336:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:228:23)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:348:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:292:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/bashir.isyaka/.pub-cache/hosted/pub.dev/patrol_cli-2.8.1/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

patrol: 3.9.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.8.1
Flutter command: flutter 
  Flutter 3.22.2 • channel stable
Android: 
• Program adb found in /Users/bashir.isyaka/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/bashir.isyaka/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by zoskar** [comment]
Hi @bash-bigpay 
It seems that the problem lies within your local enviroment - I was not able to reproduce it (I ran tests from this repository example app on the setup you mentioned without any problems). If you do not manage to fix it yourself feel free to reach out to community on [Patrol Discord server](https://discord.com/invite/ukBK5t4EZg). Maybe someone who had similar problem will be able to help you.
