### ISSUE TITLE
Android-BrowserStack test execution failures due to "PatrolAppServiceClientException: Invalid response 503"

### ISSUE THREAD

**Issue by BanuToros** [leancodepl/patrol#2317]
### Steps to reproduce

1- Execute Patrol tests on emulators locally (Successfull)
2- Execute [bs_android](https://github.com/leancodepl/mobile-tools/blob/master/bin/bs_android) scripts to run Patrol tests on BrowserStack App Automate
3- Expect to see that Patrol "Test starting" screen is displayed, the app is launched and all the 21 tests are ran successfully

### Actual results

1- Patrol "Test starting" is not displayed
2- The app is not launching (only an orange screen is displayed which belongs to the app)
3- Initialisation error is returned.

https://github.com/user-attachments/assets/6d955201-d113-4b22-b943-c8a3abf7d9ec

### Logs

<details>
<summary>Logs</summary>

```
<INSTRUMENTATION_STATUS: class=com.easyjet.travel.android.MainActivityTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.easyjet.travel.android.MainActivityTest:
INSTRUMENTATION_STATUS: test=initializationError
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: class=com.easyjet.travel.android.MainActivityTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stack=java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 503, <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
    />
    <title>Page not found</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        outline: 0;
        box-sizing: border-box;
      }

      a {
        color: #0070f0;
      }

      html {
        background-color: #e9e7ea;
        color: #333333;
      }

      h1 {
        font-size: 26px;
        line-height: 32px;
        font-weight: 400;
        text-align: center;
        padding: 30px 20px;
        padding-bottom: 20px;
        margin-bottom: -12px;
      }

      p,
      small {
        padding: 0 32px;
        line-height: 1.5;
        font-weight: 400;
        margin: 16px 0 0 0;
      }

      small {
        font-size: 16px;
        color: #666;
        display: block;
      }

      p._footer {
        border-top: 1px solid #eee;
        padding: 20px 32px 20px 32px;
        font-size: 14px;
        color: #333;
        background: #f9f9f9;
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
      }

      body {
        padding: 20px;
      }

      .message-modal {
        max-width: 520px;
        margin: auto;
        min-height: 410px;
        border-radius: 3px;
        background-color: #ffffff; /* can keep fff but well, old browsers might fail*/
        box-shadow: 0 4px 7px rgba(0, 0, 0, 0.2);
        font-family: Helvetica, Arial;
        font-size: 16px;
      }

      @media (max-width: 600px) {
        .message-modal {
          margin-top: 0;
          box-shadow: none;
          min-height: 90vh;
        }

        body {
          padding: 0;
        }

        p._footer {
          box-shadow: 0px -1px 8px #ddd;
          position: fixed;
          bottom: 0;
          z-index: 2;
        }
        h1 {
          font-size: 23px;
          font-weight: 400;
        }

        small {
          padding-bottom: 64px;
        }
      }

      @media (min-height: 620px) and (min-width: 800px) {
        .message-modal {
          margin-top: 70px;
          margin-top: 5vh;
        }
      }

      .logo {
        text-align: center;
        background-color: #fff;
        border-radius: 3px 3px 0 0;
        padding: 16px 0;
        border-bottom: 1px solid #eee;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .logo img {
        width: 160px;
      }

      .highlight {
        font-weight: 600;
      }

      ol {
        margin-left: 40px;
      }

      li {
        margin-bottom: 10px;
        margin-left: 16px;
        padding-right: 32px;
        line-height: 1.5;
      }

      /* iPhone 5S n old SE */
      @media (max-width: 340px) {
        p._footer {
          font-size: 12px;
          padding: 16px 24px;
        }

        h1 {
          font-size: 21px;
        }

        p {
          padding-left: 24px;
          padding-right: 24px;
        }

        p, ol, small {
          font-size: 14px;
          line-height: 20px;
        }

        ol {
          margin-left: 28px;
        }

        li {
          padding-right: 24px;
        }

      }
    </style>
  </head>
  <body>
    <div class="message-modal">
      <div class="logo">
        <img
          src="https://d2ogrdw2mh0rsl.cloudfront.net/production/images/static/logo.svg"
          alt="BrowserStack Logo"
        />
      </div>
      <h1>⚠️ Unable to display the page</h1>

      <p>
        We're facing issues in displaying the webpage requested. In order to
        resolve this issue, please ensure the following:
      </p>
      <br />
      <ol>
        <li>Verify the URL entered is accurate.</li>
        <li>Ensure the URL entered is accessible outside BrowserStack.</li>
        <li>Download the Local Desktop App* from "Local Testing".</li>
        <li>
          For advanced configuration*, start the <b>Local Desktop App</b> and
          navigate to <b>localhost:45454</b>.
        </li>
      </ol>

      <small
        >* If you use BrowserStack binary, refer to this
        <a
          href="https://www.browserstack.com/docs/local-testing/binary-params?ref=dashboard-privoxy-page"
          target="_blank"
          rel="noopener noreferrer"
          >guide</a
        >.</small
      >

      <p class="_footer">
        Please contact <b>support@browserstack.com</b>, if the issue persists.
      </p>
    </div>
  </body>
  <script>
    var plat = navigator.platform;
    var port = 4567;
    if (
      plat.indexOf("Mac") >= 0 ||
      plat.indexOf("iPhone") >= 0 ||
      plat.indexOf("iPad") >= 0 ||
      plat.indexOf("Linux") >= 0
    )
      port = 45671;
    var imageURL =
      "http://platform.browserstack.com:" + port + "/static/pixel.gif";
    var oImg = document.createElement("img");
    oImg.setAttribute("src", imageURL);
    oImg.setAttribute("height", "1px");
    oImg.setAttribute("width", "1px");
    document.body.appendChild(oImg);
  </script>
</html>

	at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(PatrolJUnitRunner.java:126)
	at com.easyjet.travel.android.MainActivityTest.testCases(MainActivityTest.java:19)
	... 21 trimmed
Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 503, <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
    />
    <title>Page not found</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        outline: 0;
        box-sizing: border-box;
      }

      a {
        color: #0070f0;
      }

      html {
        background-color: #e9e7ea;
        color: #333333;
      }

      h1 {
        font-size: 26px;
        line-height: 32px;
        font-weight: 400;
        text-align: center;
        padding: 30px 20px;
        padding-bottom: 20px;
        margin-bottom: -12px;
      }

      p,
      small {
        padding: 0 32px;
        line-height: 1.5;
        font-weight: 400;
        margin: 16px 0 0 0;
      }

      small {
        font-size: 16px;
        color: #666;
        display: block;
      }

      p._footer {
        border-top: 1px solid #eee;
        padding: 20px 32px 20px 32px;
        font-size: 14px;
        color: #333;
        background: #f9f9f9;
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
      }

      body {
        padding: 20px;
      }

      .message-modal {
        max-width: 520px;
        margin: auto;
        min-height: 410px;
        border-radius: 3px;
        background-color: #ffffff; /* can keep fff but well, old browsers might fail*/
        box-shadow: 0 4px 7px rgba(0, 0, 0, 0.2);
        font-family: Helvetica, Arial;
        font-size: 16px;
      }

      @media (max-width: 600px) {
        .message-modal {
          margin-top: 0;
          box-shadow: none;
          min-height: 90vh;
        }

        body {
          padding: 0;
        }

        p._footer {
          box-shadow: 0px -1px 8px #ddd;
          position: fixed;
          bottom: 0;
          z-index: 2;
        }
        h1 {
          font-size: 23px;
          font-weight: 400;
        }

        small {
          padding-bottom: 64px;
        }
      }

      @media (min-height: 620px) and (min-width: 800px) {
        .message-modal {
          margin-top: 70px;
          margin-top: 5vh;
        }
      }

      .logo {
        text-align: center;
        background-color: #fff;
        border-radius: 3px 3px 0 0;
        padding: 16px 0;
        border-bottom: 1px solid #eee;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .logo img {
        width: 160px;
      }

      .highlight {
        font-weight: 600;
      }

      ol {
        margin-left: 40px;
      }

      li {
        margin-bottom: 10px;
        margin-left: 16px;
        padding-right: 32px;
        line-height: 1.5;
      }

      /* iPhone 5S n old SE */
      @media (max-width: 340px) {
        p._footer {
          font-size: 12px;
          padding: 16px 24px;
        }

        h1 {
          font-size: 21px;
        }

        p {
          padding-left: 24px;
          padding-right: 24px;
        }

        p, ol, small {
          font-size: 14px;
          line-height: 20px;
        }

        ol {
          margin-left: 28px;
        }

        li {
          padding-right: 24px;
        }

      }
    </style>
  </head>
  <body>
    <div class="message-modal">
      <div class="logo">
        <img
          src="https://d2ogrdw2mh0rsl.cloudfront.net/production/images/static/logo.svg"
          alt="BrowserStack Logo"
        />
      </div>
      <h1>⚠️ Unable to display the page</h1>

      <p>
        We're facing issues in displaying the webpage requested. In order to
        resolve this issue, please ensure the following:
      </p>
      <br />
      <ol>
        <li>Verify the URL entered is accurate.</li>
        <li>Ensure the URL entered is accessible outside BrowserStack.</li>
        <li>Download the Local Desktop App* from "Local Testing".</li>
        <li>
          For advanced configuration*, start the <b>Local Desktop App</b> and
          navigate to <b>localhost:45454</b>.
        </li>
      </ol>

      <small
        >* If you use BrowserStack binary, refer to this
        <a
          href="https://www.browserstack.com/docs/local-testing/binary-params?ref=dashboard-privoxy-page"
          target="_blank"
          rel="noopener noreferrer"
          >guide</a
        >.</small
      >

      <p class="_footer">
        Please contact <b>support@browserstack.com</b>, if the issue persists.
      </p>
    </div>
  </body>
  <script>
    var plat = navigator.platform;
    var port = 4567;
    if (
      plat.indexOf("Mac") >= 0 ||
      plat.indexOf("iPhone") >= 0 ||
      plat.indexOf("iPad") >= 0 ||
      plat.indexOf("Linux") >= 0
    )
      port = 45671;
    var imageURL =
      "http://platform.browserstack.com:" + port + "/static/pixel.gif";
    var oImg = document.createElement("img");
    oImg.setAttribute("src", imageURL);
    oImg.setAttribute("height", "1px");
    oImg.setAttribute("width", "1px");
    document.body.appendChild(oImg);
  </script>
</html>

	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest$default(PatrolAppServiceClient.kt:27)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:18)
	at pl.leancode.patrol.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:46)
	at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(PatrolJUnitRunner.java:114)
	... 23 more

INSTRUMENTATION_STATUS: stream=
Error in initializationError(com.easyjet.travel.android.MainActivityTest):
java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 503, <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
    />
    <title>Page not found</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        outline: 0;
        box-sizing: border-box;
      }

      a {
        color: #0070f0;
      }

      html {
        background-color: #e9e7ea;
        color: #333333;
      }

      h1 {
        font-size: 26px;
        line-height: 32px;
        font-weight: 400;
        text-align: center;
        padding: 30px 20px;
        padding-bottom: 20px;
        margin-bottom: -12px;
      }

      p,
      small {
        padding: 0 32px;
        line-height: 1.5;
        font-weight: 400;
        margin: 16px 0 0 0;
      }

      small {
        font-size: 16px;
        color: #666;
        display: block;
      }

      p._footer {
        border-top: 1px solid #eee;
        padding: 20px 32px 20px 32px;
        font-size: 14px;
        color: #333;
        background: #f9f9f9;
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
      }

      body {
        padding: 20px;
      }

      .message-modal {
        max-width: 520px;
        margin: auto;
        min-height: 410px;
        border-radius: 3px;
        background-color: #ffffff; /* can keep fff but well, old browsers might fail*/
        box-shadow: 0 4px 7px rgba(0, 0, 0, 0.2);
        font-family: Helvetica, Arial;
        font-size: 16px;
      }

      @media (max-width: 600px) {
        .message-modal {
          margin-top: 0;
          box-shadow: none;
          min-height: 90vh;
        }

        body {
          padding: 0;
        }

        p._footer {
          box-shadow: 0px -1px 8px #ddd;
          position: fixed;
          bottom: 0;
          z-index: 2;
        }
        h1 {
          font-size: 23px;
          font-weight: 400;
        }

        small {
          padding-bottom: 64px;
        }
      }

      @media (min-height: 620px) and (min-width: 800px) {
        .message-modal {
          margin-top: 70px;
          margin-top: 5vh;
        }
      }

      .logo {
        text-align: center;
        background-color: #fff;
        border-radius: 3px 3px 0 0;
        padding: 16px 0;
        border-bottom: 1px solid #eee;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .logo img {
        width: 160px;
      }

      .highlight {
        font-weight: 600;
      }

      ol {
        margin-left: 40px;
      }

      li {
        margin-bottom: 10px;
        margin-left: 16px;
        padding-right: 32px;
        line-height: 1.5;
      }

      /* iPhone 5S n old SE */
      @media (max-width: 340px) {
        p._footer {
          font-size: 12px;
          padding: 16px 24px;
        }

        h1 {
          font-size: 21px;
        }

        p {
          padding-left: 24px;
          padding-right: 24px;
        }

        p, ol, small {
          font-size: 14px;
          line-height: 20px;
        }

        ol {
          margin-left: 28px;
        }

        li {
          padding-right: 24px;
        }

      }
    </style>
  </head>
  <body>
    <div class="message-modal">
      <div class="logo">
        <img
          src="https://d2ogrdw2mh0rsl.cloudfront.net/production/images/static/logo.svg"
          alt="BrowserStack Logo"
        />
      </div>
      <h1>⚠️ Unable to display the page</h1>

      <p>
        We're facing issues in displaying the webpage requested. In order to
        resolve this issue, please ensure the following:
      </p>
      <br />
      <ol>
        <li>Verify the URL entered is accurate.</li>
        <li>Ensure the URL entered is accessible outside BrowserStack.</li>
        <li>Download the Local Desktop App* from "Local Testing".</li>
        <li>
          For advanced configuration*, start the <b>Local Desktop App</b> and
          navigate to <b>localhost:45454</b>.
        </li>
      </ol>

      <small
        >* If you use BrowserStack binary, refer to this
        <a
          href="https://www.browserstack.com/docs/local-testing/binary-params?ref=dashboard-privoxy-page"
          target="_blank"
          rel="noopener noreferrer"
          >guide</a
        >.</small
      >

      <p class="_footer">
        Please contact <b>support@browserstack.com</b>, if the issue persists.
      </p>
    </div>
  </body>
  <script>
    var plat = navigator.platform;
    var port = 4567;
    if (
      plat.indexOf("Mac") >= 0 ||
      plat.indexOf("iPhone") >= 0 ||
      plat.indexOf("iPad") >= 0 ||
      plat.indexOf("Linux") >= 0
    )
      port = 45671;
    var imageURL =
      "http://platform.browserstack.com:" + port + "/static/pixel.gif";
    var oImg = document.createElement("img");
    oImg.setAttribute("src", imageURL);
    oImg.setAttribute("height", "1px");
    oImg.setAttribute("width", "1px");
    document.body.appendChild(oImg);
  </script>
</html>

	at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(PatrolJUnitRunner.java:126)
	at com.easyjet.travel.android.MainActivityTest.testCases(MainActivityTest.java:19)
	... 21 trimmed
Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 503, <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
    />
    <title>Page not found</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        outline: 0;
        box-sizing: border-box;
      }

      a {
        color: #0070f0;
      }

      html {
        background-color: #e9e7ea;
        color: #333333;
      }

      h1 {
        font-size: 26px;
        line-height: 32px;
        font-weight: 400;
        text-align: center;
        padding: 30px 20px;
        padding-bottom: 20px;
        margin-bottom: -12px;
      }

      p,
      small {
        padding: 0 32px;
        line-height: 1.5;
        font-weight: 400;
        margin: 16px 0 0 0;
      }

      small {
        font-size: 16px;
        color: #666;
        display: block;
      }

      p._footer {
        border-top: 1px solid #eee;
        padding: 20px 32px 20px 32px;
        font-size: 14px;
        color: #333;
        background: #f9f9f9;
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
      }

      body {
        padding: 20px;
      }

      .message-modal {
        max-width: 520px;
        margin: auto;
        min-height: 410px;
        border-radius: 3px;
        background-color: #ffffff; /* can keep fff but well, old browsers might fail*/
        box-shadow: 0 4px 7px rgba(0, 0, 0, 0.2);
        font-family: Helvetica, Arial;
        font-size: 16px;
      }

      @media (max-width: 600px) {
        .message-modal {
          margin-top: 0;
          box-shadow: none;
          min-height: 90vh;
        }

        body {
          padding: 0;
        }

        p._footer {
          box-shadow: 0px -1px 8px #ddd;
          position: fixed;
          bottom: 0;
          z-index: 2;
        }
        h1 {
          font-size: 23px;
          font-weight: 400;
        }

        small {
          padding-bottom: 64px;
        }
      }

      @media (min-height: 620px) and (min-width: 800px) {
        .message-modal {
          margin-top: 70px;
          margin-top: 5vh;
        }
      }

      .logo {
        text-align: center;
        background-color: #fff;
        border-radius: 3px 3px 0 0;
        padding: 16px 0;
        border-bottom: 1px solid #eee;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .logo img {
        width: 160px;
      }

      .highlight {
        font-weight: 600;
      }

      ol {
        margin-left: 40px;
      }

      li {
        margin-bottom: 10px;
        margin-left: 16px;
        padding-right: 32px;
        line-height: 1.5;
      }

      /* iPhone 5S n old SE */
      @media (max-width: 340px) {
        p._footer {
          font-size: 12px;
          padding: 16px 24px;
        }

        h1 {
          font-size: 21px;
        }

        p {
          padding-left: 24px;
          padding-right: 24px;
        }

        p, ol, small {
          font-size: 14px;
          line-height: 20px;
        }

        ol {
          margin-left: 28px;
        }

        li {
          padding-right: 24px;
        }

      }
    </style>
  </head>
  <body>
    <div class="message-modal">
      <div class="logo">
        <img
          src="https://d2ogrdw2mh0rsl.cloudfront.net/production/images/static/logo.svg"
          alt="BrowserStack Logo"
        />
      </div>
      <h1>⚠️ Unable to display the page</h1>

      <p>
        We're facing issues in displaying the webpage requested. In order to
        resolve this issue, please ensure the following:
      </p>
      <br />
      <ol>
        <li>Verify the URL entered is accurate.</li>
        <li>Ensure the URL entered is accessible outside BrowserStack.</li>
        <li>Download the Local Desktop App* from "Local Testing".</li>
        <li>
          For advanced configuration*, start the <b>Local Desktop App</b> and
          navigate to <b>localhost:45454</b>.
        </li>
      </ol>

      <small
        >* If you use BrowserStack binary, refer to this
        <a
          href="https://www.browserstack.com/docs/local-testing/binary-params?ref=dashboard-privoxy-page"
          target="_blank"
          rel="noopener noreferrer"
          >guide</a
        >.</small
      >

      <p class="_footer">
        Please contact <b>support@browserstack.com</b>, if the issue persists.
      </p>
    </div>
  </body>
  <script>
    var plat = navigator.platform;
    var port = 4567;
    if (
      plat.indexOf("Mac") >= 0 ||
      plat.indexOf("iPhone") >= 0 ||
      plat.indexOf("iPad") >= 0 ||
      plat.indexOf("Linux") >= 0
    )
      port = 45671;
    var imageURL =
      "http://platform.browserstack.com:" + port + "/static/pixel.gif";
    var oImg = document.createElement("img");
    oImg.setAttribute("src", imageURL);
    oImg.setAttribute("height", "1px");
    oImg.setAttribute("width", "1px");
    document.body.appendChild(oImg);
  </script>
</html>

	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest$default(PatrolAppServiceClient.kt:27)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:18)
	at pl.leancode.patrol.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:46)
	at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(PatrolJUnitRunner.java:114)
	... 23 more

INSTRUMENTATION_STATUS: test=initializationError
INSTRUMENTATION_STATUS_CODE: -2
INSTRUMENTATION_RESULT: stream=

Time: 0.063
There was 1 failure:
1) initializationError(com.easyjet.travel.android.MainActivityTest)
java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 503, <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
    />
    <title>Page not found</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        outline: 0;
        box-sizing: border-box;
      }

      a {
        color: #0070f0;
      }

      html {
        background-color: #e9e7ea;
        color: #333333;
      }

      h1 {
        font-size: 26px;
        line-height: 32px;
        font-weight: 400;
        text-align: center;
        padding: 30px 20px;
        padding-bottom: 20px;
        margin-bottom: -12px;
      }

      p,
      small {
        padding: 0 32px;
        line-height: 1.5;
        font-weight: 400;
        margin: 16px 0 0 0;
      }

      small {
        font-size: 16px;
        color: #666;
        display: block;
      }

      p._footer {
        border-top: 1px solid #eee;
        padding: 20px 32px 20px 32px;
        font-size: 14px;
        color: #333;
        background: #f9f9f9;
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
      }

      body {
        padding: 20px;
      }

      .message-modal {
        max-width: 520px;
        margin: auto;
        min-height: 410px;
        border-radius: 3px;
        background-color: #ffffff; /* can keep fff but well, old browsers might fail*/
        box-shadow: 0 4px 7px rgba(0, 0, 0, 0.2);
        font-family: Helvetica, Arial;
        font-size: 16px;
      }

      @media (max-width: 600px) {
        .message-modal {
          margin-top: 0;
          box-shadow: none;
          min-height: 90vh;
        }

        body {
          padding: 0;
        }

        p._footer {
          box-shadow: 0px -1px 8px #ddd;
          position: fixed;
          bottom: 0;
          z-index: 2;
        }
        h1 {
          font-size: 23px;
          font-weight: 400;
        }

        small {
          padding-bottom: 64px;
        }
      }

      @media (min-height: 620px) and (min-width: 800px) {
        .message-modal {
          margin-top: 70px;
          margin-top: 5vh;
        }
      }

      .logo {
        text-align: center;
        background-color: #fff;
        border-radius: 3px 3px 0 0;
        padding: 16px 0;
        border-bottom: 1px solid #eee;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .logo img {
        width: 160px;
      }

      .highlight {
        font-weight: 600;
      }

      ol {
        margin-left: 40px;
      }

      li {
        margin-bottom: 10px;
        margin-left: 16px;
        padding-right: 32px;
        line-height: 1.5;
      }

      /* iPhone 5S n old SE */
      @media (max-width: 340px) {
        p._footer {
          font-size: 12px;
          padding: 16px 24px;
        }

        h1 {
          font-size: 21px;
        }

        p {
          padding-left: 24px;
          padding-right: 24px;
        }

        p, ol, small {
          font-size: 14px;
          line-height: 20px;
        }

        ol {
          margin-left: 28px;
        }

        li {
          padding-right: 24px;
        }

      }
    </style>
  </head>
  <body>
    <div class="message-modal">
      <div class="logo">
        <img
          src="https://d2ogrdw2mh0rsl.cloudfront.net/production/images/static/logo.svg"
          alt="BrowserStack Logo"
        />
      </div>
      <h1>⚠️ Unable to display the page</h1>

      <p>
        We're facing issues in displaying the webpage requested. In order to
        resolve this issue, please ensure the following:
      </p>
      <br />
      <ol>
        <li>Verify the URL entered is accurate.</li>
        <li>Ensure the URL entered is accessible outside BrowserStack.</li>
        <li>Download the Local Desktop App* from "Local Testing".</li>
        <li>
          For advanced configuration*, start the <b>Local Desktop App</b> and
          navigate to <b>localhost:45454</b>.
        </li>
      </ol>

      <small
        >* If you use BrowserStack binary, refer to this
        <a
          href="https://www.browserstack.com/docs/local-testing/binary-params?ref=dashboard-privoxy-page"
          target="_blank"
          rel="noopener noreferrer"
          >guide</a
        >.</small
      >

      <p class="_footer">
        Please contact <b>support@browserstack.com</b>, if the issue persists.
      </p>
    </div>
  </body>
  <script>
    var plat = navigator.platform;
    var port = 4567;
    if (
      plat.indexOf("Mac") >= 0 ||
      plat.indexOf("iPhone") >= 0 ||
      plat.indexOf("iPad") >= 0 ||
      plat.indexOf("Linux") >= 0
    )
      port = 45671;
    var imageURL =
      "http://platform.browserstack.com:" + port + "/static/pixel.gif";
    var oImg = document.createElement("img");
    oImg.setAttribute("src", imageURL);
    oImg.setAttribute("height", "1px");
    oImg.setAttribute("width", "1px");
    document.body.appendChild(oImg);
  </script>
</html>

	at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(PatrolJUnitRunner.java:126)
	at com.easyjet.travel.android.MainActivityTest.testCases(MainActivityTest.java:19)
	... 21 trimmed
Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 503, <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
    />
    <title>Page not found</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        outline: 0;
        box-sizing: border-box;
      }

      a {
        color: #0070f0;
      }

      html {
        background-color: #e9e7ea;
        color: #333333;
      }

      h1 {
        font-size: 26px;
        line-height: 32px;
        font-weight: 400;
        text-align: center;
        padding: 30px 20px;
        padding-bottom: 20px;
        margin-bottom: -12px;
      }

      p,
      small {
        padding: 0 32px;
        line-height: 1.5;
        font-weight: 400;
        margin: 16px 0 0 0;
      }

      small {
        font-size: 16px;
        color: #666;
        display: block;
      }

      p._footer {
        border-top: 1px solid #eee;
        padding: 20px 32px 20px 32px;
        font-size: 14px;
        color: #333;
        background: #f9f9f9;
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
      }

      body {
        padding: 20px;
      }

      .message-modal {
        max-width: 520px;
        margin: auto;
        min-height: 410px;
        border-radius: 3px;
        background-color: #ffffff; /* can keep fff but well, old browsers might fail*/
        box-shadow: 0 4px 7px rgba(0, 0, 0, 0.2);
        font-family: Helvetica, Arial;
        font-size: 16px;
      }

      @media (max-width: 600px) {
        .message-modal {
          margin-top: 0;
          box-shadow: none;
          min-height: 90vh;
        }

        body {
          padding: 0;
        }

        p._footer {
          box-shadow: 0px -1px 8px #ddd;
          position: fixed;
          bottom: 0;
          z-index: 2;
        }
        h1 {
          font-size: 23px;
          font-weight: 400;
        }

        small {
          padding-bottom: 64px;
        }
      }

      @media (min-height: 620px) and (min-width: 800px) {
        .message-modal {
          margin-top: 70px;
          margin-top: 5vh;
        }
      }

      .logo {
        text-align: center;
        background-color: #fff;
        border-radius: 3px 3px 0 0;
        padding: 16px 0;
        border-bottom: 1px solid #eee;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .logo img {
        width: 160px;
      }

      .highlight {
        font-weight: 600;
      }

      ol {
        margin-left: 40px;
      }

      li {
        margin-bottom: 10px;
        margin-left: 16px;
        padding-right: 32px;
        line-height: 1.5;
      }

      /* iPhone 5S n old SE */
      @media (max-width: 340px) {
        p._footer {
          font-size: 12px;
          padding: 16px 24px;
        }

        h1 {
          font-size: 21px;
        }

        p {
          padding-left: 24px;
          padding-right: 24px;
        }

        p, ol, small {
          font-size: 14px;
          line-height: 20px;
        }

        ol {
          margin-left: 28px;
        }

        li {
          padding-right: 24px;
        }

      }
    </style>
  </head>
  <body>
    <div class="message-modal">
      <div class="logo">
        <img
          src="https://d2ogrdw2mh0rsl.cloudfront.net/production/images/static/logo.svg"
          alt="BrowserStack Logo"
        />
      </div>
      <h1>⚠️ Unable to display the page</h1>

      <p>
        We're facing issues in displaying the webpage requested. In order to
        resolve this issue, please ensure the following:
      </p>
      <br />
      <ol>
        <li>Verify the URL entered is accurate.</li>
        <li>Ensure the URL entered is accessible outside BrowserStack.</li>
        <li>Download the Local Desktop App* from "Local Testing".</li>
        <li>
          For advanced configuration*, start the <b>Local Desktop App</b> and
          navigate to <b>localhost:45454</b>.
        </li>
      </ol>

      <small
        >* If you use BrowserStack binary, refer to this
        <a
          href="https://www.browserstack.com/docs/local-testing/binary-params?ref=dashboard-privoxy-page"
          target="_blank"
          rel="noopener noreferrer"
          >guide</a
        >.</small
      >

      <p class="_footer">
        Please contact <b>support@browserstack.com</b>, if the issue persists.
      </p>
    </div>
  </body>
  <script>
    var plat = navigator.platform;
    var port = 4567;
    if (
      plat.indexOf("Mac") >= 0 ||
      plat.indexOf("iPhone") >= 0 ||
      plat.indexOf("iPad") >= 0 ||
      plat.indexOf("Linux") >= 0
    )
      port = 45671;
    var imageURL =
      "http://platform.browserstack.com:" + port + "/static/pixel.gif";
    var oImg = document.createElement("img");
    oImg.setAttribute("src", imageURL);
    oImg.setAttribute("height", "1px");
    oImg.setAttribute("width", "1px");
    document.body.appendChild(oImg);
  </script>
</html>

	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest$default(PatrolAppServiceClient.kt:27)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:18)
	at pl.leancode.patrol.PatrolAppServiceClient.listDartTests(PatrolAppServiceClient.kt:46)
	at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(PatrolJUnitRunner.java:114)
	... 23 more

FAILURES!!!
Tests run: 1,  Failures: 1


INSTRUMENTATION_CODE: -1

</details>
[AndroidLogs.txt](https://github.com/user-attachments/files/16659605/AndroidLogs.txt)



### Patrol version

Patrol: ^3.10.0
Patrol CLI: ^3.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```

Patrol doctor:
Patrol CLI version: 3.1.0
Flutter command: flutter 
  Flutter 3.22.0 • channel stable
Android: 
• Program adb found in /Users/banu.toros/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/banu.toros/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
</details>

### Flutter Doctor output

<details>
    <summary>Flutter Doctor output</summary>
    
    ```
    <Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.6.1 23G93 darwin-arm64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.88.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

</details>

**Comment by erickjtorres** [comment]
Any update on this? seeing the same issue
