### ISSUE TITLE
Error: A constant constructor can't call a non-constant super constructor.

### ISSUE THREAD

**Issue by SametSahin10** [leancodepl/patrol#2414]
### Steps to reproduce

1. Set up Patrol for Android
2. Run the example test. The command I used:
`patrol test -t integration_test/example_test_with_patrol_test.dart --flavor staging`
3. See that it fails with the error below:
```
No device specified, using the first one (395a545443503098)
• Building apk with entrypoint test_bundle.dart...
	../../../../.pub-cache/hosted/pub.dev/patrol-3.12.0/lib/src/custom_finders/patrol_integration_tester.dart:9:9: Error: A constant constructor can't call a non-constant super constructor.
	  const PatrolIntegrationTester({
	        ^
	Target kernel_snapshot_program failed: Exception


	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':app:compileFlutterBuildStagingDebug'.
	> Process 'command '/Users/sametsahin/work/flutter/bin/flutter'' finished with non-zero exit value 1

	* Try:
	> Run with --stacktrace option to get the stack trace.
	> Run with --info or --debug option to get more log output.
	> Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 8s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (8.9s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:79:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:49:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:326:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:247:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///Users/sametsahin/.pub-cache/hosted/pub.dev/patrol_cli-3.3.0/bin/main.dart:6:20)
<asynchronous suspension>
```

### Actual results

The test should run and pass without issues.

### Logs

<details>
<summary>Logs</summary>

```
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/sametsahin/work/flutter-projects/apps/volt_wallet/integration_test/example_test_with_patrol_test.dart
Generated entrypoint /Users/sametsahin/work/flutter-projects/apps/volt_wallet/integration_test/test_bundle.dart with 1 bundled test(s)
Received Android flavor: staging
Received iOS flavor: staging
Received macOS flavor: staging
$ flutter --no-version-check --suppress-analytics devices --machine
No device specified, using the first one (395a545443503098)
Received 1 device(s) to run on
Received device: 395a545443503098
$ flutter doctor --verbose
$ flutter --suppress-analytics --no-version-check pub deps --style=list
Received 10 --dart-define(s) (0 custom, 10 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=finance.voltage.app.staging
Received internal --dart-define: PATROL_APP_BUNDLE_ID=finance.voltage.app.staging
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Volt Staging
Received internal --dart-define: PATROL_IOS_APP_NAME=Volt Staging
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_TEST_SERVER_PORT=8081
Received internal --dart-define: PATROL_APP_SERVER_PORT=8082
Received internal --dart-define: COVERAGE_ENABLED=false
$ flutter build apk --config-only -t integration_test/test_bundle.dart
$ flutter doctor --verbose
• Building apk with entrypoint test_bundle.dart...
$ ./gradlew :app:assembleStagingDebug -Ptarget=/Users/sametsahin/work/flutter-projects/apps/volt_wallet/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9ZmluYW5jZS52b2x0YWdlLmFwcC5zdGFnaW5n,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9ZmluYW5jZS52b2x0YWdlLmFwcC5zdGFnaW5n,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9Vm9sdCBTdGFnaW5n,UEFUUk9MX0lPU19BUFBfTkFNRT1Wb2x0IFN0YWdpbmc=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==,UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy,Q09WRVJBR0VfRU5BQkxFRD1mYWxzZQ== -Papp-server-port=8082 -Ptest-server-port=8081
	: > Task :gradle:compileJava NO-SOURCE
	: > Task :gradle:compileGroovy UP-TO-DATE
	: > Task :gradle:pluginDescriptors UP-TO-DATE
	: > Task :gradle:processResources UP-TO-DATE
	: > Task :gradle:classes UP-TO-DATE
	: > Task :gradle:jar UP-TO-DATE
	: WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
	:
	: This Android Gradle plugin (7.3.0) was tested up to compileSdk = 33
	:
	: This warning can be suppressed by adding
	:     android.suppressUnsupportedCompileSdk=34
	: to this project's gradle.properties
	:
	: The build will continue, but you are strongly encouraged to update your project to
	: use a newer Android Gradle Plugin that has been tested with compileSdk = 34
	: WARNING:The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (30.0.3) for Android Gradle Plugin 7.3.0.
	: Android SDK Build Tools 30.0.3 will be used.
	: To suppress this warning, remove "buildToolsVersion '28.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
	: > Task :app:preBuild UP-TO-DATE
	: > Task :app:preStagingDebugBuild UP-TO-DATE
	: > Task :app:mergeStagingDebugNativeDebugMetadata NO-SOURCE
	: > Task :amplitude_flutter:preBuild UP-TO-DATE
	: > Task :amplitude_flutter:preDebugBuild UP-TO-DATE
	: > Task :amplitude_flutter:compileDebugAidl NO-SOURCE
	: > Task :amplitude_flutter:checkKotlinGradlePluginConfigurationErrors
	: > Task :amplitude_flutter:compileDebugRenderscript NO-SOURCE
	: > Task :amplitude_flutter:generateDebugBuildConfig UP-TO-DATE
	: > Task :amplitude_flutter:generateDebugResValues UP-TO-DATE
	: > Task :amplitude_flutter:generateDebugResources UP-TO-DATE
	: > Task :amplitude_flutter:packageDebugResources UP-TO-DATE
	: > Task :amplitude_flutter:parseDebugLocalResources UP-TO-DATE
	: > Task :amplitude_flutter:processDebugManifest UP-TO-DATE
	: > Task :amplitude_flutter:generateDebugRFile UP-TO-DATE
	: > Task :amplitude_flutter:compileDebugKotlin UP-TO-DATE
	: > Task :amplitude_flutter:javaPreCompileDebug UP-TO-DATE
	: > Task :amplitude_flutter:compileDebugJavaWithJavac UP-TO-DATE
	: > Task :amplitude_flutter:bundleLibCompileToJarDebug UP-TO-DATE
	:
	: > Task :app:compileFlutterBuildStagingDebug
	../../../../.pub-cache/hosted/pub.dev/patrol-3.12.0/lib/src/custom_finders/patrol_integration_tester.dart:9:9: Error: A constant constructor can't call a non-constant super constructor.
	  const PatrolIntegrationTester({
	        ^
	Target kernel_snapshot_program failed: Exception

	:
	: > Task :app:compileFlutterBuildStagingDebug FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':app:compileFlutterBuildStagingDebug'.
	> Process 'command '/Users/sametsahin/work/flutter/bin/flutter'' finished with non-zero exit value 1

	* Try:
	> Run with --stacktrace option to get the stack trace.
	> Run with --info or --debug option to get more log output.
	> Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 4s
	:
	: Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
	:
	: You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
	:
	: See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings
	: 16 actionable tasks: 2 executed, 14 up-to-date
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (4.7s)
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:79:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:49:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:326:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:247:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///Users/sametsahin/.pub-cache/hosted/pub.dev/patrol_cli-3.3.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:79:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:49:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:326:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:247:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///Users/sametsahin/.pub-cache/hosted/pub.dev/patrol_cli-3.3.0/bin/main.dart:6:20)
```

</details>

### Patrol version

patrol: ^3.12.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.3.0
Flutter command: flutter
  Flutter 3.24.4 • channel stable
Android:
• Program adb found in /Users/sametsahin/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/sametsahin/Library/Android/sdk
iOS / macOS:
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6.1 23G93 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by radyhaggag** [comment]
This issue in the latest version in pub.dev

You should use this version to solve the issue

`  patrol: ^3.13.0-dev.2
`
