### ISSUE TITLE
app:connectedDebugAndroidTest FAILED with Default Flutter Application

### ISSUE THREAD

**Issue by mattVK** [leancodepl/patrol#2418]
### Steps to reproduce

1. Clone https://github.com/mattVK/patrol_testing_inv
2. try `patrol test` or `patrol test -t integration_test/example_test.dart
3. Encounter a problem with app:connectedDebugAndroidTest when process is at status `Executing tests of apk with entrypoint test_bundle.dart on device 58f0a2...`

### Actual results

The program does not open and no tests are run.

### Logs

<details>
<summary>Logs</summary>

```
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: D:\Local\Flutter\patrol_test\integration_test/example_test.dart
Generated entrypoint D:\Local\Flutter\patrol_test\integration_test\test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check --suppress-analytics devices --machine
No device specified, using the first one (58f0a2)
Received 1 device(s) to run on
Received device: 58f0a2
$ flutter doctor --verbose
$ flutter --suppress-analytics --no-version-check pub deps --style=list
Received 11 --dart-define(s) (0 custom, 11 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.example.patrol_test
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.patrol_test
Received internal --dart-define: PATROL_MACOS_APP_BUNDLE_ID=com.example.patrol_test
Received internal --dart-define: PATROL_ANDROID_APP_NAME=My App
Received internal --dart-define: PATROL_IOS_APP_NAME=My App
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_TEST_SERVER_PORT=8081
Received internal --dart-define: PATROL_APP_SERVER_PORT=8082
Received internal --dart-define: COVERAGE_ENABLED=false
$ flutter build apk --config-only -t integration_test/test_bundle.dart
$ flutter doctor --verbose
• Building apk with entrypoint test_bundle.dart...
$ .\gradlew.bat :app:assembleDebug -Ptarget=D:\Local\Flutter\patrol_test\integration_test\test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX01BQ09TX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9TXkgQXBw,UEFUUk9MX0lPU19BUFBfTkFNRT1NeSBBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==,UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy,Q09WRVJBR0VfRU5BQkxFRD1mYWxzZQ== -Papp-server-port=8082 -Ptest-server-port=8081
        : > Task :gradle:compileJava NO-SOURCE
        : > Task :gradle:compileGroovy UP-TO-DATE
        : > Task :gradle:pluginDescriptors UP-TO-DATE
        : > Task :gradle:processResources UP-TO-DATE
        : > Task :gradle:classes UP-TO-DATE
        : > Task :gradle:jar UP-TO-DATE
        : WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (8.1.0) was tested up to compileSdk = 33 (and compileSdkPreview = "UpsideDownCakePrivacySandbox").
        : 
        : You are strongly encouraged to update your project to use a newer
        : Android Gradle plugin that has been tested with compileSdk = 34.
        : 
        : If you are already using the latest version of the Android Gradle plugin,
        : you may need to wait until a newer version with support for compileSdk = 34 is available.
        : 
        : To suppress this warning, add/update
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties.
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug UP-TO-DATE
        : > Task :app:packJniLibsflutterBuildDebug UP-TO-DATE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:packageDebugResources UP-TO-DATE
        : > Task :app:parseDebugLocalResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:compileDebugKotlin UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :app:processDebugJavaRes UP-TO-DATE
        : > Task :patrol:processDebugJavaRes UP-TO-DATE
        : > Task :app:mergeDebugJavaResource UP-TO-DATE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:dexBuilderDebug UP-TO-DATE
        : > Task :app:mergeLibDexDebug UP-TO-DATE
        : > Task :app:mergeProjectDexDebug UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :app:packageDebug UP-TO-DATE
        : > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebug
        : 
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
        : 
        : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        : 
        : For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
        : 
        : BUILD SUCCESSFUL in 1s
        : 62 actionable tasks: 4 executed, 58 up-to-date
$ .\gradlew.bat :app:assembleDebugAndroidTest -Ptarget=D:\Local\Flutter\patrol_test\integration_test\test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX01BQ09TX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9TXkgQXBw,UEFUUk9MX0lPU19BUFBfTkFNRT1NeSBBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==,UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy,Q09WRVJBR0VfRU5BQkxFRD1mYWxzZQ== -Papp-server-port=8082 -Ptest-server-port=8081
        : > Task :gradle:compileJava NO-SOURCE
        : > Task :gradle:compileGroovy UP-TO-DATE
        : > Task :gradle:pluginDescriptors UP-TO-DATE
        : > Task :gradle:processResources UP-TO-DATE
        : > Task :gradle:classes UP-TO-DATE
        : > Task :gradle:jar UP-TO-DATE
        : WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (8.1.0) was tested up to compileSdk = 33 (and compileSdkPreview = "UpsideDownCakePrivacySandbox").
        : 
        : You are strongly encouraged to update your project to use a newer
        : Android Gradle plugin that has been tested with compileSdk = 34.
        : 
        : If you are already using the latest version of the Android Gradle plugin,
        : you may need to wait until a newer version with support for compileSdk = 34 is available.
        : 
        : To suppress this warning, add/update
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties.
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:packageDebugResources UP-TO-DATE
        : > Task :app:parseDebugLocalResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:preDebugAndroidTestBuild SKIPPED
        : > Task :app:checkDebugAndroidTestAarMetadata UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResValues UP-TO-DATE
        : > Task :app:mapDebugAndroidTestSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResources UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestResources UP-TO-DATE
        : > Task :app:processDebugAndroidTestManifest UP-TO-DATE
        : > Task :app:processDebugAndroidTestResources UP-TO-DATE
        : > Task :app:javaPreCompileDebugAndroidTest UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestShaders UP-TO-DATE
        : > Task :app:compileDebugAndroidTestShaders NO-SOURCE
        : > Task :app:generateDebugAndroidTestAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:compressDebugAndroidTestAssets UP-TO-DATE
        : > Task :patrol:processDebugJavaRes UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestNativeLibs NO-SOURCE
        : > Task :app:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugAndroidTestFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebugAndroidTest UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:validateSigningDebugAndroidTest UP-TO-DATE
        : > Task :app:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
        : > Task :app:mergeLibDexDebugAndroidTest UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:bundleDebugClassesToCompileJar UP-TO-DATE
        : > Task :app:compileDebugAndroidTestKotlin NO-SOURCE
        : > Task :app:compileDebugAndroidTestJavaWithJavac UP-TO-DATE
        : > Task :app:processDebugAndroidTestJavaRes NO-SOURCE
        : > Task :app:mergeDebugAndroidTestJavaResource UP-TO-DATE
        : > Task :app:dexBuilderDebugAndroidTest
        : > Task :app:mergeProjectDexDebugAndroidTest UP-TO-DATE
        : > Task :app:packageDebugAndroidTest UP-TO-DATE
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebugAndroidTest UP-TO-DATE
        : 
        : BUILD SUCCESSFUL in 1s
        : 62 actionable tasks: 2 executed, 60 up-to-date
✓ Completed building apk with entrypoint test_bundle.dart (4.4s)
Will uninstall apps before running tests
Uninstalling com.example.patrol_test from 22021211RG
Uninstalling com.example.patrol_test.test from 22021211RG
• Executing tests of apk with entrypoint test_bundle.dart on device 58f0a2...
$ .\gradlew.bat :app:connectedDebugAndroidTest -Ptarget=D:\Local\Flutter\patrol_test\integration_test\test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX01BQ09TX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUucGF0cm9sX3Rlc3Q=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9TXkgQXBw,UEFUUk9MX0lPU19BUFBfTkFNRT1NeSBBcHA=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==,UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy,Q09WRVJBR0VfRU5BQkxFRD1mYWxzZQ== -Papp-server-port=8082 -Ptest-server-port=8081
        : > Task :gradle:compileJava NO-SOURCE
        : > Task :gradle:compileGroovy UP-TO-DATE
        : > Task :gradle:pluginDescriptors UP-TO-DATE
        : > Task :gradle:processResources UP-TO-DATE
        : > Task :gradle:classes UP-TO-DATE
        : > Task :gradle:jar UP-TO-DATE
        : WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (8.1.0) was tested up to compileSdk = 33 (and compileSdkPreview = "UpsideDownCakePrivacySandbox").
        : 
        : You are strongly encouraged to update your project to use a newer
        : Android Gradle plugin that has been tested with compileSdk = 34.
        : 
        : If you are already using the latest version of the Android Gradle plugin,
        : you may need to wait until a newer version with support for compileSdk = 34 is available.
        : 
        : To suppress this warning, add/update
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties.
        : > Task :app:compileFlutterBuildDebug UP-TO-DATE
        : > Task :app:packJniLibsflutterBuildDebug UP-TO-DATE
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:packageDebugResources UP-TO-DATE
        : > Task :app:parseDebugLocalResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:preDebugAndroidTestBuild SKIPPED
        : > Task :app:checkDebugAndroidTestAarMetadata UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResValues UP-TO-DATE
        : > Task :app:mapDebugAndroidTestSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResources UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestResources UP-TO-DATE
        : > Task :app:processDebugAndroidTestManifest UP-TO-DATE
        : > Task :app:processDebugAndroidTestResources UP-TO-DATE
        : > Task :app:javaPreCompileDebugAndroidTest UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :patrol:processDebugJavaRes UP-TO-DATE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :app:mergeLibDexDebug UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:bundleDebugClassesToCompileJar UP-TO-DATE
        : > Task :app:compileDebugAndroidTestKotlin NO-SOURCE
        : > Task :app:compileDebugAndroidTestJavaWithJavac UP-TO-DATE
        : > Task :app:processDebugJavaRes UP-TO-DATE
        : > Task :app:mergeDebugJavaResource UP-TO-DATE
        : > Task :app:dexBuilderDebug UP-TO-DATE
        : > Task :app:mergeProjectDexDebug UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :app:packageDebug UP-TO-DATE
        : > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestShaders UP-TO-DATE
        : > Task :app:compileDebugAndroidTestShaders NO-SOURCE
        : > Task :app:generateDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:compressDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:processDebugAndroidTestJavaRes NO-SOURCE
        : > Task :app:mergeDebugAndroidTestJavaResource UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestNativeLibs NO-SOURCE
        : > Task :app:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugAndroidTestFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebugAndroidTest UP-TO-DATE
        : > Task :app:mergeLibDexDebugAndroidTest UP-TO-DATE
        : > Task :app:dexBuilderDebugAndroidTest
        : > Task :app:mergeProjectDexDebugAndroidTest UP-TO-DATE
        : > Task :app:validateSigningDebugAndroidTest UP-TO-DATE
        : > Task :app:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
        : > Task :app:packageDebugAndroidTest UP-TO-DATE
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : > Task :app:connectedDebugAndroidTest FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:connectedDebugAndroidTest'.
        See the report at: file:///D:/Local/Flutter/patrol_test/build/app/reports/androidTests/connected/debug/index.html

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        > Get more help at https://help.gradle.org.

        BUILD FAILED in 7s
        : 
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
        : 
        : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        : 
        : For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
        : 86 actionable tasks: 6 executed, 80 up-to-date
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on device 58f0a2 (Gradle test execution failed with code 1) (7.9s)
Exception: Gradle test execution failed with code 1
#0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:232:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:191:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:370:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:262:23)
<asynchronous suspension>
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Uninstalling com.example.patrol_test from 22021211RG
Uninstalling com.example.patrol_test.test from 22021211RG
```
![image](https://github.com/user-attachments/assets/a0ded993-34e1-40ee-a06b-5a3ad92abfb2)

</details>

### Patrol version

patrol: ^3.13.0-dev.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.3.0
Flutter command: flutter 
  Flutter 3.24.3 • channel stable
Android:
• Program adb found in C:\Users\USER\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to C:\Users\USER\AppData\Local\Android\Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.5131], locale en-US)
    • Flutter version 3.24.3 on channel stable at C:\Users\USER\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (10 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.95.3)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[√] Connected device (4 available)
    • 22021211RG (mobile) • 58f0a2  • android-arm64  • Android 14 (API 34)
    • Windows (desktop)   • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.5131]
    • Chrome (web)        • chrome  • web-javascript • Google Chrome 130.0.6723.92
    • Edge (web)          • edge    • web-javascript • Microsoft Edge 131.0.2903.51

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by mattVK** [comment]
this fixed itself after a `flutter pub clean` and a `flutter pub get`.
