### ISSUE TITLE
Cannot select Image of Gallery with AndroidSelector

### ISSUE THREAD

**Issue by Friesenjung** [leancodepl/patrol#2449]
### Steps to reproduce

I am unable to select an image from the gallery opened in my app through the NativeSelector on Android. On iOS I was successful with the following line:
` await $.native2.tap(NativeSelector(ios: IOSSelector(instance: 1, elementType: IOSElementType.image)));`

This does not work for me.
1. Open the android phones gallery through the app
2. Select an image from the displayed images through the following command:
`await $.native2.tap(NativeSelector(android: AndroidSelector(instance: 2, className: "android.widget.FrameLayout")));`

Android dump of the site:
<details>
<summary>Dump</summary>

```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy rotation="0">
	<node index="0"
	      text=""
	      resource-id=""
	      class="android.widget.FrameLayout"
	      package="com.google.android.providers.media.module"
	      content-desc=""
	      checkable="false"
	      checked="false"
	      clickable="false"
	      enabled="true"
	      focusable="false"
	      focused="false"
	      scrollable="false"
	      long-clickable="false"
	      password="false"
	      selected="false"
	      bounds="[0,0][1080,2400]">
		<node index="0"
		      text=""
		      resource-id=""
		      class="android.widget.LinearLayout"
		      package="com.google.android.providers.media.module"
		      content-desc=""
		      checkable="false"
		      checked="false"
		      clickable="false"
		      enabled="true"
		      focusable="false"
		      focused="false"
		      scrollable="false"
		      long-clickable="false"
		      password="false"
		      selected="false"
		      bounds="[0,0][1080,2337]">
			<node index="0"
			      text=""
			      resource-id=""
			      class="android.widget.FrameLayout"
			      package="com.google.android.providers.media.module"
			      content-desc=""
			      checkable="false"
			      checked="false"
			      clickable="false"
			      enabled="true"
			      focusable="false"
			      focused="false"
			      scrollable="false"
			      long-clickable="false"
			      password="false"
			      selected="false"
			      bounds="[0,118][1080,2337]">
				<node index="0"
				      text=""
				      resource-id="com.google.android.providers.media.module:id/action_bar_root"
				      class="android.widget.LinearLayout"
				      package="com.google.android.providers.media.module"
				      content-desc=""
				      checkable="false"
				      checked="false"
				      clickable="false"
				      enabled="true"
				      focusable="false"
				      focused="false"
				      scrollable="false"
				      long-clickable="false"
				      password="false"
				      selected="false"
				      bounds="[0,118][1080,2337]">
					<node index="0"
					      text=""
					      resource-id="android:id/content"
					      class="android.widget.FrameLayout"
					      package="com.google.android.providers.media.module"
					      content-desc=""
					      checkable="false"
					      checked="false"
					      clickable="false"
					      enabled="true"
					      focusable="false"
					      focused="false"
					      scrollable="false"
					      long-clickable="false"
					      password="false"
					      selected="false"
					      bounds="[0,118][1080,2337]">
						<node index="0"
						      text=""
						      resource-id=""
						      class="android.view.ViewGroup"
						      package="com.google.android.providers.media.module"
						      content-desc=""
						      checkable="false"
						      checked="false"
						      clickable="false"
						      enabled="true"
						      focusable="false"
						      focused="false"
						      scrollable="false"
						      long-clickable="false"
						      password="false"
						      selected="false"
						      bounds="[0,118][1080,2337]">
							<node index="0"
							      text=""
							      resource-id="com.google.android.providers.media.module:id/bottom_sheet"
							      class="android.widget.LinearLayout"
							      package="com.google.android.providers.media.module"
							      content-desc=""
							      checkable="false"
							      checked="false"
							      clickable="false"
							      enabled="true"
							      focusable="false"
							      focused="false"
							      scrollable="false"
							      long-clickable="false"
							      password="false"
							      selected="false"
							      bounds="[0,897][1080,2337]">
								<node index="0"
								      text=""
								      resource-id="com.google.android.providers.media.module:id/drag_bar"
								      class="android.widget.ImageView"
								      package="com.google.android.providers.media.module"
								      content-desc=""
								      checkable="false"
								      checked="false"
								      clickable="false"
								      enabled="true"
								      focusable="false"
								      focused="false"
								      scrollable="false"
								      long-clickable="false"
								      password="false"
								      selected="false"
								      bounds="[498,939][582,950]"/>
								<node index="1"
								      text="This app can only access the photos you select"
								      resource-id="com.google.android.providers.media.module:id/privacy_text"
								      class="android.widget.TextView"
								      package="com.google.android.providers.media.module"
								      content-desc=""
								      checkable="false"
								      checked="false"
								      clickable="false"
								      enabled="true"
								      focusable="false"
								      focused="false"
								      scrollable="false"
								      long-clickable="false"
								      password="false"
								      selected="false"
								      bounds="[248,1013][832,1052]"/>
								<node index="2"
								      text=""
								      resource-id=""
								      class="android.widget.FrameLayout"
								      package="com.google.android.providers.media.module"
								      content-desc=""
								      checkable="false"
								      checked="false"
								      clickable="false"
								      enabled="true"
								      focusable="false"
								      focused="false"
								      scrollable="false"
								      long-clickable="false"
								      password="false"
								      selected="false"
								      bounds="[0,1094][1080,2337]">
									<node index="0"
									      text=""
									      resource-id="com.google.android.providers.media.module:id/fragment_container"
									      class="android.widget.FrameLayout"
									      package="com.google.android.providers.media.module"
									      content-desc=""
									      checkable="false"
									      checked="false"
									      clickable="false"
									      enabled="true"
									      focusable="false"
									      focused="false"
									      scrollable="false"
									      long-clickable="false"
									      password="false"
									      selected="false"
									      bounds="[0,1094][1080,2337]">
										<node index="0"
										      text=""
										      resource-id="com.google.android.providers.media.module:id/picker_tab_viewpager"
										      class="androidx.viewpager.widget.ViewPager"
										      package="com.google.android.providers.media.module"
										      content-desc=""
										      checkable="false"
										      checked="false"
										      clickable="false"
										      enabled="true"
										      focusable="false"
										      focused="false"
										      scrollable="true"
										      long-clickable="false"
										      password="false"
										      selected="false"
										      bounds="[0,1262][1080,2337]">
											<node index="0"
											      text=""
											      resource-id=""
											      class="androidx.recyclerview.widget.RecyclerView"
											      package="com.google.android.providers.media.module"
											      content-desc=""
											      checkable="false"
											      checked="false"
											      clickable="false"
											      enabled="true"
											      focusable="true"
											      focused="false"
											      scrollable="true"
											      long-clickable="false"
											      password="false"
											      selected="false"
											      bounds="[0,1262][1080,2337]">
												<node index="0"
												      text=""
												      resource-id=""
												      class="android.widget.FrameLayout"
												      package="com.google.android.providers.media.module"
												      content-desc=""
												      checkable="false"
												      checked="false"
												      clickable="false"
												      enabled="true"
												      focusable="false"
												      focused="false"
												      scrollable="false"
												      long-clickable="false"
												      password="false"
												      selected="false"
												      bounds="[0,1262][1080,2337]">
													<node index="0"
													      text=""
													      resource-id=""
													      class="android.widget.FrameLayout"
													      package="com.google.android.providers.media.module"
													      content-desc=""
													      checkable="false"
													      checked="false"
													      clickable="false"
													      enabled="true"
													      focusable="false"
													      focused="false"
													      scrollable="false"
													      long-clickable="false"
													      password="false"
													      selected="false"
													      bounds="[0,1262][1080,2337]">
														<node index="0"
														      text=""
														      resource-id="com.google.android.providers.media.module:id/picker_tab_recyclerview"
														      class="android.widget.GridView"
														      package="com.google.android.providers.media.module"
														      content-desc=""
														      checkable="false"
														      checked="false"
														      clickable="false"
														      enabled="true"
														      focusable="true"
														      focused="false"
														      scrollable="false"
														      long-clickable="false"
														      password="false"
														      selected="false"
														      bounds="[0,1262][1080,2337]">
															<node index="0"
															      text="Recent"
															      resource-id="com.google.android.providers.media.module:id/date_header_title"
															      class="android.widget.TextView"
															      package="com.google.android.providers.media.module"
															      content-desc=""
															      checkable="false"
															      checked="false"
															      clickable="false"
															      enabled="true"
															      focusable="false"
															      focused="false"
															      scrollable="false"
															      long-clickable="false"
															      password="false"
															      selected="false"
															      bounds="[0,1262][1080,1409]"/>
															<node index="1"
															      text=""
															      resource-id=""
															      class="android.widget.FrameLayout"
															      package="com.google.android.providers.media.module"
															      content-desc="Photo taken on Dec 11, 2024, 10:43:55 PM"
															      checkable="false"
															      checked="false"
															      clickable="true"
															      enabled="true"
															      focusable="true"
															      focused="false"
															      scrollable="false"
															      long-clickable="true"
															      password="false"
															      selected="false"
															      bounds="[0,1409][354,1764]">
																<node index="0"
																      text=""
																      resource-id=""
																      class="androidx.cardview.widget.CardView"
																      package="com.google.android.providers.media.module"
																      content-desc=""
																      checkable="false"
																      checked="false"
																      clickable="false"
																      enabled="true"
																      focusable="false"
																      focused="false"
																      scrollable="false"
																      long-clickable="false"
																      password="false"
																      selected="false"
																      bounds="[0,1409][354,1763]">
																	<node index="0"
																	      text=""
																	      resource-id=""
																	      class="android.widget.FrameLayout"
																	      package="com.google.android.providers.media.module"
																	      content-desc=""
																	      checkable="false"
																	      checked="false"
																	      clickable="false"
																	      enabled="true"
																	      focusable="false"
																	      focused="false"
																	      scrollable="false"
																	      long-clickable="false"
																	      password="false"
																	      selected="false"
																	      bounds="[0,1409][354,1763]">
																		<node index="0"
																		      text=""
																		      resource-id="com.google.android.providers.media.module:id/icon_thumbnail"
																		      class="android.widget.ImageView"
																		      package="com.google.android.providers.media.module"
																		      content-desc=""
																		      checkable="false"
																		      checked="false"
																		      clickable="false"
																		      enabled="true"
																		      focusable="false"
																		      focused="false"
																		      scrollable="false"
																		      long-clickable="false"
																		      password="false"
																		      selected="false"
																		      bounds="[0,1409][354,1763]"/>
																	</node>
																</node>
															</node>
															<node index="2"
															      text=""
															      resource-id=""
															      class="android.widget.FrameLayout"
															      package="com.google.android.providers.media.module"
															      content-desc="Photo taken on Dec 11, 2024, 10:43:33 PM"
															      checkable="false"
															      checked="false"
															      clickable="true"
															      enabled="true"
															      focusable="true"
															      focused="false"
															      scrollable="false"
															      long-clickable="true"
															      password="false"
															      selected="false"
															      bounds="[362,1409][717,1764]">
																<node index="0"
																      text=""
																      resource-id=""
																      class="androidx.cardview.widget.CardView"
																      package="com.google.android.providers.media.module"
																      content-desc=""
																      checkable="false"
																      checked="false"
																      clickable="false"
																      enabled="true"
																      focusable="false"
																      focused="false"
																      scrollable="false"
																      long-clickable="false"
																      password="false"
																      selected="false"
																      bounds="[362,1409][717,1764]">
																	<node index="0"
																	      text=""
																	      resource-id=""
																	      class="android.widget.FrameLayout"
																	      package="com.google.android.providers.media.module"
																	      content-desc=""
																	      checkable="false"
																	      checked="false"
																	      clickable="false"
																	      enabled="true"
																	      focusable="false"
																	      focused="false"
																	      scrollable="false"
																	      long-clickable="false"
																	      password="false"
																	      selected="false"
																	      bounds="[362,1409][717,1764]">
																		<node index="0"
																		      text=""
																		      resource-id="com.google.android.providers.media.module:id/icon_thumbnail"
																		      class="android.widget.ImageView"
																		      package="com.google.android.providers.media.module"
																		      content-desc=""
																		      checkable="false"
																		      checked="false"
																		      clickable="false"
																		      enabled="true"
																		      focusable="false"
																		      focused="false"
																		      scrollable="false"
																		      long-clickable="false"
																		      password="false"
																		      selected="false"
																		      bounds="[362,1409][717,1764]"/>
																	</node>
																</node>
															</node>
															<node index="3"
															      text=""
															      resource-id=""
															      class="android.widget.FrameLayout"
															      package="com.google.android.providers.media.module"
															      content-desc="Photo taken on Dec 11, 2024, 10:43:32 PM"
															      checkable="false"
															      checked="false"
															      clickable="true"
															      enabled="true"
															      focusable="true"
															      focused="false"
															      scrollable="false"
															      long-clickable="true"
															      password="false"
															      selected="false"
															      bounds="[725,1409][1080,1764]">
																<node index="0"
																      text=""
																      resource-id=""
																      class="androidx.cardview.widget.CardView"
																      package="com.google.android.providers.media.module"
																      content-desc=""
																      checkable="false"
																      checked="false"
																      clickable="false"
																      enabled="true"
																      focusable="false"
																      focused="false"
																      scrollable="false"
																      long-clickable="false"
																      password="false"
																      selected="false"
																      bounds="[725,1409][1080,1764]">
																	<node index="0"
																	      text=""
																	      resource-id=""
																	      class="android.widget.FrameLayout"
																	      package="com.google.android.providers.media.module"
																	      content-desc=""
																	      checkable="false"
																	      checked="false"
																	      clickable="false"
																	      enabled="true"
																	      focusable="false"
																	      focused="false"
																	      scrollable="false"
																	      long-clickable="false"
																	      password="false"
																	      selected="false"
																	      bounds="[725,1409][1080,1764]">
																		<node index="0"
																		      text=""
																		      resource-id="com.google.android.providers.media.module:id/icon_thumbnail"
																		      class="android.widget.ImageView"
																		      package="com.google.android.providers.media.module"
																		      content-desc=""
																		      checkable="false"
																		      checked="false"
																		      clickable="false"
																		      enabled="true"
																		      focusable="false"
																		      focused="false"
																		      scrollable="false"
																		      long-clickable="false"
																		      password="false"
																		      selected="false"
																		      bounds="[725,1409][1080,1764]"/>
																	</node>
																</node>
															</node>
															<node index="4"
															      text=""
															      resource-id=""
															      class="android.widget.FrameLayout"
															      package="com.google.android.providers.media.module"
															      content-desc="Photo taken on Dec 11, 2024, 10:43:30 PM"
															      checkable="false"
															      checked="false"
															      clickable="true"
															      enabled="true"
															      focusable="true"
															      focused="false"
															      scrollable="false"
															      long-clickable="true"
															      password="false"
															      selected="false"
															      bounds="[0,1772][354,2126]">
																<node index="0"
																      text=""
																      resource-id=""
																      class="androidx.cardview.widget.CardView"
																      package="com.google.android.providers.media.module"
																      content-desc=""
																      checkable="false"
																      checked="false"
																      clickable="false"
																      enabled="true"
																      focusable="false"
																      focused="false"
																      scrollable="false"
																      long-clickable="false"
																      password="false"
																      selected="false"
																      bounds="[0,1772][354,2126]">
																	<node index="0"
																	      text=""
																	      resource-id=""
																	      class="android.widget.FrameLayout"
																	      package="com.google.android.providers.media.module"
																	      content-desc=""
																	      checkable="false"
																	      checked="false"
																	      clickable="false"
																	      enabled="true"
																	      focusable="false"
																	      focused="false"
																	      scrollable="false"
																	      long-clickable="false"
																	      password="false"
																	      selected="false"
																	      bounds="[0,1772][354,2126]">
																		<node index="0"
																		      text=""
																		      resource-id="com.google.android.providers.media.module:id/icon_thumbnail"
																		      class="android.widget.ImageView"
																		      package="com.google.android.providers.media.module"
																		      content-desc=""
																		      checkable="false"
																		      checked="false"
																		      clickable="false"
																		      enabled="true"
																		      focusable="false"
																		      focused="false"
																		      scrollable="false"
																		      long-clickable="false"
																		      password="false"
																		      selected="false"
																		      bounds="[0,1772][354,2126]"/>
																	</node>
																</node>
															</node>
														</node>
													</node>
												</node>
											</node>
										</node>
									</node>
									<node index="1"
									      text=""
									      resource-id=""
									      class="android.widget.LinearLayout"
									      package="com.google.android.providers.media.module"
									      content-desc=""
									      checkable="false"
									      checked="false"
									      clickable="false"
									      enabled="true"
									      focusable="false"
									      focused="false"
									      scrollable="false"
									      long-clickable="false"
									      password="false"
									      selected="false"
									      bounds="[0,1094][1080,1262]">
										<node index="0"
										      text=""
										      resource-id="com.google.android.providers.media.module:id/toolbar"
										      class="android.view.ViewGroup"
										      package="com.google.android.providers.media.module"
										      content-desc=""
										      checkable="false"
										      checked="false"
										      clickable="false"
										      enabled="true"
										      focusable="false"
										      focused="false"
										      scrollable="false"
										      long-clickable="false"
										      password="false"
										      selected="false"
										      bounds="[0,1094][1080,1262]">
											<node index="0"
											      text=""
											      resource-id=""
											      class="android.widget.ImageButton"
											      package="com.google.android.providers.media.module"
											      content-desc="Cancel"
											      checkable="false"
											      checked="false"
											      clickable="true"
											      enabled="true"
											      focusable="true"
											      focused="false"
											      scrollable="false"
											      long-clickable="false"
											      password="false"
											      selected="false"
											      bounds="[0,1104][147,1251]"/>
											<node index="1"
											      text=""
											      resource-id="com.google.android.providers.media.module:id/tab_layout"
											      class="android.widget.HorizontalScrollView"
											      package="com.google.android.providers.media.module"
											      content-desc=""
											      checkable="false"
											      checked="false"
											      clickable="false"
											      enabled="true"
											      focusable="true"
											      focused="false"
											      scrollable="false"
											      long-clickable="false"
											      password="false"
											      selected="false"
											      bounds="[267,1115][813,1241]">
												<node index="0"
												      text=""
												      resource-id=""
												      class="android.widget.LinearLayout"
												      package="com.google.android.providers.media.module"
												      content-desc=""
												      checkable="false"
												      checked="false"
												      clickable="false"
												      enabled="true"
												      focusable="false"
												      focused="false"
												      scrollable="false"
												      long-clickable="false"
												      password="false"
												      selected="false"
												      bounds="[267,1115][813,1241]">
													<node index="0"
													      text=""
													      resource-id=""
													      class="android.widget.LinearLayout"
													      package="com.google.android.providers.media.module"
													      content-desc="Photos"
													      checkable="false"
													      checked="false"
													      clickable="false"
													      enabled="true"
													      focusable="true"
													      focused="false"
													      scrollable="false"
													      long-clickable="false"
													      password="false"
													      selected="true"
													      bounds="[267,1115][540,1241]">
														<node index="0"
														      text="Photos"
														      resource-id=""
														      class="android.widget.TextView"
														      package="com.google.android.providers.media.module"
														      content-desc=""
														      checkable="false"
														      checked="false"
														      clickable="false"
														      enabled="true"
														      focusable="false"
														      focused="false"
														      scrollable="false"
														      long-clickable="false"
														      password="false"
														      selected="true"
														      bounds="[345,1152][461,1203]"/>
													</node>
													<node index="1"
													      text=""
													      resource-id=""
													      class="android.widget.LinearLayout"
													      package="com.google.android.providers.media.module"
													      content-desc="Albums"
													      checkable="false"
													      checked="false"
													      clickable="true"
													      enabled="true"
													      focusable="true"
													      focused="false"
													      scrollable="false"
													      long-clickable="false"
													      password="false"
													      selected="false"
													      bounds="[540,1115][813,1241]">
														<node index="0"
														      text="Albums"
														      resource-id=""
														      class="android.widget.TextView"
														      package="com.google.android.providers.media.module"
														      content-desc=""
														      checkable="false"
														      checked="false"
														      clickable="false"
														      enabled="true"
														      focusable="false"
														      focused="false"
														      scrollable="false"
														      long-clickable="false"
														      password="false"
														      selected="false"
														      bounds="[614,1152][739,1203]"/>
													</node>
												</node>
											</node>
											<node index="2"
											      text=""
											      resource-id=""
											      class="androidx.appcompat.widget.LinearLayoutCompat"
											      package="com.google.android.providers.media.module"
											      content-desc=""
											      checkable="false"
											      checked="false"
											      clickable="false"
											      enabled="true"
											      focusable="false"
											      focused="false"
											      scrollable="false"
											      long-clickable="false"
											      password="false"
											      selected="false"
											      bounds="[975,1104][1080,1251]">
												<node index="0"
												      text=""
												      resource-id=""
												      class="android.widget.ImageView"
												      package="com.google.android.providers.media.module"
												      content-desc="More options"
												      checkable="false"
												      checked="false"
												      clickable="true"
												      enabled="true"
												      focusable="true"
												      focused="false"
												      scrollable="false"
												      long-clickable="true"
												      password="false"
												      selected="false"
												      bounds="[975,1114][1080,1240]"/>
											</node>
										</node>
									</node>
								</node>
							</node>
						</node>
					</node>
				</node>
			</node>
		</node>
		<node index="1"
		      text=""
		      resource-id="android:id/navigationBarBackground"
		      class="android.view.View"
		      package="com.google.android.providers.media.module"
		      content-desc=""
		      checkable="false"
		      checked="false"
		      clickable="false"
		      enabled="true"
		      focusable="false"
		      focused="false"
		      scrollable="false"
		      long-clickable="false"
		      password="false"
		      selected="false"
		      bounds="[0,2337][1080,2400]"/>
	</node>
</hierarchy>
```

</details>

### Actual results

I get the following error:
<details>
<summary>Logs</summary>

```
Unhandled exception:
FormatException: Unterminated string (at character 1013)
...http4k.core.Http4kKt$then$2$1.invoke(Http4k.kt:15)\n\tat pl.leancode.patrol
                                                                              ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:492:9)
#2      _parseJson (dart:convert-patch/convert_patch.dart:37:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      PatrolLogReader.parseEntry (package:patrol_log/src/patrol_log_reader.dart:142:18)
#7      PatrolLogReader._parsePatrolLog (package:patrol_log/src/patrol_log_reader.dart:102:21)
#8      PatrolLogReader.parse (package:patrol_log/src/patrol_log_reader.dart:88:7)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#14     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#15     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:164:13)
#16     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131:7)
#17     StringConversionSink.add (dart:convert/string_conversion.dart:39:5)
#18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#22     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#23     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#24     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#25     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#26     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#27     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#28     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#34     _StreamController._add (dart:async/stream_controller.dart:658:7)
#35     _StreamController.add (dart:async/stream_controller.dart:606:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2455:41)
#37     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#41     _StreamController._add (dart:async/stream_controller.dart:658:7)
#42     _StreamController.add (dart:async/stream_controller.dart:606:5)
#43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1942:33)
#44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1385:14)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

```

</details>

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

  patrol: ^3.13.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.4.1
Flutter command: flutter 
  Flutter 3.24.4 • channel stable
Android: 
• Program adb found in /Users/jonasrosskamp/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/jonasrosskamp/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by jBorkowska** [comment]
Hi @Friesenjung , I think there are 2 separate issues:
- printing logs failed (visible in Logs that you posted) @pdenert please take a look at it
- there are a lot of FrameLayouts on this screen, also instance argument can be flaky. Try using content description of those photos, eg. `content-desc="Photo taken on Dec 11, 2024, 10:43:30 PM"`

Hope it helps

**Comment by Friesenjung** [comment]
I might be able to choose a specific photo depending on the content-desc attribute, but that does not help if I want to share the test code with my team mate. He has a photo, taken at another time.
I would like to have the possibility to choose the first photo of the gallery.

**Comment by pdenert** [comment]
1. Printing logs should be fixed, after releasing changes from this PR: https://github.com/leancodepl/patrol/pull/2481
2. Second problem is that `AndroidSelector` can't handle `instance` in `bySelector` and we need to change code to handle this.
