### ISSUE TITLE
patrol develop not working

### ISSUE THREAD

**Issue by WaseemAlBizreh** [leancodepl/patrol#2453]
patrol develop not working but patrol test working:

1. **Error:** 

when run patrol test it work:
PS D:\ITE\Study\StudioProjects\Freelance\test_patrol> patrol test -t integration_test/example_test.dart   
No device specified, using the first one (R58M35WRQ4K)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (14.5s)
• Executing tests of apk with entrypoint test_bundle.dart on device R58M35WRQ4K...

Test summary:
📝 Total: 0
✅ Successful: 0
❌ Failed: 0
⏩ Skipped: 0
📊 Report: file://D:/ITE/Study/StudioProjects/Freelance/test_patrol/build/app/reports/androidTests/connected/index.html
⏱️  Duration: 4s

✓ Completed executing apk with entrypoint test_bundle.dart on device R58M35WRQ4K (4.7s)

but when use patrol develop it fails:

> patrol develop -t integration_test/example_test.dart
No device specified, using the first one (R58M35WRQ4K)
• Building apk with entrypoint test_bundle.dart...
        Invalid depfile: D:\ITE\Study\StudioProjects\Freelance\test_patrol\.dart_tool\flutter_build\17721162f1b8729b3d17d9c407237993\kernel_snapshot_program.d
        Invalid depfile: D:\ITE\Study\StudioProjects\Freelance\test_patrol\.dart_tool\flutter_build\17721162f1b8729b3d17d9c407237993\kernel_snapshot_program.d     
        Invalid depfile: D:\ITE\Study\StudioProjects\Freelance\test_patrol\.dart_tool\flutter_build\17721162f1b8729b3d17d9c407237993\kernel_snapshot_program.d     
        Invalid depfile: D:\ITE\Study\StudioProjects\Freelance\test_patrol\.dart_tool\flutter_build\17721162f1b8729b3d17d9c407237993\kernel_snapshot_program.d     
        Unhandled exception:
        FileSystemException(uri=d:/ITE/Study/StudioProjects/Freelance/test_patrol/test/example_test.dart; message=StandardFileSystem only supports file:* and data:
* URIs)
        #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:35)
        #1      IncrementalCompiler._initializeExperimentalInvalidation (package:front_end/src/base/incremental_compiler.dart:1257)
        #2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/base/incremental_compiler.dart:306)
        <asynchronous suspension>
        #3      CompilerContext.clear (package:front_end/src/base/compiler_context.dart:128)
        <asynchronous suspension>
        #4      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:77)
        <asynchronous suspension>
        #5      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:636)
        <asynchronous suspension>
        #6      starter (package:frontend_server/starter.dart:109)
        <asynchronous suspension>
        #7      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
        <asynchronous suspension>

        Target kernel_snapshot_program failed: Exception

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:compileFlutterBuildDebug'.
        > Process 'command 'D:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        > Get more help at https://help.gradle.org.

        BUILD FAILED in 6s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (7.8s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:81:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:51:5)
<asynchronous suspension>
#3      DevelopCommand._build (package:patrol_cli/src/commands/develop.dart:271:7)
<asynchronous suspension>
#4      DevelopCommand.run (package:patrol_cli/src/commands/develop.dart:239:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:20)
<asynchronous suspension>

2. **My Code:**
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

void main() {
  patrolTest(
    'counter state is the same after going to home and switching apps',
    framePolicy: LiveTestWidgetsFlutterBindingFramePolicy.fullyLive,
    ($) async {
      // Replace later with your app's main widget
      await $.pumpWidgetAndSettle(
        MaterialApp(
          home: Scaffold(
            appBar: AppBar(title: const Text('app')),
            backgroundColor: Colors.blue,
          ),
        ),
      );

      expect($('app'), findsOneWidget);
    },
  );
}

3. **Patrol info:**
Patrol CLI version: 3.4.1
Flutter command: flutter
  Flutter 3.24.5 • channel stable
Android:
• Program adb found in C:\Users\USER\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to C:\Users\USER\AppData

  patrol: ^3.13.1
  
 4. **flutter doctor:** :
 [√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.19045.5131], locale en-US)
    • Flutter version 3.24.5 on channel stable at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (5 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\USER\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM A305F (mobile) • R58M35WRQ4K • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.5131]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 131.0.6778.140
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 131.0.2903.99

[√] Network resources
    • All expected network resources are available.

**Comment by WaseemAlBizreh** [comment]
![Uploading Screenshot 2024-12-18 100428.png…]()

**Comment by WaseemAlBizreh** [comment]
my app work when i type command: flutter clean then flutter pub get.
**But**
new problem appear:
when i type command : patrol develop -t integration_test/example_test.dart
it run but the app not open or show in screen :

PS D:\ITE\Study\StudioProjects\Freelance\test_patrol> patrol develop -t integration_test/example_test.dart
No device specified, using the first one (R58M35WRQ4K)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (17.3s)
• Executing tests of apk with entrypoint test_bundle.dart on device R58M35WRQ4K...
Hot Restart: logs connected
[WARN] Hot Restart: not attached to the app yet
✓ Completed executing apk with entrypoint test_bundle.dart on device R58M35WRQ4K (4.1s)

app not open or work

**Comment by WaseemAlBizreh** [comment]
i try now to apply patrol in real app that i develop about 3 month:

the error is :
PS D:\ITE\Study\StudioProjects\Freelance\aklat24_new> patrol test -t integration_test/example_test.dart --device 'SM A305F'
• Building apk with entrypoint test_bundle.dart...

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:processDebugAndroidTestManifest'.
        > Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
           > Could not resolve androidx.test:runner:1.5.2.
             Required by:
                 project :app
                 project :app > androidx.test.espresso:espresso-core:3.5.1
              > Cannot find a version of 'androidx.test:runner' that satisfies the version constraints:
                   Dependency path 'android:app:unspecified' --> 'androidx.test:runner:1.5.2'
                   Constraint path 'android:app:unspecified' --> 'androidx.test:runner:{strictly 1.5.1}' because of the following reason: debugRuntimeClasspath use
s version 1.5.1
                   Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.5.1' (runtime) --> 'androidx.test:runner:1.5.2'

           > Could not resolve androidx.test.espresso:espresso-core:3.5.1.
             Required by:
                 project :app
              > Cannot find a version of 'androidx.test.espresso:espresso-core' that satisfies the version constraints:
                   Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.5.1'
                   Constraint path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:{strictly 3.5.0}' because of the following reason: debugRunt
imeClasspath uses version 3.5.0

           > Could not resolve androidx.test:runner:{strictly 1.5.1}.
             Required by:
                 project :app
              > Cannot find a version of 'androidx.test:runner' that satisfies the version constraints:
                   Dependency path 'android:app:unspecified' --> 'androidx.test:runner:1.5.2'
                   Constraint path 'android:app:unspecified' --> 'androidx.test:runner:{strictly 1.5.1}' because of the following reason: debugRuntimeClasspath use
s version 1.5.1
                   Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.5.1' (runtime) --> 'androidx.test:runner:1.5.2'

           > Could not resolve androidx.test.espresso:espresso-core:{strictly 3.5.0}.
             Required by:
                 project :app
              > Cannot find a version of 'androidx.test.espresso:espresso-core' that satisfies the version constraints:
                   Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.5.1'
                   Constraint path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:{strictly 3.5.0}' because of the following reason: debugRunt
imeClasspath uses version 3.5.0


        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 7s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (55.6s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:110:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:51:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:332:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:250:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///C:/Users/USER/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:20)
<asynchronous suspension>
