### ISSUE TITLE
Test run failed to complete. Instrumentation run failed due to Process crashed.

### ISSUE THREAD

**Issue by ahmedsalamay** [leancodepl/patrol#2472]
### Steps to reproduce

using  patrol develop --target=integration_test/login_test.dart --debug --verbose the following error appears, tested on  ]API_35(AVD) - 15 and ]API_34(AVD) - 14,
this issue occured after upgrading to FLutter 3.27

### Actual results

  : > Task :app:connectedDebugAndroidTest
        : Starting 0 tests on SM-A528B - 14
        : 
        : Finished 0 tests on SM-A528B - 14
        : 
        : > Task :app:connectedDebugAndroidTest
        Test run failed to complete. Instrumentation run failed due to Process crashed.
        : 

        : > Task :app:connectedDebugAndroidTest FAILED
        :
        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:connectedDebugAndroidTest'.
        See the report at: file:///C:/Users/Ahmed%20Salama/Development/CDWS/admin-mobile/cdws_admin/build/app/reports/androidTests/connected/debug/index.html

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        > Get more help at https://help.gradle.org.

        BUILD FAILED in 1m 1s
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
        :
        : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        :
        : For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
        : 394 actionable tasks: 6 executed, 388 up-to-date

Test summary:
📝 Total: 0
✅ Successful: 0
❌ Failed: 0
⏩ Skipped: 0
📊 Report: file://C:/Users/Ahmed%20Salama/Development/CDWS/admin-mobile/cdws_admin/build/app/reports/androidTests/connected/index.html
⏱️  Duration: 62s

✗ Failed to execute tests of apk with entrypoint test_bundle.dart on device RZCRC05NG9K (Gradle test execution failed with code 1) (62.2s)
Exception: Gradle test execution failed with code 1
#0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:310:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:230:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:392:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:265:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///C:/Users/Ahmed%20Salama/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:20)       
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Uninstalling com.cdws.cdws_admin from SM A528B
Uninstalling com.cdws.cdws_admin.test from SM A528B

### Patrol version

patrol: ^3.13.2
patrol_finders: ^2.6.0
 patrol_cli: ^3.4.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
> patrol doctor      
Can't load Kernel binary: Invalid kernel binary format version.
Patrol doctor:
Patrol CLI version: 3.4.1
Flutter command: flutter
  Flutter 3.27.1 • channel stable
Android:
• Program adb found in C:\Users\Ahmed Salama\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to C:\Users\Ahmed Salama\AppData\Local\Android\Sdk  
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.22631.4602],
    locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.42)
[!] Android Studio (version 2023.1)
    X Unable to find bundled Java version.
[√] Android Studio (version 2024.2)
[!] Android Studio (version unknown)
    X Unable to determine Android Studio version.
    X android-studio-dir = C:\Program Files\Android\Android Studio
    X Unable to determine bundled Java version.
[√] VS Code (version 1.96.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by jigar-f** [comment]
I am still using Flutter 3.24.5 and getting the same issue.

**Comment by zoskar** [comment]
Hi @ahmedsalamay 
Could you also attach `adb logcat` logs?

**Comment by pdenert** [comment]
Close due to lack of response. For future visitors this bug should be fixed in newest patrol - 3.14.0 and patrol_cli - 3.5.0
