### ISSUE TITLE
I am not able to run Patrol, setup guide not working

### ISSUE THREAD

**Issue by dishankjindal1** [leancodepl/patrol#2473]
### Discussed in https://github.com/leancodepl/patrol/discussions/2471

<div type='discussions-op-text'>

<sup>Originally posted by **dishankjindal1** December 25, 2024</sup>
```
• Building apk with entrypoint test_bundle.dart...
        You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

        You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        Note: /Users/dishankjindal/.puro/shared/pub_cache/hosted/pub.dev/firebase_messaging-14.7.10/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
        Note: Recompile with -Xlint:unchecked for details.

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:processDevDebugResources'.
        > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
           > Android resource linking failed
             aapt2 E 12-25 19:56:07 62486 477931 LoadedArsc.cpp:94] RES_TABLE_TYPE_TYPE entry offsets overlap actual entry data.
             aapt2 E 12-25 19:56:07 62486 477931 ApkAssets.cpp:149] Failed to load resources table in APK '/Users/dishankjindal/Library/Android/sdk/platforms/android-35/android.jar'.
             error: failed to load include path /Users/dishankjindal/Library/Android/sdk/platforms/android-35/android.jar.


        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 5s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (6.3s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:81:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:51:5)
<asynchronous suspension>
#3      DevelopCommand._build (package:patrol_cli/src/commands/develop.dart:271:7)
<asynchronous suspension>
#4      DevelopCommand.run (package:patrol_cli/src/commands/develop.dart:239:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///Users/dishankjindal/.puro/shared/pub_cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:20)
<asynchronous suspension>
```</div>

**Comment by unacorbatanegra** [comment]
and were you able to run `flutter build appbundle` without issues?

**Comment by dishankjindal1** [comment]
I am seeing this


sample code which i am trying to run
```
void main() {
  patrolTest(
    'counter state is the same after going to home and going back',
    framePolicy: LiveTestWidgetsFlutterBindingFramePolicy.fullyLive,
    config: const PatrolTesterConfig(printLogs: true),
    ($) async {
      await $.pumpWidgetAndSettle(MaterialApp(
        home: Scaffold(
          floatingActionButton: FloatingActionButton(onPressed: () {}),
        ),
      ));

      await Future.delayed(const Duration(seconds: 10));

      await $(FloatingActionButton).tap();
      await Future.delayed(const Duration(seconds: 10));

      expect($(FloatingActionButton).tap(), '1');

    },
  );
}
```

```
No device specified, using the first one (adb-351e13d3-zMfBkI._adb-tls-connect._tcp)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (19.8s)
• Executing tests of apk with entrypoint test_bundle.dart on device adb-351e13d3-zMfBkI._adb-tls-connect._tcp...
        Waiting for another flutter command to release the startup lock...
Hot Restart: logs connected
[WARN] Hot Restart: not attached to the app yet
✓ App shut down on request (12.5s)
```

**Comment by zoskar** [comment]
Hi @dishankjindal1, thanks for your report. 
Could you check if the problem will be the same on emulator with older Android version than 15/api_35? We have a known bug for it https://github.com/leancodepl/patrol/issues/2438 so this might be a problem in your case.

**Comment by dishankjindal1** [comment]
Okay okay @github-actions sorry i forgot about this. Will test and share within next day.

**Comment by AurelienKun** [comment]
@dishankjindal1 I had this error a bunch of times and solved it by doing a `flutter clean && melos bootstrap` (the last one is to recheck the dependencies of all projects of our monorepo using the melos tool). Then patrol test/develop works again.

**Comment by dishankjindal1** [comment]
This is coming with the latest version of patrol

`Execution failed for task ':app:connectedDevDebugAndroidTest'`

**Comment by koraxis** [comment]
I have the same issue, but `flutter clean`, `flutter pub get`, and even `melos bootstrap` do not help. Additionally, I am not targeting an emulator with API 35.

**Comment by dishankjindal1** [comment]
I had mate it working, at-least for android, FYI. not sure if ios will work. haven't tried yet.

I had migrated to the latest flutter versions with java 21 and all the recommended versions setup.
