### ISSUE TITLE
Null check exception when running `patrol doctor`

### ISSUE THREAD

**Issue by matthew-carroll** [leancodepl/patrol#2475]
When I run `patrol doctor` after installing the CLI, I get the following output:

```
Patrol doctor:
Patrol CLI version: 3.4.1
Flutter command: flutter 
  Flutter 3.27.1 • channel stable
Android: 
• Program adb found in /Users/admin/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME is not set. (See the link: https://developer.android.com/tools/variables#set)
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Unhandled exception:
Null check operator used on a null value
#0      PatrolCommand.flutterCommand (package:patrol_cli/src/runner/patrol_command.dart:241:30)
#1      DoctorCommand._printFlutterInfo (package:patrol_cli/src/commands/doctor.dart:49:17)
#2      DoctorCommand.run (package:patrol_cli/src/commands/doctor.dart:30:5)
#3      PatrolCommandRunner._runDoctor (package:patrol_cli/src/runner/patrol_command_runner.dart:408:57)
#4      PatrolCommandRunner._handleFirstRun (package:patrol_cli/src/runner/patrol_command_runner.dart:378:7)
#5      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:300:7)
#6      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:33)
#7      main (file:///Users/admin/.pub-cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:26)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by MarlonDSC** [comment]
Add your `ANDROID_HOME` environment variable

**Comment by matthew-carroll** [comment]
I'll give that a try and report back. Even if that's the issue, there probably shouldn't be a situation where a stacktrace error is reported for a known piece of missing info.
