### ISSUE TITLE
Patrol test failing at ":app:connectedDebugAndroidTest"

### ISSUE THREAD

**Issue by Shpaner** [leancodepl/patrol#2476]
### Steps to reproduce

1. Clone [patrol-idx-demo](https://github.com/leancodepl/patrol-idx-demo) and open it.
2. Set up patrol as prescribed in docs: `flutter pub global activate patrol_cli`
3. Run: `patrol test -t integration_test/example_test.dart`

### Actual results

Tests keep failing at _:app:connected{flavor}AndroidTest_ no matter which project I use.

<img width="1325" alt="Screenshot 2024-12-30 at 18 34 00" src="https://github.com/user-attachments/assets/ee2d8f98-e20b-48ef-b698-4379d5620529" />

### Logs

<details>
<summary>Logs</summary>

```
https://pastebin.com/EeEkpg4r
```

</details>

### Patrol version

patrol_cli v3.4.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.3 23D2057 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.3 23D2057 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Tobi. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by zoskar** [comment]
Hi @Shpaner 
Could you also add logs from `adb logcat`?

**Comment by Shpaner** [comment]
> Hi @Shpaner Could you also add logs from `adb logcat`?

[patrol-test-logcat.txt](https://github.com/user-attachments/files/18331498/patrol-test-logcat.txt)

**Comment by zoskar** [comment]
@Shpaner Could you resend the logcat by running `adb logcat` and then running the test in another console? Sorry for not specifying that right away.

**Comment by Shpaner** [comment]
> I don't quite see any Patrol related logs. Please try:
> 
> 1. run `adb logcat -T 1 > adblog.txt` in first terminal
> 2. run `patrol test -t integration_test/example_test.dart` in second terminal
> 3. once the tests in the second terminal finish and fail, stop Logcat in the first terminal (`Ctrl + C`). The log file (adblog.txt) will be saved in the current directory of the first terminal. Please send us this log file.
> 
> Hopefully this will result in some useful information that we could check

[adblog.txt](https://github.com/user-attachments/files/18344078/adblog.txt)
@zoskar please let me know if this is enough for you.

**Comment by zoskar** [comment]
Unfortunately still no Patrol logs are visible. We will take a look at this on our end

**Comment by DmytroChuchmaiBarges** [comment]
Hi, it often helps to run "cd ./android && ./gradlew :clean && cd .." from the project root folder. then build an app with "flutter build apk" command  and run the tests after

**Comment by dhirajhimani** [comment]
These logs might help, facing the issue, tried number of different approaches

> Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (19.0s)
> Exception: Gradle test execution failed with code 1
> #0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:310:9)
> <asynchronous suspension>
> #1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
> <asynchronous suspension>
> #2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:230:5)
> <asynchronous suspension>
> #3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:392:7)
> <asynchronous suspension>
> #4      TestCommand.run (package:patrol_cli/src/commands/test.dart:265:23)
> <asynchronous suspension>
> #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
> <asynchronous suspension>
> #6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:366:18)
> <asynchronous suspension>
> #7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
> <asynchronous suspension>
> #8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
> <asynchronous suspension>
> #9      main (file:///Users/dhiraj.himani/.pub-cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:20)
> <asynchronous suspension>

**Comment by Zujaj** [comment]
Hmm....this seems to be related to Android API Level 35 as per my observations. I used Patrol with my real device that has Android 12 (API Level 31) and found no errors. Similarly after quite trial, I installed Pixel 9 Pro API Level 31 on Android Studio and now everything seems to work fine as expected. 

P.S: I added the `test_bundle.dart` to `.gitignore` as it seems that it's a Patrol generated file that could keep on changing if the tests are performed on iOS and Android in a single monorepo project.

**Comment by istornz** [comment]
Hi, same issue here

**Comment by Kendru98** [comment]
Should be fixed, can anyone confirm?

**Comment by 0ttik** [comment]
I can confirm that the issue occurs, I observe it on Android API level 36 Android Studio emulator. When switched to Android API 34 everything works fine. 

1) `:app:connectedDebugAndroidTest` error in patrol test output (when running on emulator API 36)
2) Can see multiple `Binder transaction failure.` in logcat (not sure if it's ok or not)

Here's my logcat as well, hope it helps. 

[Medium-Phone-API-36.0-Android-16_2025-07-01_001540.txt](https://github.com/user-attachments/files/20993486/Medium-Phone-API-36.0-Android-16_2025-07-01_001540.txt)

**Comment by josephp-xpress** [comment]
Hi guys

I have similar problem, can anyone confirm this already fix? if not there is solution to fix the issue?

**Comment by Kendru98** [comment]
Please add more details @josephp-xpress patrol version / flutter version / cli version / emulator details logs from patrol test/develop with --verbose.

**Comment by josephp-xpress** [comment]
@Kendru98 
Patrol: 3.19.0
Flutter Version 3.32.8
cli version 3.10.0

**Comment by ghost** [comment]
Hello, 

I've also run into this issue which disappeared after 3 retries. I'll report back if I get more information. 

```
Patrol doctor:
Patrol CLI version: 4.0.2
Flutter command: flutter 
  Flutter 3.38.7 • channel stable
Patrol: 4.1.0

Device:
Samsung A36
Android 16
```

**Comment by Kendru98** [comment]
@josephp-xpress is your problem also with emulator with API 36? You can try some cleaning it helps sometimes with cases like this. Also is this possible that anyone of you guys with this problem can create minimal reproduction example in public repository? patrol idx_demo can be outdated, what about dev/e2e_app in our main patrol repo (it is working there for me)?
```
cd ./android && ./gradlew :clean && ./gradlew --stop && cd ..
rm -rf ./build
rm -rf ~/.gradle/caches
flutter clean
dart pub cache clean # this command remove pub packages and you'll need to install them manually
flutter pub get
```

**Comment by ghost** [comment]
@Kendru98 , tried running the e2e_app.

Following the steps in the README resulted in an error when building for android:
```
// Ran in repository root
dart pub global activate --source path packages/patrol_cli && patrol

// Ran in e2e_root project root
`patrol build android --verbose`.
```

```
$ flutter build apk --config-only -t <replaced>/patrol/dev/e2e_app/patrol_test/test_bundle.dart
$ flutter doctor --verbose
$ ./gradlew :app:dependencies

....lots of logs



        : > Task :app:compileFlutterBuildDebug FAILED
        : 
        : [Incubating] Problems report is available at: file:///<replaced>/patrol/dev/e2e_app/build/reports/problems/problems-report.html
        : 
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
        : 
        : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        : 
        : For more on this, please refer to https://docs.gradle.org/8.12/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
        : 7 actionable tasks: 3 executed, 4 up-to-date
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:compileFlutterBuildDebug'.
        > Process 'command '<replaced>/flutter/bin/flutter'' finished with non-zero exit value 1
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        > Get more help at https://help.gradle.org.
        
        BUILD FAILED in 7s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (7.2s)
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:84:9)
<asynchronous suspension>                                                                                                                                                                    
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)                                                                                                                 
<asynchronous suspension>                                                                                                                                                                    
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:52:5)                                                                                             
<asynchronous suspension>                                                                                                                                                                    
#3      BuildAndroidCommand.run (package:patrol_cli/src/commands/build_android.dart:199:7)                                                                                                   
<asynchronous suspension>                                                                                                                                                                    
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)                                                                                                                   
<asynchronous suspension>                                                                                                                                                                    
#5      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:405:18)                                                                                     
<asynchronous suspension>                                                                                                                                                                    
#6      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:343:18)                                                                                            
<asynchronous suspension>                                                                                                                                                                    
#7      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:80:20)                                                                                                 
<asynchronous suspension>                                                                                                                                                                    
#8      main (file:///<replaced>/patrol/packages/patrol_cli/bin/main.dart:6:20)                                                                                                  
<asynchronous suspension>                                                                                                                                                                    
                            
```

**Comment by zoskar** [comment]
In my experience wiping data from emulator helps with this issue

**Comment by Kendru98** [comment]
@keith-lytc in your logs you did not remove <replaced> - I think that issue is not a patrol issue, it is a user environment issue. Also IDX example from our docs should work correctly now, you can check example if you have some problems
