### ISSUE TITLE
Can't launch example test with patrol drive on iOS

### ISSUE THREAD

**Issue by vrnvorona** [leancodepl/patrol#340]
Cloned repo
cd to example
patrol drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart

<details>
<summary>error details</summary>

```
objc[98617]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1d9687620) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106888598). One of the two will be used. Which one is undefined.
objc[98617]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1d9687670) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1068885e8). One of the two will be used. Which one is undefined.
objc[98617]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1d96876c0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106888638). One of the two will be used. Which one is undefined.
objc[98617]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1d9687710) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106888688). One of the two will be used. Which one is undefined.
objc[98617]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1d9687760) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1068886d8). One of the two will be used. Which one is undefined.

objc[98617]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1d96877b0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106888728). One of the two will be used. Which one is undefined.

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
{ platform:iOS Simulator, OS:latest, name:iPhone X }

Available destinations for the "AutomatorServer" scheme:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-0011056E1E23001E }

Ineligible destinations for the "AutomatorServer" scheme:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }

```

</details>

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel 3.3, 3.1.0-0.0.pre.2492, on macOS 12.5.1 21G83 darwin-arm, locale en-RU)
    • Flutter version 3.1.0-0.0.pre.2492 on channel 3.3 at /Users/user/fvm/versions/3.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db51e5d944 (4 weeks ago), 2022-08-25 12:42:21 -0700
    • Engine revision b9ba679200
    • Dart version 2.19.0 (build 2.19.0-139.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Users/user/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-13.0.0.app/Contents/Developer
    • Build 13A233
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.4)
    • IntelliJ at /Users/user/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.6008.17

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone X (mobile) • 8206781A-FA79-4AFE-B4A2-309A1DFFE8C7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by bartekpacia** [comment]
Hello @vrnvorona 👋 Thanks for reporting the issue.

Could you please share the whole logs?

**Comment by bartekpacia** [comment]
Thanks for posting the log output. TBH I don't know what could be causing your issue, but this output is definitely strange:

```
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-0011056E1E23001E }
```

If you feel like tinkering, you can go to `~/.cache/patrol/ios-0.6.5`, then do `open AutomatorServer.xcodeproj` and try to fix the issue.

In the upcoming weeks, we plan to distribute ready-made `.app` files for iOS (the same as we do for Android), which will be both faster and less error-prone than what we do currently (distributing the Xcode project and making you compile it).

> Not really sure where I can get more logs

Add `--verbose` flag.

> Also, weirdly, -d doesn't work in my case (did work with android device):

You have to use `-d iPhone X` instead of the UUID. Sorry, this should be explained somewhere.

What version of XCode do you have installed?

**Comment by vrnvorona** [comment]
I use Xcode 13.0
I managed to get it running
I changed deployment target to 15.0 (it was 15.5 and not even seeing my simulator)
Also i removed Package.resolved because it was corrupted and not seeing Telegraph dependency

After than it launches, though fails instantly:

<details>
<summary>Details</summary>

```
00:00 +0: taps around
VMServiceFlutterDriver: Connected to Flutter application.
Patrol: action openQuickSettings executing
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following ClientException was thrown running a test:
Connection closed before full header was received
When the exception was thrown, this was the stack:
#0      IOClient.send (package:http/src/io_client.dart:90:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
<asynchronous suspension>
#3      NativeAutomator._wrapPost (package:patrol/src/native/native_automator.dart:112:22)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///Users/user/patrol/packages/patrol/example/integration_test/app_test.dart:11:7)
<asynchronous suspension>
#5      patrolTest.<anonymous closure> (package:patrol/src/custom_finders/common.dart:53:7)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:858:5)
<asynchronous suspension>
(elided one frame from dart:async)

```

</details>

> You have to use -d 'iPhone X' instead of the UUID. Sorry, this should be explained somewhere.

Ok, it works, though not intuitive since it works fine with Android, and native flutter commands use UDID as well. Maybe support both?

**Comment by bartekpacia** [comment]
> After than, it launches, though it fails instantly:

Looks like a problem on the iOS side. You can verify if the server is running by going to `localhost:8081` in your browser.

> Ok, it works, though not intuitive since it works fine with Android, and native flutter commands use UDID as well. Maybe support both?

I agree, we'll fix it. Thanks for the feedback.

**Comment by bartekpacia** [comment]
@vrnvorona Please let me know what you see after:

1. `$ patrol drive`
2. See the error you sent above
3. Visit localhost:8081 in your browser

Then I can help you further :)

**Comment by vrnvorona** [comment]
I see `Hello from AutomatorServer on iOS!` and tests are somewhat running, mini_test and permissions_test for example.

Seems fixed

**Comment by bartekpacia** [comment]
Nice. I'm going to close this but if you've got any more questions, just write and I'll reopen.

We'll keep an eye out for such strange issues, sorry that you encountered one of them.
