### ISSUE TITLE
Exception: error: listener not found while server install

### ISSUE THREAD

**Issue by M123-dev** [leancodepl/patrol#359]
I was about to try out Patrol but I wasn't able to get it to run due to the following exception.

<details>
  <summary>Excpetion</summary>
  
  
```
✗ Failed to install server (20.4s)
Exception: 299437 KB/s (4445442 bytes in 0.014s)

#0      Adb.install (package:adb/src/adb.dart:53:7)
<asynchronous suspension>
#1      AndroidDriver._forceInstallApk (package:patrol_cli/src/features/drive/platform/android_driver.dart:156:7)
#4      AndroidDriver._installServer (package:patrol_cli/src/features/drive/platform/android_driver.dart:42:5)
<asynchronous suspension>
#5      AndroidDriver.run (package:patrol_cli/src/features/drive/platform/android_driver.dart:33:5)
<asynchronous suspension>
#6      DriveCommand.execute (package:patrol_cli/src/features/drive/drive_command.dart:191:11)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/command_runner.dart:39:16)
<asynchronous suspension>
#9      main (file:///C:/Users/marvi/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/patrol_cli-0.6.5/bin/main.dart:6:20)
<asynchronous suspension>

error while disposing
Exception: error: listener not found
error: listener not found

#0      Adb.forwardPorts.<anonymous closure> (package:adb/src/adb.dart:150:9)
<asynchronous suspension>
#1      AndroidDriver._forwardPorts.<anonymous closure>.<anonymous closure> (package:patrol_cli/src/features/drive/platform/android_driver.dart:114:11)
<asynchronous suspension>
#2      DisposeScope.dispose (package:dispose_scope/src/dispose_scope.dart:36:7)
<asynchronous suspension>
#3      DisposeScope.dispose (package:dispose_scope/src/dispose_scope.dart:36:7)
<asynchronous suspension>
#4      DisposeScope.dispose (package:dispose_scope/src/dispose_scope.dart:36:7)
<asynchronous suspension>
#5      PatrolCommandRunner.dispose (package:patrol_cli/src/command_runner.dart:123:7)
<asynchronous suspension>
#6      patrolCommandRunner (package:patrol_cli/src/command_runner.dart:65:3)
<asynchronous suspension>
#7      main (file:///C:/Users/marvi/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/patrol_cli-0.6.5/bin/main.dart:6:20)
<asynchronous suspension>
```
</details>

<details>
  <summary>Install log</summary>

```
PS E:\111_Programming\Flutter\smooth-app\packages\smooth_app> dart pub global activate patrol_cli
Package patrol_cli is currently active at version 0.6.5.
Resolving dependencies...
+ _fe_analyzer_shared 48.0.0
+ adb 0.2.1+2
+ analyzer 5.0.0
+ ansi_styles 0.3.2+1
+ archive 3.3.1
+ args 2.3.1
+ async 2.9.0
+ boolean_selector 2.1.0
+ collection 1.16.0
+ convert 3.0.2
+ coverage 1.6.1
+ crypto 3.0.2
+ dispose_scope 2.0.0
+ file 6.1.4
+ freezed_annotation 2.1.0
+ frontend_server_client 3.0.0
+ glob 2.1.0
+ http 0.13.5
+ http_multi_server 3.2.1
+ http_parser 4.0.1
+ io 1.0.3
+ js 0.6.4
+ json_annotation 4.7.0
+ logging 1.0.2
+ mason_logger 0.1.3
+ matcher 0.12.12
+ meta 1.8.0
+ mime 1.0.2
+ mocktail 0.3.0
+ node_preamble 2.0.1
+ package_config 2.1.0
+ path 1.8.2
+ patrol_cli 0.6.5
+ platform 3.1.0
+ pool 1.5.1
+ process 4.2.4
+ pub_semver 2.1.1
+ pub_updater 0.2.2
+ shelf 1.4.0
+ shelf_packages_handler 3.0.1
+ shelf_static 1.1.1
+ shelf_web_socket 1.0.2
+ source_map_stack_trace 2.1.0
+ source_maps 0.10.10
+ source_span 1.9.1
+ stack_trace 1.10.0
+ stream_channel 2.1.1
+ string_scanner 1.1.1
+ term_glyph 1.2.1
+ test 1.21.6
+ test_api 0.4.14
+ test_core 0.4.18
+ typed_data 1.3.1
+ vm_service 9.4.0
+ watcher 1.0.1
+ web_socket_channel 2.2.0
+ webkit_inspection_protocol 1.2.0
+ yaml 3.1.1
Downloading test 1.21.6...
Downloading test_core 0.4.18...
Downloading test_api 0.4.14...
Downloading frontend_server_client 3.0.0...
Downloading analyzer 5.0.0...
Downloading _fe_analyzer_shared 48.0.0...
Building package executables...
Built patrol_cli:main.
Installed executable patrol.
Activated patrol_cli 0.6.5.
```

</details>

<details>
  <summary>`Flutter doctor -v`</summary>

```
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22000.978], locale de-DE)
    • Flutter version 3.3.2 on channel stable at C:\CommandLineProgramms\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\marvi\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\marvi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Users\marvi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683
    • Flutter plugin version 70.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Users\marvi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    • Flutter plugin version 70.0.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code, 64-bit edition (version 1.71.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 105.0.1343.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

I tried it with:

- Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
- API 31 emulator without Playstore
- Physical Samsung Galaxy S21 (SM-G991B)

Any idea how to fix this or what could cause this?

**Comment by bartekpacia** [comment]
Hi @M123-dev, I'm sorry that you encountered this problem. It looks like your `adb` command was printing some strange output to the terminal (`Exception: 299437 KB/s (4445442 bytes in 0.014s)`). I haven't seen it before.

Can you post the output of running `adb --version`? That's mine:
```
$ adb --version
Android Debug Bridge version 1.0.41
Version 33.0.3-8952118
Installed as /Users/bartek/androidsdk/platform-tools/adb
```

If yours is older, I recommend you try to update it to the newest version. You can do it through IntelliJ/Android Studio or by running `sdkmanager --update`.
