### ISSUE TITLE
Example app's `webview_test.dart` is flaky

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#428]
Most probably the cause is that we try to tap on the view before it exists. We should use something like `waitUntilVisible()` with a configurable timeout.

Should be fixed by #409.

Crash logs
```
Running webview_test.dart with flutter_driver on iPhone 14...
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:50764/rRNELTENjB8=/
VMServiceFlutterDriver: Isolate found with number: 3161786550536967
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
Patrol: creating NativeAutomator, host: localhost, port: 8081, packageName: pl.leancode.patrol.example, bundleId: pl.leancode.patrol.Example
Patrol: Initializing PatrolBinding...
00:00 +0: navigates through the app using only native semantics
VMServiceFlutterDriver: Connected to Flutter application.
Patrol: tap() started
WebView created
WebView is loading (progress : 10%)
Patrol: tap() succeeded
Patrol: tap() started
Patrol: tap() failed
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: tap() failed with code NOT_FOUND (view with text "Accept cookies" in app
"pl.leancode.patrol.Example" doesn't exist)
When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:137:7)
<asynchronous suspension>
#1      NativeAutomator.tap (package:patrol/src/native/native_automator.dart:370:5)
<asynchronous suspension>
#2      PatrolX.waitAndTap (file:///Users/bartek/dev/leancode/patrol/packages/patrol/example/integration_test/webview_test.dart:36:5)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///Users/bartek/dev/leancode/patrol/packages/patrol/example/integration_test/webview_test.dart:20:7)
<asynchronous suspension>
#4      patrolTest.<anonymous closure> (package:patrol/src/custom_finders/common.dart:60:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:5)
<asynchronous suspension>
The test description was:
  navigates through the app using only native semantics
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0: navigates through the app using only native semantics [E]
  Test failed. See exception logs above.
00:01 +0 -1: (tearDownAll)
Warning: integration_test plugin was not detected.
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
00:01 +1 -1: Some tests failed.
Failed to stop app
flutter_driver exited with code 1
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
```

**Comment by bartekpacia** [comment]
Should be fixed by #437
