### ISSUE TITLE
Bad state: no tests to run

### ISSUE THREAD

**Issue by lmlikota** [leancodepl/patrol#434]
### Screenshot
![image](https://user-images.githubusercontent.com/10289319/194852584-c92f62dd-48ef-4e0c-bc58-00dd97c0c220.png)

### Preconditions

1. Only one test in `integration_test` folder
```dart
//import 'package:flutter/cupertino.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:haven_bridge/main_common.dart';
import 'package:easy_localization/easy_localization.dart';
//import 'package:integration_test/integration_test.dart';
import 'package:patrol/patrol.dart';
import 'config.dart';

//import 'package:haven_bridge/main_qa.dart' as app;

void main() {
  patrolTest('sign in', config: patrolConfig, nativeAutomation: true,
      ($) async {
    //app.main();
    await EasyLocalization.ensureInitialized();
    await $.pumpWidgetAndSettle(const MyApp());

    await $.native.openApp();

    //await $.pumpWidgetAndSettle(const MyApp());

    //expect($('Saznajte više'), findsOneWidget);
    await $('Prijava').tap();

    await $(#emailTextField).enterText('luka.mlikota.zapovjednik@biss.hr');
    await $(#passwordTextField).enterText('password');
    await $(#loginButton).tap();

    expect($('Pregled intervencija'), findsOneWidget);
    await $.tap($('Sljedeće'));

    expect($('Odabir adrese'), findsOneWidget);
    await $.tap($('Sljedeće'));

    expect($('Voditelj intervencije'), findsOneWidget);
    await $.tap($('Sljedeće'));

    expect($('Uklanjanje vozila'), findsOneWidget);
    await $.tap($('Sljedeće'));

    expect($('Osvrt'), findsOneWidget);
    await $.tap($('Gotovo'));
    await $.pump(const Duration(seconds: 4));
    await $.native.grantPermissionWhenInUse();
  });
}
```
2. Latest version of `patrol_cli (0.6.14)`
3. Connected emulator or real device, in my case I'm using `VOG L29 (mobile)  • DUM0220811001124 • android-arm64  • Android 10 (API 29)`
```powershell
PS C:\Users\lmlikota\haven-bridge-mobile> flutter devices
4 connected devices:

VOG L29 (mobile)  • DUM0220811001124 • android-arm64  • Android 10 (API 29)
Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
Chrome (web)      • chrome           • web-javascript • Google Chrome 106.0.5249.103
Edge (web)        • edge             • web-javascript • Microsoft Edge 106.0.1370.37
```

### Steps to reproduce
1. Try to run all tests using `patrol drive --flavor development`

### Expected results
1. Test have been executed

### Actual result
1. Test didn't even run. Patrol CLI can't find test?
```powershell
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development
No device specified, using the first one (DUM0220811001124)
✓ Forwarded ports (88ms)
✓ Installed server (1.7s)
✓ Installed instrumentation (1.6s)
Bad state: no tests to run
#0      TestRunner.run (package:patrol_cli/src/features/drive/test_runner.dart:43:7)
#1      DriveCommand.execute (package:patrol_cli/src/features/drive/drive_command.dart:250:23)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#3      PatrolCommandRunner.runCommand (package:patrol_cli/src/command_runner.dart:210:18)
<asynchronous suspension>
#4      PatrolCommandRunner.run (package:patrol_cli/src/command_runner.dart:161:18)
<asynchronous suspension>
#5      patrolCommandRunner (package:patrol_cli/src/command_runner.dart:42:14)
<asynchronous suspension>
#6      main (file:///C:/Users/lmlikota/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/patrol_cli-0.6.14/bin/main.dart:6:20)
<asynchronous suspension>
```

**Comment by lmlikota** [comment]
I've also tried:

```powershell
PS C:\Users\lmlikota\haven-bridge-mobile>
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development -t patrollogin.dart 
Error: target file patrollogin.dart has invalid suffix
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development -t login           
Error: target file login has invalid suffix
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development --target login 
Error: target file login has invalid suffix
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development --target ./integration_test/login.dart
Error: target file ./integration_test/login.dart has invalid suffix
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development --target /integration_test/login.dart 
Error: target file /integration_test/login.dart has invalid suffix
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development --target ./login.dart                 
Error: target file ./login.dart has invalid suffix
PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development --target /integration_test/login.dart
Error: target file /integration_test/login.dart has invalid suffix
```

**Comment by bartekpacia** [comment]
Hi @lmlikota, thanks for this (very detailed!) bug report.

Test files must end with `_test.dart` for Patrol to find them. The same applies to Flutter's own tools, e.g `flutter test`.

**Comment by lmlikota** [comment]
You can always expected detailed bug reports from me even though sometimes 🐞 are just in my head.

I'm going to severely facapalm myself now 😄 I wasn't aware of that fact, it would be nice to state it in docs. Can I help you with docs somehow?

**Comment by bartekpacia** [comment]
Happy to help :) We should explain this better.

Thanks for offering help with the docs, but actually I'm adding it to docs right now (and fixing the docs site, which is down).

**Comment by bartekpacia** [comment]
PR is up: https://github.com/leancodepl/patrol/pull/435
