### ISSUE TITLE
Native methods don't work on some Android versions (12 and 13)

### ISSUE THREAD

**Issue by nehemiekoffi** [leancodepl/patrol#477]
Hi team, I have fully configured patrol on my flutter projet following this doc : https://patrol.leancode.co/native/setup

But I notice that all native methods doesn't work on Android 13 (API 33) and Android 12 (API 31). Yet it works well on Android 8.0 (API 26).

Here is the error message that I get : 
**java.lang.IllegalStateException: UiAutomationService**

```
The following PatrolActionException was thrown running a test:
Patrol action failed: pressHome() failed with code UNKNOWN (unknown error:
java.lang.IllegalStateException: UiAutomationService
android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@6827cefalready registered!)
When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:151:7)
<asynchronous suspension>
#1      NativeAutomator.pressHome (package:patrol/src/native/native_automator.dart:188:5)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/nehemie/Documents/Dev/Apps/front/djamo-agent-app/integration_test/app_test.dart:26:7)
<asynchronous suspension>
#3      patrolTest.<anonymous closure> (package:patrol/src/custom_finders/common.dart:62:7)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:5)
<asynchronous suspension>
The test description was:
  counter state is the same after going to home and switching apps
```

#### Here is my code

```
void main() {
  patrolTest(
    'counter state is the same after going to home and switching apps',
    config: patrolConfig,
    nativeAutomation: true,
    ($) async {
      // Replace with your own app widget.
      await app.main();

      await $.native.pressHome();

    },
  );
}
```

**Comment by bartekpacia** [comment]
Hi @nehemiekoffi 👋 Thanks for using Patrol and creating this issue.

Looks like a strange bug on the native side. Viewing logcat might help. 

1. Open two terminal tabs
2. In the first one do:

    ```console
     $ adb logcat | grep -i PatrolServer
     ```
3. In the second one do `patrol drive`

Share the output and we'll figure something out :)

**Comment by nehemiekoffi** [comment]
Hi @bartekpacia I use emulator : Google Pixel 2

I will share you the logs ASAP.

**Comment by bartekpacia** [comment]
This is probably related:
- https://github.com/appium/appium/issues/16380

**Comment by bartekpacia** [comment]
Closing because of lack of response. We can continue the discussion with a minimal, reproducible example – otherwise I'm just not able to reproduce this.
