### ISSUE TITLE
JSON decoding error in patrol_cli

### ISSUE THREAD

**Issue by Yokoi-K** [leancodepl/patrol#608]
## Error detail

When I run ```patrol devices``` or ```patrol drive```, I get this error.

```
Unexpected end of input
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      DeviceFinder.getAttachedDevices (package:patrol_cli/src/features/devices/device_finder.dart:17:24)
<asynchronous suspension>
#7      DeviceFinder.find (package:patrol_cli/src/features/devices/device_finder.dart:42:29)
<asynchronous suspension>
#8      DriveCommand.parseInput (package:patrol_cli/src/features/drive/drive_command.dart:194:29)
<asynchronous suspension>
#9      StagedCommand.run (package:patrol_cli/src/common/staged_command.dart:21:20)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     PatrolCommandRunner.runCommand (package:patrol_cli/src/command_runner.dart:238:18)
<asynchronous suspension>
#12     PatrolCommandRunner.run (package:patrol_cli/src/command_runner.dart:189:18)
<asynchronous suspension>
#13     patrolCommandRunner (package:patrol_cli/src/command_runner.dart:46:14)
<asynchronous suspension>
#14     main (file:///home/circleci/.pub-cache/hosted/pub.dartlang.org/patrol_cli-0.7.7+1/bin/main.dart:6:20)
<asynchronous suspension>


Tool for running Flutter-native UI tests with superpowers

Usage: patrol <command> [arguments]

Global options:
-h, --help       Print this usage information.
-v, --verbose    Print more logs.
-V, --version    Print version of this program.
    --debug      Use default, non-versioned artifacts.

Available commands:
  bootstrap   Create default config and test files and add patrol as a dev dependency.
  clean       Delete all downloaded artifacts.
  devices     List attached devices, simulators and emulators.
  doctor      Print configuration.
  drive       Drive the app using flutter_driver.
  update      Updates patrol CLI.

Run "patrol help <command>" for more information about a command.
```

There is nothing wrong with running ```patrol doctor```.

## Tried

Here's the code.
https://github.com/leancodepl/patrol/blob/master/packages/patrol_cli/lib/src/features/devices/device_finder.dart#L17

I checked the contents of ```[output]```. It was empty.

```
final output = await _getCommandOutput();
final jsonOutput = jsonDecode(output) as List<dynamic>;
```

## Supplement

This problem is occurring in Linux and macOS(M1 Chip).
So it does not occur in macOS(Intel).

Please help me to solve this problem.

**Comment by Yokoi-K** [comment]
@bartekpacia 

Thanks. Here is output.

```
❯ fvm flutter devices
2 connected devices:
macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

❯ fvm flutter  --version
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (8 days ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
```

**Comment by bartekpacia** [comment]
I said `flutter devices`, not `fvm flutter devices` 😛 

Patrol requires you to have `flutter` in your path.

**Comment by Yokoi-K** [comment]
@bartekpacia 
Thanks!
It was due to the fact that the Flutter path without fvm was not going through!
I put a normal flutter path through and it worked!

**Comment by bartekpacia** [comment]
Awesome! Happy that you solved it :)
