### ISSUE TITLE
Sometimes `NullPointerException` is thrown when using native features

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#613]
So far I've only seen it on our example app's tests on GitHub Actions. Happens _sometimes_.

Logs:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: pressHome() failed with code UNKNOWN (unknown error:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
android.app.UiAutomation.setOnAccessibilityEventListener(android.app.UiAutomation$OnAccessibilityEventListener)'
on a null object reference)
When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:144:7)
<asynchronous suspension>
#1      NativeAutomator.pressHome (package:patrol/src/native/native_automator.dart:181:5)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/runner/work/patrol/patrol/packages/patrol/example/integration_test/example_test.dart:21:7)
<asynchronous suspension>
#3      patrolTest.<anonymous closure> (package:patrol/src/custom_finders/common.dart:88:7)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:5)
<asynchronous suspension>
The test description was:
  counter state is the same after going to Home and switching apps
```

StackOverflow threads that might be related to this:
- https://stackoverflow.com/questions/55608688/i-used-ui-automator-with-android-junit4-but-i-got-a-nullpointerexception
- https://stackoverflow.com/questions/31474776/uidevice-getinstancegetinstrumentation-crashes-as-null-object-reference-wh

**Comment by bartekpacia** [comment]
This is now tracked as part of #765.
