### ISSUE TITLE
Sometimes `NullPointerException` is thrown when installing the instrumentation server

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#614]
So far I've only seen it on our example app's tests on GitHub Actions. Happens sometimes.

This looks like a bug in the Android's own package manager.

Logs:

```
/bin/sh -c patrol drive --target integration_test/features/services/wifi_test.dart
No device specified, using the first one (emulator-5554)
⠋ Installing server...
✗ Failed to install server (10.6s)
Exception: adb: failed to install /Users/runner/.cache/patrol/server-0.7.8.apk: 
Exception occurred while executing:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.os.storage.StorageManager.getVolumes()' on a null object reference
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:186)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:150)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:165)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:571)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:465)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2700)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1061)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
	at android.os.ShellCommand.exec(ShellCom
#0      Adb.install (package:adb/src/adb.dart:57:7)
<asynchronous suspension>
#1      AndroidDriver._forceInstallApk (package:patrol_cli/src/features/drive/platform/android_driver.dart:128:7)
<asynchronous suspension>
#2      AndroidDriver._installServer.<anonymous closure> (package:patrol_cli/src/features/drive/platform/android_driver.dart:53:9)
<asynchronous suspension>
#3      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#4      AndroidDriver._installServer (package:patrol_cli/src/features/drive/platform/android_driver.dart:41:5)
<asynchronous suspension>
#5      AndroidDriver.run (package:patrol_cli/src/features/drive/platform/android_driver.dart:35:5)
<asynchronous suspension>
#6      DriveCommand.execute (package:patrol_cli/src/features/drive/drive_command.dart:261:11)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      PatrolCommandRunner.runCommand (package:patrol_cli/src/command_runner.dart:238:18)
<asynchronous suspension>
#9      PatrolCommandRunner.run (package:patrol_cli/src/command_runner.dart:189:18)
<asynchronous suspension>
#10     patrolCommandRunner (package:patrol_cli/src/command_runner.dart:46:14)
<asynchronous suspension>
#11     main (file:///Users/runner/hostedtoolcache/flutter/stable-3.3.8-x64/.pub-cache/hosted/pub.dartlang.org/patrol_cli-0.7.8/bin/main.dart:6:20)
<asynchronous suspension>

Error: The process '/bin/sh' failed with exit code 1
```

[This StackOverflow thread](https://stackoverflow.com/questions/64810675/error-when-loading-android-apk-via-adb-storagemanager-getvolumes-on-a-null) is about this issue, but nobody commented or answered :^)

**Comment by bartekpacia** [comment]
This is only related to `patrol drive`, which is being removed as part of our 1.0 release.

Because of that, this issue is no longer valid.
