### ISSUE TITLE
First try to run test on iOS device (iOS v16.2)

### ISSUE THREAD

**Issue by ds3031** [leancodepl/patrol#704]
Hi

You did a great job with patrol. Thank you for that. Now the problem.
I tried to run one test on my iPhone device (if it matters it is iPhone SE (2nd gen)). Testing failed. This is output:
`2022-12-22 10:31:57.124 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038dbd00: name:Documentation.docc path:group:Documentation.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/swift-log/Sources/Logging/Documentation.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Documentation.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Documentation.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.127 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038c1100: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/swift-nio-transport-services/Sources/NIOTransportServices/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.130 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038c3a00: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/swift-nio-extras/Sources/NIOSOCKS/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.131 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038cc300: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/swift-nio-extras/Sources/NIOHTTPCompression/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.132 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038ccb00: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/swift-nio-extras/Sources/NIOExtras/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.151 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038f6500: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/grpc-swift/Sources/protoc-gen-grpc-swift/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.158 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038f7900: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/grpc-swift/Sources/GRPC/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.260 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x600003938400: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/swift-protobuf/Sources/protoc-gen-swift/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

2022-12-22 10:31:57.270 xcodebuild[26368:209980] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000038f2100: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/tester/Library/Developer/Xcode/DerivedData/AutomatorServer-cdvgsdgulfzyrqguwevpkksrsnmm/SourcePackages/checkouts/swift-nio-ssl/Sources/NIOSSL/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

Testing failed:
No profiles for 'pl.leancode.AutomatorServerUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'pl.leancode.AutomatorServerUITests.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
No profiles for 'pl.leancode.AutomatorServer' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'pl.leancode.AutomatorServer'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Testing cancelled because the build failed.

** TEST FAILED **
Unhandled exception:
Exception: Test failed. See logs above. Also, consider running with --verbose.
#0      IOSDriver._runServerOnDevice.<anonymous closure> (package:patrol_cli/src/features/drive/platform/ios_driver.dart:176:9)
#1      List.forEach (dart:core-patch/growable_array.dart:416:8)
#2      ProcessListeners.listenStdErr.<anonymous closure> (package:patrol_cli/src/common/extensions/process.dart:50:14)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#7      _StreamController._add (dart:async/stream_controller.dart:648:7)
#8      _StreamController.add (dart:async/stream_controller.dart:596:5)
#9      _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#14     _StreamController._add (dart:async/stream_controller.dart:648:7)
#15     _StreamController.add (dart:async/stream_controller.dart:596:5)
#16     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
#17     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)`

Maybe I am doing something wrong?

Thanks for reading

**Comment by bartekpacia** [comment]
Hi @ds3031, thanks for kind words about Patrol :)

> Maybe I am doing something wrong?

No, you're not – we are :) We didn't include info in our docs that to run tests on physical iOS devices, you have to manually codesign our automation server artifact (it should be located in `~/.cache/patrol/ios-0.8.1`). Open it with Xcode and set up signing.

See also [this issue](https://github.com/leancodepl/patrol/issues/693).

**Comment by ds3031** [comment]
I did that and AutomatorServer is signed with company team, but not AutomatorServerUITests. After signing I closed Xcode and reopen again Android Studio but still same error...

**Comment by bartekpacia** [comment]
> I did that and AutomatorServer is signed with company team, but not AutomatorServerUITests. After signing I closed Xcode and reopen again Android Studio but still same error...

You have to sign both AutomatorServer and AutomatorServerUITests.

Let me know if you need a more detailed walkthrough, I can post a video/gif :)

**Comment by ds3031** [comment]
Sorry I did that but I get error (with company team and with personal team)
![image](https://user-images.githubusercontent.com/121227203/209140547-361e7646-42dc-4e02-be97-4d1b9e973eb8.png)

**Comment by bartekpacia** [comment]
That's strange -- please try changing the _app identifier_ to something different than `pl.leancode.AutomatorServerUITests`.

**Comment by ds3031** [comment]
I changed it to **pl.leancode.AutomatorServerUI** (deleted only Test) and it is ok, but now I get this error in output>

`Testing failed:
No profiles for 'pl.leancode.AutomatorServerUI.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'pl.leancode.AutomatorServerUI.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Testing cancelled because the build failed.`

**Comment by bartekpacia** [comment]
@ds3031 I'm back from holidays. Did you solve this issue?

**Comment by ds3031** [comment]
No because I don't know how or even where to start

**Comment by bartekpacia** [comment]
Since this is a code signing issue, I highly recommend you consult your friendly neighborhood iOS developer :)
