### ISSUE TITLE
`xcodebuild test` fails when running Patrol tests on iOS Simulator

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#728]
~~The root cause appears to be https://github.com/flutter/flutter/issues/85643.~~ No, the problem was in the `xcodebuild` arguments, see https://github.com/flutter/flutter/issues/117977 for more.

If the developer wants to run example app's integration tests on iOS Simulator using:

```
xcodebuild test \
  -workspace Runner.xcworkspace \
  -scheme Runner \
  -config Flutter/Debug.xcconfig \
  -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
```

they'll encounter an error

```
error: [   +6 ms] Target aot_assembly_release failed: Exception: release/profile builds are only supported for physical devices. attempted to build for simulator.
           #0      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:75:7)
           #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:848:27)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
           <asynchronous suspension>
           #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:786:32)
           <asynchronous suspension>
           #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
           <asynchronous suspension>
           #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:32)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1275:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:290:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:351:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1275:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:290:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
Failed to package /Users/bartek/dev/leancode/patrol/packages/patrol/example.
```

The temporary workaround is to explicitly define build mode:

```
FLUTTER_BUILD_MODE=Debug xcodebuild test \
  -workspace Runner.xcworkspace \
  -scheme Runner \
  -config Flutter/Debug.xcconfig \
  -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
```

or alternatively:
```
$ xcodebuild test \
        -workspace Runner.xcworkspace \
        -scheme Runner \
        -xcconfig Flutter/Debug.xcconfig \
        -configuration Debug \
        -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
```

(it looks like `config` is interchangeable with `xcconfig`, and `configuration` is a different thing)

**Comment by bartekpacia** [comment]
The default Build Configuration can be specified here:

![Screenshot 2023-01-04 at 4 54 05 PM](https://user-images.githubusercontent.com/40357511/210595387-310b4c78-5006-46cf-8a05-a1d37b6faf08.png)

Source: https://developer.apple.com/library/archive/technotes/tn2339/_index.html
