### ISSUE TITLE
patrol drive fails in Bitrise

### ISSUE THREAD

**Issue by Mitagki** [leancodepl/patrol#746]
All my tests work locally but when I try running them in Bitrise they can't even start.
Any idea why this happens?
```
patrol drive
⠋ Artifacts are not present, downloading...
✓ Downloaded artifacts (11.2s)
Unexpected character
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      DeviceFinder.getAttachedDevices (package:patrol_cli/src/features/devices/device_finder.dart:17:24)
<asynchronous suspension>
#8      DeviceFinder.find (package:patrol_cli/src/features/devices/device_finder.dart:42:29)
<asynchronous suspension>
#9      DriveCommand.parseInput (package:patrol_cli/src/features/drive/drive_command.dart:220:29)
<asynchronous suspension>
#10     StagedCommand.run (package:patrol_cli/src/common/staged_command.dart:21:20)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     PatrolCommandRunner.runCommand (package:patrol_cli/src/command_runner.dart:257:18)
<asynchronous suspension>
#13     PatrolCommandRunner.run (package:patrol_cli/src/command_runner.dart:201:18)
<asynchronous suspension>
#14     patrolCommandRunner (package:patrol_cli/src/command_runner.dart:47:14)
<asynchronous suspension>
#15     main (file:///Users/vagrant/.pub-cache/hosted/pub.dartlang.org/patrol_cli-0.8.1/bin/main.dart:6:20)
<asynchronous suspension>
```

**Comment by bartekpacia** [comment]
Hi @Mitagki, what version of Flutter do you have set on Bitrise? Also, what device with what configuration are you using? Please give as much details as possible.

This most probably occurred because `flutter devices` returned some unexpected output on the first run (and on CI, it's always the first run, haha). For example, Flutter update prompt etc. I thought I fixed this bug, but apparently, it's made a comeback.

Please try this workaround: do `flutter doctor -v` and `flutter devices` just before you call `patrol drive ...`. Then Patrol shouldn't be the one doing the first run of `flutter` command, so the output should be normal. LMK if this helps.

**Comment by Mitagki** [comment]
You are amazing!
`flutter doctor -v` and `flutter devices` fixed it.
Thanks for the fast reply!

**Comment by bartekpacia** [comment]
Thanks a lot for your kind words :)

I should get this fixed, though.
