### ISSUE TITLE
Test failed on the example test

### ISSUE THREAD

**Issue by chengboonrong** [leancodepl/patrol#914]
**Describe the bug**
What could it be if this happened? Test with the sample code given failed because of this error:

```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: configure() failed after 60 retries
(GrpcError: configure() failed with code UNAVAILABLE (Error
connecting: SocketException: Connection refused (OS Error:
Connection refused, errno = 111), address = localhost, port =
59144)

When the exception was thrown, this was the stack:
#0      NativeAutomator.configure (package:patrol/src/native/native_automator.dart:236:7)
<asynchronous suspension>
#1      patrolTest.<anonymous closure> (package:patrol/src/common.dart:75:7)
<asynchronous suspension>
#2      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
<asynchronous suspension>
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:5)
<asynchronous suspension>

The test description was:
counter state is the same after going to home and switching
apps
═════════════════════════════════════════════════════════════════

at dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:81)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
```

**To Reproduce**
1. patrol test --target integration_test/integration_test.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

void main() {
  patrolTest(
    'counter state is the same after going to home and switching apps',
    ($) async {
      // Replace later with your app's main widget
      await $.pumpWidgetAndSettle(
        MaterialApp(
          home: Scaffold(
            appBar: AppBar(title: const Text('app')),
            backgroundColor: Colors.blue,
          ),
        ),
      );

      expect($('app'), findsOneWidget);
      await $.native.pressHome();
    },
    nativeAutomation: true,
  );
}
```

**Expected behavior**
Test should passed. 

**Device information**
 - Device: Android emulator API 30
 - Does it also both on physical and virtual devices? [didn't check]

<details>
<summary>Additional information</summary>

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (8 周前) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

patrol: ^0.10.8

patrol_cli v0.9.4

openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

</details>

**Additional context**

**Comment by bartekpacia** [comment]
Can you create an example repo with reproduction steps?

**Comment by chengboonrong** [comment]
Hi @bartekpacia, you may close this issue now as I just noticed that I was missing one of the step in setup. So sorry for the false alarm and thank you very much for the response !!!

**Comment by bartekpacia** [comment]
I'm happy that you solved your problem :)

Can you share what was wrong, so other people in the future will find it helpful?

**Comment by chengboonrong** [comment]
I was missing the step to replace the code in `MainActivityTest.java` with implementation of `PatrolTestRule` and `PatrolTestRunner`
